//! Kernel integration tests.
//!
//! These tests assert concrete verdicts, reason codes and exact shortest
//! paths. `independent_oracle` additionally re-derives reachability with a
//! separate recursion (not built on the kernel's BFS), so the expected
//! answers are not generated by the code under test.

mod common;

use common::*;
use fsm_core::reason;
use fsm_core::{explore, Budget, RunStatus, Verdict};
use fsm_lang::evidence::kind;
use fsm_lang::model::{PropertyKind, Value};

fn verdict<'a>(outcome: &'a fsm_core::ExploreOutcome, name: &str) -> &'a fsm_core::PropertyResult {
    outcome
        .properties
        .iter()
        .find(|p| p.name == name)
        .unwrap_or_else(|| panic!("missing property {name}"))
}

#[test]
fn mutex_bad_has_shortest_violation_of_four_steps() {
    let spec = load_fixture("mutex_bad");
    let outcome = explore(&spec, &Budget::default());

    assert_eq!(outcome.status, RunStatus::Complete, "{outcome:?}");
    assert!(!outcome.truncated);
    let p = verdict(&outcome, "mutex");
    assert_eq!(p.kind, PropertyKind::Ag);
    assert_eq!(p.verdict, Verdict::False);
    assert_eq!(p.reason, reason::COUNTEREXAMPLE_FOUND);

    let ev = p.evidence.as_ref().expect("counterexample evidence");
    assert_eq!(ev.kind, kind::AG_VIOLATION);
    // 5 states => 4 fired transitions.
    assert_eq!(ev.trace.len(), 5);
    let fired: Vec<&str> = ev
        .trace
        .iter()
        .skip(1)
        .map(|s| s.fired.as_deref().unwrap())
        .collect();
    assert_eq!(fired, vec!["request0", "request1", "enter0", "enter1"]);
    assert!(ev.trace[0].fired.is_none());

    let final_state = &ev.trace.last().unwrap().state;
    assert_eq!(named(final_state, "in_cs0"), &Value::Bool(true));
    assert_eq!(named(final_state, "in_cs1"), &Value::Bool(true));

    // Hand replay: assert every intermediate state explicitly.
    let s0 = &ev.trace[0].state;
    assert_eq!((named(s0, "wants0"), named(s0, "wants1")),
               (&Value::Bool(false), &Value::Bool(false)));
    let s1 = &ev.trace[1].state;
    assert_eq!(named(s1, "wants0"), &Value::Bool(true));
    assert_eq!(named(s1, "in_cs0"), &Value::Bool(false));
    let s2 = &ev.trace[2].state;
    assert_eq!((named(s2, "wants0"), named(s2, "wants1")),
               (&Value::Bool(true), &Value::Bool(true)));
    let s3 = &ev.trace[3].state;
    assert_eq!(named(s3, "in_cs0"), &Value::Bool(true));
    assert_eq!(named(s3, "in_cs1"), &Value::Bool(false));
}

#[test]
fn mutex_reachable_state_count_matches_independent_oracle() {
    let spec = load_fixture("mutex_bad");
    let outcome = explore(&spec, &Budget::default());
    assert_eq!(outcome.stats.discovered, 9);

    // Independent oracle: recursively enumerate successors with fresh code.
    let reach = common::independent_oracle::reachable_states(&spec);
    assert_eq!(reach.len(), 9);
}

#[test]
fn counter_proves_invariant_reaches_top_and_flags_unreachable_target() {
    let spec = load_fixture("counter");
    let outcome = explore(&spec, &Budget::default());
    assert_eq!(outcome.status, RunStatus::Complete);

    let ag = verdict(&outcome, "nonnegative");
    assert_eq!(ag.verdict, Verdict::True);
    assert_eq!(ag.reason, reason::PROVED);
    assert!(ag.evidence.is_none());

    let ef = verdict(&outcome, "can_reach_top");
    assert_eq!(ef.verdict, Verdict::True);
    assert_eq!(ef.reason, reason::WITNESS_FOUND);
    let witness = ef.evidence.as_ref().unwrap();
    let fired: Vec<&str> = witness
        .trace
        .iter()
        .skip(1)
        .map(|s| s.fired.as_deref().unwrap())
        .collect();
    assert_eq!(fired, vec!["inc", "inc", "inc"]);
    assert_eq!(named(&witness.trace.last().unwrap().state, "c"), &Value::Int(3));

    let bad = verdict(&outcome, "can_overflow");
    assert_eq!(bad.verdict, Verdict::False);
    assert_eq!(bad.reason, reason::TARGET_UNREACHABLE);
    assert!(bad.evidence.is_none());

    // One legal terminal (c=3, done=true), zero deadlocks.
    assert_eq!(outcome.stats.terminal_states, 1);
    assert_eq!(outcome.stats.deadlocks, 0);
    assert_eq!(outcome.terminal_evidence.len(), 1);
    let term = &outcome.terminal_evidence[0];
    assert_eq!(term.kind, kind::TERMINAL);
    let term_fired: Vec<&str> = term
        .trace
        .iter()
        .skip(1)
        .map(|s| s.fired.as_deref().unwrap())
        .collect();
    assert_eq!(term_fired, vec!["inc", "inc", "inc", "finish"]);
}

#[test]
fn deadlock_is_detected_separately_from_legal_termination() {
    let spec = load_fixture("deadlock");
    let outcome = explore(&spec, &spec_budget(&spec));
    assert_eq!(outcome.status, RunStatus::Complete);
    assert_eq!(outcome.stats.deadlocks, 1);
    assert_eq!(outcome.stats.terminal_states, 0);
    assert_eq!(outcome.deadlock_evidence.len(), 1);
    let dl = &outcome.deadlock_evidence[0];
    assert_eq!(dl.kind, kind::DEADLOCK);
    assert_eq!(dl.trace.len(), 2);
    assert_eq!(dl.trace[1].fired.as_deref(), Some("shoot"));
    assert_eq!(named(&dl.trace[1].state, "fired"), &Value::Bool(true));
    assert!(outcome.terminal_evidence.is_empty());
}

#[test]
fn missing_initial_state_is_an_invalid_run_not_a_proof() {
    let spec = load_fixture("no_initial");
    let outcome = explore(&spec, &spec_budget(&spec));
    assert_eq!(outcome.status, RunStatus::Invalid);
    assert_eq!(outcome.reason, reason::NO_INITIAL_STATE);
    assert!(outcome.properties.is_empty());
    assert_eq!(outcome.stats.initial_states, 0);
    assert_eq!(outcome.stats.initial_scanned, 3);
    assert_eq!(outcome.stats.discovered, 0);
}

#[test]
fn budget_truncation_yields_unknown_with_statistics() {
    let spec = load_fixture("truncate_chain");
    let outcome = explore(
        &spec,
        &Budget {
            max_states: 4,
            max_transitions: 1_000,
            max_initial_scan: 1_000,
        },
    );
    assert_eq!(outcome.status, RunStatus::Truncated);
    assert!(outcome.truncated);
    assert_eq!(outcome.reason, reason::BUDGET_TRUNCATED);
    assert_eq!(outcome.stats.explored, 4);
    // states n=0..=4 discovered, n=4 queued but not expanded
    assert_eq!(outcome.stats.discovered, 5);

    for p in &outcome.properties {
        assert_eq!(p.verdict, Verdict::Unknown, "{}", p.name);
        assert_eq!(p.reason, reason::BUDGET_TRUNCATED);
        assert!(
            p.evidence.is_none(),
            "truncated runs must not present a false witness; got {:?}",
            p.evidence
        );
    }
}

#[test]
fn exact_budget_covers_full_graph_without_false_truncation() {
    let spec = load_fixture("truncate_chain");
    let outcome = explore(
        &spec,
        &Budget {
            max_states: 10,
            max_transitions: 1_000,
            max_initial_scan: 1_000,
        },
    );
    assert_eq!(outcome.status, RunStatus::Complete, "{outcome:?}");
    assert!(!outcome.truncated);
    assert_eq!(outcome.stats.explored, 10);
}

#[test]
fn out_of_domain_update_is_a_model_error() {
    let spec = load_fixture("out_of_domain");
    let outcome = explore(&spec, &spec_budget(&spec));
    assert_eq!(outcome.status, RunStatus::Error);
    assert_eq!(outcome.reason, reason::EVALUATION_ERROR);
    let err = outcome.error.as_ref().expect("error block");
    assert_eq!(err.code, "VALUE_OUT_OF_DOMAIN");
    assert_eq!(err.transition.as_deref(), Some("jump"));
}

#[test]
fn integer_overflow_in_guard_is_a_model_error() {
    let spec = load_fixture("overflow");
    let outcome = explore(&spec, &spec_budget(&spec));
    assert_eq!(outcome.status, RunStatus::Error);
    assert_eq!(outcome.reason, reason::EVALUATION_ERROR);
    let err = outcome.error.as_ref().expect("error block");
    assert_eq!(err.code, "INT_OVERFLOW");
    assert_eq!(err.transition.as_deref(), Some("huge_guard"));
}

#[test]
fn simultaneous_update_reads_one_pre_state() {
    let spec = load_fixture("swap");
    let outcome = explore(&spec, &spec_budget(&spec));
    assert_eq!(outcome.status, RunStatus::Complete);
    assert_eq!(outcome.stats.discovered, 2, "swap toggles between two states");

    let ef = verdict(&outcome, "swapped_reachable");
    assert_eq!(ef.verdict, Verdict::True);
    let w = ef.evidence.as_ref().unwrap();
    assert_eq!(w.trace.len(), 2);
    assert_eq!(w.trace[1].fired.as_deref(), Some("swap"));
    assert_eq!(named(&w.trace[1].state, "a"), &Value::Int(0));
    assert_eq!(named(&w.trace[1].state, "b"), &Value::Int(1));

    // Firing swap again returns to the initial state (no new state).
    let ag = verdict(&outcome, "values_stay_binary");
    assert_eq!(ag.verdict, Verdict::True);
}
