#!/usr/bin/env python3
"""Independent reference implementation of the MPHF used by this project.

This file is intentionally written from scratch (it shares no code with the
Rust crate) and serves two purposes:

1. Documentation of the exact integer/hash/peeling/rank contract that the
   on-disk format binds.
2. The oracle behind ``golden.json``: the Rust test suite asserts concrete
   slots/hashes/fingerprints against values THIS program emits, so the test
   answers are not generated by the implementation under test.

Semantics: all 64-bit arithmetic is mod 2**64; edge table size m is the
smallest prime >= ceil(n/load_factor). Hyperedges use the BDZ triple
{h0, h1, h0+h1} mod m. Peeling is FIFO from the initially degree-1
vertices; g assignment runs in reverse with

    g[v] = (position - g[a] - g[b]) mod 3

and an occupancy bitset separates assigned vertices (which may legitimately
hold g == 0) from unassigned ones (also 0, but not ranked).

Usage:
    python3 mphf_ref.py golden --out ../fixtures/golden.json
    python3 mphf_ref.py hash-vector --key item-00001 --seed 1
    python3 mphf_ref.py verify --set-size 500 --seed 7
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import deque
from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

MASK64 = (1 << 64) - 1

SALT_0 = 0xA5A55A5AD1D1D1D1
SALT_1 = 0xA5A55A5AD2D2D2D2
SALT_2 = 0xA5A55A5AD3D3D3D3
SALT_FP = 0x52525252F0F0F0F1

# ---------------------------------------------------------------------------
# Hash contract (mirror of src/hash.rs)
# ---------------------------------------------------------------------------


def mix64(z: int) -> int:
    z = (z + 0x9E3779B97F4A7C15) & MASK64
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    return z ^ (z >> 31)


def stream(key: bytes, seed: int, salt: int) -> int:
    h = 0xCBF29CE484222325
    for b in key:
        h ^= b
        h = (h * 0x100000001B3) & MASK64
    h = mix64(h ^ seed)
    return mix64(h ^ salt)


def edge_hash(key: bytes, seed: int) -> Tuple[int, int, int]:
    return (
        stream(key, seed, SALT_0),
        stream(key, seed, SALT_1),
        stream(key, seed, SALT_2),
    )


def edge(key: bytes, seed: int, m: int) -> Optional[Tuple[int, int, int]]:
    h0, h1, _ = edge_hash(key, seed)
    a, b = h0 % m, h1 % m
    # Rust uses u64::wrapping_add before the modulo; mirror it exactly.
    c = ((h0 + h1) & MASK64) % m
    if a != b and a != c and b != c:
        return (a, b, c)
    return None


def fingerprint(key: bytes, seed: int, bits: int) -> int:
    assert bits in (8, 16, 32, 64)
    raw = stream(key, seed, SALT_FP)
    return raw % ((1 << bits) - 1) + 1


# ---------------------------------------------------------------------------
# Prime table sizing
# ---------------------------------------------------------------------------


def is_prime(x: int) -> bool:
    if x < 2:
        return False
    if x % 2 == 0:
        return x == 2
    d = 3
    while d * d <= x:
        if x % d == 0:
            return False
        d += 2
    return True


def next_prime(x: int) -> int:
    if x <= 2:
        return 2
    if x % 2 == 0:
        x += 1
    while not is_prime(x):
        x += 2
    return x


# ---------------------------------------------------------------------------
# Peeling / assignment kernel
# ---------------------------------------------------------------------------


@dataclass
class BuildAttempt:
    seed: int
    outcome: str  # "peeled" | "core_remain" | "edge_unavailable"
    remaining: Optional[int] = None


def resolve_edges(keys: Sequence[bytes], seed: int, m: int):
    edges: List[Tuple[int, int, int]] = []
    for k in keys:
        e = edge(k, seed, m)
        if e is None:
            return None
        edges.append(e)
    return edges


def peel(edges: Sequence[Tuple[int, int, int]], m: int):
    n = len(edges)
    adj: List[List[int]] = [[] for _ in range(m)]
    for i, e in enumerate(edges):
        for v in e:
            adj[v].append(i)
    degree = [len(a) for a in adj]
    alive = [True] * n
    consumed = [False] * m
    q: deque[int] = deque(v for v in range(m) if degree[v] == 1)
    steps: List[Tuple[int, int]] = []
    while q:
        v = q.popleft()
        if consumed[v] or degree[v] != 1:
            continue
        eid = next((i for i in adj[v] if alive[i]), None)
        if eid is None:
            continue
        steps.append((eid, v))
        alive[eid] = False
        consumed[v] = True
        for w in edges[eid]:
            if w == v or consumed[w]:
                continue
            degree[w] -= 1
            if degree[w] == 1:
                q.append(w)
        degree[v] = 0
    if len(steps) == n:
        return steps
    return None  # non-empty core remains


def assign(edges, steps, m: int) -> Tuple[List[int], List[bool]]:
    g = [0] * m
    occupied = [False] * m
    for eid, v in reversed(steps):
        e = edges[eid]
        pos = e.index(v)
        others = [w for j, w in enumerate(e) if j != pos]
        g[v] = (pos - g[others[0]] - g[others[1]]) % 3
        occupied[v] = True
    return g, occupied


class BitRank:
    """Rank1 over a bit vector with per-64-bit-word cumulative counts."""

    def __init__(self, bits: Sequence[bool]):
        self.bits = list(bits)
        words = (len(bits) + 63) // 64
        self.raw = [0] * words
        for i, on in enumerate(bits):
            if on:
                self.raw[i // 64] |= 1 << (i % 64)
        self.cum = [0] * (words + 1)
        total = 0
        for w, word in enumerate(self.raw):
            self.cum[w] = total
            total += word.bit_count()
        self.cum[words] = total

    def rank1(self, i: int) -> int:
        if i <= 0:
            return 0
        i = min(i, len(self.bits))
        w = i // 64
        return self.cum[w] + (self.raw[w] & ((1 << (i % 64)) - 1)).bit_count()

    def total(self) -> int:
        return self.cum[-1]


@dataclass
class MPHF:
    keys: List[bytes]
    seed: int
    m: int
    edges: List[Tuple[int, int, int]]
    g: List[int]
    occupied: List[bool]
    rank: List[BitRank]

    @classmethod
    def build(cls, keys: Sequence[bytes], base_seed: int = 1,
              load_factor: float = 0.75, max_attempts: int = 256) -> "MPHF":
        keys = list(keys)
        n = len(keys)
        # Mirror BuildConfig::vertex_count: smallest prime >= ceil(n/lf),
        # floor at 13 (slack for tiny keysets; minimality is in rank=n).
        import math

        m = next_prime(max(31, math.ceil(n / load_factor)))
        for attempt in range(max_attempts):
            if attempt == 0:
                seed = base_seed
            else:
                seed = mix64((mix64(base_seed) + attempt * 0x9E3779B97F4A7C15) & MASK64)
            edges = resolve_edges(keys, seed, m)
            if edges is None:
                continue
            steps = peel(edges, m)
            if steps is None:
                continue
            g, occ = assign(edges, steps, m)
            rank = [
                BitRank([occ[v] and g[v] == c for v in range(m)])
                for c in (0, 1, 2)
            ]
            # Verify permutation independently.
            slots = set()
            for i, e in enumerate(edges):
                s = (g[e[0]] + g[e[1]] + g[e[2]]) % 3
                v = e[s]
                assert occ[v], f"selected unoccupied v={v}"
                slot = sum(rank[c].total() for c in range(g[v])) + rank[
                    g[v]
                ].rank1(v)
                assert slot not in slots
                slots.add(slot)
            assert slots == set(range(n)), "not a permutation of 0..n"
            return cls(keys, seed, m, edges, g, occ, rank)
        raise RuntimeError("peeling failed after all attempts")

    def slot_of(self, key: bytes):
        """Return (slot, selected_vertex, occupied) or None on edge collision."""
        if not self.keys:
            return None
        e = edge(key, self.seed, self.m)
        if e is None:
            return None
        s = (self.g[e[0]] + self.g[e[1]] + self.g[e[2]]) % 3
        v = e[s]
        slot = sum(self.rank[c].total() for c in range(self.g[v])) + self.rank[
            self.g[v]
        ].rank1(v)
        return slot, v, self.occupied[v]


# ---------------------------------------------------------------------------
# Fixture generation
# ---------------------------------------------------------------------------


def synth_keys(n: int) -> List[bytes]:
    return [f"item-{i:05}".encode() for i in range(n)]


def main_golden(out: str) -> None:
    seed = 1
    keys = synth_keys(64)
    idx = MPHF.build(keys, base_seed=seed)

    slots = []
    for i, k in enumerate(keys):
        res = idx.slot_of(k)
        assert res is not None and res[2]
        slots.append({"i": i, "key": k.decode(), "slot": res[0], "vertex": res[1]})

    non_members = [b"item-00064", b"not-a-key", b"", b"ITEM-00000", b"item-00000x"]
    nm = []
    for k in non_members:
        r = idx.slot_of(k)
        nm.append(
            {
                "key": k.decode("latin1"),
                "edge_collision": r is None,
                "slot": None if r is None else r[0],
                "vertex": None if r is None else r[1],
                "occupied": False if r is None else r[2],
            }
        )

    # Exact raw hash vectors for a few keys: the strongest cross-language
    # contract check (independent of m/peeling).
    hv = []
    for k in [b"", b"a", b"item-00001", b"\x00\x01\x02\xff"]:
        hv.append(
            {
                "key_hex": k.hex(),
                "h0": stream(k, seed, SALT_0),
                "h1": stream(k, seed, SALT_1),
                "h2": stream(k, seed, SALT_2),
                "fp16": fingerprint(k, seed, 16),
                "fp8": fingerprint(k, seed, 8),
            }
        )

    # Fixed small scripted hypergraphs for kernel assertions:
    # (a) two disjoint edges peel; (b) K4^3 is a solid 3-core.
    scripted = {
        "disjoint": {"edges": [[0, 1, 2], [3, 4, 5]], "m": 6, "peels": True},
        "k4_3": {
            "edges": [[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]],
            "m": 4,
            "peels": False,
        },
    }

    fixture = {
        "format_version": 1,
        "algorithm": "bdz3-v1",
        "note": "Generated by tests/reference/mphf_ref.py — independent Python oracle.",
        "seed": idx.seed,
        "m": idx.m,
        "n": len(keys),
        "members": slots,
        "non_members": nm,
        "hash_vectors": hv,
        "scripted": scripted,
    }
    with open(out, "w", encoding="utf-8") as f:
        json.dump(fixture, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {out}: n={len(keys)} m={idx.m} seed={idx.seed}", file=sys.stderr)


def main_hash_vector(key: str, seed: int) -> None:
    k = key.encode()
    print(json.dumps({
        "h0": stream(k, seed, SALT_0),
        "h1": stream(k, seed, SALT_1),
        "h2": stream(k, seed, SALT_2),
        "fp16": fingerprint(k, seed, 16),
    }))


def main_verify(set_size: int, seed: int) -> None:
    keys = synth_keys(set_size)
    idx = MPHF.build(keys, base_seed=seed)
    seen = set()
    for i, k in enumerate(keys):
        r = idx.slot_of(k)
        assert r and r[2]
        seen.add(r[0])
    assert seen == set(range(set_size))
    print(json.dumps({"ok": True, "n": set_size, "m": idx.m, "seed": idx.seed}))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("golden")
    g.add_argument("--out", required=True)
    hv = sub.add_parser("hash-vector")
    hv.add_argument("--key", required=True)
    hv.add_argument("--seed", type=int, default=1)
    v = sub.add_parser("verify")
    v.add_argument("--set-size", type=int, default=500)
    v.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()
    if args.cmd == "golden":
        main_golden(args.out)
    elif args.cmd == "hash-vector":
        main_hash_vector(args.key, args.seed)
    else:
        main_verify(args.set_size, args.seed)
