// Package golden_test contains the independent characterization tests.
//
// These tests are deliberately placed outside internal/ and use only the
// exported API. Expected results live in testdata/golden/golden.json, which is
// a hand-authored reference document: no production code writes or "updates"
// it. When the implementation disagrees with the reference, the test fails
// with a specific mismatch category instead of a generic call failure.
package ribd_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/opp221/ribd/internal/netmodel"
	"github.com/opp221/ribd/internal/rib"
)

type fixtureRoutes struct {
	Routes []netmodel.Route `json:"routes"`
}

type goldenDoc struct {
	Comment string `json:"_comment"`
	Tables  map[string]struct {
		RoutesFile string `json:"routes_file"`
		MaxDepth   int    `json:"max_depth"`
	} `json:"tables"`
	Cases []struct {
		Name   string         `json:"name"`
		Table  string         `json:"table"`
		Target string         `json:"target"`
		Expect expectedResult `json:"expect"`
	} `json:"cases"`
}

type expectedResult struct {
	Status      string         `json:"status"`
	Failure     string         `json:"failure"`
	Family      string         `json:"family"`
	ChosenRoute string         `json:"chosen_route"`
	Egress      string         `json:"egress"`
	ResolveLen  int            `json:"resolve_len"`
	MatchChain  []expectedHit  `json:"match_chain"`
	Resolve     []expectedStep `json:"resolve"`
}

type expectedHit struct {
	Prefix       string   `json:"prefix"`
	BestID       string   `json:"best_id"`
	CandidateIDs []string `json:"candidate_ids"`
	Chosen       bool     `json:"chosen"`
}

type expectedStep struct {
	Step   int    `json:"step"`
	Target string `json:"target"`
	BestID string `json:"best_id"`
}

func loadGolden(t *testing.T) goldenDoc {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "golden", "golden.json"))
	if err != nil {
		t.Fatalf("fixture read: %v", err)
	}
	var doc goldenDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("fixture parse: %v", err)
	}
	return doc
}

// TestGoldenIsHandAuthored guards the core requirement that reference answers
// are an external artifact and are never produced by the code under test.
func TestGoldenIsHandAuthored(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "golden", "golden.json"))
	if err != nil {
		t.Fatalf("fixture read: %v", err)
	}
	if !strings.Contains(string(raw), "Hand-authored") {
		t.Fatal("golden.json is missing its hand-authored provenance marker; reference answers must not be generated by the implementation")
	}
}

func buildTable(t *testing.T, routesFile string, maxDepth int) *rib.Table {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "golden", routesFile))
	if err != nil {
		t.Fatalf("routes fixture %s: %v", routesFile, err)
	}
	var fr fixtureRoutes
	if err := json.Unmarshal(raw, &fr); err != nil {
		t.Fatalf("routes fixture %s parse: %v", routesFile, err)
	}
	changes := make([]rib.Change, 0, len(fr.Routes))
	for _, r := range fr.Routes {
		changes = append(changes, rib.Change{Kind: rib.Upsert, Route: r})
	}
	tbl := rib.NewTable(maxDepth, nil)
	snap, err := tbl.Apply(changes)
	if err != nil {
		t.Fatalf("bootstrap batch for %s rejected: %v", routesFile, err)
	}
	if snap.VersionNum() != 1 {
		t.Fatalf("bootstrap must become one version (1); got %d", snap.VersionNum())
	}
	return tbl
}

func TestGoldenCases(t *testing.T) {
	doc := loadGolden(t)
	tables := map[string]*rib.Table{}
	for name, spec := range doc.Tables {
		tables[name] = buildTable(t, spec.RoutesFile, spec.MaxDepth)
	}
	if len(doc.Cases) < 15 {
		t.Fatalf("golden suite shrank to %d cases; expected the full reference set", len(doc.Cases))
	}

	for _, tc := range doc.Cases {
		t.Run(tc.Name, func(t *testing.T) {
			tbl, ok := tables[tc.Table]
			if !ok {
				t.Fatalf("unknown table %q", tc.Table)
			}
			got := tbl.Current().LookupText(tc.Target)
			exp := tc.Expect
			fail := func(category, format string, args ...any) {
				t.Fatalf("[%s] %s: %s", tc.Name, category, fmtSprintf(format, args...))
			}

			if string(got.Status) != exp.Status {
				fail("status_mismatch", "want status=%s, got %s (reason: %s)", exp.Status, got.Status, got.Reason)
			}
			if string(got.Failure) != exp.Failure {
				fail("failure_category_mismatch", "want failure=%q, got %q", exp.Failure, got.Failure)
			}
			if got.Family != exp.Family {
				fail("family_mismatch", "want family=%q, got %q", exp.Family, got.Family)
			}
			if got.ChosenRoute != exp.ChosenRoute {
				fail("chosen_route_mismatch", "want %q, got %q", exp.ChosenRoute, got.ChosenRoute)
			}
			if got.Egress != exp.Egress {
				fail("egress_mismatch", "want %q, got %q", exp.Egress, got.Egress)
			}
			if got.TableVersion != 1 {
				fail("table_version_mismatch", "all bootstrap routes must be visible at one version 1, got %d", got.TableVersion)
			}
			if len(got.ResolveChain) != exp.ResolveLen {
				fail("resolve_chain_length", "want %d hop(s), got %d: %s", exp.ResolveLen, len(got.ResolveChain), got.Reason)
			}
			assertMatchChain(t, tc.Name, got.MatchChain, exp.MatchChain)
			assertResolveChain(t, tc.Name, got.ResolveChain, exp.Resolve)

			// A non-empty reason is itself required: diagnostics must say why
			// a verdict was reached.
			if got.Reason == "" {
				fail("missing_diagnostic_reason", "lookup result must explain the verdict")
			}
		})
	}
}

func assertMatchChain(t *testing.T, caseName string, got []rib.CandidateMatch, want []expectedHit) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("[%s] [match_chain_length] want %d level(s), got %d", caseName, len(want), len(got))
	}
	for i, w := range want {
		g := got[i]
		cat := func(sub string) string { return "match_chain[" + itoa(i) + "]." + sub }
		if g.Prefix != w.Prefix {
			t.Fatalf("[%s] [%s] want prefix %s, got %s", caseName, cat("prefix"), w.Prefix, g.Prefix)
		}
		if g.Best.ID != w.BestID {
			t.Fatalf("[%s] [%s] want best %q, got %q", caseName, cat("best_id"), w.BestID, g.Best.ID)
		}
		if g.Chosen != w.Chosen {
			t.Fatalf("[%s] [%s] want chosen=%v, got %v", caseName, cat("chosen"), w.Chosen, g.Chosen)
		}
		if len(g.CandidateIDs) != len(w.CandidateIDs) {
			t.Fatalf("[%s] [%s] want candidates %v, got %v", caseName, cat("candidate_ids"), w.CandidateIDs, g.CandidateIDs)
		}
		for j := range w.CandidateIDs {
			if g.CandidateIDs[j] != w.CandidateIDs[j] {
				t.Fatalf("[%s] [%s] candidate order mismatch at %d: want %v, got %v (policy ordering is AD, then metric, then install sequence)",
					caseName, cat("candidate_order"), j, w.CandidateIDs, g.CandidateIDs)
			}
		}
	}
}

func assertResolveChain(t *testing.T, caseName string, got []rib.ResolveHop, want []expectedStep) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("[%s] [resolve_chain_steps] want %d step(s), got %d", caseName, len(want), len(got))
	}
	for i, w := range want {
		g := got[i]
		if g.Step != w.Step {
			t.Fatalf("[%s] [resolve_step[%d].step] want %d, got %d", caseName, i, w.Step, g.Step)
		}
		if g.Target != w.Target {
			t.Fatalf("[%s] [resolve_step[%d].target] want %s, got %s", caseName, i, w.Target, g.Target)
		}
		gotBest := ""
		if g.Chosen != nil {
			gotBest = g.Chosen.ID
		}
		if gotBest != w.BestID {
			t.Fatalf("[%s] [resolve_step[%d].best_id] want %q, got %q", caseName, i, w.BestID, gotBest)
		}
	}
}
