// Package e2e contains black-box end-to-end tests. They start the two real
// HTTP services (the controller API with its reconcile loop and SQLite
// database, and the independent actual-resource service with its fault
// control plane) and talk to both only over HTTP. Assertions about "actual
// ownership" come from the resource service's own API, never from the
// controller's status, so the expected answers are not generated by the code
// under test.
package e2e

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"resourcecontroller/internal/adapter"
	"resourcecontroller/internal/api"
	"resourcecontroller/internal/diag"
	"resourcecontroller/internal/fakecloud"
	"resourcecontroller/internal/reconcile"
	"resourcecontroller/internal/store"
)

// safeBuffer is a mutex-guarded buffer both services' loggers write into.
type safeBuffer struct {
	mu sync.Mutex
	b  bytes.Buffer
}

func (s *safeBuffer) Write(p []byte) (int, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.b.Write(p)
}

func (s *safeBuffer) String() string {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.b.String()
}

type harness struct {
	t       *testing.T
	ctrlURL string
	fakeURL string
	logs    *safeBuffer
	http    *http.Client

	cancel  context.CancelFunc
	rec     *reconcile.Reconciler
	ctrlSrv *httptest.Server
	fakeSrv *httptest.Server
	st      *store.Store
}

func startHarness(t *testing.T) *harness {
	t.Helper()
	ctx, cancel := context.WithCancel(context.Background())
	logs := &safeBuffer{}

	fakeSvc := fakecloud.NewService(diag.New(logs, "fakecloud"))
	fakeSrv := httptest.NewServer(fakeSvc.Handler())

	dbDSN := "file:" + filepath.Join(t.TempDir(), "e2e.db") +
		"?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)"
	st, err := store.Open(ctx, dbDSN)
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	log := diag.New(logs, "controller")
	rec := reconcile.New(st, adapter.New(fakeSrv.URL, log.With("component", "adapter")),
		log.With("component", "reconcile"), reconcile.Config{
			Workers: 2, ResyncInterval: 500 * time.Millisecond,
			BackoffBase: 40 * time.Millisecond, BackoffMax: 500 * time.Millisecond,
		})
	go rec.Run(ctx)

	apiSrv := httptest.NewServer((&api.Server{
		Store: st, Enqueuer: rec, Log: log.With("component", "api"),
	}).Handler())

	h := &harness{
		t: t, ctrlURL: apiSrv.URL, fakeURL: fakeSrv.URL, logs: logs,
		http:   &http.Client{Timeout: 5 * time.Second},
		cancel: cancel, rec: rec, ctrlSrv: apiSrv, fakeSrv: fakeSrv, st: st,
	}
	t.Cleanup(h.close)
	return h
}

func (h *harness) close() {
	h.cancel()
	h.rec.Stop()
	h.ctrlSrv.Close()
	h.fakeSrv.Close()
	h.st.Close()
}

// ---- low level HTTP helpers ----

func (h *harness) do(method, url string, body any, headers map[string]string) (int, []byte) {
	h.t.Helper()
	var rdr io.Reader
	if body != nil {
		b, _ := json.Marshal(body)
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, url, rdr)
	if err != nil {
		h.t.Fatalf("build request: %v", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := h.http.Do(req)
	if err != nil {
		h.t.Fatalf("%s %s: %v", method, url, err)
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	return resp.StatusCode, b
}

// ---- controller API ----

type widgetStatusView struct {
	ObservedGeneration   int64  `json:"observedGeneration"`
	ReconciledGeneration int64  `json:"reconciledGeneration"`
	ExternalID           string `json:"externalId"`
	ExternalVersion      int64  `json:"externalVersion"`
	Phase                string `json:"phase"`
	LastAttempt          *struct {
		Phase    string `json:"phase"`
		Decision string `json:"decision"`
		Action   string `json:"action"`
		Reason   string `json:"reason"`
		Category string `json:"category"`
	} `json:"lastAttempt"`
}

type widgetView struct {
	Metadata struct {
		Name            string   `json:"name"`
		Generation      int64    `json:"generation"`
		ResourceVersion int64    `json:"resourceVersion"`
		Finalizers      []string `json:"finalizers"`
	} `json:"metadata"`
	Spec struct {
		Replicas int    `json:"replicas"`
		Color    string `json:"color"`
	} `json:"spec"`
	Status widgetStatusView `json:"status"`
}

func (h *harness) createWidget(name, color string, replicas int, secret string) (int, *widgetView) {
	status, b := h.do(http.MethodPost, h.ctrlURL+"/api/v1/widgets", map[string]any{
		"metadata": map[string]string{"name": name},
		"spec": map[string]any{
			"replicas": replicas, "color": color, "secretToken": secret,
		},
	}, nil)
	if status >= 300 {
		return status, nil
	}
	var v widgetView
	_ = json.Unmarshal(b, &v)
	return status, &v
}

func (h *harness) getWidget(name string) (int, *widgetView) {
	status, b := h.do(http.MethodGet, h.ctrlURL+"/api/v1/widgets/"+name, nil, nil)
	if status != http.StatusOK {
		return status, nil
	}
	var v widgetView
	if err := json.Unmarshal(b, &v); err != nil {
		h.t.Fatalf("decode widget: %v: %s", err, b)
	}
	return status, &v
}

func (h *harness) putWidget(name string, rv int64, color string, replicas int) (int, *widgetView) {
	status, b := h.do(http.MethodPut, h.ctrlURL+"/api/v1/widgets/"+name, map[string]any{
		"spec": map[string]any{"replicas": replicas, "color": color},
	}, map[string]string{"If-Match": fmt.Sprintf("%d", rv)})
	if status >= 300 {
		return status, nil
	}
	var v widgetView
	_ = json.Unmarshal(b, &v)
	return status, &v
}

func (h *harness) deleteWidget(name string) int {
	status, _ := h.do(http.MethodDelete, h.ctrlURL+"/api/v1/widgets/"+name, nil, nil)
	return status
}

// ---- fake service API ----

type fakeResource struct {
	ID      string `json:"id"`
	Version int64  `json:"version"`
	Spec    struct {
		Replicas int    `json:"replicas"`
		Color    string `json:"color"`
	} `json:"spec"`
}

func (h *harness) fakeGet(id string) (int, *fakeResource) {
	status, b := h.do(http.MethodGet, h.fakeURL+"/v1/widgets/"+id, nil, nil)
	if status != http.StatusOK {
		return status, nil
	}
	var r fakeResource
	_ = json.Unmarshal(b, &r)
	return status, &r
}

func (h *harness) fakePutRaw(id, color string, replicas int, ifMatch string) int {
	headers := map[string]string{}
	if ifMatch != "" {
		headers["If-Match"] = ifMatch
	}
	status, _ := h.do(http.MethodPut, h.fakeURL+"/v1/widgets/"+id, map[string]any{
		"name": "externally-rolled",
		"spec": map[string]any{"replicas": replicas, "color": color},
	}, headers)
	return status
}

func (h *harness) fakeListCount() int {
	status, b := h.do(http.MethodGet, h.fakeURL+"/v1/widgets", nil, nil)
	if status != http.StatusOK {
		h.t.Fatalf("fake list status %d", status)
	}
	var list struct {
		Items []json.RawMessage `json:"items"`
	}
	_ = json.Unmarshal(b, &list)
	return len(list.Items)
}

func (h *harness) armFault(op, kind string, times int) {
	status, b := h.do(http.MethodPut, h.fakeURL+"/internal/faults/"+op,
		map[string]any{"kind": kind, "times": times}, nil)
	if status != http.StatusOK {
		h.t.Fatalf("arm fault %s/%s: %d %s", op, kind, status, b)
	}
}

func (h *harness) clearFaults() {
	h.do(http.MethodDelete, h.fakeURL+"/internal/faults", nil, nil)
}

// ---- polling ----

func (h *harness) waitFor(desc string, timeout time.Duration, fn func() bool) {
	h.t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if fn() {
			return
		}
		time.Sleep(25 * time.Millisecond)
	}
	if !fn() {
		h.t.Fatalf("timed out waiting for: %s", desc)
	}
}

func (h *harness) waitReady(name string, gen int64) *widgetView {
	h.t.Helper()
	var last *widgetView
	h.waitFor(name+" ready at gen "+fmt.Sprint(gen), 12*time.Second, func() bool {
		_, w := h.getWidget(name)
		last = w
		return w != nil && w.Status.Phase == "Ready" &&
			w.Status.ReconciledGeneration == gen && w.Status.ObservedGeneration == gen
	})
	return last
}

func (h *harness) waitGone(name string) {
	h.t.Helper()
	h.waitFor(name+" fully deleted", 12*time.Second, func() bool {
		status, _ := h.getWidget(name)
		return status == http.StatusNotFound
	})
}

// eachTest uses a unique resource name prefix so cases cannot interact.
func assertContains(t *testing.T, haystack, needle, what string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("expected %s %q in output", what, needle)
	}
}

func assertNotContains(t *testing.T, haystack, needle, what string) {
	t.Helper()
	if strings.Contains(haystack, needle) {
		t.Errorf("did not expect %s %q in output", what, needle)
	}
}
