package reconciler

import (
	"context"
	"testing"

	"infraplanner/internal/journal"
	"infraplanner/internal/model"
	"infraplanner/internal/provider"
)

// fixture wires a real SQLite journal (:memory:) to the real simulated
// provider through the production reconciler. The expected results in these
// tests are hand-authored, not generated by the code under test.
type fixture struct {
	t     *testing.T
	store *journal.Store
	sim   *provider.Sim
	rec   *Service
	ctx   context.Context
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	store, err := journal.Open(":memory:")
	if err != nil {
		t.Fatalf("open journal: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })
	sim := provider.NewSim()
	rec := New(store, sim, 3)
	return &fixture{t: t, store: store, sim: sim, rec: rec, ctx: context.Background()}
}

// seedStack seeds the simulated world with an existing stack and returns the
// physical ids keyed by logical name. Live resources carry their resolved
// logical references exactly as a real provider observation would.
func (f *fixture) seedStack() map[string]string {
	ids := map[string]string{}
	seed := func(l model.Live) {
		f.sim.Seed(l)
		ids[l.Key.Name] = l.ID
	}
	seed(model.Live{
		Key: model.Key{Kind: model.KindVPC, Name: "main"}, ID: "live-vpc",
		Attrs: map[string]string{"cidr": "10.0.0.0/8", "region": "east"},
		Refs:  map[string]model.Ref{}})
	seed(model.Live{
		Key: model.Key{Kind: model.KindSubnet, Name: "web"}, ID: "live-sub",
		Attrs: map[string]string{"cidr": "10.1.0.0/16", "zone": "z1"},
		Refs:  map[string]model.Ref{"network_ref": {Kind: model.KindVPC, Name: "main"}}})
	seed(model.Live{
		Key: model.Key{Kind: model.KindInstance, Name: "api"}, ID: "live-inst",
		Attrs: map[string]string{"image": "img-1", "shape": "small"},
		Refs:  map[string]model.Ref{"subnet_ref": {Kind: model.KindSubnet, Name: "web"}}})
	return ids
}

func desiredStack() []model.Desired {
	return []model.Desired{
		{Kind: model.KindVPC, Name: "main",
			Attrs: map[string]string{"cidr": "10.0.0.0/8", "region": "east"}},
		{Kind: model.KindSubnet, Name: "web",
			Attrs: map[string]string{"cidr": "10.1.0.0/16", "zone": "z1"},
			Refs:  map[string]model.Ref{"network_ref": {Kind: model.KindVPC, Name: "main"}}},
		{Kind: model.KindInstance, Name: "api",
			Attrs: map[string]string{"image": "img-1", "shape": "small"},
			Refs:  map[string]model.Ref{"subnet_ref": {Kind: model.KindSubnet, Name: "web"}}},
	}
}

func assertErr(t *testing.T, err error, cat, code string) {
	t.Helper()
	if err == nil {
		t.Fatalf("expected %s/%s, got nil", cat, code)
	}
	me, ok := model.AsError(err)
	if !ok {
		t.Fatalf("expected typed error, got %T %v", err, err)
	}
	if me.Category != cat || me.Code != code {
		t.Fatalf("error = %s/%s, want %s/%s", me.Category, me.Code, cat, code)
	}
}

func assertRespErr(t *testing.T, r *ApplyResponse, cat, code string) {
	t.Helper()
	if r == nil || r.Error == nil {
		t.Fatalf("expected response error %s/%s, got %+v", cat, code, r)
	}
	if r.Error.Category != cat || r.Error.Code != code {
		t.Fatalf("response error = %s/%s, want %s/%s",
			r.Error.Category, r.Error.Code, cat, code)
	}
}

// overwriteLive replaces an existing live resource in place (same physical id),
// modelling an external actor mutating real state between plan and apply.
func (f *fixture) overwriteLive(l model.Live) {
	f.sim.MuLock()
	defer f.sim.MuUnlock()
	f.sim.SetLiveForTest(l)
}

// removeLive deletes a resource from the simulated world out of band.
func (f *fixture) removeLive(k model.Key) {
	f.sim.MuLock()
	defer f.sim.MuUnlock()
	f.sim.DeleteForTest(k)
}
