[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q --strict-markers --tb=short
log_cli = false
filterwarnings =
    error
    ignore::DeprecationWarning:passlib.*
