//! Independent integration-test support for huff-canonical.
//!
//! This crate intentionally re-implements decoding (`indie`) instead of
//! calling `huff_core` decoders: golden vectors generated by the Python
//! reference (`tools/gen_golden.py`) are checked by *two* decoders written in
//! different languages with different algorithms:
//!
//! * the production decoder in `huff-core` (canonical count/base table);
//! * the independent trie walker here (built directly from code lengths).
//!
//! CRC-32 is likewise re-derived here rather than imported.

pub mod indie;
pub mod http;
