[package]
name = "cuckoo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
xxhash-rust = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
getrandom = { workspace = true }
