package replay_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"igmpq/internal/cats"
	"igmpq/internal/engine"
	"igmpq/internal/model"
	"igmpq/internal/replay"
)

// expectTransition mirrors the compared fields of engine.Transition.
// The expected values in testdata/scenarios/*.json are hand-derived
// (see testdata/scenarios/README.md), never generated by the engine.
type expectTransition struct {
	TimeMS int64   `json:"time_ms"`
	Type   string  `json:"type"`
	Iface  string  `json:"iface"`
	Group  string  `json:"group"`
	Member string  `json:"member"`
	Gen    *uint64 `json:"gen"`
	Reason string  `json:"reason"`
}

type expectRejection struct {
	EventIndex int    `json:"event_index"`
	Category   string `json:"category"`
}

type expectInterval struct {
	StartMS int64  `json:"start_ms"`
	EndMS   *int64 `json:"end_ms"`
}

type scenarioFile struct {
	Name     string          `json:"name"`
	Config   json.RawMessage `json:"config"`
	Events   []model.Event   `json:"events"`
	RunUntil *int64          `json:"run_until,omitempty"`
	Expect   struct {
		Transitions []expectTransition          `json:"transitions"`
		Rejections  []expectRejection           `json:"rejections"`
		Intervals   map[string][]expectInterval `json:"intervals"`
		FinalGroups map[string]engine.GroupView `json:"final_groups"`
	} `json:"expect"`
}

func loadScenario(t *testing.T, path string) scenarioFile {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var sf scenarioFile
	if err := json.Unmarshal(data, &sf); err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}
	return sf
}

func actualTransitions(res *replay.Result) []expectTransition {
	out := make([]expectTransition, 0, len(res.Transitions))
	for _, tr := range res.Transitions {
		out = append(out, expectTransition{
			TimeMS: tr.TimeMS, Type: tr.Type, Iface: tr.Iface,
			Group: tr.Group, Member: tr.Member, Gen: tr.Gen, Reason: tr.Reason,
		})
	}
	return out
}

func actualRejections(res *replay.Result) []expectRejection {
	out := make([]expectRejection, 0, len(res.Rejections))
	for _, rj := range res.Rejections {
		out = append(out, expectRejection{EventIndex: rj.EventIndex, Category: rj.Category})
	}
	return out
}

func actualIntervals(res *replay.Result) map[string][]expectInterval {
	out := make(map[string][]expectInterval, len(res.Intervals))
	for k, ivs := range res.Intervals {
		for _, iv := range ivs {
			out[k] = append(out[k], expectInterval{StartMS: iv.StartMS, EndMS: iv.EndMS})
		}
	}
	return out
}

// TestGoldenScenarios runs every scenario in testdata/scenarios and
// compares the engine output field-by-field against the hand-derived
// reference answers embedded in the fixture.
func TestGoldenScenarios(t *testing.T) {
	paths, err := filepath.Glob("../../testdata/scenarios/s*.json")
	if err != nil || len(paths) == 0 {
		t.Fatalf("no scenarios found: %v", err)
	}
	for _, path := range paths {
		sf := loadScenario(t, path)
		t.Run(sf.Name, func(t *testing.T) {
			res, err := replay.Run(replay.Scenario{
				Name: sf.Name, Config: sf.Config, Events: sf.Events, RunUntil: sf.RunUntil,
			})
			if err != nil {
				t.Fatalf("run: %v", err)
			}
			if got := actualTransitions(res); !reflect.DeepEqual(got, sf.Expect.Transitions) {
				gotJSON, _ := json.MarshalIndent(got, "", "  ")
				t.Fatalf("transitions mismatch\ngot:  %s", gotJSON)
			}
			if got := actualRejections(res); !reflect.DeepEqual(got, sf.Expect.Rejections) {
				t.Fatalf("rejections mismatch\ngot:  %+v\nwant: %+v", got, sf.Expect.Rejections)
			}
			if got := actualIntervals(res); !reflect.DeepEqual(got, sf.Expect.Intervals) {
				t.Fatalf("intervals mismatch\ngot:  %+v\nwant: %+v", got, sf.Expect.Intervals)
			}
			if !reflect.DeepEqual(res.FinalGroups, sf.Expect.FinalGroups) {
				t.Fatalf("final groups mismatch\ngot:  %+v\nwant: %+v", res.FinalGroups, sf.Expect.FinalGroups)
			}
		})
	}
}

func TestRunUntilBeforeLastEvent(t *testing.T) {
	bad := int64(10)
	_, err := replay.Run(replay.Scenario{
		Name:   "bad",
		Config: json.RawMessage(`{"interfaces":["eth0"]}`),
		Events: []model.Event{
			{TimeMS: 100, Type: model.EventReport, Iface: "eth0", Group: "239.1.1.1", Member: "10.0.0.1"},
		},
		RunUntil: &bad,
	})
	if cats.CategoryOf(err) != cats.InvalidScenario {
		t.Fatalf("category=%s, want invalid_scenario (err=%v)", cats.CategoryOf(err), err)
	}
}

func TestEmptyScenario(t *testing.T) {
	_, err := replay.Run(replay.Scenario{
		Name:   "empty",
		Config: json.RawMessage(`{"interfaces":["eth0"]}`),
	})
	if cats.CategoryOf(err) != cats.InvalidScenario {
		t.Fatalf("category=%s, want invalid_scenario (err=%v)", cats.CategoryOf(err), err)
	}
}
