// Package replay reconstructs routing for a fixed, named flow set against two
// persisted ring generations and reports exactly which flows moved and why,
// alongside the full re-modulo baseline.
//
// The flow set is intentionally external input (a JSON fixture), never
// generated by the code under test inside a test: the golden corpus is
// produced by cmd/genfixtures from a documented seed and committed to
// testdata. Replay rebuilds rings from the persisted member/allocation rows,
// then re-derives ownership, so a run answers "what would this flow set do on
// version A vs version B".
package replay

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"

	"flowrouter/internal/apperr"
	"flowrouter/internal/flow"
	"flowrouter/internal/ring"
	"flowrouter/internal/store"
)

// FlowSet is a fixed corpus of five-tuples with a name and the seed it was
// generated with. The seed is metadata for reproducibility, not used at replay.
type FlowSet struct {
	Name  string           `json:"name"`
	Seed  int64            `json:"seed"`
	Flows []flow.FiveTuple `json:"flows"`
}

// tupleWire is the JSON shape of a tuple in fixtures (addresses as strings).
type tupleWire struct {
	SrcIP   string `json:"src_ip"`
	DstIP   string `json:"dst_ip"`
	Proto   uint8  `json:"proto"`
	SrcPort uint16 `json:"src_port"`
	DstPort uint16 `json:"dst_port"`
}

type flowSetWire struct {
	Name  string      `json:"name"`
	Seed  int64       `json:"seed"`
	Flows []tupleWire `json:"flows"`
}

// ParseFlowSet decodes and strictly validates a flow-set JSON document.
func ParseFlowSet(raw []byte) (*FlowSet, error) {
	var w flowSetWire
	if err := json.Unmarshal(raw, &w); err != nil {
		return nil, apperr.Invalid("FLOWSET_MALFORMED", "flow set is not valid JSON").WithCause(err)
	}
	if w.Name == "" {
		return nil, apperr.Invalid("FLOWSET_NO_NAME", "flow set has no name")
	}
	if len(w.Flows) == 0 {
		return nil, apperr.Invalid("FLOWSET_EMPTY", "flow set contains no flows")
	}
	fs := &FlowSet{Name: w.Name, Seed: w.Seed, Flows: make([]flow.FiveTuple, 0, len(w.Flows))}
	seen := map[string]bool{}
	for i, t := range w.Flows {
		f, err := flow.Parse(t.SrcIP, t.DstIP, t.Proto, t.SrcPort, t.DstPort)
		if err != nil {
			return nil, apperr.Invalid("FLOWSET_BAD_TUPLE",
				fmt.Sprintf("flows[%d]: %v", i, err)).WithCause(err)
		}
		key := f.CanonicalKey()
		if seen[key] {
			return nil, apperr.Invalid("FLOWSET_DUP_TUPLE",
				fmt.Sprintf("flows[%d]: duplicate flow %s", i, key))
		}
		seen[key] = true
		fs.Flows = append(fs.Flows, f)
	}
	return fs, nil
}

// persistedMember is the member shape serialized into ring_versions.
type persistedMember struct {
	ID     string `json:"id"`
	Weight int    `json:"weight"`
	Up     bool   `json:"up"`
	OnRing bool   `json:"on_ring"`
}

// Planner executes replay runs against a store.
type Planner struct {
	st         *store.Store
	vnodesPerW int
	maxVNodes  int
}

func NewPlanner(st *store.Store, vnodesPerWeight, maxVNodes int) *Planner {
	return &Planner{st: st, vnodesPerW: vnodesPerWeight, maxVNodes: maxVNodes}
}

// ringForVersion loads a persisted generation and rebuilds its ring. Only
// members that were actually on the ring (positive weight and up) are used;
// the persisted allocation is cross-checked against a fresh rebuild so a
// corrupted/inconsistent row surfaces as COMPUTATION_FAILURE rather than
// silently producing a different ring.
func (p *Planner) ringForVersion(ctx context.Context, version int64) (*ring.Ring, *store.RingVersionRow, error) {
	row, err := p.st.RingVersion(ctx, version)
	if err != nil {
		return nil, nil, err
	}
	var members []persistedMember
	if err := json.Unmarshal(row.MembersJSON, &members); err != nil {
		return nil, nil, apperr.Compute("VERSION_ROW_CORRUPT",
			fmt.Sprintf("version %d members JSON is unparsable", version)).WithCause(err)
	}
	var eff []ring.Member
	for _, m := range members {
		if m.OnRing {
			eff = append(eff, ring.Member{ID: m.ID, Weight: m.Weight})
		}
	}
	rg, err := ring.Build(eff, p.vnodesPerW, p.maxVNodes)
	if err != nil {
		return nil, nil, err
	}
	var storedAlloc struct {
		Counts map[string]int `json:"counts"`
		Total  int            `json:"total"`
	}
	if err := json.Unmarshal(row.AllocationJSON, &storedAlloc); err != nil {
		return nil, nil, apperr.Compute("VERSION_ROW_CORRUPT",
			fmt.Sprintf("version %d allocation JSON is unparsable", version)).WithCause(err)
	}
	got := rg.VNodeCounts()
	if storedAlloc.Total != rg.Len() {
		return nil, nil, apperr.Compute("ALLOCATION_MISMATCH",
			fmt.Sprintf("version %d stored total %d != rebuilt %d", version, storedAlloc.Total, rg.Len()))
	}
	for id, c := range storedAlloc.Counts {
		if got[id] != c {
			return nil, nil, apperr.Compute("ALLOCATION_MISMATCH",
				fmt.Sprintf("version %d member %s stored %d != rebuilt %d", version, id, c, got[id]))
		}
	}
	return rg, &row, nil
}

// RunResult is the API-facing report.
type RunResult struct {
	RunID       string     `json:"run_id"`
	Status      string     `json:"status"`
	FlowSet     string     `json:"flow_set"`
	FlowCount   int        `json:"flow_count"`
	FromVersion int64      `json:"from_version"`
	ToVersion   int64      `json:"to_version"`
	Diff        *ring.Diff `json:"diff,omitempty"`
	Error       *errView   `json:"error,omitempty"`
}

type errView struct {
	Kind    string `json:"kind"`
	Code    string `json:"code"`
	Message string `json:"message"`
}

func newRunID() string {
	var b [8]byte
	_, _ = rand.Read(b[:])
	return "run-" + hex.EncodeToString(b[:]) + "-" + fmt.Sprintf("%d", time.Now().UnixNano())
}

// Execute runs a replay, persisting the run row (RUNNING then COMPLETED/FAILED)
// plus every decision (for both versions) and every migration.
func (p *Planner) Execute(ctx context.Context, set *FlowSet, fromVersion, toVersion int64) (*RunResult, error) {
	runID := newRunID()
	now := time.Now()
	res := &RunResult{
		RunID: runID, FlowSet: set.Name, FlowCount: len(set.Flows),
		FromVersion: fromVersion, ToVersion: toVersion,
	}
	// Reserve the run row up-front so a later failure leaves a replayable
	// failure record with its classified error.
	if err := p.st.InsertRun(ctx, store.RunRow{
		RunID: runID, CreatedAt: now, FlowSetName: set.Name,
		FlowCount: len(set.Flows), FromVersion: fromVersion, ToVersion: toVersion,
		Status: "RUNNING",
	}); err != nil {
		return nil, err
	}

	oldR, _, err := p.ringForVersion(ctx, fromVersion)
	if err != nil {
		return p.fail(ctx, res, err)
	}
	newR, _, err := p.ringForVersion(ctx, toVersion)
	if err != nil {
		return p.fail(ctx, res, err)
	}

	d := ring.Compare(oldR, newR, set.Flows)
	res.Diff = d
	res.Status = "COMPLETED"

	// Persist decisions for both generations so the run is fully auditable.
	nowDec := time.Now()
	oldDec := make([]store.DecisionRow, 0, len(set.Flows))
	newDec := make([]store.DecisionRow, 0, len(set.Flows))
	migs := make([]store.MigrationRow, 0, len(d.Changes))
	for _, f := range set.Flows {
		h := f.Hash()
		if o, ok := oldR.Lookup(h); ok {
			oldDec = append(oldDec, store.DecisionRow{
				RunID: runID, Version: fromVersion, FlowKey: f.CanonicalKey(),
				FlowHash: h, MemberID: o, Reason: "replay", DecidedAt: nowDec,
			})
		}
		if n, ok := newR.Lookup(h); ok {
			newDec = append(newDec, store.DecisionRow{
				RunID: runID, Version: toVersion, FlowKey: f.CanonicalKey(),
				FlowHash: h, MemberID: n, Reason: "replay", DecidedAt: nowDec,
			})
		}
	}
	for _, c := range d.Changes {
		migs = append(migs, store.MigrationRow{
			RunID: runID, FlowKey: c.FlowKey, FlowHash: c.FlowHash,
			OldMember: c.From, NewMember: c.To, Reason: c.Reason,
		})
	}
	summary, _ := json.Marshal(map[string]any{
		"moved": d.Moved, "stayed": d.Stayed, "move_fraction": d.MoveFraction,
		"baseline_moved": d.BaselineMoved, "baseline_move_fraction": d.BaselineFraction,
	})
	if err := p.st.InsertDecisions(ctx, oldDec); err != nil {
		return p.fail(ctx, res, err)
	}
	if err := p.st.InsertDecisions(ctx, newDec); err != nil {
		return p.fail(ctx, res, err)
	}
	if err := p.st.InsertMigrations(ctx, migs); err != nil {
		return p.fail(ctx, res, err)
	}
	if err := p.st.UpdateRunResult(ctx, runID, "COMPLETED", summary, "", "", ""); err != nil {
		return nil, err
	}
	return res, nil
}

func (p *Planner) fail(ctx context.Context, res *RunResult, cause error) (*RunResult, error) {
	res.Status = "FAILED"
	kind, code, msg := "INTERNAL", "INTERNAL", cause.Error()
	if ae, ok := apperr.As(cause); ok {
		kind, code, msg = string(ae.Kind), ae.Code, ae.Message
	}
	res.Error = &errView{Kind: kind, Code: code, Message: msg}
	summary, _ := json.Marshal(map[string]any{})
	_ = p.st.UpdateRunResult(ctx, res.RunID, "FAILED", summary, kind, code, msg)
	// A classified failure is a normal run outcome and returned to the caller
	// with res.Status=FAILED; an unclassified store failure on the way out is
	// still surfaced as an error.
	return res, cause
}

// FetchRun reads a persisted run back (report + status + error classification).
func (p *Planner) FetchRun(ctx context.Context, runID string) (*RunResult, error) {
	r, err := p.st.GetRun(ctx, runID)
	if err != nil {
		return nil, err
	}
	out := &RunResult{
		RunID: r.RunID, Status: r.Status, FlowSet: r.FlowSetName,
		FlowCount: r.FlowCount, FromVersion: r.FromVersion, ToVersion: r.ToVersion,
	}
	if r.ErrorKind != "" {
		out.Error = &errView{Kind: r.ErrorKind, Code: r.ErrorCode, Message: r.ErrorMessage}
	}
	if out.Status == "COMPLETED" {
		// Rebuild the Diff view from persisted rows so GET stays self-contained.
		migs, err := p.st.RunMigrations(ctx, runID)
		if err != nil {
			return nil, err
		}
		var sum struct {
			Moved            int     `json:"moved"`
			Stayed           int     `json:"stayed"`
			MoveFraction     float64 `json:"move_fraction"`
			BaselineMoved    int     `json:"baseline_moved"`
			BaselineMoveFrac float64 `json:"baseline_move_fraction"`
		}
		_ = json.Unmarshal(r.Summary, &sum)
		d := &ring.Diff{
			FlowsTotal: r.FlowCount, Stayed: sum.Stayed, Moved: sum.Moved,
			MoveFraction: sum.MoveFraction, BaselineFlowsTotal: r.FlowCount,
			BaselineMoved: sum.BaselineMoved, BaselineFraction: sum.BaselineMoveFrac,
		}
		for _, m := range migs {
			d.Changes = append(d.Changes, ring.OwnerChange{
				FlowKey: m.FlowKey, FlowHash: m.FlowHash,
				From: m.OldMember, To: m.NewMember, Reason: m.Reason,
			})
		}
		out.Diff = d
	}
	return out, nil
}
