// Package replay_test contains integration tests that load hand-authored JSON
// fixtures and replay them through the real engine against both the SQLite
// store and the in-memory store. The fixture expectations are an independent
// oracle authored by hand, never generated by the engine under test.
package replay_test

import (
	"context"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"natlab/internal/config"
	"natlab/internal/memstore"
	"natlab/internal/nat"
	"natlab/internal/replay"
	"natlab/internal/store"
	"natlab/internal/testutil"
)

// fixtureDir is resolved relative to this test file: internal/replay/.
func fixtureDir() string { return filepath.Join("..", "..", "testdata", "fixtures") }

func listFixtures(t *testing.T) []string {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join(fixtureDir(), "*.json"))
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(paths)
	if len(paths) == 0 {
		t.Fatal("no fixtures found")
	}
	return paths
}

// runAgainst replays one fixture on a fresh store built by newStore.
func runAgainst(t *testing.T, path, backend string, newStore func() nat.StateStore) {
	t.Helper()
	fx, err := replay.LoadFixture(path)
	if err != nil {
		t.Fatalf("load fixture: %v", err)
	}
	rl := testutil.NewRun(t, "replay-"+backend)
	rl.Infof("fixture=%s backend=%s packets=%d", fx.Name, backend, len(fx.Packets))

	cfg := config.Defaults()
	// Unique run id per backend/fixture so cached per-run engine state never
	// leaks across subtests or across the two store backends.
	runID := rl.RunID + "-" + backend + "-" + fx.Name
	runner := replay.NewRunner(cfg, newStore, runID)
	rep, err := runner.Run(context.Background(), fx)
	if err != nil {
		t.Fatalf("replay run error: %v", err)
	}
	for i := range rep.Results {
		r := &rep.Results[i]
		verdict := "accepted"
		if !r.Match || (r.Got != nil && !r.Got.Accepted) {
			verdict = string(r.Got.Category) + "/" + r.Got.Code
		}
		port := uint16(0)
		if r.Got != nil && r.Got.Mapping != nil {
			port = r.Got.Mapping.MappedPort
		}
		rl.Step(r.Index, backend, verdict, r.Got != nil && r.Got.Accepted,
			"match="+boolStr(r.Match)+" port="+uintStr(port)+" why="+r.Mismatch)
	}
	rl.Infof("fixture=%s passed=%v failures=%d", fx.Name, rep.Passed, len(rep.Failures))
	rl.Finish(rep.Passed)
	if !rep.Passed {
		for _, msg := range rep.Failures {
			t.Errorf("%s", msg)
		}
	}
}

// newSQLite returns a factory opening an isolated on-disk temp SQLite file.
func newSQLite(t *testing.T) func() nat.StateStore {
	return func() nat.StateStore {
		dir := t.TempDir()
		st, err := store.Open(context.Background(), filepath.Join(dir, "int.db"))
		if err != nil {
			t.Fatalf("open sqlite: %v", err)
		}
		t.Cleanup(func() { _ = st.Close() })
		return st
	}
}

func newMem() func() nat.StateStore { return func() nat.StateStore { return memstore.New() } }

// TestFixtures_SQLite replays every fixture through the real SQLite store.
func TestFixtures_SQLite(t *testing.T) {
	for _, path := range listFixtures(t) {
		name := strings.TrimSuffix(filepath.Base(path), ".json")
		t.Run(name, func(t *testing.T) {
			runAgainst(t, path, "sqlite", newSQLite(t))
		})
	}
}

// TestFixtures_Mem replays every fixture through the in-memory store too, so
// that store-agnostic engine behavior is verified on two implementations.
func TestFixtures_Mem(t *testing.T) {
	for _, path := range listFixtures(t) {
		name := strings.TrimSuffix(filepath.Base(path), ".json")
		t.Run(name, func(t *testing.T) {
			runAgainst(t, path, "mem", newMem())
		})
	}
}

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func uintStr(p uint16) string {
	if p == 0 {
		return "-"
	}
	const digits = "0123456789"
	if p == 0 {
		return "0"
	}
	var buf [5]byte
	i := len(buf)
	for p > 0 {
		i--
		buf[i] = digits[p%10]
		p /= 10
	}
	return string(buf[i:])
}
