// Package replay provides the independent verification side used by tests and
// by `clsnapctl verify`.
//
// Crucially it does NOT reuse the snapshot coordinator's completion logic: it
// reads durable node records (local state + captured channel messages) and
// independently recomputes:
//
//   - each node's local total by summing the recorded account balances,
//   - each captured channel total by summing captured transfer amounts,
//   - the global snapshot total = sum(local totals) + sum(channel sums).
//     A captured message is tokens that have left the sender's recorded local
//     state but not yet reached the receiver's, so they live "in the
//     channel" and must be ADDED. The FIFO marker rule structurally prevents
//     double counting: a message credited before the receiver records is
//     already in its local total and cannot also be captured (the sender's
//     marker sits behind it in the same FIFO channel).
//   - token conservation against an expected total.
//
// Expected totals in the fixtures are hand-computed in the scenario files,
// not generated by the kernel.
package replay

import (
	"context"
	"fmt"
	"sort"

	"clsnap/internal/apperr"
	"clsnap/internal/protocol"
	"clsnap/internal/store"
)

// NodeView is one node's record for a round plus bookkeeping.
type NodeView struct {
	Node       protocol.NodeID
	Phase      protocol.Phase
	LocalTotal uint64
	// Inbound captures: map[from] = sum of amounts captured on from->node.
	Channels map[protocol.NodeID]uint64
	// Captured detail for logs.
	CapturedCount map[protocol.NodeID]int
}

// GlobalView is the independently assembled snapshot.
type GlobalView struct {
	Snapshot   protocol.SnapshotID
	Nodes      []NodeView
	NodeTotal  uint64 // sum of recorded local totals
	ChanTotal  uint64 // sum of captured in-flight amounts
	GlobalSum  uint64 // NodeTotal - ChanTotal
	Complete   bool
	Incomplete []string
}

// Assemble reads every node record of one round and recomputes the global
// view. Missing or non-complete records make the view incomplete (a concrete
// failure category, snapshot_incomplete), never silently partial.
func Assemble(ctx context.Context, st store.SnapshotStore, nodes []protocol.NodeID, snap protocol.SnapshotID) (GlobalView, error) {
	gv := GlobalView{Snapshot: snap, Complete: true}
	for _, n := range nodes {
		rec, err := st.GetRecord(ctx, n, snap)
		if err != nil {
			if isUnknown(err) {
				gv.Complete = false
				gv.Incomplete = append(gv.Incomplete, string(n)+":no-record")
				continue
			}
			return gv, err
		}
		nv := NodeView{
			Node: n, Phase: rec.Phase,
			Channels:      map[protocol.NodeID]uint64{},
			CapturedCount: map[protocol.NodeID]int{},
		}
		if rec.Phase != protocol.PhaseComplete {
			gv.Complete = false
			gv.Incomplete = append(gv.Incomplete, fmt.Sprintf("%s:%s", n, rec.Phase))
		}
		if rec.Local != nil {
			var sum uint64
			for _, a := range rec.Local.Accounts {
				sum += a.Balance
			}
			if sum != rec.Local.Total {
				return gv, apperr.Failure(apperr.CodeReplayMismatch, "replay.Assemble",
					fmt.Sprintf("node %s stored local total %d != recomputed %d (local-state corruption)",
						n, rec.Local.Total, sum), nil)
			}
			nv.LocalTotal = sum
			gv.NodeTotal += sum
		}
		for from, ch := range rec.Channels {
			var s uint64
			for _, m := range ch.Messages {
				s += m.Amount
			}
			if s != ch.Sum {
				return gv, apperr.Failure(apperr.CodeReplayMismatch, "replay.Assemble",
					fmt.Sprintf("node %s channel %s->%s stored sum %d != recomputed %d",
						n, from, n, ch.Sum, s), nil)
			}
			nv.Channels[from] = s
			nv.CapturedCount[from] = len(ch.Messages)
			if ch.Closed {
				gv.ChanTotal += s
			} else {
				gv.Complete = false
				gv.Incomplete = append(gv.Incomplete, fmt.Sprintf("channel-%s-%s-open", from, n))
			}
		}
		gv.Nodes = append(gv.Nodes, nv)
	}
	sort.Slice(gv.Nodes, func(i, j int) bool { return gv.Nodes[i].Node < gv.Nodes[j].Node })
	if !gv.Complete {
		sort.Strings(gv.Incomplete)
		return gv, apperr.Conflict(apperr.CodeSnapshotIncomplete,
			fmt.Sprintf("snapshot %s incomplete: %v", snap, gv.Incomplete))
	}
	gv.GlobalSum = gv.NodeTotal + gv.ChanTotal
	return gv, nil
}

// Conservation compares the independent global sum with an expected total.
func Conservation(gv GlobalView, expected uint64) error {
	if !gv.Complete {
		return apperr.Conflict(apperr.CodeSnapshotIncomplete,
			fmt.Sprintf("cannot check conservation on incomplete snapshot: %v", gv.Incomplete))
	}
	if gv.GlobalSum != expected {
		return apperr.Failure(apperr.CodeReplayMismatch, "replay.Conservation",
			fmt.Sprintf("tokens not conserved: global snapshot sum %d != expected %d (local %d, in-flight %d)",
				gv.GlobalSum, expected, gv.NodeTotal, gv.ChanTotal), nil)
	}
	return nil
}

func isUnknown(err error) bool {
	ae, ok := apperr.As(err)
	return ok && ae.Code == apperr.CodeUnknownSnapshot
}
