package ring_test

import (
	"fmt"
	"math"
	"testing"

	"flowrouter/internal/ring"
	"flowrouter/internal/testutil"
)

// buildScenarioRing constructs a ring for one scenario version using only
// on-ring (positive weight AND up) members, exactly as the router would.
func buildScenarioRing(t *testing.T, ver testutil.ScenarioVer, vpw, cap int) *ring.Ring {
	t.Helper()
	var ms []ring.Member
	for _, m := range ver.Members {
		if m.Weight > 0 && m.IsUp() {
			ms = append(ms, ring.Member{ID: m.ID, Weight: m.Weight})
		}
	}
	r, err := ring.Build(ms, vpw, cap)
	if err != nil {
		t.Fatalf("ring build: %v", err)
	}
	return r
}

func allScenarioTransitions(sc *testutil.Scenario) [][2]int {
	if len(sc.Trans) > 0 {
		return sc.Trans
	}
	out := make([][2]int, 0, len(sc.Versions)-1)
	for i := 0; i+1 < len(sc.Versions); i++ {
		out = append(out, [2]int{i, i + 1})
	}
	return out
}

// TestGoldenAgainstIndependentOracle is the core conformance test: every ring
// ownership, integer allocation, migration count/classification and realized
// traffic share computed by the Go implementation must equal the independent
// Python oracle's committed golden file. The oracle is a separate language and
// separate implementation and its outputs were not generated by this code.
func TestGoldenAgainstIndependentOracle(t *testing.T) {
	for _, fsName := range []string{"flows_smoke", "flows_10k"} {
		flows, _ := testutil.LoadFlowSet(t, fsName)
		golden := testutil.LoadGolden(t, fsName)
		matrix := testutil.LoadScenarios(t)
		if golden.FlowCount != len(flows) {
			t.Fatalf("[%s] golden flow count %d != fixture %d", fsName, golden.FlowCount, len(flows))
		}

		for _, sc := range matrix.Scenarios {
			gs, ok := golden.Scenarios[sc.Name]
			if !ok {
				t.Fatalf("[%s/%s] no golden scenario", fsName, sc.Name)
			}
			vpw := matrix.VNodesPerWeight
			capv := matrix.MaxVNodes
			if sc.MaxVNodes != 0 {
				capv = sc.MaxVNodes
			}
			rings := make([]*ring.Ring, len(sc.Versions))
			t.Run(fmt.Sprintf("%s/%s/allocation", fsName, sc.Name), func(t *testing.T) {
				for i, ver := range sc.Versions {
					rings[i] = buildScenarioRing(t, ver, vpw, capv)
					ga := gs.Allocations[i]
					if rings[i].Len() != ga.Total {
						t.Errorf("version %d total vnodes: got %d want %d", i, rings[i].Len(), ga.Total)
					}
					gotCounts := rings[i].VNodeCounts()
					// All positive/up members must be present with the golden
					// count; off-ring members (weight 0 or down) must be absent
					// from the vnode allocation.
					for _, m := range ver.Members {
						wantC, wantPresent := ga.Counts[m.ID]
						gotC, gotPresent := gotCounts[m.ID]
						onRing := m.Weight > 0 && m.IsUp()
						if onRing {
							if !wantPresent {
								t.Errorf("golden missing on-ring member %s", m.ID)
							}
							if !gotPresent || gotC != wantC {
								t.Errorf("version %d member %s count: got %d(present=%v) want %d",
									i, m.ID, gotC, gotPresent, wantC)
							}
						} else if gotPresent && gotC != 0 {
							t.Errorf("version %d member %s must be off ring, got %d vnodes", i, m.ID, gotC)
						}
						if ga.Strategy == "largest_remainder" && onRing {
							alloc := rings[i].Allocation()
							if alloc.Base[m.ID] != ga.Base[m.ID] {
								t.Errorf("version %d member %s base: got %d want %d",
									i, m.ID, alloc.Base[m.ID], ga.Base[m.ID])
							}
							if alloc.Extra[m.ID] != ga.Extra[m.ID] {
								t.Errorf("version %d member %s extra: got %d want %d",
									i, m.ID, alloc.Extra[m.ID], ga.Extra[m.ID])
							}
						}
					}
					if rings[i].Allocation().Strategy != ga.Strategy {
						t.Errorf("version %d strategy: got %s want %s",
							i, rings[i].Allocation().Strategy, ga.Strategy)
					}
				}
			})

			t.Run(fmt.Sprintf("%s/%s/ownership", fsName, sc.Name), func(t *testing.T) {
				if rings[0] == nil {
					for i, ver := range sc.Versions {
						rings[i] = buildScenarioRing(t, ver, vpw, capv)
					}
				}
				for fi, f := range flows {
					gow := gs.Owners[fi]
					if gow.K != f.CanonicalKey() {
						t.Fatalf("flow %d key mismatch: go=%q golden=%q", fi, f.CanonicalKey(), gow.K)
					}
					if gow.H != f.Hash() {
						t.Fatalf("flow %d %s hash mismatch: go=%d golden=%d", fi, gow.K, f.Hash(), gow.H)
					}
					for vi, r := range rings {
						got, ok := r.LookupFlow(f)
						var wantPtr *string
						if vi < len(gow.O) {
							wantPtr = gow.O[vi]
						}
						if wantPtr == nil {
							if ok {
								t.Errorf("flow %s v%d: got owner %s, want empty ring", gow.K, vi, got)
							}
							continue
						}
						if !ok || got != *wantPtr {
							t.Fatalf("flow %s v%d: got %q(ok=%v) want %q", gow.K, vi, got, ok, *wantPtr)
						}
					}
				}
			})

			t.Run(fmt.Sprintf("%s/%s/transitions", fsName, sc.Name), func(t *testing.T) {
				if rings[0] == nil {
					for i, ver := range sc.Versions {
						rings[i] = buildScenarioRing(t, ver, vpw, capv)
					}
				}
				for _, tr := range allScenarioTransitions(&sc) {
					a, b := tr[0], tr[1]
					key := fmt.Sprintf("%d->%d", a, b)
					want, ok := gs.Transitions[key]
					if !ok {
						t.Fatalf("golden missing transition %s", key)
					}
					d := ring.Compare(rings[a], rings[b], flows)
					if d.Moved != want.Moved || d.Stayed != want.Stayed {
						t.Errorf("transition %s moved/stayed: got %d/%d want %d/%d",
							key, d.Moved, d.Stayed, want.Moved, want.Stayed)
					}
					if d.Moved+d.Stayed != len(flows) {
						t.Errorf("transition %s moved+stayed=%d != total %d",
							key, d.Moved+d.Stayed, len(flows))
					}
					if math.Abs(d.MoveFraction-want.MoveFraction) > 1e-12 {
						t.Errorf("transition %s move fraction: got %.6f want %.6f",
							key, d.MoveFraction, want.MoveFraction)
					}
					if d.BaselineMoved != want.BaselineMoved {
						t.Errorf("transition %s baseline moved: got %d want %d",
							key, d.BaselineMoved, want.BaselineMoved)
					}
					if want.BaselineFraction == nil {
						if d.BaselineMoved != 0 {
							t.Errorf("transition %s baseline undefined but got %d moves",
								key, d.BaselineMoved)
						}
					} else if math.Abs(d.BaselineFraction-*want.BaselineFraction) > 1e-12 {
						t.Errorf("transition %s baseline fraction got %.6f want %.6f",
							key, d.BaselineFraction, *want.BaselineFraction)
					}
					// exact classification counts
					gotReasons := map[string]int{}
					for _, c := range d.Changes {
						gotReasons[c.Reason]++
					}
					if len(gotReasons) != len(want.Reasons) {
						t.Errorf("transition %s reason categories: got %v want %v",
							key, gotReasons, want.Reasons)
					}
					for reason, n := range want.Reasons {
						if gotReasons[reason] != n {
							t.Errorf("transition %s reason %s: got %d want %d",
								key, reason, gotReasons[reason], n)
						}
					}
					// Minimal-migration advantage is meaningful when the member
					// SET changes (add/remove): consistent hashing must move
					// strictly fewer flows than full re-modulo. For a pure
					// weight change the slot count is unchanged so modulo
					// reports 0 moves, but modulo cannot express weights at all
					// (slots stay equal-sized) — that is a baseline blind spot,
					// not a CH regression. Assert it separately: every change
					// in a weight-only transition must be weight_changed.
					idSet := func(r *ring.Ring) map[string]bool {
						m := map[string]bool{}
						for id, c := range r.VNodeCounts() {
							if c > 0 {
								m[id] = true
							}
						}
						return m
					}
					setA, setB := idSet(rings[a]), idSet(rings[b])
					membershipChanged := len(setA) != len(setB)
					if !membershipChanged {
						for id := range setA {
							if !setB[id] {
								membershipChanged = true
								break
							}
						}
					}
					if membershipChanged && want.BaselineFraction != nil {
						if d.Moved >= d.BaselineMoved {
							t.Errorf("transition %s consistent hash moved %d, baseline %d: "+
								"minimal-migration advantage lost",
								key, d.Moved, d.BaselineMoved)
						}
					}
					if !membershipChanged {
						for reason, n := range gotReasons {
							if n > 0 && reason != "weight_changed" {
								t.Errorf("weight-only transition %s has %s=%d moves",
									key, reason, n)
							}
						}
					}
				}
			})

			t.Run(fmt.Sprintf("%s/%s/traffic_share", fsName, sc.Name), func(t *testing.T) {
				if rings[0] == nil {
					for i, ver := range sc.Versions {
						rings[i] = buildScenarioRing(t, ver, vpw, capv)
					}
				}
				for vi, r := range rings {
					counts := map[string]int{}
					routed := 0
					for _, f := range flows {
						if o, ok := r.LookupFlow(f); ok {
							counts[o]++
							routed++
						}
					}
					gt := gs.Traffic[vi]
					if routed != gt.Routed {
						t.Errorf("v%d routed: got %d want %d", vi, routed, gt.Routed)
					}
					for id, wantN := range gt.Counts {
						if counts[id] != wantN {
							t.Errorf("v%d traffic counts %s: got %d want %d",
								vi, id, counts[id], wantN)
						}
					}
					// Verify the conceptual distinction explicitly: realized
					// traffic share is allowed to differ from bucket share.
					for id, wantShare := range gt.Share {
						gotShare := 0.0
						if routed > 0 {
							gotShare = float64(counts[id]) / float64(routed)
						}
						if math.Abs(gotShare-wantShare) > 1e-12 {
							t.Errorf("v%d traffic share %s: got %.6f want %.6f",
								vi, id, gotShare, wantShare)
						}
					}
				}
			})
		}
	}
}

// TestDeterminismAcrossRebuilds checks the stable-mapping guarantee directly:
// the same inputs always yield the same ring, and lookup is a pure function.
func TestDeterminismAcrossRebuilds(t *testing.T) {
	flows, _ := testutil.LoadFlowSet(t, "flows_smoke")
	golden := testutil.LoadGolden(t, "flows_smoke")
	matrix := testutil.LoadScenarios(t)
	sc := matrix.Scenarios[0] // s1_add_member v0
	wantOwners := golden.Scenarios[sc.Name].Owners

	var first map[string]string
	for iteration := 0; iteration < 3; iteration++ {
		r := buildScenarioRing(t, sc.Versions[0], matrix.VNodesPerWeight, matrix.MaxVNodes)
		owners := make(map[string]string, len(flows))
		for fi, f := range flows {
			o, ok := r.Lookup(f.Hash())
			o2, ok2 := r.LookupFlow(f)
			if o != o2 || ok != ok2 {
				t.Fatalf("Lookup/LookupFlow disagree for %s", f.CanonicalKey())
			}
			if !ok {
				t.Fatalf("flow %s has no owner", f.CanonicalKey())
			}
			owners[f.CanonicalKey()] = o
			if wantOwners[fi].O[0] == nil || o != *wantOwners[fi].O[0] {
				t.Fatalf("iteration %d flow %s owner %s != golden %v",
					iteration, f.CanonicalKey(), o, wantOwners[fi].O[0])
			}
		}
		if first == nil {
			first = owners
			continue
		}
		for k, v := range owners {
			if first[k] != v {
				t.Fatalf("rebuild %d changed owner of %s: %s -> %s", iteration, k, first[k], v)
			}
		}
	}
}

// TestStableMappingOnMemberChange verifies rule 1 at the bucket level: when
// adding a member, flows whose old owner remains must stay put; only flows now
// claimed by the new member move. Deleting moves only flows owned by the
// removed member. These are concrete assertions over the smoke corpus.
func TestStableMappingOnMemberChange(t *testing.T) {
	flows, _ := testutil.LoadFlowSet(t, "flows_smoke")
	matrix := testutil.LoadScenarios(t)

	// s1 add: every moved flow must land on hop-d; no other flow may move.
	s1 := matrix.Scenarios[0]
	r0 := buildScenarioRing(t, s1.Versions[0], matrix.VNodesPerWeight, matrix.MaxVNodes)
	r1 := buildScenarioRing(t, s1.Versions[1], matrix.VNodesPerWeight, matrix.MaxVNodes)
	for _, f := range flows {
		before, _ := r0.LookupFlow(f)
		after, _ := r1.LookupFlow(f)
		if before == after {
			continue
		}
		if after != "hop-d" {
			t.Fatalf("add member: flow %s moved %s -> %s, but only hop-d may claim buckets",
				f.CanonicalKey(), before, after)
		}
	}

	// s2 remove: only flows previously owned by hop-c may move.
	s2 := matrix.Scenarios[1]
	a := buildScenarioRing(t, s2.Versions[0], matrix.VNodesPerWeight, matrix.MaxVNodes)
	b := buildScenarioRing(t, s2.Versions[1], matrix.VNodesPerWeight, matrix.MaxVNodes)
	for _, f := range flows {
		before, _ := a.LookupFlow(f)
		after, _ := b.LookupFlow(f)
		if before != after && before != "hop-c" {
			t.Fatalf("remove hop-c: flow %s moved away from surviving member %s",
				f.CanonicalKey(), before)
		}
	}
}

// TestEmptyRingExplicit covers the empty/zero-weight ring edge behavior at the
// ring layer (routing-layer errors are tested in router tests).
func TestEmptyRingExplicit(t *testing.T) {
	r, err := ring.Build(nil, 160, 0)
	if err != nil {
		t.Fatalf("empty build: %v", err)
	}
	if !r.Empty() {
		t.Fatal("nil member ring must be empty")
	}
	if _, ok := r.Lookup(42); ok {
		t.Fatal("empty ring lookup must report no owner")
	}
	if _, ok := r.BucketShare("x"); ok {
		t.Fatal("empty ring bucket share must be false")
	}

	// zero-weight members present but none on ring
	r2, err := ring.Build([]ring.Member{{ID: "z", Weight: 0}}, 160, 0)
	if err != nil {
		t.Fatal(err)
	}
	if !r2.Empty() || r2.Len() != 0 {
		t.Fatalf("zero-weight ring: empty=%v len=%d", r2.Empty(), r2.Len())
	}
	if !r2.HasMember("z") {
		t.Fatal("weight-zero member should still appear in member set")
	}
	if r2.HasMember("nope") {
		t.Fatal("unknown member reported present")
	}
}

func TestBucketShareVsTrafficShare(t *testing.T) {
	// On the 10k corpus with weights 1:1:2 the realized share must be close
	// to bucket share (0.25/0.25/0.5), demonstrating convergence AND that the
	// two values are computed separately.
	flows, _ := testutil.LoadFlowSet(t, "flows_10k")
	golden := testutil.LoadGolden(t, "flows_10k")
	gs := golden.Scenarios["s1_add_member"]
	r := buildScenarioRing(t, testutil.LoadScenarios(t).Scenarios[0].Versions[0], 160, 0)

	// Independently count realized ownership over the fixed corpus.
	realized := map[string]int{}
	routed := 0
	for _, f := range flows {
		if o, ok := r.LookupFlow(f); ok {
			realized[o]++
			routed++
		}
	}
	if routed != gs.Traffic[0].Routed {
		t.Fatalf("routed: got %d want %d", routed, gs.Traffic[0].Routed)
	}

	for id, wantBucket := range map[string]float64{"hop-a": 0.25, "hop-b": 0.25, "hop-c": 0.5} {
		got, ok := r.BucketShare(id)
		if !ok {
			t.Fatalf("bucket share missing for %s", id)
		}
		if math.Abs(got-wantBucket) > 1e-12 {
			t.Errorf("bucket share %s: got %.4f want %.4f", id, got, wantBucket)
		}
		// realized count must equal the independent oracle's count
		wantCount := gs.Traffic[0].Counts[id]
		if realized[id] != wantCount {
			t.Errorf("realized count %s: got %d want %d", id, realized[id], wantCount)
		}
		traffic := float64(realized[id]) / float64(routed)
		if math.Abs(traffic-wantBucket) > 0.05 {
			t.Errorf("traffic share %s %.4f too far from bucket %.4f on 10k corpus",
				id, traffic, wantBucket)
		}
		// and the golden share must match the locally computed share
		if math.Abs(traffic-gs.Traffic[0].Share[id]) > 1e-12 {
			t.Errorf("traffic share %s: got %.6f golden %.6f",
				id, traffic, gs.Traffic[0].Share[id])
		}
	}
}
