// Package engine is the path-vector (SPVP-style) replay core.
//
// It executes a closed, deterministic simulation over a fixed small
// topology: the scenario's synthetic events are injected as an initial
// FIFO batch, then every generated UPDATE/WITHDRAWAL is processed to a
// fixed point. The engine performs:
//
//   - inbound AS_PATH loop rejection (route whose path carries the local
//     AS is never installed);
//   - independent import-policy application at each session end;
//   - best-path selection in the explicit comparison order of model.Compare;
//   - independent export-policy application, eBGP AS prepend / local-pref
//     stripping and split-horizon suppression;
//   - per-source candidate bookkeeping so a WITHDRAWAL removes only the
//     candidate learned from the withdrawing neighbor;
//   - oscillation detection via best-path state signatures, returning
//     cycle evidence when the step budget is exhausted while oscillating.
package engine

import (
	"pvsim/config"
	"pvsim/model"
)

// Options controls a replay.
type Options struct {
	// MaxSteps bounds processed messages. 0 selects the package default.
	MaxSteps int
}

const (
	// DefaultMaxSteps applies when the scenario/options leave it unset.
	DefaultMaxSteps = 1000
	// HardMaxSteps is the safety ceiling regardless of request.
	HardMaxSteps = 200000
)

// MessageKind enumerates message kinds on the FIFO queue.
type MessageKind string

const (
	MsgUpdate   MessageKind = "update"
	MsgWithdraw MessageKind = "withdraw"
)

// Message is one queued route delivery between two adjacent speakers
// (or an injected external event).
type Message struct {
	From     string
	To       string
	Prefix   model.Prefix
	Kind     MessageKind
	Attrs    model.Attrs
	EventSeq int  // external events only
	External bool // injected from the scenario, not generated by a speaker
}

// Candidate is a neighbor-learned route held in Adj-RIB-In.
type Candidate struct {
	Prefix          model.Prefix
	Peer            string
	SessionID       string
	SessionType     string
	Attrs           model.Attrs
	IGPCost         int // cost from choosing router to this next-hop
	PeerOrdinal     int
	ReceivedVersion int
}

// Decision records one best-path change (or first selection).
type Decision struct {
	Version      int
	Router       string
	Prefix       string
	PreviousPeer string // "" when no best existed before
	ChosenPeer   string
	ChosenAttrs  model.Attrs
	RunnerUpPeer string // "" when no alternative existed
	Reason       string // deciding comparison step / "only_candidate"
}

// Trace is one structured intermediate-state record.
type Trace struct {
	Version     int
	Category    string
	Router      string
	Peer        string
	Prefix      string
	Detail      string
	AttrsBefore *model.Attrs `json:",omitempty"`
	AttrsAfter  *model.Attrs `json:",omitempty"`
}

// Trace categories recorded in run traces.
const (
	TraceExternalEvent     = "external_event"        // a synthetic injected event
	TraceImportDenied      = "import_denied"         // inbound policy rejected an UPDATE
	TraceLoopRejected      = "loop_rejected"         // AS_PATH contains local AS
	TraceCandidateUpdate   = "candidate_update"      // neighbor candidate installed/replaced
	TraceCandidateRemoved  = "candidate_removed"     // candidate withdrawn / stale invalidated
	TraceBestChanged       = "best_changed"          // local best path changed
	TraceExportDenied      = "export_denied"         // outbound policy rejected propagation
	TracePropagateUpdate   = "propagate_update"      // UPDATE emitted
	TracePropagateWithdraw = "propagate_withdraw"    // WITHDRAWAL emitted
	TraceSuppressRedisc    = "suppress_redistribute" // split-horizon: no export back to source
	TraceWithdrawUnknown   = "withdraw_unknown"      // withdrawal with no local candidate
)

// AttrsView is the JSON shape of a trace attribute snapshot.
type AttrsView = model.Attrs

// BestView is one router's final best route for a prefix.
type BestView struct {
	Prefix      string      `json:"prefix"`
	Peer        string      `json:"peer"`
	SessionType string      `json:"session_type"`
	Attrs       model.Attrs `json:"attrs"`
	Reason      string      `json:"last_decision_reason"`
	Version     int         `json:"version"`
}

// ChoiceSnapshot is one signature entry: who each router currently believes.
type ChoiceSnapshot struct {
	Version int                            `json:"version"`
	Best    map[string]map[string]PeerPath `json:"best"`
}

// PeerPath is a compact (peer, path) pair used in cycle evidence.
type PeerPath struct {
	Peer   string   `json:"peer"`
	ASPath []uint32 `json:"as_path"`
}

// CycleEvidence documents a proven oscillation cycle.
type CycleEvidence struct {
	// EntranceVersion is the version at which the repeating signature
	// was first observed.
	EntranceVersion int `json:"entrance_version"`
	// RepetitionVersion is where the same signature reappeared.
	RepetitionVersion int `json:"repitition_version"`
	// Length is the cycle length in processed messages.
	Length int `json:"length"`
	// Signature is the canonical state signature that recurred.
	Signature string `json:"signature"`
	// Choices are the best-path snapshots at entrance and repetition.
	Choices []ChoiceSnapshot `json:"choices"`
}

// Result is the full outcome of a replay.
type Result struct {
	Converged         bool                  `json:"converged"`
	NonConvergentCode string                `json:"non_convergent_code,omitempty"`
	Steps             int                   `json:"steps"`
	Versions          int                   `json:"versions"`
	Best              map[string][]BestView `json:"best"`
	Decisions         []Decision            `json:"decisions"`
	Traces            []Trace               `json:"traces"`
	Cycle             *CycleEvidence        `json:"cycle,omitempty"`
}

// Sink receives structured replay artifacts. The engine never imports
// storage packages; replay wires an SQLite-backed sink, tests wire
// in-memory sinks.
type Sink interface {
	ExternalDelivered(version int, ev *config.Event)
	Decision(d Decision)
	Trace(t Trace)
}

// nopSink is used when no recorder is supplied.
type nopSink struct{}

func (nopSink) ExternalDelivered(int, *config.Event) {}
func (nopSink) Decision(Decision)                    {}
func (nopSink) Trace(Trace)                          {}
