"""Pydantic request/response models for the verification API."""
from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class VerifyRequest(BaseModel):
    schema_: dict[str, Any] = Field(..., alias="schema")
    records: list[dict[str, Any]]
    # Optional hand-written expected tree. When present it is an independent
    # oracle (it is NOT generated by the kernel under test).
    expected: Optional[list[dict[str, Any]]] = None
    page_slot_target: Optional[int] = Field(
        default=None, ge=1, le=1_000_000,
        description="soft kernel page-size target in leaf slots",
    )
    parquet_page_bytes: Optional[int] = Field(
        default=None, ge=32, le=1_048_576,
        description="PyArrow writer data page size in bytes",
    )
    page_version: Optional[str] = Field(default="2.0", pattern=r"^[12]\.0$")

    model_config = {"populate_by_name": True}


class SchemaAdmitRequest(BaseModel):
    schema_: dict[str, Any] = Field(..., alias="schema")

    model_config = {"populate_by_name": True}


class Step(BaseModel):
    step: str
    status: str
    detail: dict[str, Any] | None = None

    model_config = {"extra": "allow"}


class Finding(BaseModel):
    severity: str
    code: str
    message: str
    location: dict[str, Any] = Field(default_factory=dict)


class VerifyResponse(BaseModel):
    request_id: str
    status: str
    steps: list[dict[str, Any]]
    findings: list[Finding]
    kernel_pages: dict[str, Any] = Field(default_factory=dict)
    oracle_page_count: dict[str, int] = Field(default_factory=dict)
    # Values can be large; echoed only when requested via ?include=values.
    decoded: Optional[list[dict[str, Any]]] = None
    pyarrow_values: Optional[dict[str, Any]] = None
    kernel_levels: Optional[dict[str, Any]] = None
