//! Tests against the independently generated reference vectors in
//! tests/data/test_vectors.json (produced by scripts/gen_vectors.py).
//!
//! The expected answers here are NOT generated by the Rust kernel under
//! test: they come from a separate Python implementation that derives the
//! same code via a different algorithmic path (Russian-peasant field
//! multiplication and augmented-block solving instead of log/exp tables and
//! an explicit P*A^-1 multiply).

mod common;

use ec_service::erasure;
use ec_service::gf256;

fn vectors() -> serde_json::Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/test_vectors.json");
    serde_json::from_slice(&std::fs::read(path).unwrap())
        .expect("test vectors must exist; run scripts/gen_vectors.py")
}

#[test]
fn field_matches_external_spot_checks() {
    gf256::init();
    let v = vectors();
    for check in v["gf_spot_checks"].as_array().unwrap() {
        let name = check["name"].as_str().unwrap();
        let expected = check["value"].as_u64().unwrap() as u8;
        let got = match name {
            "2*0x80" => gf256::mul(2, 0x80),
            "3*3" => gf256::mul(3, 3),
            "16*16" => gf256::mul(0x10, 0x10),
            "2**255" => gf256::pow(2, 255),
            "inv(3)*3" => gf256::mul(gf256::inv(3).unwrap(), 3),
            "53/53" => gf256::mul(gf256::mul(0x53, 0x7e), gf256::inv(0x53).unwrap()),
            other => panic!("unknown spot check {other}"),
        };
        assert_eq!(got, expected, "field spot check {name}");
    }
}

#[test]
fn encoding_matrix_matches_reference_for_every_case() {
    let v = vectors();
    for case in v["cases"].as_array().unwrap() {
        let (k, m) = (case["k"].as_u64().unwrap() as u8, case["m"].as_u64().unwrap() as u8);
        let em = erasure::encoding_matrix(k, m).unwrap();
        let expected: Vec<Vec<u8>> = case["encoding_matrix"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| {
                row.as_array()
                    .unwrap()
                    .iter()
                    .map(|x| x.as_u64().unwrap() as u8)
                    .collect()
            })
            .collect();
        assert_eq!(em, expected, "encoding matrix mismatch for {}", case["label"]);
    }
}

#[test]
fn encoded_shards_match_reference_byte_for_byte() {
    let v = vectors();
    for case in v["cases"].as_array().unwrap() {
        let (k, m) = (case["k"].as_u64().unwrap() as u8, case["m"].as_u64().unwrap() as u8);
        let data = hex_decode(case["data_hex"].as_str().unwrap());
        let enc = erasure::encode(&data, k, m).unwrap();
        assert_eq!(enc.shard_len, case["shard_len"].as_u64().unwrap() as usize);
        let expected_shards: Vec<Vec<u8>> = case["shards_hex"]
            .as_array()
            .unwrap()
            .iter()
            .map(|h| hex_decode(h.as_str().unwrap()))
            .collect();
        assert_eq!(
            enc.shards, expected_shards,
            "shard bytes mismatch for {}",
            case["label"]
        );
    }
}

#[test]
fn every_recoverable_erasure_combination_reconstructs_exact_bytes() {
    // The exhaustive requirement: enumerate ALL 1..=m-erasure combinations
    // for every small profile/case and compare the complete rebuilt shard
    // vector byte-by-byte against the reference's expected rebuild (which is
    // asserted in the generator to equal the original shard set).
    let v = vectors();
    let mut total = 0usize;
    for case in v["cases"].as_array().unwrap() {
        let (k, m) = (case["k"].as_u64().unwrap() as u8, case["m"].as_u64().unwrap() as u8);
        let shard_len = case["shard_len"].as_u64().unwrap() as usize;
        let original_shards: Vec<Vec<u8>> = case["shards_hex"]
            .as_array()
            .unwrap()
            .iter()
            .map(|h| hex_decode(h.as_str().unwrap()))
            .collect();
        for rec in case["erasure_recoveries"].as_array().unwrap() {
            let available_idx: Vec<usize> = rec["available"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_u64().unwrap() as usize)
                .collect();
            let available: Vec<(u8, Vec<u8>)> = available_idx
                .iter()
                .map(|&i| (i as u8, original_shards[i].clone()))
                .collect();
            let rebuilt = erasure::reconstruct(&available, k, m, shard_len)
                .unwrap_or_else(|e| {
                    panic!(
                        "case {} missing {:?}: unexpected error {e:?}",
                        case["label"],
                        rec["missing"]
                    )
                });

            // 1) compare against reference-recorded expected rebuild
            let expected_rebuilt: Vec<Vec<u8>> = rec["rebuilt_shards_hex"]
                .as_array()
                .unwrap()
                .iter()
                .map(|h| hex_decode(h.as_str().unwrap()))
                .collect();
            assert_eq!(rebuilt, expected_rebuilt, "case {:?}", case["label"]);
            // 2) compare against freshly encoded shards (identity property)
            assert_eq!(rebuilt, original_shards, "case {:?}", case["label"]);

            // 3) payload after truncation must equal the original data
            let mut payload = Vec::new();
            for s in rebuilt.iter().take(k as usize) {
                payload.extend_from_slice(s);
            }
            payload.truncate(case["original_len"].as_u64().unwrap() as usize);
            assert_eq!(
                payload,
                hex_decode(case["data_hex"].as_str().unwrap()),
                "payload byte mismatch case {} missing {:?}",
                case["label"],
                rec["missing"]
            );
            total += 1;
        }
    }
    // Guard against a silently emptied vector file weakening the test.
    assert_eq!(total, 47, "must enumerate all 47 recoverable combinations");
}

#[test]
fn over_tolerance_examples_are_refused_with_a_category() {
    let v = vectors();
    for case in v["cases"].as_array().unwrap() {
        let (k, m) = (case["k"].as_u64().unwrap() as u8, case["m"].as_u64().unwrap() as u8);
        let shard_len = case["shard_len"].as_u64().unwrap() as usize;
        let ex = &case["over_tolerance_example"];
        let missing: Vec<usize> = ex["missing"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_u64().unwrap() as usize)
            .collect();
        let original: Vec<Vec<u8>> = case["shards_hex"]
            .as_array()
            .unwrap()
            .iter()
            .map(|h| hex_decode(h.as_str().unwrap()))
            .collect();
        let available: Vec<(u8, Vec<u8>)> = (0..(k + m) as usize)
            .filter(|i| !missing.contains(i))
            .map(|i| (i as u8, original[i].clone()))
            .collect();
        assert_eq!(available.len(), ex["available_count"].as_u64().unwrap() as usize);
        let err = erasure::reconstruct(&available, k, m, shard_len).unwrap_err();
        assert_eq!(
            err.code(),
            ex["expected_error_code"].as_str().unwrap(),
            "case {}",
            case["label"]
        );
        assert_eq!(
            err,
            erasure::CodeError::NotEnoughShards {
                have: available.len(),
                need: k as usize,
            }
        );
    }
}

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}
