//! Fixture-driven tests: hand-computed obligation sets vs kernel vs oracle.
//!
//! Each scenario (see `fixtures/expected/*.json`) was computed by hand on
//! paper first; the expected file is not generated by the code under test.

mod common;

#[test]
fn fixture_a_boundary_satisfied() {
    common::cross_check(
        "hand-a-boundary-satisfied",
        "fixture_a",
        "shop-v1.json",
        "a_boundary_satisfied.json",
        "a.json",
    );
}

#[test]
fn fixture_b_overlapping_triggers_consume_and_correlation() {
    common::cross_check(
        "hand-b-overlap-triggers",
        "fixture_b",
        "shop-v1.json",
        "b_overlap_triggers.json",
        "b.json",
    );
}

#[test]
fn fixture_c_missing_responses_deadline_expiry() {
    common::cross_check(
        "hand-c-missing-response",
        "fixture_c",
        "shop-v1.json",
        "c_missing_response.json",
        "c.json",
    );
}

#[test]
fn fixture_d_early_close_seals_pending_obligations() {
    common::cross_check(
        "hand-d-early-close",
        "fixture_d",
        "shop-v1.json",
        "d_early_close.json",
        "d.json",
    );
}

#[test]
fn fixture_e_sustain_window_breaks_after_overlap() {
    common::cross_check(
        "hand-e-sustain-break",
        "fixture_e",
        "shop-v1.json",
        "e_sustain_break.json",
        "e.json",
    );
}

#[test]
fn fixture_f_overlapping_sustain_windows_both_complete() {
    common::cross_check(
        "hand-f-sustain-overlap-ok",
        "fixture_f",
        "shop-v1.json",
        "f_sustain_overlap_ok.json",
        "f.json",
    );
}

#[test]
fn fixture_g_empty_trace_vacuous_satisfaction() {
    common::cross_check(
        "hand-g-empty-closed",
        "fixture_g",
        "shop-v1.json",
        "g_empty_closed.json",
        "g.json",
    );
}
