//! Fixture-driven tests: every case in `fixtures/runs/` is checked against
//! (1) the hand-written exact expectations in `fixtures/expected/`,
//! (2) prefix verdict checks embedded in the fixture,
//! (3) the independent set-based oracle (open and closed).
//!
//! None of these answers are generated by the kernel under test.

mod common;

use common::*;

use btmon::lang::Verdict;
use btmon::monitor::{Limits, Monitor};
use serde_json::Value;

fn verdict_str(v: Verdict) -> &'static str {
    match v {
        Verdict::Sat => "sat",
        Verdict::Viol => "viol",
        Verdict::Wait => "wait",
    }
}

fn assert_expected(d: &mut Driven, expected: &Value) {
    // Open verdict and exact open-state obligations (kernel vs oracle).
    let open_oracle = oracle_open(d);
    assert_kernel_matches_oracle(&d.monitor, &open_oracle);
    assert_eq!(
        verdict_str(d.monitor.global_verdict()),
        expected["open_verdict"].as_str().unwrap(),
        "{}: open verdict mismatch",
        d.run_id
    );

    let closed = d.monitor.end().expect("close");
    let closed_oracle = oracle_closed(d);
    assert_kernel_matches_oracle(&d.monitor, &closed_oracle);
    assert_eq!(
        verdict_str(closed.verdict),
        expected["closed_verdict"].as_str().unwrap(),
        "{}: closed verdict mismatch",
        d.run_id
    );

    let expected_instances = expected["instances"].as_array().unwrap();
    assert_eq!(
        d.monitor.obligations.len(),
        expected_instances.len(),
        "{}: instance count",
        d.run_id
    );
    for exp in expected_instances {
        let id = exp["id"].as_str().unwrap();
        let o = d
            .monitor
            .obligations
            .iter()
            .find(|o| o.id == id)
            .unwrap_or_else(|| panic!("{}: missing obligation {id}", d.run_id));
        assert_eq!(
            serde_json::to_value(o.status).unwrap().as_str().unwrap(),
            exp["status"].as_str().unwrap(),
            "{id}: status"
        );
        assert_eq!(
            serde_json::to_value(o.reason).unwrap().as_str().unwrap(),
            exp["reason"].as_str().unwrap(),
            "{id}: reason"
        );
        assert_eq!(
            o.window_start,
            exp["window"][0].as_i64().unwrap(),
            "{id}: window_start"
        );
        assert_eq!(
            o.window_end,
            exp["window"][1].as_i64().unwrap(),
            "{id}: window_end"
        );
        assert_eq!(
            o.satisfied_at,
            exp["satisfied_at"].as_i64(),
            "{id}: satisfied_at"
        );
        assert_eq!(o.failed_at, exp["failed_at"].as_i64(), "{id}: failed_at");
    }
    log_run(file!(), d);
    log_line(
        file!(),
        &d.run_id,
        "closed",
        serde_json::to_value(d.monitor.status()).unwrap(),
    );
}

#[test]
fn case_01_overlap_all() {
    let f = load_run("01-overlap-all");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("01-overlap-all"));
}

#[test]
fn case_02_boundary() {
    let f = load_run("02-boundary");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("02-boundary"));
}

#[test]
fn case_03_missing_response_strict() {
    let f = load_run("03-missing-early");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("03-missing-early"));
}

#[test]
fn case_04_missing_response_lenient() {
    let f = load_run("04-lenient");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("04-lenient"));
}

#[test]
fn case_05_sustain_condition_fails() {
    let f = load_run("05-sustain-fail");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("05-sustain-fail"));
}

#[test]
fn case_06_sustain_incomplete() {
    let f = load_run("06-sustain-incomplete");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("06-sustain-incomplete"));
}

#[test]
fn case_07_satisfy_one_ok() {
    let f = load_run("07-satisfy-one-ok");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("07-satisfy-one-ok"));
}

#[test]
fn case_08_satisfy_one_miss() {
    let f = load_run("08-satisfy-one-miss");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("08-satisfy-one-miss"));
}

#[test]
fn case_09_rotation_seals_epochs() {
    let f = load_run("09-rotation");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("09-rotation"));
    // Extra version-isolation assertions.
    assert_eq!(d.monitor.active_epoch, 1);
    assert_eq!(d.monitor.rulesets.len(), 2);
    let epoch0: Vec<_> = d
        .monitor
        .obligations
        .iter()
        .filter(|o| o.epoch == 0)
        .collect();
    let epoch1: Vec<_> = d
        .monitor
        .obligations
        .iter()
        .filter(|o| o.epoch == 1)
        .collect();
    assert_eq!(epoch0.len(), 1);
    assert_eq!(epoch1.len(), 2);
    assert!(epoch0
        .iter()
        .all(|o| o.status != btmon::lang::ObligationStatus::Pending));
}

#[test]
fn case_10_mixed_rules() {
    let f = load_run("10-mixed");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("10-mixed"));
}

#[test]
fn case_11_overlap_all_control() {
    let f = load_run("11-overlap-all-control");
    let mut d = drive(&f);
    assert_expected(&mut d, &load_expected("11-overlap-all-control"));
}

// ----------------------------------------------------------- prefix checks
/// Re-drive each fixture and assert its embedded `open_checks` prefix
/// verdicts. Critically: an open trace with pending obligations must yield
/// `wait`, never `sat`.
#[test]
fn prefix_verdicts_are_three_valued() {
    let cases = [
        "03-missing-early",
        "04-lenient",
        "05-sustain-fail",
        "06-sustain-incomplete",
        "10-mixed",
    ];
    for name in cases {
        let f = load_run(name);
        assert!(!f.open_checks.is_empty(), "{name} should embed open_checks");
        // Drive incrementally so we can inspect prefixes.
        let mut monitor = Monitor::new(
            "prefix".into(),
            f.run_id.clone(),
            f.segments[0].ruleset.clone(),
            Limits::replay(),
        )
        .unwrap();
        for (idx, seg) in f.segments.iter().enumerate() {
            if idx > 0 {
                monitor.rotate(seg.ruleset.clone()).unwrap();
            }
            for v in &seg.events {
                let ev = match v.get("event") {
                    Some(inner) => serde_json::from_value(inner.clone()).unwrap(),
                    None => serde_json::from_value(v.clone()).unwrap(),
                };
                monitor.append(&ev, None).unwrap();
                let fed = monitor.next_step as usize;
                for check in &f.open_checks {
                    if check.after_events == fed {
                        assert_eq!(
                            verdict_str(monitor.global_verdict()),
                            check.global_verdict,
                            "{name} prefix after {fed} events"
                        );
                        log_line(
                            file!(),
                            &f.run_id,
                            "prefix_check",
                            serde_json::json!({
                                "after_events": check.after_events,
                                "verdict": verdict_str(monitor.global_verdict()),
                                "pending": monitor.pending_count(),
                            }),
                        );
                    }
                }
            }
        }
    }
}

/// A wait on an open trace must never collapse to sat after merely adding
/// more irrelevant events without closing.
#[test]
fn wait_is_not_pass_while_open() {
    let f = load_run("03-missing-early");
    let mut d = drive(&f);
    assert_eq!(d.monitor.global_verdict(), Verdict::Wait);
    use btmon::lang::Event;
    d.monitor.append(&Event::new("noise"), None).unwrap(); // t3: window [1,3] ends here -> actually becomes violated
    assert_eq!(d.monitor.global_verdict(), Verdict::Viol);

    // Fresh run where the deadline remains open and keep feeding noise:
    // verdict must stay wait, never sat.
    let f2 = load_run("04-lenient"); // window [1,3], ends at t2
    let d2 = drive(&f2);
    assert_eq!(d2.monitor.global_verdict(), Verdict::Wait);
}
