"""Hand-written synthetic fixtures.

These expected trees are authored by hand to pin down the three-way list
distinction (NULL list vs empty list vs NULL element), multi-level nesting,
empty structs, runs of consecutive NULLs, and cross-page volumes. They are NOT
generated by the kernel under test.
"""
from __future__ import annotations

from typing import Any

# --------------------------------------------------------------------------- #
# Schema descriptions
# --------------------------------------------------------------------------- #

SCHEMA_NESTED_LIST = {
    "name": "nested_messages",
    "fields": [
        {"name": "id", "type": "int64", "repetition": "required"},
        {"name": "ids", "type": "list", "repetition": "optional",
         "element": {"type": "list", "element": {"type": "int32"}}},
        {"name": "tags", "type": "list", "repetition": "optional",
         "element": {"type": "string"}},
    ],
}

SCHEMA_LIST_OF_STRUCT = {
    "name": "list_of_struct",
    "fields": [
        {"name": "id", "type": "int64", "repetition": "required"},
        {"name": "items", "type": "list", "repetition": "optional",
         "element": {"type": "struct", "fields": [
             {"name": "k", "type": "int32"},
             {"name": "v", "type": "string"},
         ]}},
    ],
}

SCHEMA_STRUCT_LIST = {
    "name": "struct_with_list",
    "fields": [
        {"name": "id", "type": "int64", "repetition": "required"},
        {"name": "s", "type": "struct", "repetition": "optional", "fields": [
            {"name": "x", "type": "int32", "repetition": "optional"},
            {"name": "ys", "type": "list", "repetition": "optional",
             "element": {"type": "int64"}},
        ]},
    ],
}

SCHEMA_EMPTY_STRUCT = {
    "name": "empty_struct_case",
    "fields": [
        {"name": "id", "type": "int64", "repetition": "required"},
        {"name": "marker", "type": "struct", "repetition": "optional",
         "fields": []},
        {"name": "tail", "type": "string", "repetition": "optional"},
    ],
}

SCHEMA_PRIMITIVES = {
    "name": "primitives",
    "fields": [
        {"name": "id", "type": "int64", "repetition": "required"},
        {"name": "b", "type": "boolean", "repetition": "optional"},
        {"name": "i32", "type": "int32", "repetition": "optional"},
        {"name": "f32", "type": "float", "repetition": "optional"},
        {"name": "f64", "type": "double", "repetition": "optional"},
        {"name": "s", "type": "string", "repetition": "optional"},
    ],
}


# --------------------------------------------------------------------------- #
# Hand-written expected trees
# --------------------------------------------------------------------------- #

NESTED_LIST_RECORDS: list[dict[str, Any]] = [
    # 0: NULL outer list, populated scalar list
    {"id": 1, "ids": None, "tags": ["a", "b"]},
    # 1: empty outer list, NULL scalar list
    {"id": 2, "ids": [], "tags": None},
    # 2: outer populated; NULL inner, populated inner, empty inner,
    #    inner with NULL element -- all four states in one record
    {"id": 3, "ids": [None, [10, 20], [], [None, 30]],
     "tags": ["x", None, "y"]},
    # 3: two empty inner lists
    {"id": 4, "ids": [[], []], "tags": []},
    # 4: two outer elements, each a singleton inner -- the [[1],[2]] case
    {"id": 5, "ids": [[40], [50]], "tags": None},
    # 5: one outer element, two inner values -- the [[1,2]] case
    {"id": 6, "ids": [[60, 70]], "tags": ["only"]},
    # 6: consecutive NULLs across adjacent records
    {"id": 7, "ids": None, "tags": None},
    {"id": 8, "ids": None, "tags": None},
    # 9: NULL inner mixed with empties
    {"id": 9, "ids": [None, None, []], "tags": []},
]

# Exact (DL, RL, value) expectations for the ids.list.list.list.element leaf,
# record by record. Hand-derived from the canonical 3-level LIST ladder
# (outer optional=1, repeated=1, inner optional=1, repeated=1, leaf optional=1;
# max DL 5, max RL 2).
NESTED_IDS_LEVELS: list[list[tuple[int, int, Any]]] = [
    [(0, 0, None)],                                   # NULL outer
    [(1, 0, None)],                                   # empty outer
    [(2, 0, None),                                    # NULL inner element
     (5, 1, 10), (5, 2, 20),                          # [10,20]
     (3, 1, None),                                    # [] inner
     (4, 1, None), (5, 2, 30)],                       # [None,30]
    [(3, 0, None), (3, 1, None)],                     # [[],[]]
    [(5, 0, 40), (5, 1, 50)],                         # [[40],[50]]
    [(5, 0, 60), (5, 2, 70)],                         # [[60,70]]
    [(0, 0, None)],
    [(0, 0, None)],
    [(2, 0, None), (2, 1, None), (3, 1, None)],       # [None,None,[]]
]

LIST_OF_STRUCT_RECORDS: list[dict[str, Any]] = [
    {"id": 1, "items": [
        {"k": 1, "v": "one"}, None, {"k": None, "v": "three"}]},
    {"id": 2, "items": None},
    {"id": 3, "items": []},
    {"id": 4, "items": [{"k": 4, "v": "four"}]},
    {"id": 5, "items": [None, None, {"k": 5, "v": "five"}, None]},
]

STRUCT_LIST_RECORDS: list[dict[str, Any]] = [
    {"id": 1, "s": {"x": 1, "ys": [10, 20]}},
    {"id": 2, "s": None},
    {"id": 3, "s": {"x": None, "ys": None}},
    {"id": 4, "s": {"x": 4, "ys": []}},
    {"id": 5, "s": {"x": None, "ys": [50]}},
]

EMPTY_STRUCT_RECORDS: list[dict[str, Any]] = [
    {"id": 1, "marker": {}, "tail": "present"},
    {"id": 2, "marker": None, "tail": None},
    {"id": 3, "marker": None, "tail": "no-marker-key"},
    {"id": 4, "marker": {}, "tail": "again"},
]

PRIMITIVE_RECORDS: list[dict[str, Any]] = [
    {"id": 1, "b": True, "i32": -7, "f32": 1.5, "f64": 2.25, "s": "héllo"},
    {"id": 2, "b": False, "i32": 2147483647, "f32": -3.5,
     "f64": 0.0, "s": ""},
    {"id": 3, "b": None, "i32": None, "f32": None, "f64": None, "s": None},
    {"id": 4, "b": True, "i32": -2147483648, "f32": 0.0,
     "f64": -1.0, "s": "x"},
]

# Schemas that must be explicitly rejected.
UNSUPPORTED_SCHEMAS = [
    {"fields": [{"name": "x", "type": "decimal", "precision": 10, "scale": 2}]},
    {"fields": [{"name": "x", "type": "timestamp"}]},
    {"fields": [{"name": "x", "type": "date"}]},
    {"fields": [{"name": "x", "type": "uuid"}]},
    {"fields": [{"name": "m", "type": "map", "element": {"type": "string"}}]},
    {"fields": [{"name": "x", "type": "float16"}]},
    {"fields": [{"name": "x", "type": "json"}]},
]


def cross_page_records(target_records: int = 500) -> list[dict[str, Any]]:
    """Deterministic large fixture: varied nesting spanning many pages."""
    records: list[dict[str, Any]] = []
    for i in range(target_records):
        if i % 7 == 0:
            ids = None
        elif i % 7 == 1:
            ids = []
        elif i % 7 == 2:
            ids = [None, [i, i + 1], [], [None, i + 2]]
        elif i % 7 == 3:
            ids = [[i], [i + 1], [i + 2]]
        elif i % 7 == 4:
            ids = [[i, i + 1, i + 2]]
        elif i % 7 == 5:
            ids = [None, None]
        else:
            ids = [[], [i]]
        tags = None if i % 5 == 0 else [f"t{i}", None, f"u{i}"]
        records.append({"id": i, "ids": ids, "tags": tags})
    return records
