//! Fixture tests against HAND-WRITTEN expected files in fixtures/expected/.
//! The expected JSON files are authored from the semantic definitions, not
//! generated by the analyzer: this test fails if the engine's output drifts
//! from the independently stated answers.

use interval_analyzer::kernel::Interval;
use interval_analyzer::{analyze_source, config::Config};
use serde_json::Value;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn format_interval(i: &Interval) -> String {
    format!("{i}")
}

fn parse_expected_interval(s: &str) -> Interval {
    // accepts "[lo, hi]" with -inf/inf — enough for hand-written expectations
    let inner = s
        .trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .trim();
    let (lo_s, hi_s) = inner.split_once(',').expect("expected `lo, hi`");
    fn bound(t: &str) -> interval_analyzer::kernel::Bound {
        let t = t.trim();
        match t {
            "-inf" => interval_analyzer::kernel::Bound::NegInf,
            "inf" => interval_analyzer::kernel::Bound::PosInf,
            _ => interval_analyzer::kernel::Bound::Fin(t.parse().expect("integer bound")),
        }
    }
    Interval::from(bound(lo_s), bound(hi_s))
}

#[test]
fn all_fixtures_match_hand_written_expectations() {
    let prog_dir = Path::new("fixtures/programs");
    let exp_dir = Path::new("fixtures/expected");
    let mut count = 0;
    for entry in fs::read_dir(prog_dir).expect("fixtures/programs") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("isl") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_str().unwrap().to_string();
        let exp_path = exp_dir.join(format!("{stem}.json"));
        let exp_text = fs::read_to_string(&exp_path)
            .unwrap_or_else(|_| panic!("missing hand-written expectation {exp_path:?}"));
        let exp: Value = serde_json::from_str(&exp_text).expect("expected JSON parses");

        let src = fs::read_to_string(&path).unwrap();
        let report = analyze_source(&src, Config::default())
            .unwrap_or_else(|e| panic!("analysis failed for {stem}: {e}"));

        // ---- checks: (kind, line) -> verdict ----
        let mut actual: BTreeMap<(String, u32), String> = BTreeMap::new();
        for c in &report.checks {
            actual.insert(
                (c.kind_label().to_string(), c.span.line),
                c.verdict.as_str().to_string(),
            );
        }
        let expected_checks = exp["checks"].as_array().unwrap();
        assert_eq!(
            expected_checks.len(),
            actual.len(),
            "{stem}: check count differs: expected {expected_checks:?}, got {actual:?}"
        );
        for ec in expected_checks {
            let key = (
                ec["kind"].as_str().unwrap().to_string(),
                ec["line"].as_u64().unwrap() as u32,
            );
            let want = ec["verdict"].as_str().unwrap();
            let got = actual.get(&key).unwrap_or_else(|| {
                panic!("{stem}: no check for expected {key:?}; actual {actual:?}")
            });
            assert_eq!(got, want, "{stem}: check {key:?} verdict mismatch");
        }

        // ---- unreachable lines ----
        let exp_unreachable: Vec<u32> = exp["unreachable"]
            .as_array()
            .map(|a| a.iter().map(|v| v.as_u64().unwrap() as u32).collect())
            .unwrap_or_default();
        let got_unreachable: Vec<u32> = report
            .checks
            .iter()
            .filter(|c| c.verdict == interval_analyzer::report::Verdict::Unreachable)
            .map(|c| c.span.line)
            .collect();
        assert_eq!(
            got_unreachable, exp_unreachable,
            "{stem}: unreachable lines differ"
        );

        // ---- exit state ----
        let exit = &exp["exit"];
        if let Some(true) = exit["vars_bottom"].as_bool() {
            assert!(
                report.exit_state.is_bottom,
                "{stem}: expected bottom exit state"
            );
        } else {
            assert!(
                !report.exit_state.is_bottom,
                "{stem}: unexpected bottom exit state"
            );
            for (name, want_s) in exit["vars"].as_object().unwrap() {
                let want = parse_expected_interval(want_s.as_str().unwrap());
                let got = report
                    .exit_state
                    .vars
                    .get(name)
                    .unwrap_or_else(|| panic!("{stem}: missing exit var {name}"));
                assert_eq!(
                    format_interval(got),
                    format!("{want}"),
                    "{stem}: exit var {name}"
                );
            }
            for (name, arr) in exit["arrays"]
                .as_object()
                .unwrap_or(&serde_json::Map::new())
            {
                let got = report
                    .exit_state
                    .arrays
                    .get(name)
                    .unwrap_or_else(|| panic!("{stem}: missing exit array {name}"));
                assert_eq!(
                    got.len as u64,
                    arr["len"].as_u64().unwrap(),
                    "{stem}: array {name} len"
                );
                let want = parse_expected_interval(arr["elem"].as_str().unwrap());
                assert_eq!(
                    format_interval(&got.elem),
                    format!("{want}"),
                    "{stem}: array {name} elem"
                );
            }
        }

        // ---- observations: multiset of intervals per target ----
        let mut got_obs: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for o in &report.observations {
            match o {
                interval_analyzer::report::Observation::AssignValue {
                    target, interval, ..
                } => {
                    got_obs
                        .entry(target.clone())
                        .or_default()
                        .push(format_interval(interval));
                }
            }
        }
        for v in got_obs.values_mut() {
            v.sort();
        }
        if let Some(obj) = exp["observations"].as_object() {
            for (target, arr) in obj {
                let mut want: Vec<String> = arr
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| format!("{}", parse_expected_interval(v.as_str().unwrap())))
                    .collect();
                want.sort();
                let got = got_obs.get(target).cloned().unwrap_or_default();
                assert_eq!(got, want, "{stem}: observations for {target} differ");
            }
        }

        // ---- loop count ----
        assert_eq!(
            report.loop_invariants.len(),
            exp["loops"].as_u64().unwrap() as usize,
            "{stem}: loop invariant count"
        );

        count += 1;
    }
    assert!(count >= 5, "expected at least 5 fixtures, found {count}");
}
