//! Cross-checked golden vectors generated by the independent Python
//! reference (`tools/reference_rangecoder.py`).  The Rust code must produce
//! byte-identical payloads and identical per-symbol `(low, range)` states.
//!
//! These vectors are checked in; regenerate with:
//!     python3 tools/generate_golden.py

use rangecode::range::{RangeDecoder, RangeEncoder};
use rangecode::table::FreqTable;
use serde_json::Value;
use std::path::PathBuf;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/golden_vectors.json")
}

fn load_cases() -> Vec<Value> {
    let text = std::fs::read_to_string(fixture_path()).expect("golden fixture present");
    let doc: Value = serde_json::from_str(&text).expect("fixture is valid JSON");
    assert_eq!(doc["format"], "rangecode-golden-v1");
    doc["cases"].as_array().unwrap().clone()
}

#[test]
fn fixture_covers_required_input_shapes() {
    let cases = load_cases();
    let names: Vec<&str> = cases.iter().map(|c| c["name"].as_str().unwrap()).collect();
    for required in [
        "empty_binary",
        "single_zero",
        "single_one",
        "long_run_zeros",
        "long_run_ones",
        "alternating_ab",
        "full_alphabet_once",
        "full_alphabet_cycle",
        "all_same_in_full",
        "fibonacci_weights",
        "sparse_table",
        "total_equals_bound",
        "lcg_walk_full",
    ] {
        assert!(names.contains(&required), "missing golden case {required}");
    }
}

#[test]
fn rust_encoder_matches_python_reference_byte_for_byte() {
    for case in load_cases() {
        let name = case["name"].as_str().unwrap();
        let freqs: Vec<u32> = case["freqs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        let bound = case["bound"].as_u64().unwrap() as u32;
        let symbols: Vec<u32> = case["symbols"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        let expected = hex_to_bytes(case["payload_hex"].as_str().unwrap());

        let table = FreqTable::new(&freqs, bound).unwrap();
        let mut enc = RangeEncoder::new();
        let mut rust_trace_low = Vec::new();
        let mut rust_trace_range = Vec::new();
        for &s in &symbols {
            enc.encode(&table, s).unwrap();
            rust_trace_low.push(enc.low());
            rust_trace_range.push(enc.range());
        }
        let payload = enc.finish();

        assert_eq!(
            payload.len(),
            case["byte_len"].as_u64().unwrap() as usize,
            "{name}: len"
        );
        assert_eq!(
            payload, expected,
            "{name}: payload bytes differ from Python reference"
        );

        let py_low: Vec<u64> = case["trace_low"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap())
            .collect();
        let py_range: Vec<u32> = case["trace_range"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(rust_trace_low, py_low, "{name}: low trace divergence");
        assert_eq!(rust_trace_range, py_range, "{name}: range trace divergence");
    }
}

#[test]
fn rust_decoder_reads_python_payloads_and_matches_state() {
    for case in load_cases() {
        let name = case["name"].as_str().unwrap();
        let freqs: Vec<u32> = case["freqs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        let bound = case["bound"].as_u64().unwrap() as u32;
        let symbols: Vec<u32> = case["symbols"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        let payload = hex_to_bytes(case["payload_hex"].as_str().unwrap());

        let table = FreqTable::new(&freqs, bound).unwrap();
        let mut dec = RangeDecoder::new(&payload).expect("{name}: decoder init");
        let mut got = Vec::with_capacity(symbols.len());
        for _ in &symbols {
            got.push(dec.decode(&table).unwrap());
        }
        dec.finish_check().unwrap();
        assert_eq!(got, symbols, "{name}: decoded symbols mismatch");
    }
}

fn hex_to_bytes(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}
