//!
//! Golden-vector tests driven by vectors emitted from the *independent*
//! Python oracle (`tests/golden/generate_fixtures.py`) and decoded by an
//! *independent* Rust decoder (`tests/support/independent_decoder.rs`) that
//! shares no code with the crate under test.
//!
//! In addition, the real `hcomp` encoder is run over every roundtrip vector
//! and its bytes are decoded by the independent decoder (and vice versa via
//! the real decoder), giving a three-way cross-check:
//!
//! ```text
//!   Python oracle  <-->  hcomp encoder/decoder  <-->  independent Rust decoder
//! ```
//!
//! Tests assert concrete values and concrete failure categories.

#[path = "support/independent_decoder.rs"]
mod independent;

use hcomp::container::{decode_container, encode_container, inspect};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

fn read_bin(name: &str) -> Vec<u8> {
    std::fs::read(golden_dir().join(name)).unwrap_or_else(|e| panic!("missing {name}: {e}"))
}

fn manifest() -> serde_json::Value {
    let text = std::fs::read_to_string(golden_dir().join("manifest.json"))
        .expect("manifest.json missing; run tests/golden/generate_fixtures.py");
    serde_json::from_str(&text).expect("manifest.json is valid JSON")
}

/// Independent ground-truth originals written by the Python oracle as
/// `*.orig.bin` sidecars (never produced by the code under test).
fn read_original(original_file: &str) -> Vec<u8> {
    std::fs::read(golden_dir().join(original_file))
        .unwrap_or_else(|e| panic!("missing {original_file}: {e}"))
}

/// A tiny deterministic LCG matching the documented fixed seed is NOT used
/// (Python's Mersenne Twister differs); the exact originals come from the
/// oracle's sidecar files shipped in the repo.
static SEED_NOTE: OnceLock<()> = OnceLock::new();

#[test]
fn manifest_is_present_and_version_one() {
    let m = manifest();
    assert_eq!(m["format"], "HCMP");
    assert_eq!(m["version"], 1);
    assert!(m["vectors"].as_array().unwrap().len() >= 12);
    SEED_NOTE.get_or_init(|| ());
}

#[test]
fn exact_canonical_lengths_and_codes_match_oracle() {
    let text =
        std::fs::read_to_string(golden_dir().join("lengths.json")).expect("lengths.json missing");
    let doc: serde_json::Value = serde_json::from_str(&text).unwrap();

    for case in doc["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let mut freq = [0u64; 256];
        for pair in case["freq"].as_array().unwrap() {
            let s = pair[0].as_u64().unwrap() as usize;
            freq[s] = pair[1].as_u64().unwrap();
        }
        let table =
            hcomp::huffman::build_lengths(&freq).unwrap_or_else(|e| panic!("{name}: {e:?}"));
        let got: Vec<[u64; 2]> = table
            .iter()
            .map(|sl| [sl.symbol as u64, sl.length as u64])
            .collect();
        let want: Vec<[u64; 2]> = case["lengths"]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| [p[0].as_u64().unwrap(), p[1].as_u64().unwrap()])
            .collect();
        assert_eq!(got, want, "lengths mismatch for {name}");

        // Exact code bit strings as emitted by the Python recurrence.
        let codes = hcomp::huffman::canonical_codes(&table).unwrap();
        for (sl, code_msb) in table.iter().zip(codes) {
            let want_str = case["codes"]
                .as_array()
                .unwrap()
                .iter()
                .find(|c| c[0].as_u64().unwrap() == sl.symbol as u64)
                .unwrap();
            let expected_bits = want_str[2].as_str().unwrap();
            let actual = if sl.length == 0 {
                String::new()
            } else {
                (0..sl.length)
                    .map(|i| {
                        if (code_msb >> (31 - i)) & 1 == 1 {
                            '1'
                        } else {
                            '0'
                        }
                    })
                    .collect()
            };
            assert_eq!(
                actual, expected_bits,
                "code bits mismatch for {name} symbol {}",
                sl.symbol
            );
        }
    }
}

#[test]
fn roundtrip_vectors_agree_across_all_three_implementations() {
    let m = manifest();
    for v in m["vectors"].as_array().unwrap() {
        if v["kind"] != "roundtrip" {
            continue;
        }
        let name = v["name"].as_str().unwrap();
        let file = v["file"].as_str().unwrap();
        let blob = read_bin(file);

        // Independent decoder on the Python-generated bytes.
        let indep_blocks = independent::decode_container(&blob)
            .unwrap_or_else(|e| panic!("{name}: independent decoder error {e}"));

        // Real decoder on the same Python-generated bytes.
        let real = decode_container(&blob, 1 << 20)
            .unwrap_or_else(|e| panic!("{name}: real decoder error {:?}", e.kind()));

        assert_eq!(indep_blocks.len(), real.len(), "{name} block count");
        for (a, b) in indep_blocks.iter().zip(real.iter()) {
            assert_eq!(a, &b.data, "{name} block mismatch");
        }

        // Independent ground-truth original from the Python sidecar (never
        // produced by the code under test).
        let original_file = v["original_file"].as_str().unwrap();
        let original = read_original(original_file);

        // Both decoders on the Python-generated bytes must agree with each
        // other and with the ground-truth original.
        assert_eq!(indep_blocks.len(), real.len(), "{name} block count");
        for (a, b) in indep_blocks.iter().zip(real.iter()) {
            assert_eq!(a, &b.data, "{name} block mismatch");
        }
        let decoded_concat: Vec<u8> = indep_blocks.concat();
        assert_eq!(decoded_concat, original, "{name} exact original mismatch");

        // Re-encode the ground-truth original with the REAL encoder (as a
        // single block; all fixtures fit the 1 MiB limit) and confirm the
        // independent decoder recovers it, and vice versa.
        let limit = 1u64 << 20;
        let chunks = vec![original.clone()];
        let reencoded = encode_container(&chunks, limit)
            .unwrap_or_else(|e| panic!("{name}: re-encode failed {e:?}"));
        let redecoded = independent::decode_container(&reencoded)
            .unwrap_or_else(|e| panic!("{name}: indep decode of real encode: {e}"));
        assert_eq!(
            redecoded.concat(),
            original,
            "{name} real-encode -> indep-decode"
        );
        let round = decode_container(&reencoded, limit)
            .unwrap_or_else(|e| panic!("{name}: real roundtrip {:?}", e.kind()));
        assert_eq!(
            round
                .iter()
                .flat_map(|b| b.data.iter().copied())
                .collect::<Vec<_>>(),
            original
        );
    }
}

#[test]
fn malformed_vectors_report_the_expected_failure_category() {
    let m = manifest();
    let mut seen = std::collections::HashSet::new();
    for v in m["vectors"].as_array().unwrap() {
        if v["kind"] != "malformed" {
            continue;
        }
        let name = v["name"].as_str().unwrap();
        let file = v["file"].as_str().unwrap();
        let expect = v["expect_error"].as_str().unwrap();
        seen.insert(expect);

        // Independent decoder must reject with the exact category.
        let blob = read_bin(file);
        let indep_err = independent::decode_container(&blob).expect_err(&format!(
            "{name}: independent decoder accepted corrupt data"
        ));
        assert_eq!(indep_err, expect, "{name}: independent decoder category");

        // Real decoder must reject too (never report success).
        let real_err = decode_container(&blob, 1 << 20)
            .expect_err(&format!("{name}: real decoder accepted corrupt data"));
        let real_cat = real_err.kind().as_str();
        assert_eq!(
            real_cat, expect,
            "{name}: real decoder category {real_cat} != {expect}"
        );
    }
    // The required adversarial classes are all present.
    for required in [
        "unknown_version",
        "over_subscribed_tree",
        "truncated_bitstream",
        "invalid_trailing_bits",
    ] {
        assert!(
            seen.contains(required),
            "golden set is missing required failure class {required}"
        );
    }
}

#[test]
fn all_bytes_extreme_skew_and_random_roundtrip() {
    // Explicitly named per the acceptance brief; these vectors exist in the
    // manifest and are exercised above; assert their identity here too so the
    // requirement is visibly enforced with concrete sizes.
    let names = ["all_bytes", "extreme_skew", "random_12k"];
    let expected_total = [256usize, 20064, 12000];
    for (name, total) in names.iter().zip(expected_total) {
        let file = format!("{name}.bin");
        let blob = read_bin(&file);
        let blocks = independent::decode_container(&blob).unwrap();
        let n: usize = blocks.iter().map(|b| b.len()).sum();
        assert_eq!(n, total, "{name} decoded size");
        // Container structure parses with the same block count.
        let info = inspect(&blob).unwrap();
        assert_eq!(info.blocks.len(), blocks.len());
    }
}

#[test]
fn single_symbol_and_empty_have_independent_definitions() {
    // Empty: directory records a zero-length block and zero bits.
    let empty = read_bin("empty.bin");
    let info = inspect(&empty).unwrap();
    assert_eq!(info.blocks.len(), 1);
    assert_eq!(info.blocks[0].original_len, 0);

    // Single symbol: block body is absent (11-byte payload) regardless of n.
    for n in [1usize, 7, 1000] {
        let blob = read_bin(&format!("single_{n}.bin"));
        let info = inspect(&blob).unwrap();
        assert_eq!(info.blocks[0].original_len, n as u64);
        assert_eq!(info.blocks[0].payload_len, 11, "table(3)+bit_total(8)");
    }
}
