"""Shared test helpers: configuration, logging, independent oracles.

The oracle functions here deliberately do NOT import the kernel under test
(``arrowzero.kernel``): expected NULL maps, offsets and values are computed
from raw bytes. PyArrow is used as a *second* independent oracle — answers are
never generated by the code being verified.
"""

from __future__ import annotations

import json
import os
import sys
import time
import uuid
from pathlib import Path

import numpy as np
import pyarrow as pa

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "samples"))


def make_run_id(kind: str) -> str:
    return f"test-{kind}-{uuid.uuid4().hex[:8]}"


class TestLog:
    """Per-test structured log: correlates run id, input hash, steps, verdict."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.lines: list[dict] = []

    def step(self, run_id: str, step: str, verdict: str, **detail) -> None:
        import arrowzero

        record = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime()) + "Z",
            "run_id": run_id,
            "step": step,
            "verdict": verdict,
            "versions": {
                "python": sys.version.split()[0],
                "pyarrow": pa.__version__,
                "arrowzero": arrowzero.__version__,
            },
            "detail": detail,
        }
        self.lines.append(record)
        with self.path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record, sort_keys=True, ensure_ascii=False) + "\n")


# --------------------------------------------------------------------------
# Independent oracle: raw Arrow buffers -> expected semantics
# --------------------------------------------------------------------------

def oracle_null_map(validity: bytes | None, length: int, offset: int = 0) -> list[bool]:
    """Return [True/False = is-null] computed directly from validity bytes."""
    if validity is None:
        return [False] * length
    out = []
    for i in range(offset, offset + length):
        byte = validity[i >> 3]
        present = bool((byte >> (i & 7)) & 1)
        out.append(not present)
    return out


def oracle_primitive_values(data: bytes, dtype: str, length: int, offset: int) -> list:
    arr = np.frombuffer(data, dtype=np.dtype(dtype))
    return [x.item() for x in arr[offset : offset + length]]


def oracle_string_values(
    validity: bytes | None,
    offsets: bytes,
    data: bytes,
    length: int,
    offset: int,
) -> list[str | None]:
    offs = np.frombuffer(offsets, dtype=np.int32)
    out: list[str | None] = []
    for i in range(offset, offset + length):
        if validity is not None and not bool(
            (validity[i >> 3] >> (i & 7)) & 1
        ):
            out.append(None)
        else:
            s, e = int(offs[i]), int(offs[i + 1])
            out.append(data[s:e].decode("utf-8"))
    return out


def pyarrow_values(view) -> list:
    """Second oracle: materialize via PyArrow itself."""
    return view.to_arrow().to_pylist()


def buffers_identical(view_a, view_b) -> dict[str, bool]:
    names = (
        ["validity", "offsets", "data"]
        if str(view_a.type) == "string"
        else ["validity", "data"]
    )
    return {
        name: (a is b)
        for name, a, b in zip(names, view_a.buffers, view_b.buffers)
    }


def pyarrow_violations(descriptor: dict) -> str | None:
    """Ask PyArrow's own validator; None when it accepts the descriptor."""
    type_name = descriptor["type"]
    t = pa.utf8() if type_name in ("utf8", "string") else getattr(pa, type_name)()
    import base64

    raw = [
        None if x is None else pa.py_buffer(base64.b64decode(x))
        for x in descriptor["buffers"]
    ]
    try:
        arr = pa.Array.from_buffers(t, descriptor["length"], raw, offset=descriptor.get("offset", 0))
        arr.validate(full=True)
        # Force a read so string length invariants are exercised.
        arr.to_pylist()
        return None
    except Exception as exc:  # noqa: BLE001 - oracle records the category text
        return type(exc).__name__ + ": " + str(exc)
