"""INDEPENDENT TEST ORACLE.

This file deliberately does NOT import ``localffg.kernel``,
``localffg.checker`` or ``localffg.encoding``. It is a from-scratch
reimplementation used to decide, for each synthetic input, what the system
ought to do — so expected results are not "generated by the code under test".

It still relies on the mature Ed25519 primitive (cryptography) and reads the
fixture manifest; everything else (canonicalization alternative, epoch math,
membership rules, exact conflict predicates, per-step sequential state) is
written independently here.
"""
from __future__ import annotations

import hashlib
import struct
from dataclasses import dataclass, field
from typing import Optional

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

# Status strings intentionally mirror the wire categories; the logic that
# produces them is independent.
ACCEPTED = "accepted"
DUPLICATE = "duplicate_retransmit"
DOUBLE = "double_vote"
SURROUND = "surround_vote"
INV_SIG = "invalid_signature"
INV_CHAIN = "invalid_chain"
INV_ROUNDS = "invalid_rounds"
INV_MEMBER = "invalid_membership"
UNKNOWN = "unknown_validator"
MALFORMED = "malformed"

SLASHABLE = {DOUBLE, SURROUND}
INVALID = {INV_SIG, INV_CHAIN, INV_ROUNDS, INV_MEMBER, UNKNOWN, MALFORMED}


# --------------------------------------------------------------------------- #
# Alternative canonical encoding (different code path: nested length sections)
# Used to prove the production encoding is unambiguous for the signed fields.
# --------------------------------------------------------------------------- #

def alt_section(data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + data


def alt_signed_payload(domain: bytes, d: dict) -> bytes:
    # Explicit key ordering and typed sections; shape differs from production
    # TLV but must bind exactly the same six semantic fields.
    return b"".join(
        [
            b"ALT",
            alt_section(b"vote-domain"),
            alt_section(domain),
            alt_section(b"chain-id"),
            alt_section(str(d["chain_id"]).encode()),
            alt_section(b"validator-id"),
            alt_section(str(d["validator_id"]).encode()),
            alt_section(b"source-round"),
            alt_section(struct.pack(">Q", int(d["source_round"]))),
            alt_section(b"target-round"),
            alt_section(struct.pack(">Q", int(d["target_round"]))),
            alt_section(b"block-root"),
            alt_section(bytes.fromhex(d["block_root"])),
        ]
    )


def production_signed_payload(domain: bytes, d: dict) -> bytes:
    """Re-implement the PRODUCTION wire format independently, field by field,
    so signatures on fixtures can be verified without importing encoding.py."""
    def u64(n: int) -> bytes:
        return struct.pack(">Q", n)

    def tag_bytes(tag: int, value: bytes) -> bytes:
        return bytes([tag]) + u64(len(value)) + value

    def tag_str(tag: int, value: str) -> bytes:
        return tag_bytes(tag, value.encode("utf-8"))

    def tag_u64(tag: int, value: int) -> bytes:
        return bytes([tag]) + u64(value)

    return b"".join(
        [
            tag_bytes(0x01, b"LFV1"),
            tag_bytes(0x10, domain),
            tag_str(0x11, str(d["chain_id"])),
            tag_str(0x12, str(d["validator_id"])),
            tag_u64(0x13, int(d["source_round"])),
            tag_u64(0x14, int(d["target_round"])),
            tag_bytes(0x15, bytes.fromhex(d["block_root"])),
        ]
    )


# --------------------------------------------------------------------------- #
# Independent registry / epoch model
# --------------------------------------------------------------------------- #

@dataclass
class OracleRegistry:
    chain_id: str
    epoch_length: int
    pubkeys: dict[str, bytes] = field(default_factory=dict)
    # vid -> sorted [(effective_epoch, weight)]
    weights: dict[str, list[tuple[int, int]]] = field(default_factory=dict)

    @classmethod
    def from_manifest(cls, reg: dict) -> "OracleRegistry":
        r = cls(chain_id=reg["chain_id"], epoch_length=int(reg["epoch_length"]))
        for v in reg["validators"]:
            r.pubkeys[v["validator_id"]] = bytes.fromhex(v["pubkey"])
            r.weights[v["validator_id"]] = sorted(
                (int(e), int(w)) for e, w in v["weight_updates"]
            )
        return r

    def epoch_of(self, round_index: int) -> int:
        return round_index // self.epoch_length

    def weight_at_epoch(self, vid: str, epoch: int) -> Optional[int]:
        if vid not in self.weights:
            return None
        w = 0
        for eff, weight in self.weights[vid]:
            if eff <= epoch:
                w = weight
        return w


# --------------------------------------------------------------------------- #
# Independent signature verification (direct Ed25519)
# --------------------------------------------------------------------------- #

def oracle_verify_signature(domain: bytes, envelope: dict, expected_pubkey: bytes) -> tuple[bool, str]:
    try:
        pub = bytes.fromhex(envelope["signer_pubkey"])
        sig = bytes.fromhex(envelope["signature"])
    except (KeyError, ValueError):
        return False, "hex decode"
    if len(pub) != 32 or len(sig) != 64:
        return False, "length"
    if pub != expected_pubkey:
        return False, "embedded pubkey != registry key"
    payload = production_signed_payload(domain, envelope)
    try:
        Ed25519PublicKey.from_public_bytes(pub).verify(sig, payload)
    except InvalidSignature:
        return False, "bad signature"
    return True, "ok"


# --------------------------------------------------------------------------- #
# Independent conflict predicates
# --------------------------------------------------------------------------- #

def _identical(x: dict, y: dict) -> bool:
    keys = ("validator_id", "source_round", "target_round", "block_root", "signer_pubkey", "signature")
    return all(x[k] == y[k] for k in keys)


def oracle_classify_pair(x: dict, y: dict) -> Optional[str]:
    """Given two envelopes, classify their pair.

    Returns DOUBLE / SURROUND / None (None includes different validators,
    identical retransmission, equal-boundary and crossing links).
    """
    if x["validator_id"] != y["validator_id"]:
        return None
    if _identical(x, y):
        return None
    s1, t1 = int(x["source_round"]), int(x["target_round"])
    s2, t2 = int(y["source_round"]), int(y["target_round"])
    if t1 == t2:
        return DOUBLE
    # strict nesting, either direction
    if (s2 < s1 < t1 < t2) or (s1 < s2 < t2 < t1):
        return SURROUND
    return None


# --------------------------------------------------------------------------- #
# Sequential per-step expected outcome (independent state machine)
# --------------------------------------------------------------------------- #

@dataclass
class ExpectedStep:
    label: str
    status: str
    slashable: bool
    expected_evidence_valid: list[str] = field(default_factory=list)  # kinds emitted at this step
    weight_of_offense: Optional[int] = None
    weight_epoch: Optional[int] = None


@dataclass
class ScenarioExpectation:
    name: str
    steps: list[ExpectedStep]
    total_evidence: int = 0


def _shape_ok(env: dict) -> bool:
    try:
        assert isinstance(env["chain_id"], str) and env["chain_id"]
        assert isinstance(env["validator_id"], str) and env["validator_id"]
        s, t = int(env["source_round"]), int(env["target_round"])
        br = bytes.fromhex(env["block_root"])
        assert 0 < len(br) <= 64
        assert len(bytes.fromhex(env["signer_pubkey"])) == 32
        assert len(bytes.fromhex(env["signature"])) == 64
        return True
    except Exception:
        return False


def expected_sequence(domain: bytes, registry: OracleRegistry, steps: list[dict]) -> list[ExpectedStep]:
    """Reproduce the ingest order independently. Only signature-valid,
    active-membership votes enter the state used for conflict detection."""
    accepted_state: dict[str, list[dict]] = {}
    out: list[ExpectedStep] = []

    for step in steps:
        env = step["signed"]
        label = step["label"]

        if not _shape_ok(env):
            out.append(ExpectedStep(label, MALFORMED, False))
            continue

        s, t = int(env["source_round"]), int(env["target_round"])
        if not (0 <= s < t):
            out.append(ExpectedStep(label, INV_ROUNDS, False))
            continue
        if env["chain_id"] != registry.chain_id:
            out.append(ExpectedStep(label, INV_CHAIN, False))
            continue

        vid = env["validator_id"]
        weight = registry.weight_at_epoch(vid, registry.epoch_of(t))
        if weight is None:
            out.append(ExpectedStep(label, UNKNOWN, False))
            continue
        if weight <= 0:
            out.append(ExpectedStep(label, INV_MEMBER, False))
            continue

        ok, _why = oracle_verify_signature(domain, env, registry.pubkeys[vid])
        if not ok:
            out.append(ExpectedStep(label, INV_SIG, False))
            continue

        prior = accepted_state.setdefault(vid, [])

        # duplicate first?
        if any(_identical(env, p) for p in prior):
            out.append(ExpectedStep(label, DUPLICATE, False))
            continue

        pair_kinds = [k for k in (oracle_classify_pair(env, p) for p in prior) if k is not None]
        if pair_kinds:
            # SURROUND dominates DOUBLE when both occur in one step
            kind = SURROUND if SURROUND in pair_kinds else DOUBLE
            earlier_target = min(t, min(int(p["target_round"]) for p in prior
                                        if oracle_classify_pair(env, p) is not None))
            epoch = registry.epoch_of(earlier_target)
            w = registry.weight_at_epoch(vid, epoch) or 0
            out.append(ExpectedStep(label, kind, True, pair_kinds, w, epoch))
            prior.append(env)  # valid conflicting vote is still recorded
            continue

        prior.append(env)
        out.append(ExpectedStep(label, ACCEPTED, False))

    return out


def expected_evidence_pairs(domain: bytes, registry: OracleRegistry, steps: list[dict]) -> list[tuple[str, str, dict, dict]]:
    """Offense EMISSIONS through the scenario: one per offending submission,
    with SURROUND dominating DOUBLE when the new vote conflicts with several
    prior votes (mirrors the kernel's one status per submission)."""
    state: dict[str, list[dict]] = {}
    emissions: list[tuple[str, str, dict, dict]] = []
    for step in steps:
        env = step["signed"]
        try:
            s, t = int(env["source_round"]), int(env["target_round"])
        except Exception:
            continue
        if not _shape_ok(env) or not (0 <= s < t) or env["chain_id"] != registry.chain_id:
            continue
        vid = env["validator_id"]
        w = registry.weight_at_epoch(vid, registry.epoch_of(t))
        if not w or w <= 0:
            continue
        ok, _ = oracle_verify_signature(domain, env, registry.pubkeys[vid])
        if not ok:
            continue
        prior = state.setdefault(vid, [])
        if any(_identical(env, p) for p in prior):
            continue
        conflicts = [(p, k) for p in prior for k in [oracle_classify_pair(env, p)] if k is not None]
        if conflicts:
            kind = SURROUND if any(k == SURROUND for _p, k in conflicts) else DOUBLE
            other = next(p for p, k in conflicts if k == kind)
            emissions.append((kind, vid, other, env))
        prior.append(env)
    return emissions


def envelope_fingerprint(env: dict) -> bytes:
    """Content fingerprint the test can compare between inputs/outputs."""
    return hashlib.sha256(
        b"|".join(
            str(env[k]).encode() for k in
            ("validator_id", "source_round", "target_round", "block_root", "signer_pubkey", "signature")
        )
    ).digest()
