//! Kernel-level tests driven by the *independent Python oracle* fixture
//! (`tests/fixtures/golden.json`, generated by `mphf_ref.py`).
//!
//! Expected edges, peel outcomes and g/slot values are the Python program's
//! outputs, never computed by the crate under test.

mod common;

use common::load_fixture;
use mphf::hash;
use mphf::kernel::{assign, peel, EdgeSource, PeelOutcome};

struct FixedSource {
    edges: Vec<[u64; 3]>,
    m: usize,
}
impl EdgeSource for FixedSource {
    fn n(&self) -> usize {
        self.edges.len()
    }
    fn m(&self) -> usize {
        self.m
    }
    fn edge(&self, i: usize) -> Option<[u64; 3]> {
        Some(self.edges[i])
    }
}

#[test]
fn raw_hash_vectors_match_python_oracle() {
    // hash_vectors in the fixture are pinned at seed 1 (see main_golden in
    // mphf_ref.py), independent of the seed the build happened to need.
    let fx = load_fixture();
    let seed = 1u64;
    for v in fx["hash_vectors"].as_array().unwrap() {
        let key_hex = v["key_hex"].as_str().unwrap();
        let key = decode_hex(key_hex);
        let got = hash::edge_hash(&key, seed);
        assert_eq!(
            got.h0,
            v["h0"].as_u64().unwrap(),
            "h0 mismatch for {}",
            key_hex
        );
        assert_eq!(got.h1, v["h1"].as_u64().unwrap(), "h1 mismatch");
        assert_eq!(got.h2, v["h2"].as_u64().unwrap(), "h2 mismatch");
        assert_eq!(
            hash::fingerprint(&key, seed, 16),
            v["fp16"].as_u64().unwrap()
        );
        assert_eq!(
            hash::fingerprint(&key, seed, 8),
            v["fp8"].as_u64().unwrap()
        );
    }
}

#[test]
fn hash_vectors_for_seed_one_are_exact_pinned_values() {
    // Pinned by `python3 tests/reference/mphf_ref.py hash-vector --seed 1`.
    // These are concrete constants emitted by the independent oracle; if the
    // hash contract changes, they change — the format binding breaks loudly.
    struct Row {
        key: &'static [u8],
        h0: u64,
        h1: u64,
        h2: u64,
        fp16: u64,
    }
    let rows = [
        Row {
            key: b"item-00001",
            h0: 6990891533008902279,
            h1: 18155429034359613529,
            h2: 12168125247651088027,
            fp16: 38336,
        },
        Row {
            key: b"alpha",
            h0: 9776891714465508287,
            h1: 12913638530555306196,
            h2: 18286557494073834064,
            fp16: 34230,
        },
        Row {
            key: b"",
            h0: 7565362702677110517,
            h1: 1022040345128796356,
            h2: 5149892213239774945,
            fp16: 11707,
        },
    ];
    for r in rows {
        let h = hash::edge_hash(r.key, 1);
        assert_eq!((h.h0, h.h1, h.h2), (r.h0, r.h1, r.h2), "key {:?}", r.key);
        assert_eq!(hash::fingerprint(r.key, 1, 16), r.fp16);
    }
}

fn decode_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn scripted_disjoint_edges_peel_and_assign() {
    let fx = load_fixture();
    let s = &fx["scripted"]["disjoint"];
    let edges: Vec<[u64; 3]> = s["edges"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| {
            [
                a[0].as_u64().unwrap(),
                a[1].as_u64().unwrap(),
                a[2].as_u64().unwrap(),
            ]
        })
        .collect();
    let m = s["m"].as_u64().unwrap() as usize;
    let src = FixedSource { edges: edges.clone(), m };
    let steps = match peel(&src) {
        PeelOutcome::Success(st) => st,
        other => panic!("expected peel success, got {other:?}"),
    };
    assert_eq!(steps.len(), 2);
    let a = assign(&edges, &steps, m);
    // Selector for each edge selects its own peel vertex (Python invariant).
    for (id, e) in edges.iter().enumerate() {
        let sum = (a.g[e[0] as usize] + a.g[e[1] as usize] + a.g[e[2] as usize]) % 3;
        let v = e[sum as usize];
        assert_eq!(steps.iter().find(|st| st.edge_id == id).unwrap().vertex, v);
    }
}

#[test]
fn scripted_k4_hypergraph_is_a_solid_core() {
    let fx = load_fixture();
    let s = &fx["scripted"]["k4_3"];
    assert_eq!(s["peels"].as_bool(), Some(false));
    let edges: Vec<[u64; 3]> = s["edges"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| {
            [
                a[0].as_u64().unwrap(),
                a[1].as_u64().unwrap(),
                a[2].as_u64().unwrap(),
            ]
        })
        .collect();
    let m = s["m"].as_u64().unwrap() as usize;
    let src = FixedSource { edges, m };
    match peel(&src) {
        PeelOutcome::CoreRemain { remaining } => {
            // All four edges are stuck in the 3-core.
            assert_eq!(remaining, 4);
        }
        other => panic!("expected core_remain(4), got {other:?}"),
    }
}

#[test]
fn empty_keyset_peels_with_zero_steps() {
    let src = FixedSource {
        edges: vec![],
        m: 3,
    };
    match peel(&src) {
        PeelOutcome::Success(steps) => assert!(steps.is_empty()),
        other => panic!("empty set must peel trivially, got {other:?}"),
    }
}
