"""Independent per-transaction reference implementation ("the oracle").

This module is deliberately written as if from the written specification in
README.md: it imports **no** production package (``utxo_ledger.encoding`` /
``kernel`` / ``storage`` are all forbidden here). It shares only:

* the Python standard library (``struct``/``hashlib``), and
* the mature ``cryptography`` library for Ed25519 verification.

Constants below are re-declared from the spec text, not imported, so a wrong
constant or a shared encoder bug cannot make the system agree with itself.

The oracle is transaction-at-a-time: after each transaction inside a block it
exposes the reference UTXO set (``intermediate_states``), letting the test suite
compare the production system's behavior -- and, after a rejection, prove the
committed set is byte-for-byte unchanged -- against an answer generated by
different code.
"""

from __future__ import annotations

import hashlib
import struct
from dataclasses import dataclass, field

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric import ed25519

# --- spec constants (independent re-declaration; keep in sync with README) ---
TX_TAG = b"UTXO-TXN/1\x00"
BLOCK_TAG = b"UTXO-BLOCK/1\x00"
SIGHASH_TAG = b"UTXO-SIGHASH/1\x00"
MAX_MONEY = 2**64 - 1
BLOCK_SUBSIDY = 1_000_000
ZERO = b"\x00" * 32
SUPPORTED_TX_VERSION = 1
SUPPORTED_BLOCK_VERSION = 1


class OracleError(Exception):
    """Structured reference verdict mirroring the production error contract."""

    def __init__(self, code: str, category: str, message: str, tx_index=None):
        super().__init__(message)
        self.code = code
        self.category = category
        self.message = message
        self.tx_index = tx_index

    def to_dict(self):
        d = {"code": self.code, "category": self.category, "message": self.message}
        if self.tx_index is not None:
            d["tx_index"] = self.tx_index
        return d


# Category membership, independently listed for each code.
STATE = "state"
INPUT = "input"
RESOURCE = "resource"
COMPUTATION = "computation"
_CATEGORIES = {
    "malformed": INPUT,
    "empty_block": INPUT,
    "bad_version": INPUT,
    "bad_header": INPUT,
    "bad_txid": INPUT,
    "bad_public_key": INPUT,
    "bad_signature": INPUT,
    "invalid_encoding": INPUT,
    "value_out_of_range": INPUT,
    "zero_value_output": INPUT,
    "unknown_outpoint": STATE,
    "already_spent": STATE,
    "duplicate_input": STATE,
    "duplicate_txid": STATE,
    "double_spend": STATE,
    "forward_reference": STATE,
    "cyclic_reference": STATE,
    "orphan_transaction": STATE,
    "bad_coinbase": STATE,
    "balance_mismatch": STATE,
    "fee_negative": STATE,
    "value_overflow": STATE,
    "sig_tampered": STATE,
    "block_height_invalid": STATE,
    "prev_block_hash_mismatch": STATE,
    "duplicate_block": STATE,
    "block_too_large": RESOURCE,
    "too_many_txs": RESOURCE,
    "too_many_inputs": RESOURCE,
    "too_many_outputs": RESOURCE,
    "too_many_sigops": RESOURCE,
    "block_validation_steps_exceeded": RESOURCE,
    "crypto_failure": COMPUTATION,
    "storage_failure": COMPUTATION,
    "serialization_failure": COMPUTATION,
    "internal_error": COMPUTATION,
    "not_found": INPUT,
}


def fail(code, message, tx_index=None):
    raise OracleError(code, _CATEGORIES.get(code, COMPUTATION), message, tx_index)


# --------------------------------------------------------------------------- #
# Independent wire codec
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class OIn:
    txid: bytes
    vout: int
    sig: bytes


@dataclass(frozen=True)
class OOut:
    value: int
    pubkey: bytes


@dataclass
class OTx:
    version: int
    inputs: list[OIn]
    outputs: list[OOut]

    @property
    def txid(self) -> bytes:
        return hashlib.sha256(self._encode(True)).digest()

    def sighash(self) -> bytes:
        return hashlib.sha256(SIGHASH_TAG + self._encode(False)).digest()

    def _encode(self, with_sigs: bool) -> bytes:
        if len(self.inputs) > 0xFFFF or len(self.outputs) > 0xFFFF:
            fail("malformed", "too many in/out")
        parts = [
            TX_TAG,
            struct.pack("<I", self.version),
            struct.pack("<H", len(self.inputs)),
            struct.pack("<H", len(self.outputs)),
        ]
        for i in self.inputs:
            if len(i.txid) != 32:
                fail("bad_txid", "txid len")
            parts += [i.txid, struct.pack("<I", i.vout)]
            if with_sigs:
                parts += [struct.pack("<H", len(i.sig)), i.sig]
        for o in self.outputs:
            parts += [struct.pack("<Q", o.value), struct.pack("<H", len(o.pubkey)), o.pubkey]
        return b"".join(parts)


@dataclass
class OBlock:
    version: int
    height: int
    prev_hash: bytes
    txs: list[OTx] = field(default_factory=list)


class _Cursor:
    def __init__(self, data: bytes):
        self.data = data
        self.pos = 0

    def need(self, n: int, what: str) -> bytes:
        if self.pos + n > len(self.data):
            fail("malformed", f"truncated at {what}")
        chunk = self.data[self.pos : self.pos + n]
        self.pos += n
        return chunk

    def u16(self, what):
        return struct.unpack("<H", self.need(2, what))[0]

    def u32(self, what):
        return struct.unpack("<I", self.need(4, what))[0]

    def u64(self, what):
        return struct.unpack("<Q", self.need(8, what))[0]

    def tag(self, tag, what):
        if self.need(len(tag), what) != tag:
            fail("malformed", f"bad {what} tag")

    def blob(self, max_len, what):
        n = self.u16(what)
        if n > max_len:
            fail("malformed", f"{what} too long")
        return self.need(n, what)


def decode_tx_bytes(data: bytes) -> OTx:
    c = _Cursor(data)
    c.tag(TX_TAG, "tx")
    version = c.u32("version")
    n_in, n_out = c.u16("n_in"), c.u16("n_out")
    if n_in > 256:
        fail("too_many_inputs", f"{n_in}>256")
    if n_out > 256:
        fail("too_many_outputs", f"{n_out}>256")
    if n_in == 0 or n_out == 0:
        fail("malformed", "tx needs >=1 input and >=1 output")
    ins, outs = [], []
    for _ in range(n_in):
        txid = c.need(32, "txid")
        vout = c.u32("vout")
        sig = c.blob(512, "sig")
        ins.append(OIn(txid, vout, sig))
    for _ in range(n_out):
        value = c.u64("value")
        pk = c.blob(64, "pk")
        if len(pk) != 32:
            fail("bad_public_key", f"pk len {len(pk)}")
        outs.append(OOut(value, pk))
    return OTx(version, ins, outs)


def _merkle(txids: list[bytes]) -> bytes:
    if not txids:
        return ZERO
    level = list(txids)
    while len(level) > 1:
        if len(level) % 2:
            level.append(level[-1])
        level = [
            hashlib.sha256(level[i] + level[i + 1]).digest()
            for i in range(0, len(level), 2)
        ]
    return level[0]


def block_hash(version, height, prev_hash, txs: list[OTx]) -> bytes:
    return hashlib.sha256(
        b"".join(
            [
                BLOCK_TAG,
                struct.pack("<I", version),
                struct.pack("<Q", height),
                prev_hash,
                _merkle([t.txid for t in txs]),
                struct.pack("<I", len(txs)),
            ]
        )
    ).digest()


def decode_block_bytes(data: bytes) -> OBlock:
    if len(data) > 1_000_000:
        fail("block_too_large", f"{len(data)}>1MB")
    c = _Cursor(data)
    c.tag(BLOCK_TAG, "block")
    version = c.u32("version")
    height = c.u64("height")
    prev_hash = c.need(32, "prev_hash")
    n_tx = c.u32("n_tx")
    if n_tx > 1_000:
        fail("too_many_txs", f"{n_tx}>1000")
    txs = []
    for _ in range(n_tx):
        # Transactions are self-delimiting via their length-prefixed vectors.
        start = c.pos
        txs.append(decode_tx_bytes(c.data[start:]))
        # Advance the cursor by actually re-walking via a nested cursor: decode
        # length by running the same parser bound to the current position.
        c.pos = start + _tx_span(c.data, start)
    if c.pos != len(data):
        fail("invalid_encoding", "trailing block bytes")
    return OBlock(version, height, prev_hash, txs)


def _tx_span(data: bytes, start: int) -> int:
    c = _Cursor(data)
    c.pos = start
    c.need(len(TX_TAG), "tag")
    c.need(4 + 2 + 2, "header")
    n_in = struct.unpack("<H", data[start + len(TX_TAG) + 4 : start + len(TX_TAG) + 6])[0]
    n_out = struct.unpack(
        "<H", data[start + len(TX_TAG) + 6 : start + len(TX_TAG) + 8]
    )[0]
    for _ in range(n_in):
        c.need(32 + 4, "outpoint")
        n = c.u16("siglen")
        c.need(n, "sig")
    for _ in range(n_out):
        c.need(8, "value")
        n = c.u16("pklen")
        c.need(n, "pk")
    return c.pos - start


# --------------------------------------------------------------------------- #
# Reference state
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class RefUtxo:
    value: int
    pubkey: bytes
    created_height: int


class OracleState:
    """Reference committed UTXO set + tip; independent of SqliteStore."""

    def __init__(self, tip_height: int = 0, tip_hash: bytes = ZERO):
        self.utxos: dict[tuple[bytes, int], RefUtxo] = {}
        self.spent: set[tuple[bytes, int]] = set()
        self.tip_height = tip_height
        self.tip_hash = tip_hash

    def snapshot(self) -> dict[tuple[str, int], dict]:
        return {
            (txid.hex(), vout): {
                "value": u.value,
                "pubkey": u.pubkey.hex(),
                "height": u.created_height,
            }
            for (txid, vout), u in sorted(self.utxos.items())
        }

    def copy(self) -> "OracleState":
        clone = OracleState(self.tip_height, self.tip_hash)
        clone.utxos = dict(self.utxos)
        clone.spent = set(self.spent)
        return clone


@dataclass
class OracleVerdict:
    accepted: bool
    block_hash: str | None
    fees_by_tx: dict[int, int]
    intermediate_states: list[dict]   # reference snapshot after each tx
    error: dict | None = None


def _checked_add(a: int, b: int, what: str, tx_index=None) -> int:
    if a < 0 or b < 0 or a > MAX_MONEY or b > MAX_MONEY or a > MAX_MONEY - b:
        fail("value_overflow", f"overflow summing {what}: {a}+{b}", tx_index)
    return a + b


def _ed_verify(pubkey: bytes, message: bytes, signature: bytes, tx_index=None) -> None:
    if len(pubkey) != 32:
        fail("bad_public_key", "pubkey length", tx_index)
    if len(signature) != 64:
        fail("bad_signature", "signature length", tx_index)
    try:
        key = ed25519.Ed25519PublicKey.from_public_bytes(pubkey)
        key.verify(signature, message)
    except InvalidSignature:
        fail("sig_tampered", "signature invalid for referenced pubkey", tx_index)
    except Exception as exc:  # pragma: no cover - backend fault
        fail("crypto_failure", repr(exc), tx_index)


def apply_block_to_state(
    raw_block: bytes,
    state: OracleState,
) -> OracleVerdict:
    """Reference validator+applier. On rejection ``state`` is left untouched."""
    blk = decode_block_bytes(raw_block)
    if blk.version != SUPPORTED_BLOCK_VERSION:
        fail("bad_version", f"block version {blk.version}")
    if not blk.txs:
        fail("empty_block", "no txs")
    if blk.height != state.tip_height + 1:
        fail(
            "block_height_invalid",
            f"height {blk.height} != tip+1 ({state.tip_height + 1})",
        )
    if blk.prev_hash != state.tip_hash:
        fail("prev_block_hash_mismatch", "prev_hash != tip hash")

    for i, t in enumerate(blk.txs):
        if t.version != SUPPORTED_TX_VERSION:
            fail("bad_version", f"tx version {t.version}", i)

    txids = [t.txid for t in blk.txs]
    positions: dict[bytes, int] = {}
    for i, h in enumerate(txids):
        if h in positions:
            fail("duplicate_txid", f"txid at {positions[h]} and {i}", i)
        positions[h] = i

    # Work on a scratch overlay; only swap in on full success.
    live = dict(state.utxos)
    spent = set(state.spent)
    pending_outputs: dict[bytes, list[RefUtxo]] = {}
    consumed_in_block: set[tuple[bytes, int]] = set()
    fees: dict[int, int] = {}
    intermediate: list[dict] = []

    def snapshot_scratch():
        return {
            (txid.hex(), vout): {
                "value": u.value,
                "pubkey": u.pubkey.hex(),
                "height": u.created_height,
            }
            for (txid, vout), u in sorted(live.items())
        }

    total_fees = 0
    for i, tx in enumerate(blk.txs):
        digest = tx.sighash()
        is_cb = len(tx.inputs) == 1 and tx.inputs[0].txid == ZERO

        if i == 0:
            if not is_cb:
                fail("bad_coinbase", "tx[0] must be coinbase", 0)
            cb_in = tx.inputs[0]
            if cb_in.vout != blk.height:
                fail(
                    "bad_coinbase",
                    f"coinbase height {cb_in.vout} != {blk.height}",
                    0,
                )
            if cb_in.sig != b"":
                fail("bad_coinbase", "coinbase must carry no signature", 0)
            claim = 0
            created = []
            for vout, o in enumerate(tx.outputs):
                if o.value <= 0:
                    fail("zero_value_output", f"coinbase out {vout}", 0)
                if o.value > MAX_MONEY:
                    fail("value_out_of_range", "coinbase value > MAX_MONEY", 0)
                claim = _checked_add(claim, o.value, "coinbase sums", 0)
                created.append((vout, RefUtxo(o.value, o.pubkey, blk.height)))
            pending_outputs[tx.txid] = [u for _, u in created]
            # Coinbase outputs enter the overlay immediately (spendable by
            # later txs in this same block).
            for vout, u in created:
                live[(tx.txid, vout)] = u
            fees[0] = 0
            intermediate.append(snapshot_scratch())
            continue

        if is_cb:
            fail("bad_coinbase", "non-first coinbase", i)

        local_seen: set[tuple[bytes, int]] = set()
        in_sum = 0
        spend_keys: list[tuple[bytes, int]] = []
        for inp in tx.inputs:
            key = (inp.txid, inp.vout)
            if key in local_seen:
                fail(
                    "duplicate_input",
                    f"same outpoint twice in tx[{i}]",
                    i,
                )
            local_seen.add(key)

            if inp.txid in positions:
                j = positions[inp.txid]
                if j == i or inp.txid == tx.txid:
                    fail(
                        "cyclic_reference",
                        f"tx[{i}] references itself",
                        i,
                    )
                if j > i:
                    fail(
                        "forward_reference",
                        f"tx[{i}] spends later tx[{j}]",
                        i,
                    )

            if key in consumed_in_block:
                # Distinct from a within-transaction repeat (local_seen): this
                # is a second transaction spending the same outpoint in-block.
                fail(
                    "double_spend",
                    f"outpoint already spent by an earlier tx in block (tx[{i}])",
                    i,
                )

            if inp.txid in pending_outputs:
                outs = pending_outputs[inp.txid]
                if not (0 <= inp.vout < len(outs)):
                    fail("unknown_outpoint", "bad intra-block vout", i)
                source = outs[inp.vout]
                # If it came from the overlay, it may also already be spent
                # intra-block; consumed_in_block check above covers it.
            elif key in live:
                source = live[key]
            elif key in spent:
                fail("already_spent", f"{inp.txid.hex()}:{inp.vout} spent", i)
            else:
                fail(
                    "unknown_outpoint",
                    f"{inp.txid.hex()}:{inp.vout} never existed",
                    i,
                )

            _ed_verify(source.pubkey, digest, inp.sig, i)
            in_sum = _checked_add(in_sum, source.value, "input sums", i)
            spend_keys.append(key)

        out_sum = 0
        created = []
        for vout, o in enumerate(tx.outputs):
            if o.value <= 0:
                fail("zero_value_output", f"output {vout} is zero", i)
            if o.value > MAX_MONEY:
                fail("value_out_of_range", "value > MAX_MONEY", i)
            out_sum = _checked_add(out_sum, o.value, "output sums", i)
            created.append(RefUtxo(o.value, o.pubkey, blk.height))

        if out_sum > in_sum:
            fail(
                "fee_negative",
                f"out={out_sum} > in={in_sum}",
                i,
            )
        fee = in_sum - out_sum
        fees[i] = fee
        total_fees = _checked_add(total_fees, fee, "fees", i)

        # Apply this tx onto the overlay.
        for key in spend_keys:
            del live[key]
            spent.add(key)
            consumed_in_block.add(key)
        pending_outputs[tx.txid] = created
        for vout, u in enumerate(created):
            live[(tx.txid, vout)] = u

        intermediate.append(snapshot_scratch())

    # Coinbase claim check against accumulated fees.
    # ``claim`` was accumulated (with overflow checks) while processing tx[0].
    allowed = _checked_add(BLOCK_SUBSIDY, total_fees, "subsidy+fees", 0)
    if claim != allowed:
        fail(
            "bad_coinbase",
            f"coinbase claims {claim}, allowed {allowed}",
            0,
        )

    # Full block valid: commit the overlay atomically.
    state.utxos = live
    state.spent = spent
    state.tip_height = blk.height
    state.tip_hash = block_hash(blk.version, blk.height, blk.prev_hash, blk.txs)
    return OracleVerdict(
        accepted=True,
        block_hash=state.tip_hash.hex(),
        fees_by_tx=fees,
        intermediate_states=intermediate,
        error=None,
    )
