"""Independent oracle for test expectations.

CRITICAL: expected answers must not be generated by the code under test.
This oracle never imports :mod:`textindex.index`, :mod:`textindex.edits`,
:mod:`textindex.service` or :mod:`textindex.storage`.  Its independent data
sources are:

* ``regex`` 2026.9.10 (a different library/version) and its ``\\X`` pattern
  for extended grapheme cluster boundaries;
* CPython's ``str.encode('utf-8')`` scanned independently for lead-byte
  offsets;
* ``unicodedata.normalize`` for the expected canonical text;
* direct codepoint arithmetic for edits and rebuilds.

If both implementations agree over thousands of randomized and hand-built
cases, a shared mistake is far less likely.
"""

from __future__ import annotations

import unicodedata

import regex as re  # intentionally the third-party regex engine

GRAPHEME_X = re.compile(r"\X")


def cluster_spans(text: str) -> list[tuple[int, int]]:
    return [(m.start(), m.end()) for m in GRAPHEME_X.finditer(text)]


def cluster_starts(text: str) -> list[int]:
    starts = [s for s, _ in cluster_spans(text)]
    starts.append(len(text))
    return starts


def byte_length(text: str) -> int:
    return len(text.encode("utf-8"))


def lead_byte_starts(text: str) -> list[int]:
    """All UTF-8 lead-byte offsets, scanning code points one by one."""
    out = [0]
    pos = 0
    for ch in text:
        pos += len(ch.encode("utf-8"))
        out.append(pos)
    return out


def cp_byte_offsets(text: str) -> list[int]:
    """Byte offset of each codepoint start, followed by total length."""
    out = [0]
    pos = 0
    for ch in text:
        pos += len(ch.encode("utf-8"))
        out.append(pos)
    return out


def cluster_byte_starts(text: str) -> list[int]:
    """Byte offset of each grapheme cluster start, then total byte length."""
    cp_bytes = cp_byte_offsets(text)
    return [cp_bytes[s] for s in cluster_starts(text)]


def expected_index(text: str) -> dict:
    """Full expected offset tables (cp starts and byte starts per cluster)."""
    return {
        "cp_starts": cluster_starts(text),
        "byte_starts": cluster_byte_starts(text),
        "clusters": [text[s:e] for s, e in cluster_spans(text)],
        "codepoints": len(text),
        "bytes": byte_length(text),
    }


def cluster_at_codepoint(text: str, cp: int) -> int:
    starts = cluster_starts(text)
    if cp not in starts:
        raise ValueError(f"{cp} is not a cluster boundary")
    return starts.index(cp)


def cluster_at_byte(text: str, byte: int) -> int:
    cp_bytes = cp_byte_offsets(text)
    starts = cluster_byte_starts(text)
    if byte not in cp_bytes:
        raise ValueError("not_a_utf8_lead")
    if byte not in starts:
        raise ValueError("not_a_cluster_boundary")
    return starts.index(byte)


def is_utf8_lead(text: str, byte: int) -> bool:
    return byte in set(cp_byte_offsets(text))


def normalize(text: str, form: str) -> str:
    if form.upper() == "NONE":
        return text
    return unicodedata.normalize(form.upper(), text)


def apply_text_edit(text: str, start_cp: int, end_cp: int,
                    replacement: str) -> str:
    """Independently perform the edit at codepoint offsets."""
    return text[:start_cp] + replacement + text[end_cp:]


def normalize_edit(text: str, start_cp: int, end_cp: int, replacement: str,
                   form: str) -> str:
    raw = apply_text_edit(text, start_cp, end_cp, replacement)
    return normalize(raw, form)


# --- deterministic random input generation --------------------------------

# Categories chosen specifically to exercise context-dependent breaks.
_POOL = {
    "ascii": list("abABx01 "),
    "combining": ["́", "̀", "̂", "̧", "̈"],
    "spacing_mark": ["ः", "ा"],
    "zwj": ["‍"],
    "pictographic": ["\U0001F468", "\U0001F469", "\U0001F467", "\U0001F44B",
                     "\U0001F600", "❤", "\U0001F466", "\U0001F49B",
                     "\U0001F30D"],
    "skin_tone": ["\U0001F3FD", "\U0001F3FB", "\U0001F3FF"],
    "ris": ["\U0001F1FA", "\U0001F1F8", "\U0001F1EF", "\U0001F1F5",
            "\U0001F1E9", "\U0001F1EA"],
    "cr": ["\r"],
    "lf": ["\n"],
    "hangul": ["ᄀ", "ᅡ", "ᆨ", "가", "각"],
    "prepend": ["؅"],
}

_CATEGORY_KEYS = list(_POOL)


def random_text(rng, min_len: int = 0, max_len: int = 60) -> str:
    n = rng.randint(min_len, max_len)
    chars: list[str] = []
    for _ in range(n):
        cat = rng.choice(_CATEGORY_KEYS)
        chars.append(rng.choice(_POOL[cat]))
    return "".join(chars)


def random_cluster_anchored_edit(rng, text: str) -> tuple[int, int, str]:
    """Pick start/end at cluster boundaries (valid edit) + random replacement."""
    starts = cluster_starts(text)
    i, j = sorted(rng.sample(range(len(starts)), 2))
    replacement = random_text(rng, 0, 8)
    return starts[i], starts[j], replacement
