"""Independent reference oracle for tests.

This is deliberately a *separate, naive implementation* from the service
kernel: it is plain dict/set Python written against the specification
document, sharing NO production code paths with dictsvc.core. Tests derive
expected outputs from here and additionally assert hardcoded concrete
values, so the answer key cannot simply be regenerated by the code under
test.
"""
from __future__ import annotations

from dataclasses import dataclass

# Independent copies of the policy constants (re-declared, not imported).
WIDTHS = (8, 16, 32, 64)
TYPE_RANK = {"int64": 0, "utf8": 1}
NULL = -1


@dataclass(frozen=True)
class RefBatch:
    batch_id: str
    values: tuple          # declared local dictionary
    indices: tuple         # local code per row, NULL on null rows
    valid: tuple           # validity bitmap per row


@dataclass(frozen=True)
class RefEncoding:
    global_types: tuple
    global_values: tuple
    local_to_global: dict  # batch_id -> tuple[global_code per local code]
    remapped: dict         # batch_id -> (indices tuple, valid tuple)
    width: int
    cardinality: int


def _typ(v):
    if isinstance(v, bool) or not isinstance(v, int):
        raise ValueError(f"oracle supports int64/utf8 only, got {v!r}")
    return "int64"


def _key(v):
    t = "int64" if isinstance(v, int) and not isinstance(v, bool) else "utf8"
    return t, v


def _capacity(w):
    return 1 << w


def expected_global_dict(batches):
    """Naive set union, then fixed (type-rank, value) ordering."""
    keys = set()
    for b in batches:
        for v in b.values:
            keys.add(_key(v))
    def sort_key(kv):
        t, v = kv
        return (TYPE_RANK[t], v if t == "int64" else v.encode("utf-8"))
    return sorted(keys, key=sort_key)


def expected_encoding(batches, target_width=8, width_policy="reject"):
    ordered = expected_global_dict(batches)
    code_of = {key: i for i, key in enumerate(ordered)}
    cardinality = len(ordered)

    required = next((w for w in WIDTHS if cardinality <= _capacity(w)), None)
    if cardinality <= _capacity(target_width):
        width = target_width
    elif width_policy == "reject":
        raise OverflowError(
            f"cardinality {cardinality} > {_capacity(target_width)}")
    elif required is None:
        raise OverflowError("above 64-bit ladder")
    else:
        width = required

    l2g, remapped = {}, {}
    for b in batches:
        mapping = tuple(code_of[_key(v)] for v in b.values)
        out = tuple(mapping[i] if ok else NULL
                    for i, ok in zip(b.indices, b.valid))
        l2g[b.batch_id] = mapping
        remapped[b.batch_id] = (out, tuple(b.valid))
    return RefEncoding(
        global_types=tuple(t for t, _ in ordered),
        global_values=tuple(v for _, v in ordered),
        local_to_global=l2g, remapped=remapped,
        width=width, cardinality=cardinality)


def expected_decoded_rows(batches):
    """Spec-level decode directly from the ORIGINAL batches."""
    out = {}
    for b in batches:
        out[b.batch_id] = tuple(
            None if not ok else b.values[i]
            for i, ok in zip(b.indices, b.valid))
    return out


def decode_ref_encoding(ref: RefEncoding):
    """Decode the oracle's own global encoding back to typed rows."""
    out = {}
    values = ref.global_values
    for bid, (idx, valid) in ref.remapped.items():
        out[bid] = tuple(None if not ok else values[c]
                         for c, ok in zip(idx, valid))
    return out
