//! Assert the Rust kernel matches the independent Python reference
//! vectors in tests/fixtures/reference_vectors.json (generated by
//! scripts/gen_reference.py). These expected g-arrays, slots and
//! fingerprints are NOT produced by the Rust implementation.

use mph_service::hash::fingerprint;
use mph_service::kernel::builder::{build, vertex_count};
use mph_service::kernel::{Lookup, NotMemberReason};
use serde_json::Value;

#[test]
fn kernel_matches_reference_vectors() {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/reference_vectors.json"
    ))
    .expect("reference fixture missing; run: python3 scripts/gen_reference.py");
    let doc: Value = serde_json::from_str(&text).unwrap();
    assert_eq!(doc["format"], "mphf-bdz-reference/1");

    let mut checked_cases = 0;
    for case in doc["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let base_seed = case["base_seed"].as_u64().unwrap();
        let input: Vec<Vec<u8>> = case["input_keys"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().as_bytes().to_vec())
            .collect();
        let unique: Vec<Vec<u8>> = case["unique_keys"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().as_bytes().to_vec())
            .collect();
        let expected_dups = case["duplicates_removed"].as_u64().unwrap() as usize;
        let expected_m = case["m"].as_u64().unwrap() as usize;
        let expected_seed = case["seed"].as_u64().unwrap();
        let expected_g: Vec<u32> = case["g"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();

        let outcome = build(&input, base_seed, 128, 1_000_000)
            .unwrap_or_else(|e| panic!("case {name}: build failed: {e}"));

        assert_eq!(outcome.duplicates_removed, expected_dups, "case {name} dups");
        assert_eq!(outcome.unique_keys, unique, "case {name} unique order");
        assert_eq!(outcome.seed, expected_seed, "case {name} seed");
        assert_eq!(outcome.index.n, unique.len(), "case {name} n");
        assert_eq!(vertex_count(unique.len()), expected_m, "case {name} m formula");
        assert_eq!(outcome.index.m, expected_m, "case {name} m");
        assert_eq!(outcome.index.g, expected_g, "case {name} g array");

        // Expected slots are verified memberships.
        for (key, slot) in case["slots"].as_object().unwrap() {
            let expected_slot = slot.as_u64().unwrap();
            match outcome.index.lookup(key.as_bytes()) {
                Lookup::Member { slot: got } => {
                    assert_eq!(got, expected_slot, "case {name} slot for {key:?}")
                }
                other => panic!("case {name}: {key:?} expected member, got {other:?}"),
            }
        }
        // Expected fingerprints bit-identical.
        for (key, fp) in case["fingerprints"].as_object().unwrap() {
            let expected = fp.as_u64().unwrap();
            let got = fingerprint(outcome.seed, key.as_bytes());
            assert_eq!(got, expected, "case {name} fingerprint for {key:?}");
        }
        // No slot is ever assigned twice: reference slots form a permutation.
        let mut slots: Vec<u64> = case["slots"]
            .as_object()
            .unwrap()
            .values()
            .map(|v| v.as_u64().unwrap())
            .collect();
        slots.sort_unstable();
        assert_eq!(slots, (0..unique.len() as u64).collect::<Vec<_>>());

        // Every other input-string over the same small alphabet must be
        // rejected (guarded query, not perfect-hash-only).
        for bad in ["not-present", "ALPHA", "alpha ", "alpha\n", "x", "\0"] {
            if unique.iter().any(|u| u == bad.as_bytes()) {
                continue;
            }
            match outcome.index.lookup(bad.as_bytes()) {
                Lookup::NotMember { reason } => match (unique.is_empty(), reason) {
                    (true, NotMemberReason::EmptyIndex) => {}
                    (false, NotMemberReason::FingerprintMismatch { .. }) => {}
                    (_, other) => panic!("case {name}: bad reason {other:?}"),
                },
                Lookup::Member { slot } => {
                    panic!("case {name}: false positive for {bad:?} at {slot}")
                }
            }
        }
        checked_cases += 1;
    }
    assert!(checked_cases >= 6, "must exercise all committed cases");
}
