"""Kernel tests: exact definition/repetition levels and tree reconstruction.

Expected levels are hand-derived (see fixtures.NESTED_IDS_LEVELS), not
generated by the code under test. These assertions pin the mechanism that
distinguishes NULL list / empty list / NULL element and the fixed repetition
depths that separate [[1,2]] (RL 0,2) from [[1],[2]] (RL 0,1).
"""
import pytest

from app.kernel.levels import LevelDecodeError, decode_records, encode_records
from app.kernel.schema import build_schema

from .fixtures import (
    EMPTY_STRUCT_RECORDS, SCHEMA_EMPTY_STRUCT, SCHEMA_NESTED_LIST,
    SCHEMA_STRUCT_LIST, NESTED_IDS_LEVELS, NESTED_LIST_RECORDS,
    STRUCT_LIST_RECORDS,
)


def _nested_ids_column(enc):
    return next(c for c in enc.columns if c.leaf.path[-1] == "element"
                and c.leaf.path[0] == "ids")


def test_exact_nested_list_definition_and_repetition_levels():
    root = build_schema(SCHEMA_NESTED_LIST)
    enc = encode_records(root, NESTED_LIST_RECORDS)
    col = _nested_ids_column(enc)
    got = []
    pos = 0
    for record_levels in NESTED_IDS_LEVELS:
        n = len(record_levels)
        got.append([(e.definition_level, e.repetition_level, e.value)
                    for e in col.events[pos:pos + n]])
        pos += n
    assert got == NESTED_IDS_LEVELS
    assert pos == len(col.events)


def test_the_two_ambiguous_nested_cases_have_distinct_levels():
    root = build_schema(SCHEMA_NESTED_LIST)

    def levels(ids):
        rec = {"id": 1, "ids": ids, "tags": None}
        col = _nested_ids_column(encode_records(root, [rec]))
        return [(e.definition_level, e.repetition_level) for e in col.events]

    # [[1,2]] repeats at the inner repeated group (RL=2); [[1],[2]] opens a
    # new outer element instead (RL=1).
    assert levels([[1, 2]]) == [(5, 0), (5, 2)]
    assert levels([[1], [2]]) == [(5, 0), (5, 1)]


@pytest.mark.parametrize("records,schema,key", [
    (NESTED_LIST_RECORDS, SCHEMA_NESTED_LIST, "nested lists"),
    (STRUCT_LIST_RECORDS, SCHEMA_STRUCT_LIST, "struct with list"),
])
def test_kernel_roundtrip_preserves_tree(records, schema, key):
    root = build_schema(schema)
    enc = encode_records(root, records)
    back = decode_records(root, enc.columns, enc.num_records,
                          enc.empty_struct_present)
    assert back == records, key


def test_list_of_struct_with_null_elements():
    from .fixtures import LIST_OF_STRUCT_RECORDS, SCHEMA_LIST_OF_STRUCT
    root = build_schema(SCHEMA_LIST_OF_STRUCT)
    enc = encode_records(root, LIST_OF_STRUCT_RECORDS)
    back = decode_records(root, enc.columns, enc.num_records,
                          enc.empty_struct_present)
    assert back == LIST_OF_STRUCT_RECORDS
    # record 0: present struct, NULL element, struct with null k
    assert back[0]["items"][1] is None
    assert back[0]["items"][2]["k"] is None
    assert back[0]["items"][2]["v"] == "three"


def test_empty_struct_presence_is_per_record():
    root = build_schema(SCHEMA_EMPTY_STRUCT)
    enc = encode_records(root, EMPTY_STRUCT_RECORDS)
    present = enc.empty_struct_present["marker"]
    assert present == [0, 3]  # only records that explicitly carried {}
    back = decode_records(root, enc.columns, enc.num_records,
                          enc.empty_struct_present)
    assert back == EMPTY_STRUCT_RECORDS


def test_null_vs_empty_list_are_distinct_in_tree():
    root = build_schema({"fields": [
        {"name": "v", "type": "list", "repetition": "optional",
         "element": {"type": "int32"}}]})
    records = [{"v": None}, {"v": []}, {"v": [1, None, 2]}]
    enc = encode_records(root, records)
    col = enc.columns[0]
    # DL ladder for optional list<int>: NULL list 0; empty list 1;
    # NULL element 2; present element 3.
    dls = [e.definition_level for e in col.events]
    assert dls == [0, 1, 3, 2, 3]
    back = decode_records(root, enc.columns, enc.num_records,
                          enc.empty_struct_present)
    assert back == records


def test_record_boundary_mismatch_detected():
    root = build_schema({"fields": [
        {"name": "a", "type": "int64"}, {"name": "b", "type": "int64"}]})
    enc = encode_records(root, [{"a": 1, "b": 9}, {"a": 2, "b": 8}])
    # corrupt column b: drop one event so record counts disagree
    a_col, b_col = enc.columns
    b_col.events.pop()
    with pytest.raises(LevelDecodeError) as exc:
        decode_records(root, [a_col, b_col])
    assert "record boundary mismatch" in str(exc.value)
    diag = exc.value.diagnostics[0]
    assert diag.column_path == "b"
