"""Integration against the synthetic fixtures and their hand-derived oracle.

Expected results live in ``data/fixtures/expected.json`` produced by
``data/fixtures_builder.py`` — they are authored constants (len(rows), sum()),
not generated by the service under test.
"""
from __future__ import annotations

import json
from pathlib import Path

import pyarrow.parquet as pq
import pytest

ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(scope="module")
def fixtures() -> dict:
    from data.fixtures_builder import build

    return build()


def _fixture_path(fixtures: dict, rel: str) -> Path:
    return ROOT / "data" / "fixtures" / rel


def test_oracle_file_row_counts_match_parquet(fixtures):
    for rel, expected in fixtures["files"].items():
        table_file = _fixture_path(fixtures, rel)
        assert pq.ParquetFile(table_file).metadata.num_rows == expected["row_count"]


def test_documented_demo_endstate_matches_oracle(service, fixtures):
    service.create_table(fixtures["table"], fixtures["partition_spec"])
    base = 1
    for name in ["us_20240101.parquet", "us_20240102.parquet", "eu_20240101.parquet"]:
        path = _fixture_path(fixtures, f"events/{name}")
        r = service.commit(
            table_name="events", operation="APPEND",
            request_id=f"req-{name}", source_paths=[path],
            base_snapshot_id=base,
        )
        base = r.snapshot_id

    head = service.store.head_snapshot_id("events")
    entries = service.store.snapshot_entries(head)
    assert sum(e.row_count for e in entries) == fixtures["after_append_all"]["row_count"]

    # Concurrent-looking stale append on a disjoint partition from base=1.
    eu_path = _fixture_path(fixtures, "events/eu_20240101.parquet")
    from app.kernel.errors import ErrorCategory

    with pytest.raises(Exception) as exc:
        service.commit(
            table_name="events", operation="APPEND",
            request_id="req-dup-eu", source_paths=[eu_path], base_snapshot_id=1,
        )
    assert exc.value.category is ErrorCategory.CONFLICT_OVERLAPPING_PARTITION

    # Overwrite us/0101 from current base.
    v2 = _fixture_path(fixtures, "events/us_20240101_v2.parquet")
    ovw = service.commit(
        table_name="events", operation="OVERWRITE",
        request_id="req-ovw", source_paths=[v2],
        base_snapshot_id=service.store.head_snapshot_id("events"),
    )
    final = service.store.snapshot_entries(ovw.snapshot_id)
    expected = fixtures["after_overwrite_us_0101"]
    assert sum(e.row_count for e in final) == expected["row_count"]

    # Verify amount sum by reading actual published files (independent check).
    amount_sum = 0
    for e in final:
        table_file = pq.read_table(service.storage.warehouse_dir / e.file_relpath)
        amount_sum += sum(table_file.column("amount").to_pylist())
    assert amount_sum == expected["amount_sum"]


def test_bad_fixtures_are_rejected(service, fixtures):
    service.create_table("events", fixtures["partition_spec"])
    from app.kernel.errors import ErrorCategory

    # not parquet -> STAGING_FAILED
    with pytest.raises(Exception) as exc:
        service.commit(
            table_name="events", operation="APPEND", request_id="req-bad1",
            source_paths=[_fixture_path(fixtures, "bad/not_parquet.parquet")],
            base_snapshot_id=1,
        )
    assert exc.value.category is ErrorCategory.STAGING_FAILED

    # Establish the table schema with one valid file so schema drift becomes
    # observable (the first readable file would otherwise define the schema).
    good = service.commit(
        table_name="events", operation="APPEND", request_id="req-good",
        source_paths=[_fixture_path(fixtures, "events/eu_20240101.parquet")],
        base_snapshot_id=1,
    )
    head = good.snapshot_id

    # wrong schema (amount:int64 -> string) -> VALIDATION
    with pytest.raises(Exception) as exc:
        service.commit(
            table_name="events", operation="APPEND", request_id="req-bad2",
            source_paths=[_fixture_path(fixtures, "bad/wrong_schema.parquet")],
            base_snapshot_id=head,
        )
    assert exc.value.category is ErrorCategory.VALIDATION

    # missing partition column -> VALIDATION
    with pytest.raises(Exception) as exc:
        service.commit(
            table_name="events", operation="APPEND", request_id="req-bad3",
            source_paths=[_fixture_path(fixtures, "bad/missing_partition_col.parquet")],
            base_snapshot_id=head,
        )
    assert exc.value.category is ErrorCategory.VALIDATION

    # Only the one good commit created a snapshot beyond root.
    assert service.store.head_snapshot_id("events") == head


def test_orphan_fixture_is_detected(service, container, fixtures):
    service.create_table("events", fixtures["partition_spec"])
    # Builder planted data/_orphan_demo outside the warehouse; copy it in to
    # simulate a physical stray folder under the warehouse root.
    import shutil

    # Builder plants the folder under data/ (relpath is relative to data/).
    stray_source = ROOT / "data" / fixtures["orphan_fixture_relpath"]
    dest = container.settings.warehouse_dir / "_orphan_demo"
    shutil.copytree(stray_source.parent, dest)

    scan = service.scan_orphans()
    assert any(
        p == "_orphan_demo/stray.parquet" for p in scan["orphan_files"]
    ), scan
    result = service.reconcile_orphans()
    assert "_orphan_demo/stray.parquet" in result["removed_files"]
