"""Golden, hand-authored segmentation cases.

Every case pins the EXACT token sequence, exact costs/gaps and exact original
spans expected. In addition the independent brute-force oracle (tests/oracle.py)
re-derives the optimum from raw frequencies, so the answers are neither
"interface callable only" checks nor generated by the code under test.
"""
from __future__ import annotations

import pytest

from app.storage.registry import VersionRegistry
from app.storage.repository import DictionaryRepository

from .oracle import Oracle, oracle_normalize


def surfaces(result):
    return [t.surface for t in result.tokens]


def kinds(result):
    return [t.kind for t in result.tokens]


def ranges(result):
    return [(t.orig_start, t.orig_end) for t in result.tokens]


# --------------------------------------------------------------------------- #
# G1: ambiguous short sentence, explicit costs, tie between two runner-ups
# --------------------------------------------------------------------------- #
G1_ENTRIES = [
    {"surface": "研究", "cost": 5.0},
    {"surface": "研究生", "cost": 6.0},
    {"surface": "生命", "cost": 2.0},
    {"surface": "学", "cost": 7.0},
    {"surface": "生", "cost": 6.0},
    {"surface": "命", "cost": 6.0},
]


def test_g1_ambiguous_exact_path_and_gap(registry, diag):
    registry.publish(G1_ENTRIES, note="g1")
    result = registry.segment("研究生命", diag)

    # Hand-authored optimum: 研究/生命 = 5 + 2 = 7.
    assert surfaces(result) == ["研究", "生命"]
    assert kinds(result) == ["dict", "dict"]
    assert result.best.cost == pytest.approx(7.0, abs=1e-9)
    assert result.best.token_count == 2

    # Two distinct segmentations tie for second at cost 12; the stable rule
    # (fewer tokens first) picks the 3-token path 研究生/命.
    assert result.runner_up is not None
    assert result.runner_up.surfaces == ("研究生", "命")
    assert result.runner_up.cost == pytest.approx(12.0, abs=1e-9)
    assert result.gap_rounded == pytest.approx(5.0, abs=1e-9)
    assert result.gap_status == "available"

    # Oracle agreement over the exhaustive enumeration.
    oracle = Oracle(G1_ENTRIES, unknown_char_cost=8.0)
    ranked = oracle.enumerate_paths("研究生命")
    assert len(ranked) == 5                      # every partition enumerated
    assert ranked[0][0] == ("研究", "生命")
    assert ranked[1][0] == ("研究生", "命")      # same tie rule, independently
    assert ranked[1][1] - ranked[0][1] == pytest.approx(5.0, abs=1e-9)

    # Original coverage: tiles and rebuilds verbatim.
    assert result.orig_covered is True
    assert result.reconstructed is True
    assert ranges(result) == [(0, 2), (2, 4)]


@pytest.fixture
def registry_oov12(tmp_path):
    """Registry with a higher single-char OOV penalty for the tie cases."""
    repo = DictionaryRepository(tmp_path / "tie.db")
    return VersionRegistry(repo, unknown_char_cost=12.0, min_word_cost=0.01)


# --------------------------------------------------------------------------- #
# G2: equal cost -> fewer tokens wins (whole word beats character split)
# --------------------------------------------------------------------------- #
G2_ENTRIES = [
    {"surface": "ab", "cost": 10.0},
    {"surface": "a", "cost": 5.0},
    {"surface": "b", "cost": 5.0},
]


def test_g2_tie_fewer_tokens_wins(registry_oov12, diag):
    registry_oov12.publish(G2_ENTRIES, note="g2")
    result = registry_oov12.segment("ab", diag)

    assert surfaces(result) == ["ab"]
    assert result.best.cost == pytest.approx(10.0)
    assert result.runner_up.surfaces == ("a", "b")
    assert result.gap_rounded == pytest.approx(0.0, abs=1e-9)
    assert result.gap_status == "available"

    oracle = Oracle(G2_ENTRIES, unknown_char_cost=12.0)
    ranked = oracle.enumerate_paths("ab")
    assert [p for p, _ in ranked] == [("ab",), ("a", "b")]


# --------------------------------------------------------------------------- #
# G3: equal cost and equal token count -> lexicographic surface sequence
# --------------------------------------------------------------------------- #
G3_ENTRIES = [
    {"surface": "abc", "cost": 19.0},
    {"surface": "a", "cost": 5.0},
    {"surface": "bc", "cost": 14.0},
    {"surface": "ab", "cost": 14.0},
    {"surface": "c", "cost": 5.0},
]


def test_g3_tie_lexicographic_surfaces(registry_oov12, diag):
    registry_oov12.publish(G3_ENTRIES, note="g3")
    result = registry_oov12.segment("abc", diag)

    assert surfaces(result) == ["abc"]
    assert result.best.cost == pytest.approx(19.0)
    # ("a","bc") < ("ab","c") lexicographically.
    assert result.runner_up.surfaces == ("a", "bc")
    assert result.runner_up.cost == pytest.approx(19.0)
    assert result.gap_rounded == pytest.approx(0.0, abs=1e-9)

    oracle = Oracle(G3_ENTRIES, unknown_char_cost=12.0)
    ranked = oracle.enumerate_paths("abc")
    # First three are the all-dict partitions in the tie order; the OOV
    # partition ('a','b','c') = 22 follows.
    assert [p for p, _ in ranked[:3]] == [("abc",), ("a", "bc"), ("ab", "c")]
    assert ("a", "b", "c") in [p for p, _ in ranked[3:]]


# --------------------------------------------------------------------------- #
# G4: OOV fallback length/cost, no character dropped, known word + unknown run
# --------------------------------------------------------------------------- #
G4_ENTRIES = [{"surface": "研究", "cost": 3.0}]


def test_g4_oov_fallback_keeps_every_character(registry, diag):
    registry.publish(G4_ENTRIES, note="g4")
    result = registry.segment("研究xyz", diag)

    assert surfaces(result) == ["研究", "x", "y", "z"]
    assert kinds(result) == ["dict", "unknown", "unknown", "unknown"]
    assert result.unknown_tokens == 3
    # OOV edges each cost exactly the configured single-char penalty.
    assert [round(t.cost, 9) for t in result.tokens] == [3.0, 8.0, 8.0, 8.0]
    assert result.best.cost == pytest.approx(27.0)
    assert result.orig_covered is True
    assert result.reconstructed is True
    # Exact one-character spans per unknown fallback token.
    assert ranges(result) == [(0, 2), (2, 3), (3, 4), (4, 5)]

    oracle = Oracle(G4_ENTRIES, unknown_char_cost=8.0)
    best_surf, best_cost = oracle.best("研究xyz")
    assert best_surf == ("研究", "x", "y", "z")
    assert best_cost == pytest.approx(27.0)


# --------------------------------------------------------------------------- #
# G5: variable-length normalization expansion (ligature, eszett) + spans
# --------------------------------------------------------------------------- #
G5_ENTRIES = [{"surface": "fish", "cost": 4.0}, {"surface": "strasse", "cost": 6.0}]


def test_g5a_ligature_expands_and_matches(registry, diag):
    registry.publish(G5_ENTRIES, note="g5")
    result = registry.segment("ﬁsh", diag)  # U+FB01 LATIN SMALL LIGATURE FI

    assert oracle_normalize("ﬁsh") == "fish"
    assert surfaces(result) == ["fish"]
    assert kinds(result) == ["dict"]
    # One original character ("ﬁ") expands to two normalized chars, but the
    # token maps back to the whole original range (3 original chars).
    assert (result.tokens[0].norm_start, result.tokens[0].norm_end) == (0, 4)
    assert (result.tokens[0].orig_start, result.tokens[0].orig_end) == (0, 3)
    assert result.reconstructed is True


def test_g5b_eszett_expands_two_chars_with_mid_span(registry, diag):
    registry.publish(G5_ENTRIES, note="g5")
    result = registry.segment("aßb", diag)  # ß casefolds to "ss"

    assert result.normalized_text == "assb"
    assert surfaces(result) == ["a", "s", "s", "b"]
    assert all(t.is_unknown for t in result.tokens)
    # The empty slice between the two "s" characters splits at the expansion;
    # slices still concatenate back to the original.
    assert ranges(result) == [(0, 1), (1, 2), (2, 2), (2, 3)]
    assert "".join("aßb"[s:e] for s, e in ranges(result)) == "aßb"
    assert result.orig_covered is True


def test_g5c_eszett_word_matches_across_expansion(registry, diag):
    registry.publish(G5_ENTRIES, note="g5")
    result = registry.segment("STRAßE", diag)
    assert surfaces(result) == ["strasse"]
    assert kinds(result) == ["dict"]
    assert ranges(result) == [(0, 6)]
    assert result.reconstructed is True


# --------------------------------------------------------------------------- #
# G6: zero-width character removal still tiles the original
# --------------------------------------------------------------------------- #
G6_ENTRIES = [{"surface": "研究", "cost": 3.0}, {"surface": "生命", "cost": 2.0}]


def test_g6_zero_width_char_attaches_to_following_token(registry, diag):
    registry.publish(G6_ENTRIES, note="g6")
    result = registry.segment("研​生命", diag)  # ZWSP between 研 and 生

    assert result.normalized_text == "研生命"
    assert result.removed_chars == 1
    assert surfaces(result) == ["研", "生命"]
    # ZWSP attaches forward to 生命: first token [0,1), second [1,4).
    assert ranges(result) == [(0, 1), (1, 4)]
    assert "".join("研​生命"[s:e] for s, e in ranges(result)) == "研​生命"
    assert result.orig_covered is True


def test_g6b_format_only_input_kept_not_dropped(registry, diag):
    registry.publish(G6_ENTRIES, note="g6")
    text = "​­"  # ZWSP + SOFT HYPHEN
    result = registry.segment(text, diag)
    assert result.normalized_text == ""
    assert result.removed_chars == 2
    # One format token covering the full original span -- no char dropped.
    assert len(result.tokens) == 1
    assert result.tokens[0].kind == "format"
    assert ranges(result) == [(0, 2)]
    assert result.reconstructed is True


# --------------------------------------------------------------------------- #
# G7: repeated words - whole repeated word beats shorter split
# --------------------------------------------------------------------------- #
G7_ENTRIES = [
    {"surface": "研究", "cost": 5.0},
    {"surface": "研究生", "cost": 7.0},
    {"surface": "学", "cost": 5.0},
]


def test_g7_repeated_word(registry, diag):
    registry.publish(G7_ENTRIES, note="g7")
    result = registry.segment("研究研究", diag)

    assert surfaces(result) == ["研究", "研究"]
    assert result.best.cost == pytest.approx(10.0)
    # Runner-up identity/gap come from the exhaustive oracle, not hardcoded.
    oracle = Oracle(G7_ENTRIES)
    ranked = oracle.enumerate_paths("研究研究")
    assert ranked[0][0] == ("研究", "研究")
    second_surfaces, second_cost = ranked[1]
    assert result.runner_up.surfaces == tuple(second_surfaces)
    assert result.gap_rounded == pytest.approx(second_cost - ranked[0][1], abs=1e-9)
    assert ranges(result) == [(0, 2), (2, 4)]
    assert result.reconstructed is True


# --------------------------------------------------------------------------- #
# G8: empty input and the single-path "undetermined" gap case
# --------------------------------------------------------------------------- #
def test_g8a_empty_text(registry, diag):
    registry.publish([{"surface": "研究", "cost": 5.0}], note="g8")
    result = registry.segment("", diag)
    assert surfaces(result) == []
    assert result.best.cost == 0.0
    assert result.runner_up is None
    assert result.gap is None
    assert result.gap_status == "unique_path"
    assert result.orig_covered is True
    assert result.reconstructed is True


def test_g8b_single_dictionary_char_has_no_runner_up(registry, diag):
    registry.publish([{"surface": "a", "cost": 5.0}], note="g8")
    result = registry.segment("a", diag)
    assert surfaces(result) == ["a"]
    # No OOV edge is emitted for a known character: genuinely one path.
    assert result.runner_up is None
    assert result.gap_status == "unique_path"


# --------------------------------------------------------------------------- #
# G9: regression -- an interior-vertex tie that must not be pruned.
#
# Two ways to read "wxy" are EXACTLY equal in cost and token count:
#   wx(4) + y(4)  vs  w(4) + xy(4)   -> tie at the interior boundary v=3.
# Both then append z(1), yielding two full 9-cost/3-token paths. A naive
# "keep two labels per vertex and cut" DP discards one interior branch and
# reports the wrong runner-up; the stable rule must keep both and select the
# lexicographically smaller surface sequence. (The whole word wxyz=7 is the
# unique best.)
# --------------------------------------------------------------------------- #
G9_ENTRIES = [
    {"surface": "wxyz", "cost": 7.0},
    {"surface": "wx", "cost": 4.0},
    {"surface": "y", "cost": 4.0},
    {"surface": "z", "cost": 1.0},
    {"surface": "w", "cost": 4.0},
    {"surface": "xy", "cost": 4.0},
]
G9_TEXT = "wxyz"


def test_g9_tied_interior_prefixes_are_not_pruned(registry, diag):
    registry.publish(G9_ENTRIES, note="g9")
    result = registry.segment(G9_TEXT, diag)

    assert result.best.surfaces == ("wxyz",)
    assert result.best.cost == pytest.approx(7.0)
    assert result.runner_up is not None
    # ("w","xy","z") < ("wx","y","z") lexicographically.
    assert result.runner_up.surfaces == ("w", "xy", "z")
    assert result.runner_up.cost == pytest.approx(9.0)
    assert result.gap_rounded == pytest.approx(2.0, abs=1e-9)

    oracle = Oracle(G9_ENTRIES, unknown_char_cost=25.0)
    ranked = oracle.enumerate_paths(G9_TEXT)
    assert [p for p, _ in ranked[:3]] == [
        ("wxyz",),
        ("w", "xy", "z"),
        ("wx", "y", "z"),
    ]
    assert result.runner_up.surfaces == ranked[1][0]


def test_g10_float_summation_noise_treated_as_tie(registry, diag):
    """Same word costs summed in different order differ only by ULPs.

    The two 6-token runner-up paths contain the identical set of word costs;
    raw float addition makes them differ ~1e-15. They must be recognized as a
    tie and broken by surface lexicographic order, not summation order.
    """
    import random

    rng = random.Random(1002)
    alphabet = "甲乙丙丁"
    keys: set[str] = set()
    entries: list[dict] = []
    for _ in range(14):
        key = "".join(rng.choice(alphabet) for _ in range(rng.randint(1, 4)))
        if key in keys:
            continue
        keys.add(key)
        entries.append({"surface": key, "cost": round(rng.uniform(1.0, 20.0), 4)})
    text = "乙甲乙甲乙丁丙"

    registry.publish(entries, note="g10")
    result = registry.segment(text, diag)

    oracle = Oracle(entries, unknown_char_cost=25.0)
    ranked = oracle.enumerate_paths(text)
    assert tuple(result.best.surfaces) == ranked[0][0]
    assert result.runner_up.surfaces == ranked[1][0]
    # The second and third oracle paths share the same multiset of costs.
    assert abs(ranked[1][1] - ranked[2][1]) < 1e-9
    assert ranked[1][0] < ranked[2][0]  # lex-smaller one reported
