"""Core merge tests against hand-authored fixtures.

Every assertion compares against explicit literals in :mod:`fixtures`,
never against output generated by the engine under test.  The failure
category (conflict type) is asserted explicitly per case.
"""

import pytest

from merge3 import MergeEngine, ResolutionError, three_way_merge
from merge3.model import ConflictType

from fixtures import ALL_CASES, MergeCase


def run_case(case: MergeCase):
    engine, result = three_way_merge(case.base, case.local, case.remote,
                                     f"req-{case.case_id}")
    return engine, result


@pytest.mark.parametrize("case", ALL_CASES, ids=[c.case_id for c in ALL_CASES])
def test_fixture_expectations(case: MergeCase):
    engine, result = run_case(case)

    if case.expected_auto is not None:
        # Automatic path: exact text, zero conflicts.
        assert result.auto_merged is True, (
            f"{case.case_id}: expected clean merge, got conflicts "
            f"{[c.conflict_type.value for c in result.conflicts]}")
        assert result.conflicts == []
        assert result.merged_text == case.expected_auto
    else:
        # Conflict path: no guessed text, exact ordered conflict categories.
        assert result.auto_merged is False
        assert result.merged_text is None
        assert tuple(c.conflict_type.value for c in result.conflicts) == \
            case.expected_conflict_types

        if case.expected_resolutions:
            for choice, expected in case.expected_resolutions.items():
                rebuilt = engine.rebuild(
                    result,
                    {"c1": ({"choice": choice} if choice != "custom_text"
                            else {"choice": "custom_text", "text": expected})})
                assert rebuilt == expected, (
                    f"{case.case_id}: resolution {choice!r} rebuilt "
                    f"{rebuilt!r}, expected {expected!r}")


def test_every_auto_case_has_independent_edit_consistency():
    """Oracle property for clean merges.

    For each conflict-free fixture, re-running the merge with roles swapped
    must give the identical result (symmetry), and the merged text must
    contain each side's exact changed material.  These checks do not use the
    engine to generate expected strings; they assert algebraic invariants.
    """
    for case in ALL_CASES:
        if case.expected_auto is None:
            continue
        e1, r1 = three_way_merge(case.base, case.local, case.remote, "x")
        e2, r2 = three_way_merge(case.base, case.remote, case.local, "y")
        assert r1.merged_text == r2.merged_text == case.expected_auto


def test_conflict_blocks_carry_three_way_ranges():
    from fixtures import CASE_DELETE_MODIFY
    _, result = run_case(CASE_DELETE_MODIFY)
    block = result.conflicts[0]
    assert block.conflict_type == ConflictType.DELETE_MODIFY
    # base region covers exactly "beta\n" (line index 1)
    assert (block.base_region.line_start, block.base_region.line_end) == (1, 2)
    assert block.base_text == "beta\n"
    # local deleted it: its region collapses to an empty point
    assert block.local_region.start == block.local_region.end
    assert block.local_text == ""
    # remote modified it: its region covers one line containing BETA!
    assert block.remote_text == "BETA!\n"
    # edit provenance must identify both participating edits
    assert block.local_edit_ids and block.remote_edit_ids
    # allowed choices are exactly the documented set
    assert set(block.allowed_resolutions) == {
        "local", "remote", "base", "custom_text"}
    # ranges slice their own documents exactly
    assert CASE_DELETE_MODIFY.base[block.base_region.start:
                                  block.base_region.end] == "beta\n"
    assert CASE_DELETE_MODIFY.remote[block.remote_region.start:
                                    block.remote_region.end] == "BETA!\n"


def test_same_point_insert_ranges_are_empty_points_on_both_sides():
    from fixtures import CASE_SAME_POINT_CONFLICT as case
    _, result = run_case(case)
    block = result.conflicts[0]
    assert block.conflict_type == ConflictType.SAME_POINT_INSERT
    assert block.base_region.start == block.base_region.end == 0
    assert block.local_region.start == block.local_region.end == 0
    assert block.remote_region.start == block.remote_region.end == 0
    assert block.local_text == "INS-L\n"
    assert block.remote_text == "INS-R\n"
    assert set(block.allowed_resolutions) == {
        "local", "remote", "base", "local_then_remote",
        "remote_then_local", "custom_text"}


def test_core_never_emits_conflict_markers():
    for case in ALL_CASES:
        _, result = run_case(case)
        if result.merged_text is not None:
            assert "<<<<<<<" not in result.merged_text
            assert ">>>>>>>" not in result.merged_text


def test_rebuild_requires_every_conflict():
    from fixtures import CASE_PARTIAL_OVERLAP
    engine, result = run_case(CASE_PARTIAL_OVERLAP)
    with pytest.raises(ResolutionError, match="missing resolutions"):
        engine.rebuild(result, {})
    with pytest.raises(ResolutionError, match="unknown conflict ids"):
        engine.rebuild(result, {"c9": {"choice": "local"}})
    with pytest.raises(ResolutionError, match="not allowed"):
        engine.rebuild(result, {"c1": {"choice": "coin_flip"}})


def test_custom_text_must_be_string():
    from fixtures import CASE_DIVERGENT
    engine, result = run_case(CASE_DIVERGENT)
    with pytest.raises(ResolutionError, match="requires string"):
        engine.rebuild(result, {"c1": {"choice": "custom_text"}})


def test_text_field_rejected_for_choice_other_than_custom():
    from fixtures import CASE_DIVERGENT
    engine, result = run_case(CASE_DIVERGENT)
    with pytest.raises(ResolutionError, match="only valid with custom_text"):
        engine.rebuild(result, {"c1": {"choice": "local", "text": "x"}})


def test_conflict_ids_stable_and_sequential():
    # Two genuinely independent conflicts in one merge: same-point insert at
    # the top boundary and a divergent replacement of an unrelated line.
    base = "a\nb\nc\nd\n"
    local = "I1\na\nB\nc\nd\n"
    remote = "I2\na\nC\nc\nd\n"
    engine = MergeEngine(base, local, remote, "multi")
    result = engine.run()
    assert [c.conflict_id for c in result.conflicts] == ["c1", "c2"]
    assert result.conflicts[0].conflict_type == ConflictType.SAME_POINT_INSERT
    assert result.conflicts[1].conflict_type == ConflictType.DIVERGENT_MODIFY
    rebuilt = engine.rebuild(result, {
        "c1": {"choice": "local_then_remote"},
        "c2": {"choice": "local"},
    })
    assert rebuilt == "I1\nI2\na\nB\nc\nd\n"


def test_invalid_input_types_rejected():
    with pytest.raises(ValueError):
        MergeEngine(b"a\nb\n", "a\n", "a\n")  # bytes not accepted
