"""Golden-vector tests.

``tests/golden/golden.json`` is generated by ``scripts/generate_golden.py``
with deterministic salts. These tests replay it:

* the kernel and the stdlib-only independent verifier both accept the sample
  proof against the recorded root;
* recomputing every field commitment with the documented deterministic salt
  derivation reproduces the recorded roots byte-for-byte;
* a mutation fails with the expected category in BOTH implementations.

Regenerate with: ``python scripts/generate_golden.py``.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from app.core.batch import verify_proof
from app.core.commitment import field_commitment
from app.core.merkle import build_levels
from app.parsing.fixtures import FIXTURE_BATCH_ID, deterministic_salt
from independent.verifier import independent_verify

GOLDEN = Path(__file__).parent / "golden" / "golden.json"


@pytest.fixture(scope="module")
def golden():
    if not GOLDEN.exists():
        pytest.fail("golden.json missing; run python scripts/generate_golden.py")
    return json.loads(GOLDEN.read_text())


def test_sample_proof_accepted_by_both_implementations(golden):
    root = golden["batch_root_hex"]
    proof = golden["sample_proof"]
    path = proof["claim"]["path"]

    kv = verify_proof(proof, trusted_batch_root_hex=root, expected_path=path)
    assert kv.valid is True
    assert kv.checked_steps[-1] == "batch_root_matches_trusted_root"

    ok, cat, reason, steps = independent_verify(
        proof, root, expected_path=path, expected_record=0
    )
    assert ok is True
    assert golden["independent_verifier_result"]["valid"] is True


def test_recorded_roots_reproduce_from_deterministic_salts(golden):
    digest = golden["digest"]
    record_nodes = []
    for rec in golden["records"]:
        nodes = []
        for f in rec["fields"]:
            salt = None
            value = None
            if f["state"] != "missing":
                salt = deterministic_salt(
                    FIXTURE_BATCH_ID, rec["record_index"], f["position"], f["path"]
                )
            commit = field_commitment(
                digest_name=digest,
                batch_id=FIXTURE_BATCH_ID,
                record_index=rec["record_index"],
                position=f["position"],
                path=f["path"],
                field_type=f["field_type"],
                state=f["state"],
                value=value,  # present values come from fixture below
                salt=salt,
            ) if f["state"] != "present" else None
            if f["state"] == "present":
                commit = _present_commitment(rec["record_index"], f, digest)
            assert commit.hex() == f["commitment_hex"], (
                f"field commitment mismatch at {rec['record_index']}/{f['path']}"
            )
            nodes.append(commit)
        root, _ = build_levels("field", digest, nodes)
        assert root.hex() == rec["record_root_hex"]
        record_nodes.append(root)
    batch_root, _ = build_levels("record", digest, record_nodes)
    assert batch_root.hex() == golden["batch_root_hex"]


def _present_commitment(record_index, field, digest):
    # Values come from the canonical fixture, keyed by path.
    from app.parsing.fixtures import FIXTURE_RECORDS
    from app.parsing import parse_field_specs, parse_records
    from app.parsing.fixtures import FIXTURE_FIELDS

    specs = parse_field_specs(FIXTURE_FIELDS)
    rows = parse_records(FIXTURE_RECORDS, specs)
    value = rows[record_index][field["path"]]["value"]
    salt = deterministic_salt(
        FIXTURE_BATCH_ID, record_index, field["position"], field["path"]
    )
    return field_commitment(
        digest_name=digest,
        batch_id=FIXTURE_BATCH_ID,
        record_index=record_index,
        position=field["position"],
        path=field["path"],
        field_type=field["field_type"],
        state="present",
        value=value,
        salt=salt,
    )


def test_golden_proof_wrong_salt_fails_in_both(golden):
    proof = copy.deepcopy(golden["sample_proof"])
    s = bytes.fromhex(proof["reveal"]["salt_hex"])
    proof["reveal"]["salt_hex"] = (b"\x00" + s[1:]).hex()
    root = golden["batch_root_hex"]

    kv = verify_proof(proof, trusted_batch_root_hex=root)
    assert kv.valid is False and kv.category == "COMMITMENT_MISMATCH"
    ok, cat, _, _ = independent_verify(proof, root)
    assert ok is False and cat == "COMMITMENT_MISMATCH"


def test_golden_proof_foreign_root_fails_in_both(golden):
    proof = golden["sample_proof"]
    foreign = "ab" * 32
    kv = verify_proof(proof, trusted_batch_root_hex=foreign)
    assert kv.valid is False and kv.category == "ROOT_MISMATCH"
    ok, cat, _, _ = independent_verify(proof, foreign)
    assert ok is False and cat == "ROOT_MISMATCH"
