"""Frozen vector tests — expected digests produced by a stdlib-only script.

The reference answers in tests/fixtures/frozen_vectors.json were generated by
scripts/generate_vectors.py, which imports NOTHING from app.*, so the kernel
cannot self-certify. These tests assert concrete digest literals:
  * canonical encoded bytes,
  * field commitments (incl. empty/null/missing distinction),
  * identity binding (name swap / position swap / record swap / wrong salt),
  * Merkle roots incl. odd-node folding and tampered-leaf detection.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.crypto.commitment import CommitmentInput, commit_field
from app.crypto.merkle import build_merkle_tree, empty_root_hex, verify_proof, ProofStep
from app.domain.types import FieldType, canonical_encode

VECTORS = json.loads((Path(__file__).parent / "fixtures" / "frozen_vectors.json").read_text())


def _commit(enc_hex, salt_hex, rec, pos, name):
    return commit_field(CommitmentInput(
        record_index=rec, field_position=pos, field_name=name,
        encoded_value=bytes.fromhex(enc_hex),
        salt=bytes.fromhex(salt_hex) if salt_hex else b"")).commitment_hex


def test_canonical_encoded_bytes_match_frozen_values():
    enc = VECTORS["encoded_hex"]
    assert canonical_encode(FieldType.DECIMAL, "12.30").hex() == enc["decimal_12.30"]
    assert canonical_encode(FieldType.DECIMAL, 7).hex() == enc["decimal_7_str"]
    assert canonical_encode(FieldType.INT, 7).hex() == enc["int_7"]
    assert canonical_encode(FieldType.STRING, "7").hex() == enc["string_7"]
    assert canonical_encode(FieldType.STRING, "").hex() == enc["string_empty"]
    assert canonical_encode(FieldType.BOOL, True).hex() == enc["bool_true"]
    assert canonical_encode(FieldType.BOOL, False).hex() == enc["bool_false"]
    assert canonical_encode(FieldType.DATE, "2026-03-01").hex() == enc["date_2026-03-01"]
    assert canonical_encode(FieldType.TIMESTAMP, "2026-03-01T09:00:00Z").hex() == enc["ts_zulu"]
    assert canonical_encode(FieldType.NULL, None).hex() == enc["null"]
    # Three distinct encodings: empty string, explicit null, missing marker.
    assert enc["string_empty"] != enc["null"] != enc["missing"]
    assert enc["string_empty"] != enc["missing"]
    # int 7 and string "7" are different commitments inputs.
    assert enc["int_7"] != enc["string_7"]


def test_field_commitments_match_frozen_digests():
    enc = VECTORS["encoded_hex"]
    salts = VECTORS["salts"]
    commits = VECTORS["commitments"]
    # (vector key, record, position, name, encoded-key, salt-key)
    rows = [
        ("amount_r0_salted", 0, 1, "amount", "decimal_12.30", "salt16"),
        ("amount_r1_same_value_other_cell", 1, 1, "amount", "decimal_12.30", "salt16b"),
        ("merchant_r0_salted", 0, 0, "merchant", "string_blue_kiosk", "salt16"),
        ("merchant_r1_same_value_other_cell", 1, 0, "merchant",
         "string_blue_kiosk", "salt16b"),
        ("note_empty_r0", 0, 6, "note", "string_empty", "salt16"),
        ("note_null_r1", 1, 6, "note", "null_any_type", "salt16b"),
        ("status_missing_r1", 1, 7, "status", "missing", "salt16b"),
        ("int7_quantity", 2, 2, "quantity", "int_7", "salt16"),
        ("string7_note", 2, 6, "note", "string_7", "salt16"),
        ("status_paid_unsalted", 0, 7, "status", None, None),
    ]
    for key, rec, pos, name, enc_key, salt_key in rows:
        if enc_key is None:  # unsalted PAID string
            encoded_hex = canonical_encode(FieldType.STRING, "PAID").hex()
        elif enc_key == "null_any_type":
            encoded_hex = "1f"
        else:
            encoded_hex = enc[enc_key]
        salt_hex = salts[salt_key] if salt_key else ""
        assert _commit(encoded_hex, salt_hex, rec, pos, name) == commits[key], key


def test_identity_binding_blocks_all_substitutions():
    binding = VECTORS["identity_binding"]
    enc = VECTORS["encoded_hex"]
    salts = VECTORS["salts"]
    base = _commit(enc["string_blue_kiosk"], salts["salt16"], 0, 0, "merchant")
    assert base == binding["baseline"]
    # 1. Same value, same salt, different FIELD NAME -> different commitment.
    assert _commit(enc["string_blue_kiosk"], salts["salt16"], 0, 6, "note") \
        == binding["name_swapped_to_note"]
    assert _commit(enc["string_blue_kiosk"], salts["salt16"], 0, 6, "note") != base
    # 2. Different field position -> different commitment.
    assert _commit(enc["string_blue_kiosk"], salts["salt16"], 0, 3, "merchant") \
        == binding["position_swapped"]
    assert _commit(enc["string_blue_kiosk"], salts["salt16"], 0, 3, "merchant") != base
    # 3. Different record position -> different commitment.
    assert _commit(enc["string_blue_kiosk"], salts["salt16"], 1, 0, "merchant") \
        == binding["record_swapped"]
    assert _commit(enc["string_blue_kiosk"], salts["salt16"], 1, 0, "merchant") != base
    # 4. Wrong salt -> different commitment.
    assert _commit(enc["string_blue_kiosk"], salts["salt16b"], 0, 0, "merchant") \
        == binding["wrong_salt"]
    assert _commit(enc["string_blue_kiosk"], salts["salt16b"], 0, 0, "merchant") != base


def test_same_value_same_cell_identity_deterministic():
    enc = VECTORS["encoded_hex"]
    salts = VECTORS["salts"]
    # Repeated computation with identical inputs is stable.
    a = _commit(enc["decimal_12.30"], salts["salt16"], 0, 1, "amount")
    b = _commit(enc["decimal_12.30"], salts["salt16"], 0, 1, "amount")
    assert a == b == VECTORS["commitments"]["amount_r0_salted"]


def test_merkle_frozen_roots_and_proofs():
    commits = VECTORS["commitments"]
    roots = VECTORS["merkle_roots"]
    assert empty_root_hex() == roots["empty"]

    four = [commits["merchant_r0_salted"], commits["amount_r0_salted"],
            commits["note_empty_r0"], commits["int7_quantity"]]
    root_hex, paths = build_merkle_tree(four)
    assert root_hex == roots["four_leaves"]
    for i, c in enumerate(four):
        assert verify_proof(c, paths[i], root_hex)
    # A proof built for leaf 0 must NOT validate leaf 1's commitment (binding).
    assert not verify_proof(four[1], paths[0], root_hex)
    # Wrong root rejected.
    assert not verify_proof(four[0], paths[0], roots["tampered_last_leaf"])

    three = [commits["merchant_r0_salted"], commits["amount_r0_salted"],
             commits["note_null_r1"]]
    odd_root, odd_paths = build_merkle_tree(three)
    assert odd_root == roots["three_leaves_odd"]
    assert verify_proof(three[2], odd_paths[2], odd_root)


def test_merkle_detects_tampered_leaf():
    commits = VECTORS["commitments"]
    three = [commits["merchant_r0_salted"], commits["amount_r0_salted"],
             commits["note_null_r1"]]
    root_hex, _ = build_merkle_tree(three)
    tampered = three[:-1] + [VECTORS["merkle_roots"]["tampered_last_leaf"]]
    # The "tampered" root fixture was built over a modified last commitment.
    tampered_list = [commits["merchant_r0_salted"], commits["amount_r0_salted"],
                     commits["note_null_r1"][:-1] + "0"]
    t_root, _ = build_merkle_tree(tampered_list)
    assert t_root == VECTORS["merkle_roots"]["tampered_last_leaf"]
    assert t_root != root_hex
    assert tampered  # used to keep intent explicit


if __name__ == "__main__":  # pragma: no cover
    pytest.main([__file__, "-v"])
