"""Independent oracle tests.

These tests deliberately do NOT import ``app.kernel`` or ``app.rules``: the
oracle is a separate, hand-written scanner. It checks properties any correct
implementation must satisfy, so expectations are not generated by the code
under test.
"""
from __future__ import annotations

import re

from app.kernel import redact_full  # system under test (entry point only)
from app.rules import build_ruleset  # used only to select a rule version

from tests.synth_fixtures import (
    SYNTH_API_TOKEN,
    SYNTH_BANK_CARD,
    SYNTH_CN_ID,
    SYNTH_EMAIL,
    SYNTH_MOBILE,
)

# --- oracle secrets, defined independently of the product rules -----------
_ORACLE_PATTERNS = {
    "email": re.compile(r"[A-Za-z0-9._%+\-]{1,64}@[A-Za-z0-9.\-]{1,64}\.[A-Za-z]{2,24}"),
    "api_token": re.compile(r"\b(?:sk|pk|tok)_[A-Za-z0-9_]{10,60}\b"),
    "mobile": re.compile(r"\b1[3-9][0-9]{9}\b"),
    "bank_card": re.compile(r"\b62[0-9]{14,17}\b"),
    "cn_id": re.compile(r"\b[0-9]{17}[0-9X]\b"),
}
_REDACTION = re.compile(r"\[REDACTED:[a-z_]+\]")


def _oracle_find(text: str) -> list[tuple[str, int, int, str]]:
    hits = []
    for name, rx in _ORACLE_PATTERNS.items():
        for m in rx.finditer(text):
            hits.append((name, m.start(), m.end(), m.group(0)))
    return hits


def test_oracle_no_synthetic_secret_ever_remains():
    standard = build_ruleset("standard")
    strict = build_ruleset("strict")
    cases = [
        (standard, f"a {SYNTH_EMAIL} b {SYNTH_API_TOKEN} c {SYNTH_MOBILE}"),
        (standard, f"card:{SYNTH_BANK_CARD};mail={SYNTH_EMAIL}"),
        (strict, f"id {SYNTH_CN_ID} token {SYNTH_API_TOKEN}"),
        (standard, SYNTH_EMAIL + SYNTH_MOBILE),  # adjacent
        (standard, f'\\"email\\":\\"{SYNTH_EMAIL}\\"'),  # escaped
    ]
    for ruleset, text in cases:
        out = redact_full(text, ruleset).redacted
        for name, s, e, frag in _oracle_find(out):
            raise AssertionError(
                f"secret {name} fragment survived redaction: {frag!r} in {out!r}"
            )


def test_oracle_mapping_offsets_are_consistent_and_complete():
    ruleset = build_ruleset("standard")
    text = f"head {SYNTH_EMAIL} gap {SYNTH_API_TOKEN} tail"
    result = redact_full(text, ruleset)
    out = result.redacted

    # 1. Every mapping points at a redaction marker in the output.
    for m in result.mappings:
        assert _REDACTION.fullmatch(
            out[m.output_start : m.output_end]
        ), out[m.output_start : m.output_end]
    # 2. Every marker in the output is explained by a mapping.
    markers = [(m.start(), m.end()) for m in _REDACTION.finditer(out)]
    assert sorted((m.output_start, m.output_end) for m in result.mappings) == sorted(
        markers
    )
    # 3. Original coordinates reconstruct the original when spliced back.
    rebuilt_parts = []
    cursor = 0
    for m in sorted(result.mappings, key=lambda x: x.original_start):
        rebuilt_parts.append(text[cursor : m.original_start])
        rebuilt_parts.append(
            f"M{text[m.original_start:m.original_end]}M"
        )
        cursor = m.original_end
    rebuilt_parts.append(text[cursor:])
    rebuilt = "".join(rebuilt_parts)
    for secret in (SYNTH_EMAIL, SYNTH_API_TOKEN):
        assert f"M{secret}M" in rebuilt  # originals locatable via map only
    # 4. Length accounting: delta rule holds exactly.
    delta = sum(m.replaced_length - m.original_length for m in result.mappings)
    assert result.output_length == result.input_length + delta
    # 5. Ordering/non-overlap of mappings.
    ordered = sorted(result.mappings, key=lambda x: x.original_start)
    for a, b in zip(ordered, ordered[1:]):
        assert a.original_end <= b.original_start
        assert a.output_end <= b.output_start


def test_oracle_streaming_reconstruction_matches_input_lengths():
    ruleset = build_ruleset("strict")
    text = f"{SYNTH_CN_ID}..{SYNTH_EMAIL}..{SYNTH_BANK_CARD}"
    # Independent chunking simulation through the public kernel API.
    from app.kernel import StreamRedactor

    for cut in (1, 3, 11, 18, 64, 1000):
        sr = StreamRedactor(ruleset)
        got = ""
        for i in range(0, len(text), cut):
            got += sr.push(text[i : i + cut])
        got += sr.finish()
        assert got == redact_full(text, ruleset).redacted
