"""Kernel + node semantic tests.

Every rejection test asserts three things independently:

1. the production code rejects with the *specific* ``ErrorCode`` and category;
2. the independent oracle (:mod:`tests.oracle`, which imports no production
   module) rejects with the same code and category -- the expected answer is
   never generated by the code under test;
3. the committed UTXO set is byte-for-byte identical before and after, and
   equals the untouched oracle state (whole-block atomicity).

Happy-path tests additionally compare per-transaction intermediate reference
states via the oracle.
"""

from __future__ import annotations

import pytest

from utxo_ledger.encoding import (
    Block,
    Outpoint,
    Transaction,
    TxInput,
    TxOutput,
    encode_block,
    tx_sighash,
)
from utxo_ledger.errors import ErrorCode, LedgerError, category_of
from utxo_ledger.kernel import (
    InMemoryChainView,
    Utxo,
    _Pending,
    _resolve_outpoint,
    checked_add,
)
from utxo_ledger.protocol import MAX_BLOCK_TXS, MAX_MONEY, ZERO_HASH

from tests.fixtures import coinbase_tx, named_key, transfer_tx
from tests.scenarios import Scenario


def _op(txid: bytes, vout: int) -> Outpoint:
    return Outpoint(txid, vout)


def _funded_scenario():
    """One accepted block; alice owns one 1_000_000 UTXO at height 1.

    Returns ``(scenario, alice_keypair, genesis_block)``.
    """
    sc = Scenario()
    alice = named_key("alice")
    block = sc.append([coinbase_tx(1, [(1_000_000, alice.public_bytes)])])
    return sc, alice, block


def _assert_rejected_matches_oracle(res, code: ErrorCode, tx_index=None):
    """Production rejection == independent oracle rejection == atomic no-op."""
    expected_category = category_of(code).value
    assert not res.prod_result.accepted
    err = res.prod_result.error
    assert err["code"] == code.value
    assert err["category"] == expected_category
    if tx_index is not None:
        assert err["tx_index"] == tx_index

    assert res.oracle_error is not None, "independent oracle unexpectedly accepted"
    assert res.oracle_error["code"] == code.value
    assert res.oracle_error["category"] == expected_category
    if tx_index is not None:
        assert res.oracle_error["tx_index"] == tx_index

    # Whole-block atomicity: production set unchanged and equal to the
    # untouched reference state.
    assert res.prod_result.state_unchanged
    assert res.prod_snapshot == res.oracle_snapshot


# --------------------------------------------------------------------------- #
# Happy paths
# --------------------------------------------------------------------------- #
def test_valid_multi_tx_block_matches_oracle():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    cb = coinbase_tx(2, [(1_001_000, alice.public_bytes)])  # subsidy + 1000 fee
    tx = transfer_tx(
        [(_op(genesis.transactions[0].txid, 0), alice.public_bytes)],
        [(400_000, bob.public_bytes), (599_000, alice.public_bytes)],
        {0: alice},
    )
    res = sc.run_target([cb, tx])
    assert res.prod_result.accepted, res.prod_result.error
    assert res.prod_result.fee_total == 1_000
    assert res.oracle_error is None
    assert res.prod_snapshot == res.oracle_snapshot
    assert len(res.prod_snapshot) == 3
    # Per-transaction reference states must match production prefix replays.
    assert res.intermediate_match
    assert len(res.prod_intermediate) == 2


def test_intra_block_back_reference_is_spendable():
    sc, alice, genesis = _funded_scenario()
    bob, carol = named_key("bob"), named_key("carol")
    tx1 = transfer_tx(
        [(_op(genesis.transactions[0].txid, 0), alice.public_bytes)],
        [(100_000, bob.public_bytes), (899_000, alice.public_bytes)],
        {0: alice},
    )  # fee 1000
    tx2 = transfer_tx(
        [(_op(tx1.txid, 0), bob.public_bytes)],
        [(99_500, carol.public_bytes)],
        {0: bob},
    )  # fee 500, spends an output created earlier in the same block
    cb = coinbase_tx(2, [(1_001_500, alice.public_bytes)])
    res = sc.run_target([cb, tx1, tx2])
    assert res.prod_result.accepted, res.prod_result.error
    assert res.oracle_error is None
    assert res.prod_snapshot == res.oracle_snapshot
    assert res.prod_result.fee_total == 1_500
    assert res.intermediate_match
    # One reference snapshot after each of the three transactions.
    assert len(res.prod_intermediate) == 3


# --------------------------------------------------------------------------- #
# Required negative cases
# --------------------------------------------------------------------------- #
def test_intra_block_double_spend_across_txs():
    sc, alice, genesis = _funded_scenario()
    bob, carol = named_key("bob"), named_key("carol")
    src = _op(genesis.transactions[0].txid, 0)
    tx1 = transfer_tx(
        [(src, alice.public_bytes)],
        [(400_000, bob.public_bytes), (599_000, alice.public_bytes)],
        {0: alice},
    )
    tx2 = transfer_tx(
        [(src, alice.public_bytes)],
        [(400_000, carol.public_bytes), (599_000, alice.public_bytes)],
        {0: alice},
    )
    cb = coinbase_tx(2, [(1_000_000, alice.public_bytes)])
    res = sc.run_target([cb, tx1, tx2])
    _assert_rejected_matches_oracle(res, ErrorCode.DOUBLE_SPEND, tx_index=2)


def test_duplicate_input_within_single_transaction():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    unsigned = Transaction(
        version=1,
        inputs=(TxInput(src, b""), TxInput(src, b"")),
        outputs=(TxOutput(999_000, bob.public_bytes),),
    )
    sig = alice.sign(tx_sighash(unsigned))
    signed = Transaction(
        version=1,
        inputs=(TxInput(src, sig), TxInput(src, sig)),
        outputs=unsigned.outputs,
    )
    cb = coinbase_tx(2, [(1_001_000, alice.public_bytes)])
    res = sc.run_target([cb, signed])
    _assert_rejected_matches_oracle(res, ErrorCode.DUPLICATE_INPUT, tx_index=1)


def test_zero_value_output_rejected_and_state_untouched():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    tx = transfer_tx(
        [(src, alice.public_bytes)],
        [(0, bob.public_bytes), (999_000, alice.public_bytes)],
        {0: alice},
    )
    cb = coinbase_tx(2, [(1_001_000, alice.public_bytes)])
    res = sc.run_target([cb, tx])
    _assert_rejected_matches_oracle(res, ErrorCode.ZERO_VALUE_OUTPUT, tx_index=1)
    # The originally funded UTXO is still live.
    assert (src.txid.hex(), 0) in res.prod_snapshot


def test_signature_tamper_wrong_signer_rejected():
    sc, alice, genesis = _funded_scenario()
    attacker, bob = named_key("attacker"), named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    tx = transfer_tx(
        [(src, alice.public_bytes)],
        [(400_000, bob.public_bytes), (599_000, alice.public_bytes)],
        {0: attacker},  # wrong key signs a spend of alice's output
    )
    cb = coinbase_tx(2, [(1_001_000, alice.public_bytes)])
    res = sc.run_target([cb, tx])
    _assert_rejected_matches_oracle(res, ErrorCode.SIG_TAMPERED, tx_index=1)


def test_signature_byte_flip_rejected():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    tx = transfer_tx(
        [(src, alice.public_bytes)],
        [(400_000, bob.public_bytes), (599_000, alice.public_bytes)],
        {0: alice},
    )
    bad = bytearray(tx.inputs[0].signature)
    bad[10] ^= 0x01
    tampered = Transaction(tx.version, (TxInput(src, bytes(bad)),), tx.outputs)
    cb = coinbase_tx(2, [(1_001_000, alice.public_bytes)])
    res = sc.run_target([cb, tampered])
    _assert_rejected_matches_oracle(res, ErrorCode.SIG_TAMPERED, tx_index=1)


# --------------------------------------------------------------------------- #
# Ordering / conservation / spendability
# --------------------------------------------------------------------------- #
def test_forward_reference_rejected():
    sc, alice, genesis = _funded_scenario()
    bob, carol = named_key("bob"), named_key("carol")
    src = _op(genesis.transactions[0].txid, 0)
    fund = transfer_tx(
        [(src, alice.public_bytes)],
        [(100_000, bob.public_bytes), (899_000, alice.public_bytes)],
        {0: alice},
    )
    # `early` spends fund's output although fund is positioned AFTER it.
    early = transfer_tx(
        [(_op(fund.txid, 0), bob.public_bytes)],
        [(99_000, carol.public_bytes)],
        {0: bob},
    )
    cb = coinbase_tx(2, [(1_000_000, alice.public_bytes)])
    res = sc.run_target([cb, early, fund])
    _assert_rejected_matches_oracle(res, ErrorCode.FORWARD_REFERENCE, tx_index=1)


def test_cyclic_reference_guard_whitebox():
    """The same-position (self) branch cannot be produced by valid encoding:
    a literal self-spend requires an input whose txid equals the spending
    transaction's own txid, i.e. a SHA-256 preimage fixed point. The guard
    therefore exists as defense-in-depth and is exercised directly here.
    """
    sc, alice, genesis = _funded_scenario()
    self_txid = b"\xcc" * 32
    pending = _Pending(created={}, positions={self_txid: 1}, spent_in_block=set())
    with pytest.raises(LedgerError) as ei:
        _resolve_outpoint(
            _op(self_txid, 0),
            tx_index=1,
            view=sc.store,
            pending=pending,
            spend_txid=self_txid,
        )
    assert ei.value.code is ErrorCode.CYCLIC_REFERENCE
    assert ei.value.category.value == "state"


def test_conservation_outputs_exceed_inputs():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    tx = transfer_tx(
        [(src, alice.public_bytes)],
        [(1_000_001, bob.public_bytes)],
        {0: alice},
    )
    cb = coinbase_tx(2, [(1_000_000, alice.public_bytes)])
    res = sc.run_target([cb, tx])
    _assert_rejected_matches_oracle(res, ErrorCode.FEE_NEGATIVE, tx_index=1)


def test_unknown_outpoint():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    tx = transfer_tx(
        [(_op(b"\x11" * 32, 0), alice.public_bytes)],
        [(100, bob.public_bytes)],
        {0: alice},
    )
    cb = coinbase_tx(2, [(1_000_000, alice.public_bytes)])
    res = sc.run_target([cb, tx])
    _assert_rejected_matches_oracle(res, ErrorCode.UNKNOWN_OUTPOINT, tx_index=1)


def test_spending_an_already_spent_committed_output():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    spend = transfer_tx(
        [(src, alice.public_bytes)],
        [(400_000, bob.public_bytes), (599_000, alice.public_bytes)],
        {0: alice},
    )
    sc.append([coinbase_tx(2, [(1_001_000, alice.public_bytes)]), spend])
    replay = transfer_tx(
        [(src, alice.public_bytes)],
        [(100, bob.public_bytes)],
        {0: alice},
    )
    res = sc.run_target([coinbase_tx(3, [(1_000_000, alice.public_bytes)]), replay])
    _assert_rejected_matches_oracle(res, ErrorCode.ALREADY_SPENT, tx_index=1)


def test_coinbase_overclaim():
    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    src = _op(genesis.transactions[0].txid, 0)
    tx = transfer_tx(
        [(src, alice.public_bytes)],
        [(400_000, bob.public_bytes), (599_000, alice.public_bytes)],
        {0: alice},
    )  # fee 1000
    cb = coinbase_tx(2, [(1_000_000, alice.public_bytes)])  # claims subsidy only
    res = sc.run_target([cb, tx])
    _assert_rejected_matches_oracle(res, ErrorCode.BAD_COINBASE, tx_index=0)


def test_wrong_height_and_prev_hash():
    sc, alice, genesis = _funded_scenario()
    # Wrong height (tip is 1): submit raw directly without advancing builder.
    bad_height = Block(
        1, 9, sc.prev_hash,
        (coinbase_tx(9, [(1_000_000, alice.public_bytes)]),),
    )
    pres = sc.node.submit_raw_block(encode_block(bad_height), seq=99)
    assert not pres.accepted
    assert pres.error["code"] == ErrorCode.BLOCK_HEIGHT_INVALID.value
    assert pres.error["category"] == "state"
    assert pres.state_unchanged

    # Correct height but wrong prev_hash.
    bad_prev = Block(
        1, 2, b"\xab" * 32,
        (coinbase_tx(2, [(1_000_000, alice.public_bytes)]),),
    )
    pres2 = sc.node.submit_raw_block(encode_block(bad_prev), seq=100)
    assert not pres2.accepted
    assert pres2.error["code"] == ErrorCode.PREV_BLOCK_HASH_MISMATCH.value
    assert pres2.state_unchanged


# --------------------------------------------------------------------------- #
# Overflow / resource / pure kernel
# --------------------------------------------------------------------------- #
def test_checked_add_overflow_uses_u64_bound():
    assert checked_add(5, 6, "x") == 11
    with pytest.raises(LedgerError) as ei:
        checked_add(MAX_MONEY, 1, "x")
    assert ei.value.code is ErrorCode.VALUE_OVERFLOW
    assert ei.value.category.value == "state"
    with pytest.raises(LedgerError):
        checked_add(2**63, 2**63, "x")


def test_summing_two_max_money_inputs_overflows():
    view = InMemoryChainView()
    rich = named_key("rich")
    pay = named_key("pay")
    view._utxos[(b"\x77" * 32, 0)] = Utxo(MAX_MONEY, rich.public_bytes, 1)
    view._utxos[(b"\x88" * 32, 0)] = Utxo(MAX_MONEY, rich.public_bytes, 1)
    view._tip_height = 1
    tx = transfer_tx(
        [
            (_op(b"\x77" * 32, 0), rich.public_bytes),
            (_op(b"\x88" * 32, 0), rich.public_bytes),
        ],
        [(1, pay.public_bytes)],
        {0: rich, 1: rich},
    )
    blk = Block(
        1, 2, ZERO_HASH,
        (coinbase_tx(2, [(1_000_000, rich.public_bytes)]), tx),
    )
    with pytest.raises(LedgerError) as ei:
        from utxo_ledger.kernel import validate_block

        validate_block(blk, view)
    assert ei.value.code is ErrorCode.VALUE_OVERFLOW
    assert ei.value.tx_index == 1
    # Overflow during validation must not mutate the view.
    assert view.utxo_count() == 2


def test_too_many_transactions_is_resource_category():
    sc, alice, genesis = _funded_scenario()
    raw = (
        b"UTXO-BLOCK/1\x00"
        + (1).to_bytes(4, "little")
        + (2).to_bytes(8, "little")
        + ZERO_HASH
        + (MAX_BLOCK_TXS + 1).to_bytes(4, "little")
    )
    pres = sc.node.submit_raw_block(raw, seq=123)
    assert not pres.accepted
    assert pres.error["code"] == ErrorCode.TOO_MANY_TXS.value
    assert pres.error["category"] == "resource"
    assert pres.state_unchanged


def test_sigop_budget_is_resource_category():
    """Exceeding the per-block signature-check budget is a resource error."""
    from utxo_ledger import kernel as kern

    sc, alice, genesis = _funded_scenario()
    bob = named_key("bob")
    # Drive the block with the sigops budget forced below one input's cost.
    original = kern.MAX_BLOCK_SIGOPS
    kern.MAX_BLOCK_SIGOPS = 0
    try:
        src = _op(genesis.transactions[0].txid, 0)
        tx = transfer_tx(
            [(src, alice.public_bytes)],
            [(999_000, bob.public_bytes)],
            {0: alice},
        )
        res = sc.run_target([coinbase_tx(2, [(1_001_000, alice.public_bytes)]), tx])
    finally:
        kern.MAX_BLOCK_SIGOPS = original
    assert not res.prod_result.accepted
    assert res.prod_result.error["code"] == ErrorCode.TOO_MANY_SIGOPS.value
    assert res.prod_result.error["category"] == "resource"


def test_crypto_failure_is_computation_category():
    """An unexpected backend fault is COMPUTATION, distinct from a bad sig."""
    from utxo_ledger import crypto

    alice = named_key("alice")
    # The Ed25519 verify method is a C builtin that cannot be monkeypatched on
    # the class; force a non-signature, non-material backend fault by replacing
    # the module's key loader with one raising an unexpected library error.
    original = crypto._load_public_key

    def boom(_pub):
        raise RuntimeError("simulated backend fault")

    crypto._load_public_key = boom
    try:
        with pytest.raises(LedgerError) as ei:
            crypto.verify_signature(alice.public_bytes, b"msg", b"\x00" * 64)
    finally:
        crypto._load_public_key = original
    assert ei.value.code is ErrorCode.CRYPTO_FAILURE
    assert ei.value.category.value == "computation"
