"""End-to-end scanner tests against hand-authored expected answers.

The expected answers live in tests/fixtures/expected_scan_v1.json and are not
generated by the scanner: masks, locations, confidence and independent
HKDF/HMAC fingerprints are asserted verbatim.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from secretscan.fingerprint import CandidateFingerprinter
from secretscan.rules import load_rules
from secretscan.scanner import Scanner

EXPECTED = json.loads(
    (Path(__file__).resolve().parent / "fixtures" / "expected_scan_v1.json").read_text()
)
RULES = load_rules("config/rules.yaml")


def scan(snapshot, fixed_keys, scan_id="scan_t1"):
    master, salt = fixed_keys
    scanner = Scanner(RULES, CandidateFingerprinter(master, salt))
    return scanner.scan(
        str(snapshot), scan_id=scan_id, project_id="proj_test", request_id="req_test"
    ).to_dict()


def by_key(result):
    return {(c["rule_id"], c["fingerprint"]): c for c in result["candidates"]}


def test_summary_matches_expected(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    assert result["summary"] == EXPECTED["summary"]
    assert result["rules_version"] == EXPECTED["rules_version"]
    assert result["classification_version"] == EXPECTED["classification_version"]
    assert result["request_id"] == "req_test"
    assert result["config_digest"]  # bound to exact config content


def test_scanned_ignored_skipped_errors(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    scanned = sorted(f["path"] for f in result["files"])
    assert scanned == sorted(EXPECTED["scanned_files"])
    assert sorted(result["ignored"]) == sorted(EXPECTED["ignored"])

    skipped = {(s["path"], s["reason"]) for s in result["skipped"]}
    assert skipped == {(s["path"], s["reason"]) for s in EXPECTED["skipped"]}
    too_large = next(s for s in result["skipped"] if s["reason"] == "too_large")
    assert too_large["size_bytes"] > RULES.scope.max_file_bytes
    assert "not opened" in too_large["detail"]

    errors = {(e["path"], e["code"]) for e in result["errors"]}
    assert errors == {(e["path"], e["code"]) for e in EXPECTED["errors"]}


def test_every_expected_candidate_matches_verbatim(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    found = by_key(result)
    for exp in EXPECTED["candidates"]:
        c = next(
            v for k, v in found.items()
            if k[0] == exp["rule_id"]
            and ("fingerprint" not in exp or k[1] == exp["fingerprint"])
        )
        assert c["masked"] == exp["masked"], exp["rule_id"]
        assert c["confidence"] == exp["confidence"]
        assert c["source"] == exp["source"]
        assert c["uncertain"] is exp["uncertain"]
        for eloc in exp["locations"]:
            match = next(
                (l for l in c["locations"] if l["path"] == eloc["path"]), None
            )
            assert match is not None, (exp["rule_id"], eloc["path"])
            assert match["kind"] == eloc["kind"]
            assert match["line"] == eloc["line"]
            if "column" in eloc:
                assert match["column"] == eloc["column"]


def test_independent_fingerprints_are_asserted(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    fps = {k[0]: k[1] for k in by_key(result)}
    for exp in EXPECTED["candidates"]:
        if "fingerprint" in exp:
            assert fps[exp["rule_id"]] == exp["fingerprint"]


def test_uncertain_high_entropy_token_is_not_a_confirmed_match(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    c = next(c for c in result["candidates"] if c["rule_id"] == "entropy_heuristic")
    assert c["uncertain"] is True
    assert c["confidence"] == "low"
    assert c["reasons"] == ["entropy_only:>=4.5"]


def test_ordinary_structured_hex_and_ignored_and_unscanned_values_absent(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    rendered = json.dumps(result)
    # The 64-char repeating digest is ordinary high-entropy-looking text:
    # entropy 4.0 < 4.5, so it must not appear as a candidate at all.
    digest = EXPECTED["not_expected_as_candidates"][0]
    assert digest not in rendered
    # Decoy values in ignored dir, oversize file, unreadable file never appear.
    for decoy in EXPECTED["not_expected_as_candidates"][1:]:
        assert decoy not in rendered


def test_no_raw_secret_anywhere_in_result_payload(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    rendered = json.dumps(result)
    for raw in EXPECTED["fixture_secrets"].values():
        assert raw not in rendered


def test_binary_match_reports_byte_position(snapshot_copy, fixed_keys):
    result = scan(snapshot_copy, fixed_keys)
    c = next(
        c for c in result["candidates"] if c["rule_id"] == "github_personal_token"
    )
    loc = c["locations"][0]
    assert loc["kind"] == "binary"
    blob = (snapshot_copy / "data/blob.bin").read_bytes()
    raw = EXPECTED["fixture_secrets"]["github"].encode()
    assert blob[loc["byte_offset"]:loc["byte_end"]] == raw
    assert loc["byte_offset"] == 132


def test_same_secret_twice_in_one_file_is_one_candidate_with_two_locations(tmp_path, fixed_keys):
    (tmp_path / "f.txt").write_text(
        "a = AKIAFAKE000000000001\nb = AKIAFAKE000000000001\n"
    )
    result = scan(tmp_path, fixed_keys)
    aws = [c for c in result["candidates"] if c["rule_id"] == "aws_access_key_id"]
    assert len(aws) == 1
    assert len(aws[0]["locations"]) == 2


def test_moving_a_file_keeps_the_content_candidate(tmp_path, fixed_keys):
    (tmp_path / "old").mkdir()
    (tmp_path / "old" / "secrets.txt").write_text("AKIAFAKE000000000001\n")
    first = scan(tmp_path, fixed_keys, scan_id="scan_a")
    fp = next(
        k[1] for k in by_key(first) if k[0] == "aws_access_key_id"
    )
    (tmp_path / "old").rename(tmp_path / "new")
    second = scan(tmp_path, fixed_keys, scan_id="scan_b")
    fp2 = next(k[1] for k in by_key(second) if k[0] == "aws_access_key_id")
    loc = next(
        c for c in second["candidates"] if c["rule_id"] == "aws_access_key_id"
    )["locations"][0]
    assert fp == fp2  # fingerprint is bound to content, survives the move
    assert loc["path"] == "new/secrets.txt"
