// Package scenario defines the deterministic teaching scenarios (fixtures) and
// an INDEPENDENT oracle that predicts the global snapshot from the scenario
// steps. The oracle is a separate, minimal re-implementation of the
// Chandy-Lamport cut semantics — it never imports internal/node or
// internal/snapshot, so the reference answer cannot be generated by the code
// under test.
package scenario

import (
	"fmt"

	"clsnap/internal/protocol"
)

// Scenario is one fully scripted run. Steps execute strictly in order; the
// runner waits for each step's effect before the next.
type Scenario struct {
	Name           string                 `json:"name"`
	Description    string                 `json:"description"`
	Nodes          []NodeSpec             `json:"nodes"`
	InitialBalance map[string]int64       `json:"initial_balance"`
	Steps          []Step                 `json:"steps"`
	Expect         map[string]Expectation `json:"expect"`
	// ConserveTotal, when nonzero, is the token total every complete snapshot
	// must conserve (3 nodes x initial default = 300).
	ConserveTotal int64 `json:"conserve_total"`
}

type NodeSpec struct {
	ID      string `json:"id"`
	Address string `json:"address"` // populated by runner; fixtures use ""
}

// Step is a single control action. Only one Action per step.
type Step struct {
	Action string                 `json:"action"`
	Node   string                 `json:"node,omitempty"`
	Peer   string                 `json:"peer,omitempty"`
	To     string                 `json:"to,omitempty"`
	TxID   string                 `json:"tx_id,omitempty"`
	Amount int64                  `json:"amount,omitempty"`
	SnapID string                 `json:"snap_id,omitempty"`
	Reason string                 `json:"reason,omitempty"`
	Note   string                 `json:"note,omitempty"`
	Wait   string                 `json:"wait,omitempty"` // "delivered", "complete", etc.
	Meta   map[string]interface{} `json:"meta,omitempty"`
}

const (
	ActPin            = "pin"
	ActRelease        = "release"
	ActTransfer       = "transfer"
	ActStartSnapshot  = "start_snapshot"
	ActAwaitDelivered = "await_delivered"
	ActAwaitComplete  = "await_complete"
	ActAwaitSettled   = "await_settled"
	ActAwaitMarker    = "await_marker" // node has received snap marker on Peer incoming channel
	ActExpectSnapshot = "expect_snapshot"
	ActRestartNode    = "restart_node"
	ActAbortSnapshot  = "abort_snapshot"
	ActFail           = "fail" // assert the named call fails with a given class
	ActSleep          = "sleep"
)

// Expectation is the hand-authored expected cut for one snapshot. These
// numbers come from the scenario designer's arithmetic, not from the system.
type Expectation struct {
	Complete         bool                   `json:"complete"`
	ExpectAborted    bool                   `json:"expect_aborted,omitempty"` // snapshot must fail, not complete
	AbortedOn        []string               `json:"aborted_on,omitempty"`     // nodes expected to abort
	StatusByNode     map[string]string      `json:"status_by_node,omitempty"`
	Local            map[string]int64       `json:"local"`                   // local balance per node
	Channels         map[string][]ExpectedTransfer `json:"channels,omitempty"` // key "from->to"
	GlobalTotal      int64                  `json:"global_total"`
	InFlightSum      int64                  `json:"in_flight_sum"`
	FinalBalances    map[string]int64       `json:"final_balances,omitempty"` // after settle
}

type ExpectedTransfer struct {
	TxID   string `json:"tx_id"`
	Amount int64  `json:"amount"`
}

// Validate performs fixture-level validation (unknown nodes, bad steps).
func (s *Scenario) Validate() error {
	if len(s.Nodes) != 3 {
		return fmt.Errorf("scenario %q: exactly 3 nodes required, got %d", s.Name, len(s.Nodes))
	}
	known := map[string]bool{}
	for _, n := range s.Nodes {
		if n.ID == "" {
			return fmt.Errorf("scenario %q: node without id", s.Name)
		}
		known[n.ID] = true
	}
	for acct, v := range s.InitialBalance {
		if !known[acct] {
			return fmt.Errorf("scenario %q: initial balance for unknown node %q", s.Name, acct)
		}
		if v < 0 {
			return fmt.Errorf("scenario %q: negative initial balance %q", s.Name, acct)
		}
	}
	for i, st := range s.Steps {
		if st.Node != "" && !known[st.Node] {
			return fmt.Errorf("step %d references unknown node %q", i, st.Node)
		}
		if st.Peer != "" && !known[st.Peer] && st.Peer[0] != '_' {
			return fmt.Errorf("step %d references unknown peer %q", i, st.Peer)
		}
		if st.To != "" && !known[st.To] && (len(st.Peer) == 0 || st.Peer[0] != '_') {
			return fmt.Errorf("step %d references unknown destination %q", i, st.To)
		}
		switch st.Action {
		case ActTransfer:
			if st.To == "" || st.TxID == "" || st.Amount <= 0 {
				return fmt.Errorf("step %d transfer requires to, tx_id, positive amount", i)
			}
		case ActStartSnapshot, ActAwaitComplete, ActExpectSnapshot, ActAbortSnapshot:
			if st.SnapID == "" {
				return fmt.Errorf("step %d %s requires snap_id", i, st.Action)
			}
		case ActPin, ActRelease:
			if st.Peer == "" {
				return fmt.Errorf("step %d %s requires peer", i, st.Action)
			}
		case ActFail:
			if st.Reason == "" {
				return fmt.Errorf("step %d fail requires reason (expected class)", i)
			}
		case "", ActAwaitDelivered, ActAwaitSettled, ActRestartNode, ActSleep, ActAwaitMarker:
			// ok
		default:
			return fmt.Errorf("step %d unknown action %q", i, st.Action)
		}
	}
	for snapID, e := range s.Expect {
		if !e.ExpectAborted && e.Local == nil {
			return fmt.Errorf("expectation %q missing local balances (or expect_aborted)", snapID)
		}
	}
	return nil
}

// NodeIDs returns the three node ids in fixture order.
func (s *Scenario) NodeIDs() []string {
	out := make([]string, 0, len(s.Nodes))
	for _, n := range s.Nodes {
		out = append(out, n.ID)
	}
	return out
}

var _ = protocol.KindTransfer // keep protocol import stable for fixture tooling
