"""Deterministic synthetic fixture generation.

Produces ONLY inputs (plus the registry ground truth). Expected outcomes are
NOT generated by the kernel here — the independent test oracle
(`tests/independent_oracle.py`) derives them. Keys are synthetic and
deterministic (sha256-seeded Ed25519), safe for local use.

Scenarios cover: duplicate retransmission, same-target double vote,
surround/nested rounds in both directions, boundary equality (non-offense),
membership change (join/exit), weight change, unknown validator, bad
signature, wrong chain/domain, malformed rounds, cross-validator
non-conflict.
"""
from __future__ import annotations

import json
from pathlib import Path

from .crypto import Signer

CHAIN_ID = "local-chain-0"
EPOCH_LENGTH = 10

# block-root digests (synthetic, 32 bytes)
def _root(seed: str) -> bytes:
    import hashlib

    return hashlib.sha256(f"block/{seed}".encode()).digest()


def _vote(signer: Signer, domain: bytes, chain_id: str, s: int, t: int, root: bytes):
    return signer.sign_vote(domain=domain, chain_id=chain_id, source_round=s, target_round=t, block_root=root)


def _envelope(signed) -> dict:
    return signed.to_json_dict()


def build_fixture_set(out_dir: str | Path) -> dict[str, str]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    domain = b"localffg/validator-vote/v1"

    # --- signers ----------------------------------------------------------
    alice = Signer.from_seed("alice", b"localffg-fixture/alice")
    bob = Signer.from_seed("bob", b"localffg-fixture/bob")
    carol = Signer.from_seed("carol", b"localffg-fixture/carol")
    dave = Signer.from_seed("dave", b"localffg-fixture/dave")  # joins at epoch 2
    erin = Signer.from_seed("erin", b"localffg-fixture/erin")  # exits after epoch 1
    frank = Signer.from_seed("frank", b"localffg-fixture/frank")  # never in registry
    mallory = Signer.from_seed("mallory", b"localffg-fixture/mallory")  # attack signer

    signers = {
        "alice": alice,
        "bob": bob,
        "carol": carol,
        "dave": dave,
        "erin": erin,
        "frank": frank,
        "mallory": mallory,
    }

    # registry ground truth (pubkeys + weight updates). NOT produced by kernel.
    registry = {
        "chain_id": CHAIN_ID,
        "epoch_length": EPOCH_LENGTH,
        "validators": [
            {"validator_id": "alice", "pubkey": alice.public_key_bytes.hex(),
             "weight_updates": [[0, 100], [2, 150]]},
            {"validator_id": "bob", "pubkey": bob.public_key_bytes.hex(),
             "weight_updates": [[0, 100]]},
            {"validator_id": "carol", "pubkey": carol.public_key_bytes.hex(),
             "weight_updates": [[0, 100]]},
            {"validator_id": "dave", "pubkey": dave.public_key_bytes.hex(),
             "weight_updates": [[2, 80]]},
            {"validator_id": "erin", "pubkey": erin.public_key_bytes.hex(),
             "weight_updates": [[0, 60], [2, 0]]},
        ],
    }

    # --- scenarios: ordered submission steps ------------------------------
    scenarios: dict[str, list[dict]] = {}

    # 1. duplicate retransmission of an identical vote
    v = _vote(alice, domain, CHAIN_ID, 0, 5, _root("a-0-5"))
    scenarios["S1_duplicate_retransmit"] = [
        {"label": "alice-vote-1", "signed": _envelope(v)},
        {"label": "alice-vote-1-rexmit", "signed": _envelope(v)},
        {"label": "alice-vote-1-rexmit-2", "signed": _envelope(v)},
    ]

    # 2. same-target double vote (different source and root)
    v1 = _vote(bob, domain, CHAIN_ID, 0, 8, _root("b-0-8"))
    v2 = _vote(bob, domain, CHAIN_ID, 2, 8, _root("b-2-8-other"))
    scenarios["S2_double_vote_same_target"] = [
        {"label": "bob-vote-a", "signed": _envelope(v1)},
        {"label": "bob-vote-b", "signed": _envelope(v2)},
    ]

    # 3. surround: second vote nests inside the first: outer [0,15] inner [5,10]
    outer = _vote(carol, domain, CHAIN_ID, 0, 15, _root("c-0-15"))
    inner = _vote(carol, domain, CHAIN_ID, 5, 10, _root("c-5-10"))
    scenarios["S3_surround_nested"] = [
        {"label": "carol-outer", "signed": _envelope(outer)},
        {"label": "carol-inner", "signed": _envelope(inner)},
    ]

    # 3b. surround in reverse arrival order (inner first, then outer)
    scenarios["S3b_surround_reverse_order"] = [
        {"label": "carol-inner-first", "signed": _envelope(inner)},
        {"label": "carol-outer-after", "signed": _envelope(outer)},
    ]

    # 3c. boundary equality — NOT surround, not double: [0,10] then [10,15]
    share = _vote(alice, domain, CHAIN_ID, 0, 10, _root("a-0-10"))
    adjacent = _vote(alice, domain, CHAIN_ID, 10, 15, _root("a-10-15"))
    scenarios["S3c_boundary_equality_no_offense"] = [
        {"label": "alice-adj-1", "signed": _envelope(share)},
        {"label": "alice-adj-2", "signed": _envelope(adjacent)},
    ]

    # 3d. crossing links [0,10] and [5,20] — not strict nesting (s2<s1 false
    #     one way; other way 0<5 but 20>10 => t2<t1 false) -> no surround
    cross_a = _vote(bob, domain, CHAIN_ID, 0, 10, _root("b-cross-a"))
    cross_b = _vote(bob, domain, CHAIN_ID, 5, 20, _root("b-cross-b"))
    scenarios["S3d_crossing_no_surround"] = [
        {"label": "bob-cross-a", "signed": _envelope(cross_a)},
        {"label": "bob-cross-b", "signed": _envelope(cross_b)},
    ]

    # 4. membership change — dave joins at epoch 2; erin exits after epoch 1
    dave_early = _vote(dave, domain, CHAIN_ID, 0, 5, _root("d-early"))
    dave_late = _vote(dave, domain, CHAIN_ID, 20, 25, _root("d-late"))
    erin_early = _vote(erin, domain, CHAIN_ID, 0, 5, _root("e-early"))
    erin_late = _vote(erin, domain, CHAIN_ID, 20, 25, _root("e-late"))
    scenarios["S4_membership_change"] = [
        {"label": "dave-before-join-invalid", "signed": _envelope(dave_early)},
        {"label": "dave-after-join-ok", "signed": _envelope(dave_late)},
        {"label": "erin-while-active-ok", "signed": _envelope(erin_early)},
        {"label": "erin-after-exit-invalid", "signed": _envelope(erin_late)},
    ]

    # 5. tampered signature (valid envelope shape, garbage signature)
    tampered = _vote(alice, domain, CHAIN_ID, 30, 35, _root("a-tamper"))
    tampered_dict = _envelope(tampered)
    sig = bytearray(bytes.fromhex(tampered_dict["signature"]))
    sig[0] ^= 0xFF
    tampered_dict["signature"] = sig.hex()
    scenarios["S5_bad_signature"] = [
        {"label": "alice-tampered-signature", "signed": tampered_dict}
    ]

    # 5b. signed by someone else (mallory signs a vote claiming alice's id)
    forged = _vote(mallory, domain, CHAIN_ID, 40, 45, _root("a-forged"))
    forged_dict = _envelope(forged)
    forged_dict["validator_id"] = "alice"  # embedded signer is mallory -> mismatch
    scenarios["S5b_wrong_signer_pubkey"] = [
        {"label": "mallory-claims-alice", "signed": forged_dict}
    ]

    # 6. unknown validator (frank not in registry)
    unknown = _vote(frank, domain, CHAIN_ID, 0, 5, _root("f-unknown"))
    scenarios["S6_unknown_validator"] = [
        {"label": "frank-unknown", "signed": _envelope(unknown)}
    ]

    # 7. wrong chain id binding (signed for a different chain)
    wrong_chain = _vote(bob, domain, "other-chain-9", 0, 5, _root("b-wrongchain"))
    scenarios["S7_wrong_chain"] = [
        {"label": "bob-other-chain", "signed": _envelope(wrong_chain)}
    ]

    # 8. malformed rounds: source >= target
    bad_rounds = _vote(carol, domain, CHAIN_ID, 9, 9, _root("c-badrounds"))
    scenarios["S8_bad_rounds"] = [
        {"label": "carol-s-equals-t", "signed": _envelope(bad_rounds)}
    ]

    # 9. different validators same target — NOT an offense
    va = _vote(alice, domain, CHAIN_ID, 0, 12, _root("a-x"))
    vb = _vote(bob, domain, CHAIN_ID, 1, 12, _root("b-x"))
    scenarios["S9_cross_validator_no_conflict"] = [
        {"label": "alice-t12", "signed": _envelope(va)},
        {"label": "bob-t12", "signed": _envelope(vb)},
    ]

    # 10. weight snapshot across an epoch boundary + offense:
    # alice weight 100 in epoch 0, 150 in epoch 2. Two epoch-0 votes conflict.
    w1 = _vote(alice, domain, CHAIN_ID, 1, 3, _root("a-w1"))
    w2 = _vote(alice, domain, CHAIN_ID, 2, 3, _root("a-w2"))
    scenarios["S10_weight_snapshot_offense"] = [
        {"label": "alice-epoch0-a", "signed": _envelope(w1)},
        {"label": "alice-epoch0-b", "signed": _envelope(w2)},
    ]

    # 11. mixed sequence with retransmission after a real conflict
    m1 = _vote(carol, domain, CHAIN_ID, 0, 9, _root("c-m1"))
    m2 = _vote(carol, domain, CHAIN_ID, 4, 9, _root("c-m2"))
    scenarios["S11_mixed_conflict_then_rexmit"] = [
        {"label": "carol-m1", "signed": _envelope(m1)},
        {"label": "carol-m2-double", "signed": _envelope(m2)},
        {"label": "carol-m1-rexmit", "signed": _envelope(m1)},
    ]

    manifest = {
        "chain_id": CHAIN_ID,
        "epoch_length": EPOCH_LENGTH,
        "domain": domain.decode(),
        "registry": registry,
        "scenarios": scenarios,
    }

    paths = {}
    manifest_path = out / "fixture_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    paths["manifest"] = str(manifest_path)

    # private keys file (synthetic only!) for the demo/HTTP client
    key_material = {
        name: signer.private_pem().decode() for name, signer in signers.items()
    }
    keys_path = out / "fixture_synthetic_keys.pem.json"
    keys_path.write_text(json.dumps(key_material, indent=2, sort_keys=True), encoding="utf-8")
    paths["synthetic_keys"] = str(keys_path)
    return paths
