#!/usr/bin/env python3
"""Independent reference oracle for flowrouter.

This program is NOT part of the system under test. It is a from-scratch,
stdlib-only reimplementation in a different language (Python) of:

  * FNV-1a 64-bit hashing with a splitmix64 avalanche finalizer and the
    versioned key spaces
        flow:  b"flow-v1|"  + "<proto>|<src>:<sport>|<dst>:<dport>"
        vnode: b"vnode-v1|" + "<memberID>#<replica>"
  * the weighted integer vnode allocation (linear; and two-stage
    largest-remainder when a cap is set),
  * consistent-hash ring ownership with wrap-around successor lookup,
  * the full re-modulo baseline over sorted positive member IDs,
  * migration classification (member_added / member_removed /
    weight_changed / *_ring_empty).

It reads the same fixed flow-set fixture the Go tests use and the shared
scenario matrix, and emits golden_<flowset>.json. The Go test suite asserts
its computed results against this file, so expected answers cannot be
silently regenerated by the code being tested.

Usage: oracle.py --repo-root <dir> --flowset flows_smoke [--out PATH]
"""
import argparse
import json
import math
import os
import struct
import sys

MASK64 = (1 << 64) - 1
FNV_OFFSET = 0xcbf29ce484222325
FNV_PRIME = 0x100000001b3
SM_GOLDEN = 0x9e3779b97f4a7c15
SM_C1 = 0xbf58476d1ce4e5b9
SM_C2 = 0x94d049bb133111eb

PROTO_NAMES = {6: "tcp", 17: "udp", 132: "sctp"}


def fnv1a64(data: bytes) -> int:
    h = FNV_OFFSET
    for b in data:
        h ^= b
        h = (h * FNV_PRIME) & MASK64
    return h


def splitmix64(h: int) -> int:
    h = (h + SM_GOLDEN) & MASK64
    h = ((h ^ (h >> 30)) * SM_C1) & MASK64
    h = ((h ^ (h >> 27)) * SM_C2) & MASK64
    return h ^ (h >> 31)


def hash64(data: bytes) -> int:
    # Must match internal/hashx: splitmix64 finalizer over FNV-1a 64.
    return splitmix64(fnv1a64(data))


def flow_hash(flow: dict) -> int:
    name = PROTO_NAMES.get(flow["proto"], "p%d" % flow["proto"])
    key = "%s|%s:%d|%s:%d" % (
        name, flow["src_ip"], flow["src_port"],
        flow["dst_ip"], flow["dst_port"],
    )
    return hash64(("flow-v1|" + key).encode("utf-8"))


def vnode_hash(member_id: str, replica: int) -> int:
    return hash64(("vnode-v1|%s#%d" % (member_id, replica)).encode("utf-8"))


def allocate(members, vpw, cap):
    """Return dict id->vnode count plus audit fields."""
    positive = sorted((m for m in members if m["weight"] > 0),
                      key=lambda m: m["id"])
    total_w = sum(m["weight"] for m in positive)
    counts = {m["id"]: 0 for m in positive}
    base = {}
    extra = {}
    ideal = {}
    remainder = {}
    if not positive:
        return {"counts": counts, "base": {}, "extra": {}, "total": 0,
                "ideal": {}, "remainder": {}, "strategy": "empty",
                "vnodes_per_weight": vpw, "capped_to": cap}
    if cap <= 0:
        for m in positive:
            c = m["weight"] * vpw
            counts[m["id"]] = c
            ideal[m["id"]] = float(m["weight"])
            remainder[m["id"]] = 0.0
        return {"counts": counts, "base": {}, "extra": {},
                "total": sum(counts.values()), "ideal": ideal,
                "remainder": remainder, "strategy": "linear_weight",
                "vnodes_per_weight": vpw, "capped_to": 0}
    n = len(positive)
    assert cap >= n, "cap below positive member count"
    rem_budget = cap - n
    floors = {}
    floors_sum = 0
    for m in positive:
        exact = cap * m["weight"] / total_w
        extra_exact = rem_budget * m["weight"] / total_w
        flr = int(math.floor(extra_exact))
        floors[m["id"]] = flr
        floors_sum += flr
        ideal[m["id"]] = exact
        remainder[m["id"]] = extra_exact - flr
        base[m["id"]] = 1
    leftover = rem_budget - floors_sum
    # largest fractional remainder wins; tie broken by ascending member id
    order = sorted(positive, key=lambda m: (-remainder[m["id"]], m["id"]))
    extras = dict(floors)
    for k in range(leftover):
        extras[order[k % len(order)]["id"]] += 1
    for m in positive:
        c = base[m["id"]] + extras[m["id"]]
        counts[m["id"]] = c
        extra[m["id"]] = extras[m["id"]]
    return {"counts": counts, "base": base, "extra": extra,
            "total": sum(counts.values()), "ideal": ideal,
            "remainder": remainder, "strategy": "largest_remainder",
            "vnodes_per_weight": vpw, "capped_to": cap}


def build_ring(members, vpw, cap):
    """Return (sorted_vnodes, on_ring_ids). A vnode is (hash, id, replica)."""
    on = [m for m in members if m["weight"] > 0 and m.get("up", True)]
    alloc = allocate(on, vpw, cap)
    vnodes = []
    for m in on:
        for r in range(alloc["counts"][m["id"]]):
            vnodes.append((vnode_hash(m["id"], r), m["id"], r))
    vnodes.sort(key=lambda v: (v[0], v[1], v[2]))
    on_ids = {m["id"] for m in on}
    return vnodes, on_ids, alloc


def ring_owner(vnodes, h):
    if not vnodes:
        return None
    # first vnode with hash >= h (list sorted); else wrap to first
    lo, hi = 0, len(vnodes)
    while lo < hi:
        mid = (lo + hi) // 2
        if vnodes[mid][0] >= h:
            hi = mid
        else:
            lo = mid + 1
    return vnodes[0 if lo == len(vnodes) else lo][1]


def modulo_baseline(members):
    ordered = sorted(m["id"] for m in members
                     if m["weight"] > 0 and m.get("up", True))
    return ordered


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--flowset", default="flows_smoke")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    root = args.repo_root
    with open(os.path.join(root, "testdata", "flowsets",
                           args.flowset + ".json")) as f:
        fs = json.load(f)
    with open(os.path.join(root, "testdata", "scenarios",
                           "scenarios.json")) as f:
        matrix = json.load(f)

    global_vpw = matrix["vnodes_per_weight"]
    global_cap = matrix.get("max_vnodes", 0)

    hashes = [(flow_hash(fl),
               "%s|%s:%d|%s:%d" % (PROTO_NAMES.get(fl["proto"], "p%d" % fl["proto"]),
                                   fl["src_ip"], fl["src_port"],
                                   fl["dst_ip"], fl["dst_port"]))
              for fl in fs["flows"]]

    out_scenarios = {}
    for sc in matrix["scenarios"]:
        vpw = sc.get("vnodes_per_weight", global_vpw)
        cap = sc.get("max_vnodes", global_cap)
        versions = []
        rings = []
        ids_per_version = []
        for ver in sc["versions"]:
            vnodes, ids, alloc = build_ring(ver["members"], vpw, cap)
            rings.append(vnodes)
            ids_per_version.append(ids)
            versions.append(alloc)

        owners = []
        for h, key in hashes:
            owners.append({"k": key, "h": h,
                           "o": [ring_owner(rv, h) for rv in rings]})

        transitions = sc.get("transitions")
        if transitions is None:
            transitions = [[i, i + 1] for i in range(len(sc["versions"]) - 1)]
        trans_out = {}
        for a, b in transitions:
            moved = stayed = base_moved = 0
            reasons = {}
            for h, _ in hashes:
                frm = ring_owner(rings[a], h)
                to = ring_owner(rings[b], h)
                if frm == to and frm is not None:
                    stayed += 1
                elif frm != to:
                    moved += 1
                    if frm is None:
                        reason = "old_ring_empty"
                    elif to is None:
                        reason = "new_ring_empty"
                    elif frm not in ids_per_version[b]:
                        reason = "member_removed"
                    elif to not in ids_per_version[a]:
                        reason = "member_added"
                    else:
                        reason = "weight_changed"
                    reasons[reason] = reasons.get(reason, 0) + 1
                # modulo baseline; undefined when either ring is empty
                oa = modulo_baseline(sc["versions"][a]["members"])
                ob = modulo_baseline(sc["versions"][b]["members"])
                if oa and ob and oa[h % len(oa)] != ob[h % len(ob)]:
                    base_moved += 1
            n = len(hashes)
            base_frac = (base_moved / n) if (oa and ob) else None
            trans_out["%d->%d" % (a, b)] = {
                "moved": moved, "stayed": stayed,
                "move_fraction": moved / n if n else 0.0,
                "baseline_moved": base_moved,
                "baseline_move_fraction": base_frac,
                "reasons": reasons,
            }

        # realized traffic distribution per version over this exact flow set
        traffic = []
        for i, rv in enumerate(rings):
            dist = {m["id"]: 0 for m in sc["versions"][i]["members"]}
            routed = 0
            for h, _ in hashes:
                o = ring_owner(rv, h)
                if o is not None:
                    dist[o] += 1
                    routed += 1
            traffic.append({"routed": routed, "counts": dist,
                            "share": {k: (v / routed if routed else 0.0)
                                      for k, v in dist.items()}})

        out_scenarios[sc["name"]] = {
            "allocations": versions,
            "transitions": trans_out,
            "traffic": traffic,
            "owners": owners,
        }

    golden = {
        "generated_by": "testdata/oracle/oracle.py (independent Python/FNV-1a implementation)",
        "flowset": args.flowset,
        "flow_count": len(hashes),
        "scenarios": out_scenarios,
    }
    text = json.dumps(golden, indent=2, sort_keys=True)
    if args.out:
        out_path = args.out
    else:
        out_path = os.path.join(root, "testdata", "oracle",
                                "golden_" + args.flowset + ".json")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(text + "\n")
    print("wrote %s (%d flows, %d scenarios)" %
          (out_path, len(hashes), len(out_scenarios)))


if __name__ == "__main__":
    sys.exit(main())
