package netmodel

import (
	"encoding/binary"
	"errors"
	"fmt"
	"net/netip"
	"time"
)

// Minimal offline pcap (libpcap) reader, sufficient for synthetic fixtures:
// classic global header (microsecond or nanosecond resolution), link-layer
// types Ethernet and raw IPv4/IPv6. PCAP-NG is deliberately rejected with a
// clear error rather than mis-parsed.
//
// Fixtures are generated by test helpers (see internal/netmodel/capture.go),
// never by the reassembly core, so the golden answers in tests stay
// independent of the implementation under test.

// Link-layer types we understand, from the pcap registry (tcpdump.org).
const (
	linkEthernet  = 1
	linkRaw       = 12 // raw IPv4, as written by Linux cooked captures vary
	linkRawIPv6   = 31 // DLT_IP6 / raw IPv6 in some stacks; we also probe
	linkLinuxSLL  = 113
	linkLinuxSLL2 = 276
)

var pcapMagicMicro = [4]byte{0xd4, 0xc3, 0xb2, 0xa1} // native order, us
var pcapMagicNano = [4]byte{0x4d, 0x3c, 0xb2, 0xa1}  // native order, ns

// ParsePCap extracts TCP packets from a classic pcap byte stream.
// Non-TCP records are skipped. Truncated records stop parsing and return the
// packets read so far together with the error, so a corrupt tail never
// silently disappears.
func ParsePCap(data []byte) ([]Packet, error) {
	if len(data) < 24 {
		return nil, errors.New("pcap: file shorter than 24-byte global header")
	}
	var order binary.ByteOrder = binary.LittleEndian
	nano := false
	switch magic := [4]byte(data[0:4]); magic {
	case pcapMagicMicro:
	case pcapMagicNano:
		nano = true
	case [4]byte{0xa1, 0xb2, 0xc3, 0xd4}:
		order = binary.BigEndian
	case [4]byte{0xa1, 0xb2, 0x3c, 0x4d}:
		order = binary.BigEndian
		nano = true
	default:
		return nil, errors.New("pcap: bad magic (pcap-ng not supported; use classic pcap)")
	}

	linkType := order.Uint32(data[20:24])

	var out []Packet
	pos := 24
	for pos < len(data) {
		if len(data)-pos < 16 {
			return out, fmt.Errorf("pcap: truncated record header at offset %d", pos)
		}
		tsSec := order.Uint32(data[pos : pos+4])
		tsFrac := order.Uint32(data[pos+4 : pos+8])
		capLen := int(order.Uint32(data[pos+8 : pos+12]))
		origLen := int(order.Uint32(data[pos+12 : pos+16]))
		pos += 16
		if capLen > len(data)-pos {
			return out, fmt.Errorf("pcap: record claims %d bytes but only %d remain", capLen, len(data)-pos)
		}
		frame := data[pos : pos+capLen]
		pos += capLen

		rec, ok, err := parseFrame(frame, linkType)
		if err != nil {
			return out, fmt.Errorf("pcap: record at ts=%d.%09d: %w", tsSec, tsFrac, err)
		}
		if ok {
			ts := time.Unix(int64(tsSec), int64(tsFrac))
			if !nano {
				ts = time.Unix(int64(tsSec), int64(tsFrac)*1000)
			}
			rec.Timestamp = ts.UTC().Format(time.RFC3339Nano)
			if origLen != capLen {
				rec.RecordID = fmt.Sprintf("snaplen-truncated:%d<%d", capLen, origLen)
			}
			out = append(out, rec)
		}
	}
	return out, nil
}

// parseFrame decodes one link-layer frame. ok=false means "not TCP, skip".
func parseFrame(frame []byte, linkType uint32) (p Packet, ok bool, err error) {
	var ipPayload []byte
	var src, dst netip.Addr
	var proto byte

	switch linkType {
	case linkEthernet:
		if len(frame) < 14 {
			return Packet{}, false, errors.New("ethernet frame too short")
		}
		etherType := frame[12:14]
		body := frame[14:]
		// Single VLAN tag (0x8100): skip 4 bytes.
		if etherType[0] == 0x81 && etherType[1] == 0x00 && len(body) >= 4 {
			etherType = body[2:4]
			body = body[4:]
		}
		switch {
		case etherType[0] == 0x08 && etherType[1] == 0x00:
			ipPayload, src, dst, proto, err = parseIPv4(body)
		case etherType[0] == 0x86 && etherType[1] == 0xdd:
			ipPayload, src, dst, proto, err = parseIPv6(body)
		default:
			return Packet{}, false, nil // non-IP: skip
		}
	case linkRaw, 228 /*DLT_IPV4*/ :
		ipPayload, src, dst, proto, err = parseIPv4(frame)
	case linkRawIPv6, 229 /*DLT_IPV6*/ :
		ipPayload, src, dst, proto, err = parseIPv6(frame)
	case linkLinuxSLL, linkLinuxSLL2:
		// SLL: 16-byte header, SLL2: 20-byte header; then ethertype+payload.
		hdr := 16
		if linkType == linkLinuxSLL2 {
			hdr = 20
		}
		if len(frame) < hdr+2 {
			return Packet{}, false, errors.New("linux cooked frame too short")
		}
		etherType := frame[hdr : hdr+2]
		body := frame[hdr+2:]
		switch {
		case etherType[0] == 0x08 && etherType[1] == 0x00:
			ipPayload, src, dst, proto, err = parseIPv4(body)
		case etherType[0] == 0x86 && etherType[1] == 0xdd:
			ipPayload, src, dst, proto, err = parseIPv6(body)
		default:
			return Packet{}, false, nil
		}
	default:
		// Last resort: probe the first nibble so raw captures written with
		// an unusual linktype still work for local fixtures.
		if len(frame) > 0 && frame[0]>>4 == 4 {
			ipPayload, src, dst, proto, err = parseIPv4(frame)
		} else if len(frame) > 0 && frame[0]>>4 == 6 {
			ipPayload, src, dst, proto, err = parseIPv6(frame)
		} else {
			return Packet{}, false, nil
		}
	}
	if errors.Is(err, errIPv4Fragment) {
		return Packet{}, false, nil // IP fragments carry no standalone TCP segment
	}
	if err != nil {
		return Packet{}, false, err
	}
	if proto != 6 { // not TCP
		return Packet{}, false, nil
	}
	return parseTCP(ipPayload, src, dst)
}

func parseIPv4(b []byte) (payload []byte, src, dst netip.Addr, proto byte, err error) {
	if len(b) < 20 {
		return nil, netip.Addr{}, netip.Addr{}, 0, errors.New("ipv4 packet too short")
	}
	if b[0]>>4 != 4 {
		return nil, netip.Addr{}, netip.Addr{}, 0, errors.New("not ipv4")
	}
	ihl := int(b[0]&0x0f) * 4
	if ihl < 20 || len(b) < ihl {
		return nil, netip.Addr{}, netip.Addr{}, 0, errors.New("ipv4 bad IHL")
	}
	proto = b[9]
	s, _ := netip.AddrFromSlice(b[12:16])
	d, _ := netip.AddrFromSlice(b[16:20])
	total := int(binary.BigEndian.Uint16(b[2:4]))
	end := len(b)
	if total >= ihl && total < end {
		end = total
	}
	// Fragmented IP datagrams other than the first fragment carry no TCP
	// header; skip them (see errIPv4Fragment handling in parseFrame).
	frag := binary.BigEndian.Uint16(b[6:8]) & 0x1fff
	mf := b[6]&0x20 != 0
	if frag != 0 || mf {
		return nil, netip.Addr{}, netip.Addr{}, 0, errIPv4Fragment
	}
	return b[ihl:end], s, d, proto, nil
}

func parseIPv6(b []byte) (payload []byte, src, dst netip.Addr, proto byte, err error) {
	if len(b) < 40 {
		return nil, netip.Addr{}, netip.Addr{}, 0, errors.New("ipv6 packet too short")
	}
	if b[0]>>4 != 6 {
		return nil, netip.Addr{}, netip.Addr{}, 0, errors.New("not ipv6")
	}
	next := b[6]
	s, _ := netip.AddrFromSlice(b[8:24])
	d, _ := netip.AddrFromSlice(b[24:40])
	payload = b[40:]
	if next != 6 {
		return payload, s, d, next, nil // extension headers unsupported: non-TCP unless next==6
	}
	return payload, s, d, 6, nil
}

// errIPv4Fragment marks an IP-fragmented record that cannot contain a complete
// TCP header. The parser treats it as "skip" rather than fatal.
var errIPv4Fragment = errors.New("ipv4 fragmented record skipped")

func parseTCP(b []byte, srcIP, dstIP netip.Addr) (Packet, bool, error) {
	if len(b) < 20 {
		return Packet{}, false, errors.New("tcp segment too short for header")
	}
	sp := binary.BigEndian.Uint16(b[0:2])
	dp := binary.BigEndian.Uint16(b[2:4])
	seq := binary.BigEndian.Uint32(b[4:8])
	ack := binary.BigEndian.Uint32(b[8:12])
	dataOff := int(b[12]>>4) * 4
	if dataOff < 20 || len(b) < dataOff {
		return Packet{}, false, errors.New("tcp bad data offset")
	}
	flags := b[13]
	payload := append([]byte(nil), b[dataOff:]...)
	var names []string
	for _, bit := range []struct {
		mask byte
		name string
	}{
		{0x01, "FIN"}, {0x02, "SYN"}, {0x04, "RST"}, {0x08, "PSH"},
		{0x10, "ACK"}, {0x20, "URG"},
	} {
		if flags&bit.mask != 0 {
			names = append(names, bit.name)
		}
	}
	return Packet{
		SrcIP:   srcIP.String(),
		SrcPort: sp,
		DstIP:   dstIP.String(),
		DstPort: dp,
		Flags:   names,
		Seq:     seq,
		Ack:     ack,
		Payload: payload,
	}, true, nil
}
