// Package harness builds the in-process three-node cluster used by scenario
// tests and by `clsnapctl scenario`, runs a director.Scenario, and checks the
// hand-computed expectations independently of the snapshot coordinator:
//
//   - expected values come from the fixture file (authored by hand),
//   - observed values are assembled by the replay package from durable node
//     records, and live totals are summed directly from the kernel ledgers,
//   - no expectation is generated by the code under test.
package harness

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"sync"

	"clsnap/internal/apperr"
	"clsnap/internal/clock"
	"clsnap/internal/director"
	"clsnap/internal/kernel"
	"clsnap/internal/logrun"
	"clsnap/internal/protocol"
	"clsnap/internal/replay"
	"clsnap/internal/snapshot"
	"clsnap/internal/store"
)

// LoadScenario parses a fixture file.
func LoadScenario(path string) (*director.Scenario, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, apperr.Failure(apperr.CodeStoreIO, "LoadScenario", "read "+path, err)
	}
	var sc director.Scenario
	if err := json.Unmarshal(b, &sc); err != nil {
		return nil, apperr.Inputf(apperr.CodeMalformed, "scenario %s: %v", path, err)
	}
	if len(sc.Nodes) != 3 {
		return nil, apperr.Inputf(apperr.CodeMalformed,
			"scenario %s must declare exactly 3 nodes, got %d", sc.Name, len(sc.Nodes))
	}
	return &sc, nil
}

// ValidateFixture checks internal accounting consistency WITHOUT running the
// kernel: every account has exactly one owner, initial_total equals the sum
// of seeded balances, and every expected snapshot global total equals it.
func ValidateFixture(sc *director.Scenario) error {
	owners := map[string]protocol.NodeID{}
	var sum uint64
	for _, a := range sc.Accounts {
		if a.ID == "" {
			return apperr.Inputf(apperr.CodeMalformed, "account with empty id")
		}
		if prev, dup := owners[a.ID]; dup {
			return apperr.Inputf(apperr.CodeMalformed,
				"account %s assigned to two owners %s and %s", a.ID, prev, a.Owner)
		}
		owners[a.ID] = a.Owner
		sum += a.Balance
	}
	if sum != sc.Expect.InitialTotal {
		return apperr.Inputf(apperr.CodeMalformed,
			"scenario %s: initial_total %d != sum of seeded balances %d",
			sc.Name, sc.Expect.InitialTotal, sum)
	}
	for sid, ex := range sc.Expect.Snapshots {
		if ex.Complete && ex.GlobalTotal != sc.Expect.InitialTotal {
			return apperr.Inputf(apperr.CodeMalformed,
				"scenario %s: expected snapshot %s global %d != initial total %d (tokens cannot be conserved)",
				sc.Name, sid, ex.GlobalTotal, sc.Expect.InitialTotal)
		}
	}
	return nil
}

// Holds the wired pieces for one scenario execution.
type nodeWiring struct {
	id      protocol.NodeID
	peers   []protocol.NodeID
	st      store.Store
	led     *kernel.Ledger
	coord   *snapshot.Coordinator
	journal *logrun.Journal
}

// Harness is the running test cluster.
type Harness struct {
	sc      *director.Scenario
	cluster *director.Cluster
	journ   *logrun.Journal
	logdir  string

	mu    sync.Mutex
	nodes map[protocol.NodeID]*nodeWiring
	stop  []func()

	pgDSN string
}

// Option configures the harness.
type Option func(*Harness)

// WithPostgres switches every node to an isolated Postgres database. dsnTmpl
// uses "{db}" as a placeholder replaced with per-node database names.
func WithPostgres(dsnTmpl string) Option {
	return func(h *Harness) { h.pgDSN = dsnTmpl }
}

// New wires all three nodes against one direct transport.
func New(ctx context.Context, sc *director.Scenario, logdir, runID string, opts ...Option) (*Harness, error) {
	if err := ValidateFixture(sc); err != nil {
		return nil, err
	}
	h := &Harness{
		sc:      sc,
		logdir:  logdir,
		nodes:   map[protocol.NodeID]*nodeWiring{},
	}
	for _, o := range opts {
		o(h)
	}
	h.journ = logrun.New(nil, logdir, runID, sc.Name)
	h.cluster = director.NewCluster(sc)

	seed := h.cluster.Accounts
	router := newRouterMap(seed)

	for _, n := range sc.Nodes {
		var st store.Store
		if h.pgDSN != "" {
			dbName := "clsnap_" + string(n) + "_" + sanitize(runID)
			pgStore, err := openFreshPostgres(ctx, h.pgDSN, dbName)
			if err != nil {
				return nil, err
			}
			st = pgStore
			h.stop = append(h.stop, func() { pgStore.Close() })
		} else {
			st = store.NewMemory()
		}
		if err := st.Bootstrap(ctx, n, seed[n]); err != nil {
			return nil, err
		}
		if _, err := st.BumpEpoch(ctx, n); err != nil {
			return nil, err
		}
		led, err := kernel.NewLedger(n, seed[n])
		if err != nil {
			return nil, err
		}
		peers := peersExcept(sc.Nodes, n)
		coord, err := snapshot.New(snapshot.Deps{
			Node: n, Peers: peers, Ledger: led, Store: st,
			Transport: h.cluster.Dir, Clock: clock.New(),
			Logger: h.journ, Router: router, Epoch: 1,
		})
		if err != nil {
			return nil, err
		}
		h.cluster.Dir.RegisterReceiver(n, receiverAdapter{coord})
		h.nodes[n] = &nodeWiring{
			id: n, peers: peers, st: st, led: led, coord: coord, journal: h.journ,
		}
	}

	h.cluster.Transfer = func(ctx context.Context, node protocol.NodeID, t protocol.Transfer) error {
		return h.nodes[node].coord.StartTransfer(ctx, t)
	}
	h.cluster.Snapshot = func(ctx context.Context, node protocol.NodeID, s protocol.SnapshotID) error {
		return h.nodes[node].coord.Initiate(ctx, s)
	}
	h.cluster.Flush = func(ctx context.Context, src, dst protocol.NodeID) (int, error) {
		return h.nodes[src].coord.FlushPeer(ctx, dst)
	}
	return h, nil
}

// Run executes the scenario steps.
func (h *Harness) Run(ctx context.Context) error {
	h.journ.Event(ctx, protocol.Event{
		Kind: "scenario_started", Detail: map[string]any{
			"steps": len(h.sc.Steps), "nodes": h.sc.Nodes,
		},
	})
	if err := h.cluster.Run(ctx, h.sc); err != nil {
		return err
	}
	h.assertExpectations(ctx)
	return nil
}

// Journal exposes the run journal (for tests that add their own checks).
func (h *Harness) Journal() *logrun.Journal { return h.journ }

// Cluster exposes the director cluster (for custom steps).
func (h *Harness) Cluster() *director.Cluster { return h.cluster }

// Coord returns one node's coordinator.
func (h *Harness) Coord(n protocol.NodeID) *snapshot.Coordinator { return h.nodes[n].coord }

// Ledger returns one node's live ledger.
func (h *Harness) Ledger(n protocol.NodeID) *kernel.Ledger { return h.nodes[n].led }

// Store returns one node's store.
func (h *Harness) Store(n protocol.NodeID) store.Store { return h.nodes[n].st }

// NodeIDs returns the three node ids.
func (h *Harness) NodeIDs() []protocol.NodeID { return append([]protocol.NodeID(nil), h.sc.Nodes...) }

// RestartNode simulates a process restart for one node: it loads durable
// accounts, bumps the boot epoch, builds a fresh ledger and coordinator,
// registers the new receiver, and runs the boot recovery (which aborts every
// round left recording). It returns the new coordinator and the new epoch.
func (h *Harness) RestartNode(ctx context.Context, n protocol.NodeID) (*snapshot.Coordinator, uint64, error) {
	w := h.nodes[n]
	accounts, err := w.st.LoadAccounts(ctx, n)
	if err != nil {
		return nil, 0, err
	}
	led, err := kernel.NewLedger(n, accounts)
	if err != nil {
		return nil, 0, err
	}
	epoch, err := w.st.BumpEpoch(ctx, n)
	if err != nil {
		return nil, 0, err
	}
	peers := peersExcept(h.sc.Nodes, n)
	coord, err := snapshot.New(snapshot.Deps{
		Node: n, Peers: peers, Ledger: led, Store: w.st,
		Transport: h.cluster.Dir, Clock: clock.New(),
		Logger: h.journ, Router: newRouterMap(h.cluster.Accounts), Epoch: epoch,
	})
	if err != nil {
		return nil, 0, err
	}
	if _, err := coord.RecoverAbortedRounds(ctx); err != nil {
		return nil, 0, err
	}
	h.cluster.Dir.RegisterReceiver(n, receiverAdapter{coord})
	w.led = led
	w.coord = coord
	return coord, epoch, nil
}

// RouterForTest exposes the account-owner table (used by custom tests).
func (h *Harness) RouterForTest() snapshot.Router { return newRouterMap(h.cluster.Accounts) }

// Finalize writes the replayable report.
func (h *Harness) Finalize(ctx context.Context) (logrun.Report, string, error) {
	summary := fmt.Sprintf("scenario %s executed; verdicts carry the concrete conservation and ordering judgments", h.sc.Name)
	return h.journ.Finalize(ctx, summary)
}

// Close releases any backing resources.
func (h *Harness) Close() {
	for _, fn := range h.stop {
		fn()
	}
}

func (h *Harness) assertExpectations(ctx context.Context) {
	// 1. Live ledger conservation AFTER the run (independent summation).
	var liveTotal uint64
	for _, n := range h.sc.Nodes {
		accts := h.nodes[n].led.Accounts()
		var t uint64
		for _, a := range accts {
			t += a.Balance
		}
		liveTotal += t
	}
	h.journ.Check("live ledger total conserved after scenario",
		liveTotal == h.sc.Expect.FinalLiveTotal,
		fmt.Sprintf("sum of live balances %d vs expected final total %d", liveTotal, h.sc.Expect.FinalLiveTotal),
		h.sc.Expect.FinalLiveTotal, liveTotal)
	h.journ.Check("live ledger total equals initial total (no token creation)",
		liveTotal == h.sc.Expect.InitialTotal,
		"no process was paused; complete transfers still conserve",
		h.sc.Expect.InitialTotal, liveTotal)

	// 2. Per-snapshot independent assembly and conservation.
	for sid, ex := range h.sc.Expect.Snapshots {
		// Build a SnapshotStore view from the three node stores.
		view := multiStore{nodes: h.sc.Nodes, stores: func() map[protocol.NodeID]store.SnapshotStore {
			m := map[protocol.NodeID]store.SnapshotStore{}
			for n, w := range h.nodes {
				m[n] = w.st
			}
			return m
		}()}
		gv, err := replay.Assemble(ctx, view, h.sc.Nodes, protocol.SnapshotID(sid))
		if !ex.Complete {
			// The fixture expects this round to be incomplete/aborted.
			h.journ.CheckErrorClass("snapshot "+sid+" incomplete as expected",
				apperr.KindConflict, err)
			continue
		}
		if err != nil {
			h.journ.Check("snapshot "+sid+" assembled", false,
				"expected complete snapshot but assembly failed: "+err.Error(), nil, err)
			continue
		}
		h.journ.Check("snapshot "+sid+" global token conservation",
			gv.GlobalSum == ex.GlobalTotal,
			fmt.Sprintf("independent global sum %d vs expected %d (local totals %d, captured in-flight %d)",
				gv.GlobalSum, ex.GlobalTotal, gv.NodeTotal, gv.ChanTotal),
			ex.GlobalTotal, gv.GlobalSum)

		// Exact per-node local totals.
		for _, n := range h.sc.Nodes {
			want, present := ex.LocalTotals[string(n)]
			if !present {
				continue
			}
			var got uint64
			for _, nv := range gv.Nodes {
				if nv.Node == n {
					got = nv.LocalTotal
				}
			}
			h.journ.Check(fmt.Sprintf("snapshot %s local total @%s", sid, n),
				got == want, fmt.Sprintf("recorded local total %d vs expected %d", got, want),
				want, got)
		}
		// Exact per-channel captured in-flight amounts.
		for ch, want := range ex.InFlight {
			parts := strings.SplitN(ch, "->", 2)
			if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
				h.journ.Check("in-flight key "+ch, false, "bad key, want src->dst", nil, nil)
				continue
			}
			src, dst := parts[0], parts[1]
			var got uint64
			var count int
			for _, nv := range gv.Nodes {
				if string(nv.Node) == dst {
					got = nv.Channels[protocol.NodeID(src)]
					count = nv.CapturedCount[protocol.NodeID(src)]
				}
			}
			h.journ.Check(fmt.Sprintf("snapshot %s captured in-flight %s (%d msgs)", sid, ch, count),
				got == want,
				fmt.Sprintf("captured sum %d vs expected %d on %s", got, want, ch), want, got)
		}

		// Recompute conservation directly against the initial total too:
		// Chandy-Lamport must cut a consistent global state.
		if err := replay.Conservation(gv, h.sc.Expect.InitialTotal); err != nil {
			h.journ.Check("replay.Conservation("+sid+")", false, err.Error(),
				h.sc.Expect.InitialTotal, gv.GlobalSum)
		} else {
			h.journ.Check("replay.Conservation("+sid+")", true,
				"global snapshot sum equals initial token supply", h.sc.Expect.InitialTotal, gv.GlobalSum)
		}
	}
}

// receiverAdapter bridges coordinator Receive into transport.Receiver.
type receiverAdapter struct{ c *snapshot.Coordinator }

func (r receiverAdapter) Receive(ctx context.Context, env protocol.Envelope) error {
	return r.c.Receive(ctx, env)
}

// multiStore unions the three node stores for replay.Assemble. Each node
// record lives in that node's own store/database.
type multiStore struct {
	nodes  []protocol.NodeID
	stores map[protocol.NodeID]store.SnapshotStore
}

func (m multiStore) SaveRecord(context.Context, protocol.NodeRecord) error {
	return apperr.Failure(apperr.CodeNotPermitted, "multiStore", "read-only view", nil)
}
func (m multiStore) GetRecord(ctx context.Context, node protocol.NodeID, snap protocol.SnapshotID) (protocol.NodeRecord, error) {
	return m.stores[node].GetRecord(ctx, node, snap)
}
func (m multiStore) ListRecords(ctx context.Context, snap protocol.SnapshotID) ([]protocol.NodeRecord, error) {
	var out []protocol.NodeRecord
	for _, n := range m.nodes {
		rec, err := m.stores[n].GetRecord(ctx, n, snap)
		if err != nil {
			continue
		}
		out = append(out, rec)
	}
	return out, nil
}
func (m multiStore) ListSnapshots(context.Context) ([]protocol.SnapshotID, error) {
	return nil, apperr.Failure(apperr.CodeNotPermitted, "multiStore", "read-only view", nil)
}
func (m multiStore) Abort(context.Context, protocol.NodeID, protocol.SnapshotID, string) error {
	return apperr.Failure(apperr.CodeNotPermitted, "multiStore", "read-only view", nil)
}

// routerMap is the static account->owner table.
type routerMap struct{ m map[string]protocol.NodeID }

func newRouterMap(seed map[protocol.NodeID][]protocol.Account) *routerMap {
	r := &routerMap{m: map[string]protocol.NodeID{}}
	for n, accts := range seed {
		for _, a := range accts {
			r.m[a.ID] = n
		}
	}
	return r
}
func (r *routerMap) OwnerOf(a string) (protocol.NodeID, bool) { n, ok := r.m[a]; return n, ok }

func peersExcept(all []protocol.NodeID, me protocol.NodeID) []protocol.NodeID {
	out := []protocol.NodeID{}
	for _, n := range all {
		if n != me {
			out = append(out, n)
		}
	}
	return out
}

func sanitize(s string) string {
	b := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			b = append(b, c)
		case c >= 'A' && c <= 'Z':
			b = append(b, c+('a'-'A'))
		default:
			b = append(b, '_')
		}
	}
	if len(b) > 24 {
		b = b[len(b)-24:]
	}
	return string(b)
}
