//! Golden-vector tests against the INDEPENDENT Python oracle
//! (`tests/oracle/oracle.py`).
//!
//! The fixtures in `fixtures/golden/golden.json` are generated by
//! `python3 tests/oracle/oracle.py`; none of those bytes are produced by the
//! Rust implementation under test. These tests assert:
//!
//! * exact kernel payload bytes (encoder must match the oracle bit-for-bit);
//! * exact container bytes (framing, tables, big-endian integers, CRC);
//! * per-step `(low, range)` for the encoder and `(code, range, scaled)` for
//!   the decoder, so interval evolution is compared step by step;
//! * every negative fixture produces the exact error code, and the
//!   reserved-flag fixture is specifically `indeterminate`.

use range_codec::container::{decode, DecodeBudget, ModelMode};
use range_codec::error::{CodecError, Decision};
use range_codec::model::{AdaptiveModel, StaticModel};
use range_codec::range::RangeEncoder;
use serde_json::Value;
use std::path::PathBuf;

fn golden() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures/golden/golden.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("golden.json must be valid JSON")
}

fn as_u32(v: &Value) -> u32 {
    v.as_u64().unwrap() as u32
}

fn oracle_payload(case: &Value) -> Vec<u8> {
    hex_to_bytes(case["payload_hex"].as_str().unwrap())
}
fn oracle_container(case: &Value) -> Vec<u8> {
    hex_to_bytes(case["container_hex"].as_str().unwrap())
}
fn hex_to_bytes(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn spec_constants_match_oracle() {
    let spec = &golden()["spec"];
    assert_eq!(spec["TOP"].as_u64().unwrap(), 1 << 24);
    assert_eq!(spec["MAX_FREQ_TOTAL"].as_u64().unwrap(), 1 << 14);
    assert_eq!(spec["MAX_SYMBOLS"].as_u64().unwrap(), 256);
    assert_eq!(spec["TAIL_SHIFTS"].as_u64().unwrap(), 4);
    assert_eq!(spec["byte_order"].as_str().unwrap(), "big-endian");
}

#[test]
fn kernel_bytes_match_oracle_for_every_positive_case() {
    let doc = golden();
    let mut n = 0;
    for case in doc["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let symbols = hex_to_bytes(case["symbols_hex"].as_str().unwrap());
        let want_payload = oracle_payload(case);

        let payload = if case["mode"].as_str().unwrap() == "static" {
            let freqs: Vec<u32> = case["freqs"]
                .as_array()
                .unwrap()
                .iter()
                .map(as_u32)
                .collect();
            let mut enc = RangeEncoder::new();
            let mut model = StaticModel::new(&freqs).expect("oracle freqs must validate");
            enc.encode_all(&mut model, &symbols).unwrap();
            enc.finish().unwrap()
        } else {
            let n_sym = as_u32(&case["num_symbols"]);
            let mut enc = RangeEncoder::new();
            let mut model = AdaptiveModel::uniform(n_sym, 1).unwrap();
            enc.encode_all(&mut model, &symbols).unwrap();
            enc.finish().unwrap()
        };

        assert_eq!(
            payload, want_payload,
            "kernel payload bytes diverge from oracle for case {name}"
        );
        n += 1;
    }
    assert!(n >= 10, "expected a rich positive set, got {n}");
}

#[test]
fn container_bytes_match_oracle_for_every_positive_case() {
    let doc = golden();
    for case in doc["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let want = oracle_container(case);
        // Decode the oracle-produced container with the Rust decoder.
        let d = decode(&want, &DecodeBudget::default())
            .unwrap_or_else(|e| panic!("oracle container {name} rejected: {e:?}"));
        let expected_symbols = hex_to_bytes(case["symbols_hex"].as_str().unwrap());
        assert_eq!(d.symbols, expected_symbols, "case {name}");
        assert_eq!(d.chunks, case["expected_chunks"].as_u64().unwrap() as usize);
        assert_eq!(d.num_symbols as u64, case["num_symbols"].as_u64().unwrap());
        assert_eq!(
            d.mode == ModelMode::Adaptive,
            case["mode"].as_str().unwrap() == "adaptive"
        );
    }
}

#[test]
fn encoder_step_intervals_match_oracle_traces() {
    let doc = golden();
    for case in doc["cases"].as_array().unwrap() {
        // Skip all-symbols-256 giant traces? No — they are still cheap enough.
        let name = case["name"].as_str().unwrap();
        let symbols = hex_to_bytes(case["symbols_hex"].as_str().unwrap());
        let freqs: Vec<u32> = case["freqs"]
            .as_array()
            .map(|a| a.iter().map(as_u32).collect())
            .unwrap_or_default();
        let n_sym = as_u32(&case["num_symbols"]);

        let mut enc = RangeEncoder::new();
        if case["mode"].as_str().unwrap() == "static" {
            let mut model = StaticModel::new(&freqs).unwrap();
            enc.encode_all(&mut model, &symbols).unwrap();
        } else {
            let mut model = AdaptiveModel::uniform(n_sym, 1).unwrap();
            enc.encode_all(&mut model, &symbols).unwrap();
        }
        let trace = enc.trace();
        let oracle_trace = case["encoder_trace"].as_array().unwrap();
        assert_eq!(trace.len(), oracle_trace.len(), "case {name} length");
        for (rt, ot) in trace.iter().zip(oracle_trace.iter()) {
            assert_eq!(rt.index as u64, ot["index"].as_u64().unwrap());
            assert_eq!(rt.symbol as u64, ot["symbol"].as_u64().unwrap());
            assert_eq!(rt.cum as u64, ot["cum"].as_u64().unwrap(), "case {name} cum");
            assert_eq!(rt.freq as u64, ot["freq"].as_u64().unwrap());
            assert_eq!(rt.low, ot["low"].as_u64().unwrap(), "case {name} low");
            assert_eq!(rt.range as u64, ot["range"].as_u64().unwrap(), "case {name} range");
            let em: Vec<u64> = rt.emitted.iter().map(|&b| b as u64).collect();
            let oe: Vec<u64> = ot["emitted"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap())
                .collect();
            assert_eq!(em, oe, "case {name} emitted bytes");
        }
    }
}

#[test]
fn decoder_step_intervals_match_oracle_traces() {
    let doc = golden();
    for case in doc["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let payload = oracle_payload(case);
        let want_len = case["expected_len"].as_u64().unwrap() as usize;
        let freqs: Vec<u32> = case["freqs"]
            .as_array()
            .map(|a| a.iter().map(as_u32).collect())
            .unwrap_or_default();
        let n_sym = as_u32(&case["num_symbols"]);

        let mut dec = range_codec::range::RangeDecoder::new(&payload).unwrap();
        if case["mode"].as_str().unwrap() == "static" {
            let mut model = StaticModel::new(&freqs).unwrap();
            for _ in 0..want_len {
                dec.decode_symbol(&mut model).unwrap();
            }
        } else {
            let mut model = AdaptiveModel::uniform(n_sym, 1).unwrap();
            for _ in 0..want_len {
                dec.decode_symbol(&mut model).unwrap();
            }
        }
        let trace = dec.trace();
        let oracle_trace = case["decoder_trace"].as_array().unwrap();
        assert_eq!(trace.len(), oracle_trace.len(), "case {name}");
        for (rt, ot) in trace.iter().zip(oracle_trace.iter()) {
            assert_eq!(rt.code as u64, ot["code"].as_u64().unwrap(), "case {name} code");
            assert_eq!(rt.range as u64, ot["range"].as_u64().unwrap(), "case {name} range");
            assert_eq!(rt.scaled as u64, ot["scaled"].as_u64().unwrap(), "case {name} scaled");
            assert_eq!(rt.symbol as u64, ot["symbol"].as_u64().unwrap());
        }
    }
}

#[test]
fn negative_fixtures_return_exact_error_codes() {
    let doc = golden();
    for neg in doc["negatives"].as_array().unwrap() {
        let name = neg["name"].as_str().unwrap();
        let expected = neg["expected_code"].as_str().unwrap();

        let err: CodecError = if neg["kind"].as_str().unwrap() == "decode" {
            let blob = hex_to_bytes(neg["blob_hex"].as_str().unwrap());
            decode(&blob, &DecodeBudget::default())
                .err()
                .unwrap_or_else(|| panic!("negative case {name} should fail"))
        } else {
            // Encoder-side rejection: static model encode.
            let freqs: Vec<u32> = neg["freqs"]
                .as_array()
                .unwrap()
                .iter()
                .map(as_u32)
                .collect();
            let symbols = hex_to_bytes(neg["symbols_hex"].as_str().unwrap());
            let build = StaticModel::new(&freqs).and_then(|mut model| {
                let mut enc = RangeEncoder::new();
                enc.encode_all(&mut model, &symbols)?;
                enc.finish()
            });
            build.err().unwrap_or_else(|| panic!("negative case {name} should fail"))
        };

        assert_eq!(
            err.code(),
            expected,
            "case {name}: expected {expected}, got {err:?}"
        );
    }
}

#[test]
fn reserved_flag_is_indeterminate_everything_else_rejected() {
    let doc = golden();
    for neg in doc["negatives"].as_array().unwrap() {
        if neg["kind"].as_str().unwrap() != "decode" {
            continue;
        }
        let name = neg["name"].as_str().unwrap();
        let blob = hex_to_bytes(neg["blob_hex"].as_str().unwrap());
        let err = decode(&blob, &DecodeBudget::default()).unwrap_err();
        let want_decision = neg
            .get("expected_decision")
            .and_then(|v| v.as_str())
            .unwrap_or("rejected");
        let got = match err.decision() {
            Decision::Rejected => "rejected",
            Decision::Indeterminate => "indeterminate",
        };
        assert_eq!(got, want_decision, "case {name}");
    }
}

#[test]
fn http_status_codes_cover_every_golden_error() {
    // Every golden failure must map to a 4xx client error (not a panic / 500).
    let doc = golden();
    for neg in doc["negatives"].as_array().unwrap() {
        if neg["kind"].as_str().unwrap() != "decode" {
            continue;
        }
        let blob = hex_to_bytes(neg["blob_hex"].as_str().unwrap());
        let err = decode(&blob, &DecodeBudget::default()).unwrap_err();
        let s = err.http_status();
        assert!((400..500).contains(&s), "{:?}: status {s}", neg["name"]);
    }
}
