"""Generate known-answer test vectors with the INDEPENDENT reference code.

Run once to (re)create independent_tests/vectors.json.  The production
package is deliberately not imported here, so the vectors cannot be
generated by the code under test.

    PYTHONPATH=independent_tests:. python independent_tests/generate_vectors.py
"""
from __future__ import annotations

import json
import os

from reference_impl import (  # noqa: E402 - independent path
    EMPTY,
    check,
    insert,
    leaf_hash,
    kbit,
    lookup,
    nid,
)

HERE = os.path.dirname(os.path.abspath(__file__))


def hx(b: bytes) -> str:
    return b.hex()


def build_proof(node, key: bytes, depth: int, steps: list):
    """Walk the reference tuple-tree, collecting siblings (compressed later)."""
    if node[0] == "empty":
        return {"terminal": {"kind": "empty"}, "terminal_depth": depth, "steps": list(steps)}
    if node[0] == "leaf":
        term = {"kind": "leaf", "key": hx(node[1]), "value": node[2].hex()}
        return {"terminal": term, "terminal_depth": depth, "steps": list(steps)}
    b = kbit(key, depth)
    on, off = (node[1], node[2]) if b == 0 else (node[2], node[1])
    steps.append((depth, b, nid(off)))
    return build_proof(on, key, depth + 1, steps)


def compress(steps):
    out = []
    i = 0
    while i < len(steps):
        d, b, sib = steps[i]
        if sib == EMPTY[d + 1]:
            run = 1
            while (
                i + run < len(steps)
                and steps[i + run][0] == d + run
                and steps[i + run][2] == EMPTY[d + run + 1]
            ):
                run += 1
            out.append({"kind": "empty_run", "depth": d, "length": run})
            i += run
        else:
            out.append({"kind": "sibling", "depth": d, "sibling_hash": hx(sib)})
            i += 1
    return out


def make_proof(root_node, root_hex, key, exists):
    p = build_proof(root_node, key, 0, [])
    return {
        "version": "smt-v1",
        "root": root_hex,
        "key": hx(key),
        "exists": exists,
        "terminal_depth": p["terminal_depth"],
        "terminal": p["terminal"],
        "steps": compress(p["steps"]),
    }


def main() -> None:
    k_a = bytes.fromhex("00" * 30 + "ab" + "00")
    k_b = bytes.fromhex("00" * 30 + "ab" + "01")
    k_c = bytes.fromhex("ff" * 32)
    k_abs_sub = bytes.fromhex("00" * 30 + "ab" + "02")
    k_abs_far = bytes.fromhex("11" * 32)
    v_a, v_b, v_c = b"alpha", b"beta", b"gamma"

    # Stages, built functionally in the reference model.
    n0 = ("empty", 0)
    n1 = insert(n0, 0, k_a, v_a)
    n2 = insert(n1, 0, k_b, v_b)
    n3 = insert(n2, 0, k_c, v_c)

    vectors = {
        "spec": "smt-v1",
        "keys": {
            "ka": hx(k_a), "kb": hx(k_b), "kc": hx(k_c),
            "abs_subtree": hx(k_abs_sub), "abs_far": hx(k_abs_far),
        },
        "empty_hashes": {
            "level_0": hx(EMPTY[0]),
            "level_1": hx(EMPTY[1]),
            "level_255": hx(EMPTY[255]),
            "level_256": hx(EMPTY[256]),
        },
        "leaf_hashes": {
            "ka_alpha": hx(leaf_hash(k_a, v_a)),
            "ka_emptyvalue": hx(leaf_hash(k_a, b"")),
            "kb_beta": hx(leaf_hash(k_b, v_b)),
        },
        "roots": {
            "empty": hx(nid(n0)),
            "ka_only": hx(nid(n1)),
            "ka_kb": hx(nid(n2)),
            "ka_kb_kc": hx(nid(n3)),
        },
    }

    # delete ka then reinsert alpha -> exactly the ka+kb root
    n_del = insert(n2, 0, k_a, None)
    n_back = insert(n_del, 0, k_a, v_a)
    vectors["delete_restore"] = {
        "root_after_delete_ka": hx(nid(n_del)),
        "root_after_reinsert_ka": hx(nid(n_back)),
        "restored_matches_ka_kb": nid(n_back) == nid(n2),
        "delete_ka_leaves_kb_root_equals_kaonly_shape_with_kb": lookup(n_del, k_b) == (True, v_b),
    }

    # batch equivalence: unordered insertion permutations all give n3 root
    import itertools
    roots = set()
    for perm in itertools.permutations([(k_a, v_a), (k_b, v_b), (k_c, v_c)]):
        node = ("empty", 0)
        for k, v in perm:
            node = insert(node, 0, k, v)
        roots.add(nid(node))
    vectors["batch"] = {
        "distinct_roots_for_all_orders": len(roots),
        "root": hx(nid(n3)),
        "empty_value_is_distinct_from_absent": leaf_hash(k_a, b"") != leaf_hash(k_a, v_a),
    }

    proofs = {}
    proofs["membership_ka"] = make_proof(n3, nid(n3).hex(), k_a, True)
    proofs["membership_kb"] = make_proof(n3, nid(n3).hex(), k_b, True)
    proofs["membership_kc"] = make_proof(n3, nid(n3).hex(), k_c, True)
    proofs["nonmember_in_subtree"] = make_proof(n3, nid(n3).hex(), k_abs_sub, False)
    proofs["nonmember_far"] = make_proof(n3, nid(n3).hex(), k_abs_far, False)
    proofs["nonmember_empty_tree"] = make_proof(n0, nid(n0).hex(), k_abs_far, False)
    vectors["proofs"] = proofs

    # self-check every generated proof with the independent checker
    for name, p in proofs.items():
        ok, cat, detail = check(p)
        assert ok, (name, cat, detail)
    vectors["all_generated_proofs_check"] = True

    with open(os.path.join(HERE, "vectors.json"), "w", encoding="utf-8") as fh:
        json.dump(vectors, fh, indent=2, ensure_ascii=False)
    print("wrote vectors.json:", os.path.join(HERE, "vectors.json"))
    print("root ka_kb_kc:", vectors["roots"]["ka_kb_kc"])


if __name__ == "__main__":
    main()
