"""CROSS-VALIDATION against known answers generated by the independent code.

These tests deliberately never let the implementation under test provide
the expected answers: expected roots/hashes come from ``vectors.json``
(built by ``reference_impl.py``), and proofs are checked BOTH by the
production verifier and by the independently written checker.
"""
from __future__ import annotations

from smt.crypto import empty_at, hash_leaf
from smt.kernel import MemoryNodeStore, SparseMerkleTree, verify_proof


def test_production_empty_hashes_equal_independent_vectors(vectors):
    assert empty_at(0).hex() == vectors["empty_hashes"]["level_0"]
    assert empty_at(1).hex() == vectors["empty_hashes"]["level_1"]
    assert empty_at(255).hex() == vectors["empty_hashes"]["level_255"]
    assert empty_at(256).hex() == vectors["empty_hashes"]["level_256"]


def test_production_leaf_hashes_equal_independent_vectors(vectors):
    ka = bytes.fromhex(vectors["keys"]["ka"])
    assert hash_leaf(ka, b"alpha").hex() == vectors["leaf_hashes"]["ka_alpha"]
    assert hash_leaf(ka, b"").hex() == vectors["leaf_hashes"]["ka_emptyvalue"]
    # empty value is a distinct commitment from "missing"
    assert vectors["leaf_hashes"]["ka_emptyvalue"] != vectors["leaf_hashes"]["ka_alpha"]


def _build_production(vectors, stage_keys, values):
    store = MemoryNodeStore()
    tree = SparseMerkleTree(store)
    for k in stage_keys:
        tree.update(bytes.fromhex(vectors["keys"][k]), values[k])
    return store, tree


def test_production_roots_match_known_answers_at_every_stage(vectors):
    ka = bytes.fromhex(vectors["keys"]["ka"])
    kb = bytes.fromhex(vectors["keys"]["kb"])
    kc = bytes.fromhex(vectors["keys"]["kc"])

    t0 = SparseMerkleTree(MemoryNodeStore())
    assert t0.root.hex() == vectors["roots"]["empty"]

    s1 = MemoryNodeStore()
    t1 = SparseMerkleTree(s1)
    t1.update(ka, b"alpha")
    assert t1.root.hex() == vectors["roots"]["ka_only"]

    t1.update(kb, b"beta")
    assert t1.root.hex() == vectors["roots"]["ka_kb"]

    t1.update(kc, b"gamma")
    assert t1.root.hex() == vectors["roots"]["ka_kb_kc"]


def test_batch_root_equals_independent_root_and_sequential_root(vectors):
    ka = bytes.fromhex(vectors["keys"]["ka"])
    kb = bytes.fromhex(vectors["keys"]["kb"])
    kc = bytes.fromhex(vectors["keys"]["kc"])
    expected = vectors["roots"]["ka_kb_kc"]

    # batch
    sb = MemoryNodeStore()
    tb = SparseMerkleTree(sb)
    batch_root = tb.update_batch([(kc, b"gamma"), (ka, b"alpha"), (kb, b"beta")])
    assert batch_root.hex() == expected

    # one-by-one, deliberately in a DIFFERENT order than the batch
    ss = MemoryNodeStore()
    ts = SparseMerkleTree(ss)
    ts.update(kb, b"beta")
    ts.update(kc, b"gamma")
    ts.update(ka, b"alpha")
    assert ts.root.hex() == expected
    assert ts.root == batch_root
    assert vectors["batch"]["distinct_roots_for_all_orders"] == 1


def test_delete_restore_matches_independent_vectors(vectors):
    # The vector records delete/restore of ka against the {ka,kb} tree.
    ka = bytes.fromhex(vectors["keys"]["ka"])
    kb = bytes.fromhex(vectors["keys"]["kb"])
    s = MemoryNodeStore()
    t = SparseMerkleTree(s)
    t.update_batch([(ka, b"alpha"), (kb, b"beta")])

    t.update(ka, None)
    assert t.root.hex() == vectors["delete_restore"]["root_after_delete_ka"]
    t.update(ka, b"alpha")
    assert t.root.hex() == vectors["delete_restore"]["root_after_reinsert_ka"]
    assert t.root.hex() == vectors["roots"]["ka_kb"]


def test_every_proof_passes_both_verifiers(vectors, ref_check):
    for name, proof in vectors["proofs"].items():
        # independent checker accepts its own well-formed vector
        ok, cat, detail = ref_check(proof)
        assert ok, f"{name}: independent checker rejected {cat}: {detail}"
        # production verifier must agree
        result = verify_proof(proof)
        assert result.ok, f"{name}: production rejected {result.verdict.value}: {result.reason}"


def test_production_issued_proofs_pass_independent_checker(vectors, ref_check):
    """The reverse direction: proofs ISSUED by production must be accepted by
    the independent checker (so production can't emit a self-consistent but
    spec-violating proof that only its own verifier accepts)."""
    ka = bytes.fromhex(vectors["keys"]["ka"])
    kb = bytes.fromhex(vectors["keys"]["kb"])
    kc = bytes.fromhex(vectors["keys"]["kc"])
    abs_sub = bytes.fromhex(vectors["keys"]["abs_subtree"])
    abs_far = bytes.fromhex(vectors["keys"]["abs_far"])

    s = MemoryNodeStore()
    t = SparseMerkleTree(s)
    t.update_batch([(ka, b"alpha"), (kb, b"beta"), (kc, b"gamma")])

    issued = {
        "membership_ka": (t.prove(ka).to_dict(), True),
        "membership_kb": (t.prove(kb).to_dict(), True),
        "membership_kc": (t.prove(kc).to_dict(), True),
        "nonmember_abs_sub": (t.prove(abs_sub).to_dict(), False),
        "nonmember_abs_far": (t.prove(abs_far).to_dict(), False),
    }
    for name, (proof, exists) in issued.items():
        assert proof["exists"] is exists
        ok, cat, detail = ref_check(proof)
        assert ok, f"{name}: independent checker rejected production proof: {cat}: {detail}"


def test_independent_checker_flags_tampered_compressed_run(vectors, ref_check):
    p = {k: v for k, v in vectors["proofs"]["membership_kb"].items()}
    p["steps"] = [dict(e) for e in p["steps"]]
    run = next(e for e in p["steps"] if e["kind"] == "empty_run")
    run["length"] += 1  # now covers beyond the terminal depth
    ok, cat, _ = ref_check(p)
    assert not ok and cat == "step_invalid"


def test_independent_checker_flags_root_and_value_tamper(vectors, ref_check):
    p = vectors["proofs"]["membership_kc"]
    ok, cat, _ = ref_check({**p, "root": "00" * 32})
    assert not ok and cat == "root_mismatch"

    p2 = {**p, "terminal": {**p["terminal"], "value": (b"gamma" + b"!").hex()}}
    ok, cat, _ = ref_check(p2)
    assert not ok and cat == "root_mismatch"


def test_independent_checker_flags_key_mismatch(vectors, ref_check):
    p = vectors["proofs"]["membership_kc"]
    bad = {**p, "terminal": {**p["terminal"], "key": vectors["keys"]["ka"]}}
    ok, cat, _ = ref_check(bad)
    assert not ok and cat == "key_mismatch"


def test_both_verifiers_reject_garbage(vectors, ref_check):
    ok, cat, _ = ref_check({"version": "smt-v1"})
    assert not ok and cat == "malformed"
    assert verify_proof({"version": "smt-v1"}).verdict.value == "malformed"
