//! `hbs-testkit`: an independent reference oracle and deterministic
//! synthetic fixtures for verifying `hbs-core` / `hbs-format`.
//!
//! The oracle is a plain [`std::collections::BTreeSet<u32>`] wrapper. It
//! deliberately shares **no** algorithmic code with the system under test:
//! no containers, no rank/select routines, no serialiser. Every expected
//! answer (membership, cardinality, rank, select, union, intersection,
//! difference) is produced by ordinary sorted-set operations on the host
//! standard library, so the test answers cannot be generated by the code
//! they are checking.
pub mod fixtures;
pub mod generator;
pub mod oracle;
pub mod props;

pub use generator::{Distribution, Rng, Sample, sample};
pub use oracle::ReferenceSet;
