//! Shared synthetic fixtures for integration tests.
//!
//! These formulas and their expected properties are written out by hand (or
//! computed by the independent oracle), never generated by the BDD kernel.

#![allow(dead_code)]

/// Variable order used across the small exhaustive tests.
pub const ORDER3: [&str; 3] = ["a", "b", "c"];

/// A handful of non-trivial formulas over `a,b,c`.
pub const FORMULAS3: [&str; 8] = [
    "true",
    "false",
    "a",
    "!a",
    "(a && b) || c",
    "(a || b) && c",
    "a ^ b ^ c",
    "(a -> b) <-> (!a || b)",
];

/// Equivalent surface pairs (same Boolean function, different syntax).
pub const EQUIV_PAIRS: [(&str, &str); 4] = [
    ("a -> b", "!a || b"),
    ("a <-> b", "(a && b) || (!a && !b)"),
    ("!(a && b)", "!a || !b"),
    ("a ^ b", "(a || b) && !(a && b)"),
];

/// Definitely non-equivalent pairs with a known distinguishing assignment.
pub const NON_EQUIV_PAIRS: [(&str, &str); 3] = [
    ("a && b", "a || b"),
    ("a -> b", "b -> a"),
    ("a ^ b", "a <-> b"),
];

/// Rename fixtures for the left/right manager tests.
pub const RENAME_LEFT_ORDER: [&str; 2] = ["x", "y"];
pub const RENAME_RIGHT_ORDER: [&str; 2] = ["p", "q"];
