//! Independent test oracle.
//!
//! Nothing in here calls the Bellman–Ford kernel or the service solver.
//! Feasibility is decided by exhaustive enumeration over a small bounded
//! integer box, and assignments/cycles are checked by direct constraint
//! arithmetic. This gives the tests expected results generated by a
//! fundamentally different method than the code under test.

use std::collections::{BTreeMap, BTreeSet};

use diffconstraints::model::Constraint;

/// Brute-force feasibility: enumerate every assignment with each variable in
/// `[-range, range]` and test constraints one by one.
///
/// Intended only for tiny hand-built instances. It returns:
/// * `Some(assignment)` — the first satisfying assignment found;
/// * `None` — provably infeasible within the box.
///
/// Callers must pick a range large enough that a feasible instance has a
/// witness inside the box. For difference constraints with max absolute
/// bound `B`, a feasible instance always has a witness with all values in
/// `[-B, B]` (shift the minimal-potential solution), so `range = B` suffices.
pub fn brute_feasible(constraints: &[Constraint], range: i64) -> Option<BTreeMap<String, i64>> {
    let mut vars: BTreeSet<String> = BTreeSet::new();
    for c in constraints {
        vars.insert(c.lhs.clone());
        vars.insert(c.rhs.clone());
    }
    let vars: Vec<String> = vars.into_iter().collect();
    if vars.is_empty() {
        return Some(BTreeMap::new());
    }
    let width = (2 * range + 1) as u128;
    if width.saturating_pow(vars.len() as u32) > 2_000_000 {
        panic!("brute_feasible box too large: {} vars x range {range}", vars.len());
    }
    let mut current: Vec<i64> = vec![-range; vars.len()];
    loop {
        let assign: BTreeMap<String, i64> = vars
            .iter()
            .cloned()
            .zip(current.iter().copied())
            .collect();
        if constraints
            .iter()
            .all(|c| direct_satisfied(c, &assign) == Some(true))
        {
            return Some(assign);
        }
        // increment mixed-radix counter
        let mut k = 0;
        loop {
            if k == vars.len() {
                return None; // exhausted
            }
            if current[k] < range {
                current[k] += 1;
                break;
            }
            current[k] = -range;
            k += 1;
        }
    }
}

/// Direct check of one constraint using checked arithmetic.
pub fn direct_satisfied(c: &Constraint, a: &BTreeMap<String, i64>) -> Option<bool> {
    let x = *a.get(&c.lhs)?;
    let y = *a.get(&c.rhs)?;
    let d = x.checked_sub(y)?;
    Some(d <= c.bound)
}

/// Independent cycle weight + closure check, tracking component ids by
/// following the rhs->lhs edges directly from constraint records.
pub fn direct_cycle_check(constraints: &[Constraint], ids: &[String]) -> CycleResult {
    let by_id: BTreeMap<&str, &Constraint> = constraints.iter().map(|c| (c.id.as_str(), c)).collect();
    if ids.is_empty() {
        return CycleResult::Invalid("empty cycle");
    }
    let mut seen = BTreeSet::new();
    let mut weight: i128 = 0;
    let mut start_rhs: Option<&str> = None;
    let mut prev_lhs: Option<&str> = None;
    for id in ids {
        if !seen.insert(id.as_str()) {
            return CycleResult::Invalid("duplicate constraint id in cycle");
        }
        let c = match by_id.get(id.as_str()) {
            Some(c) => *c,
            None => return CycleResult::Invalid("unknown constraint id in cycle"),
        };
        if start_rhs.is_none() {
            start_rhs = Some(c.rhs.as_str());
        }
        if let Some(p) = prev_lhs {
            if p != c.rhs {
                return CycleResult::Invalid("edges do not chain");
            }
        }
        weight = weight.saturating_add(c.bound as i128);
        prev_lhs = Some(c.lhs.as_str());
    }
    if prev_lhs != start_rhs {
        return CycleResult::Invalid("walk does not close");
    }
    if weight < 0 {
        CycleResult::Negative(weight)
    } else {
        CycleResult::Invalid("cycle weight is not strictly negative")
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum CycleResult {
    Negative(i128),
    Invalid(&'static str),
}

/// Verify every constraint individually against an assignment and return
/// ids of violations — a second implementation style vs. the crate's
/// `verify_assignment` (returns rich records).
pub fn violation_ids(
    constraints: &[Constraint],
    a: &BTreeMap<String, i64>,
) -> Vec<String> {
    constraints
        .iter()
        .filter(|c| direct_satisfied(c, a) != Some(true))
        .map(|c| c.id.clone())
        .collect()
}
