//! Determinism of the equal-frequency tie-break rule and of canonical code
//! assignment. Expected tables here are hand-derived, not generated by the
//! codec; the Python fixture provides a second implementation's agreement.

use std::fs;
use std::path::Path;

use huff_core::container::HEADER_LEN;
use huff_core::huff::Codebook;

const FRAME_OH: usize = 8;
const PAYLOAD_HEAD: usize = 12;
const BODY_OFF: usize = PAYLOAD_HEAD + 256;

fn frequencies(pairs: &[(u8, u64)]) -> [u64; 256] {
    let mut f = [0u64; 256];
    for &(s, w) in pairs {
        f[s as usize] = w;
    }
    f
}

#[test]
fn hand_derived_fibonacci_weights() {
    // Frequencies A=5, B=2, C=2, D=1 (leaf ids assigned in symbol order).
    // Pop sequence under the (weight, height, id) tie-break:
    //   (1,D,3)+(2,B,1) -> n4 (w3,h1);
    //   (2,C,2)+n4      -> n5 (w5,h2);
    //   (5,A,0)+n5      -> root.
    // Depths: A=1, C=2, B=3, D=3.
    // Canonical order by (length, symbol): A='0', C='10', B='110', D='111'.
    let f = frequencies(&[(b'A', 5), (b'B', 2), (b'C', 2), (b'D', 1)]);
    let cb = Codebook::from_frequencies(&f).unwrap();
    assert_eq!(cb.lengths[b'A' as usize], 1);
    assert_eq!(cb.lengths[b'C' as usize], 2);
    assert_eq!(cb.lengths[b'B' as usize], 3);
    assert_eq!(cb.lengths[b'D' as usize], 3);

    assert_eq!((cb.codes[b'A' as usize], 1), (0b0, 1));
    assert_eq!((cb.codes[b'C' as usize], 2), (0b10, 2));
    assert_eq!((cb.codes[b'B' as usize], 3), (0b110, 3));
    assert_eq!((cb.codes[b'D' as usize], 3), (0b111, 3));
}

#[test]
fn equal_weights_are_tied_by_symbol_order() {
    // Four symbols equal weight: depth 2 everywhere, codes assigned in
    // ascending symbol order regardless of insertion order.
    let f = frequencies(&[(b'd', 4), (b'a', 4), (b'c', 4), (b'b', 4)]);
    let cb = Codebook::from_frequencies(&f).unwrap();
    assert_eq!((cb.codes[b'a' as usize], cb.lengths[b'a' as usize]), (0b00, 2));
    assert_eq!((cb.codes[b'b' as usize], cb.lengths[b'b' as usize]), (0b01, 2));
    assert_eq!((cb.codes[b'c' as usize], cb.lengths[b'c' as usize]), (0b10, 2));
    assert_eq!((cb.codes[b'd' as usize], cb.lengths[b'd' as usize]), (0b11, 2));
}

#[test]
fn construction_is_deterministic_across_runs() {
    // The same frequency table must always yield identical bytes; we rebuild
    // several times and compare every field.
    let f = frequencies(&[
        (0, 100), (1, 60), (2, 40), (5, 30), (9, 20), (200, 10), (255, 5),
    ]);
    let a = Codebook::from_frequencies(&f).unwrap();
    for _ in 0..10 {
        let b = Codebook::from_frequencies(&f).unwrap();
        assert_eq!(a.lengths, b.lengths);
        assert_eq!(a.codes, b.codes);
        assert_eq!(a.present, b.present);
    }
}

#[test]
fn python_generator_agrees_on_uniform_256_symbol_table() {
    // all_bytes.hfc encodes bytes 0..255, each with frequency 1: every code
    // must be length 8 and the canonical code of symbol s must equal s.
    // Therefore the first block's bitstream body must be exactly 0..=255.
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join("all_bytes.hfc");
    let blob = fs::read(path).expect("run `python3 tools/gen_golden.py` first");
    let payload_len = u32::from_le_bytes(blob[HEADER_LEN..HEADER_LEN + 4].try_into().unwrap())
        as usize;
    let payload = &blob[HEADER_LEN + FRAME_OH..HEADER_LEN + FRAME_OH + payload_len];
    let symbol_count = u16::from_le_bytes(payload[8..10].try_into().unwrap());
    assert_eq!(symbol_count, 256);

    let lengths = &payload[PAYLOAD_HEAD..BODY_OFF];
    assert!(lengths.iter().all(|&l| l == 8), "every symbol must use 8 bits");

    let body = &payload[BODY_OFF..];
    let expected: Vec<u8> = (0u16..256).map(|b| b as u8).collect();
    assert_eq!(body, expected, "Python and Rust canonical tables disagree");
}
