"""Command line front end.

Examples
--------
Scan a snapshot with the bundled packs::

    python -m secretscan.cli scan /path/to/repo --workspace .workspaces/demo

Baseline fingerprints are generated by the independent stdlib-only tool::

    python tools/make_baseline.py --pepper-id --value ghp_... >> config/baselines/x.toml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import audit
from .baseline import BaselineError, load_baseline
from .config import ConfigError, load_rule_pack, load_scope_pack, load_settings
from .security import Fingerprinter
from . import service, state

DEFAULT_RULES = Path("config/rules/default.toml")
DEFAULT_SCOPE = Path("config/scopes/default.toml")
DEFAULT_DB = Path(".secretscan/workspace.db")


def _print_human_report(report: service.ScanReport) -> None:
    print(f"scan #{report.scan_id}  request={report.request_id}  "
          f"actor={report.actor_id}")
    print(f"root: {report.root}")
    print(f"versions: rules={report.versions['rule_pack']} "
          f"scope={report.versions['scope_pack']} "
          f"pepper={report.versions['fingerprint_pepper_id']}")
    print(f"started: {report.started_at}  finished: {report.finished_at}")
    print("counts:", " ".join(f"{k}={v}" for k, v in report.counts.items()))
    labels = {
        service.STATE_NEW: "NEW candidates",
        service.STATE_OPEN: "still open",
        service.STATE_MOVED: "MOVED (same content, new path)",
        service.STATE_KNOWN_FIXED: "KNOWN-FIXED (content replaced at old path)",
        service.STATE_UNCERTAIN_REMOVAL:
            "UNCERTAIN removals (path gone/ignored — can't conclude fixed)",
        service.STATE_BASELINE_EXEMPT: "baseline exempt",
    }
    for state_name, title in labels.items():
        views = report.findings.get(state_name, [])
        print(f"\n== {title}: {len(views)} ==")
        for view in views:
            print(f"  [{view.rule_id}] confidence={view.confidence} "
                  f"mask={view.mask}")
            for occ in view.occurrences:
                where = occ["relpath"]
                if occ["line"] is not None:
                    where += f":{occ['line']}:{occ['column']}"
                else:
                    where += f":byte{occ['column']}"
                print(f"      {where} ({occ['content_media']}) "
                      f"H={occ['entropy']} evidence={occ['evidence']!r}")
            if view.resolution:
                r = view.resolution
                print(f"      resolution={r['reason_code']}: {r['reason']}")
    if report.unscanned:
        print(f"\n-- NOT SCANNED ({len(report.unscanned)}) --")
        for item in report.unscanned:
            print(f"   {item['relpath']} ({item['reason_code']}: {item['reason']})")
    if report.failures:
        print(f"\n-- FAILURES ({len(report.failures)}) --")
        for item in report.failures:
            print(f"   {item['relpath']} ({item['reason_code']}: {item['reason']})")
    print(f"\n{report.disclaimer}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="secretscan",
        description="Offline secret-candidate scanner (structure + entropy).")
    sub = parser.add_subparsers(dest="command", required=True)

    scan = sub.add_parser("scan", help="scan a repository snapshot")
    scan.add_argument("root", help="absolute or relative path to the snapshot")
    scan.add_argument("--rules", default=str(DEFAULT_RULES))
    scan.add_argument("--scope", default=str(DEFAULT_SCOPE))
    scan.add_argument("--workspace", default=str(DEFAULT_DB),
                      help="isolated SQLite workspace database path")
    scan.add_argument("--baseline", default=None)
    scan.add_argument("--log-file", default=None)
    scan.add_argument("--request-id", default=None)
    scan.add_argument("--actor-id", default=None)
    scan.add_argument("--json", action="store_true",
                      help="emit the full report JSON instead of text")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        rules = load_rule_pack(args.rules)
        scope = load_scope_pack(args.scope)
        settings = load_settings(args.workspace, log_file=args.log_file)
        fingerprinter = Fingerprinter(settings.fingerprint_pepper)
        baseline = None
        if args.baseline:
            baseline = load_baseline(args.baseline, fingerprinter)
    except (ConfigError, BaselineError) as exc:
        print(f"configuration error: {exc}", file=sys.stderr)
        return 2

    logger, _ = audit.configure_logging(settings.log_file)
    if baseline is not None:
        audit.audit_event(logger, action=audit.ACT_BASELINE_LOADED,
                          target_type="baseline", target=str(baseline.path),
                          entries=len(baseline.entries),
                          pepper_id=baseline.pepper_id)
    conn = state.connect(settings.workspace_db)
    try:
        svc = service.ScanService(
            conn, rules, scope, fingerprinter, logger, baseline)
        ctx = audit.RequestContext.create(args.request_id, args.actor_id)
        report = svc.run_scan(Path(args.root), ctx)
    except (PermissionError, NotADirectoryError) as exc:
        print(f"scan rejected: {exc}", file=sys.stderr)
        return 2
    finally:
        conn.close()

    if args.json:
        print(report.to_json())
    else:
        _print_human_report(report)
    # Exit 0 even with candidates: candidates are not errors. Unscanned files
    # are reported, and humans decide.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
