package scheduler_test

import (
	"fmt"
	"math/rand"
	"testing"

	"placer/internal/model"
	"placer/internal/scheduler"
	"placer/test/oracle"
)

// TestFuzz_DifferentialAgainstOracle generates many random small clusters
// and asserts the production scheduler and the independent oracle agree on
// feasibility, optimum assignment and objective. This directly satisfies
// "reference answers must not all be generated by the core under test".
func TestFuzz_DifferentialAgainstOracle(t *testing.T) {
	const iterations = 400
	for seed := int64(0); seed < iterations; seed++ {
		rng := rand.New(rand.NewSource(seed))
		tc := randomCase(rng)
		req := model.PlanRequest{
			RunID: fmt.Sprintf("run-fuzz-%d", seed),
			Nodes: tc.nodes, Instances: tc.instances, Bound: tc.bound,
			Policy:  model.Policy{Groups: tc.rules},
			Options: model.PlanOptions{MaxNodesForExact: 8},
		}
		got, err := schedulerPlanSafe(req)
		if err != nil {
			// Oracle only covers valid requests; skip structural edge cases
			// but never accept a planner panic/error on well-formed input.
			if reqWellFormed(req) {
				t.Fatalf("seed %d: unexpected planner error: %v\nnodes=%+v\ninst=%+v",
					seed, err, tc.nodes, tc.instances)
			}
			continue
		}

		in := oracle.Input{
			Nodes: tc.nodes, Instances: tc.instances,
			Bound: tc.bound, Rules: tc.rules, Key: "zone",
		}
		want := in.Solve()

		if got.Feasible != want.Feasible {
			t.Fatalf("seed %d: feasibility scheduler=%v oracle=%v\nnodes=%+v\ninst=%+v\nbound=%+v",
				seed, got.Feasible, want.Feasible, tc.nodes, tc.instances, tc.bound)
		}
		if !want.Feasible {
			// Intrinsic reject codes must agree when the oracle found one.
			codes := conflictCodes(got)
			for id, code := range want.IntrinsicReject {
				if codes[id] != code {
					t.Fatalf("seed %d: instance %s code scheduler=%q oracle=%q",
						seed, id, codes[id], code)
				}
			}
			continue
		}
		if *got.Objective != want.Objective {
			t.Fatalf("seed %d: objective scheduler=%+v oracle=%+v best=%v\nnodes=%+v\ninst=%+v",
				seed, *got.Objective, want.Objective, want.Best, tc.nodes, tc.instances)
		}
		for _, d := range got.Decisions {
			if want.Best[d.InstanceID] != d.NodeID {
				t.Fatalf("seed %d: %s scheduler=%q oracle=%q",
					seed, d.InstanceID, d.NodeID, want.Best[d.InstanceID])
			}
		}
	}
}

func schedulerPlanSafe(req model.PlanRequest) (res *model.PlanResult, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("planner panic: %v", r)
		}
	}()
	return planReq(req)
}

func planReq(req model.PlanRequest) (*model.PlanResult, error) {
	return scheduler.Plan(req)
}

type fuzzCase struct {
	nodes     []model.Node
	instances []model.Instance
	bound     []model.Binding
	rules     []model.GroupRule
}

func randomCase(rng *rand.Rand) fuzzCase {
	zoneNames := []string{"za", "zb", "zc"}
	nNodes := 1 + rng.Intn(5)
	var nodes []model.Node
	for k := 0; k < nNodes; k++ {
		n := model.Node{
			ID:     fmt.Sprintf("n%02d", k),
			Zone:   zoneNames[rng.Intn(len(zoneNames))],
			Region: "r",
			Status: model.NodeReady,
			Capacity: model.Resources{
				MilliCPU: int64(1000 + rng.Intn(3000)),
				Memory:   1e10, Storage: 1e11,
			},
		}
		if rng.Intn(5) == 0 {
			n.Status = model.NodeDisabled
		}
		if rng.Intn(6) == 0 {
			n.Taints = []model.Taint{{Key: "dedicated", Value: "x",
				Effect: model.TaintNoSchedule}}
		}
		nodes = append(nodes, n)
	}

	var rules []model.GroupRule
	if rng.Intn(2) == 0 {
		rules = append(rules, model.GroupRule{
			Group: "app", Mode: model.ModeHard, TopologyKey: "zone"})
	} else if rng.Intn(2) == 0 {
		rules = append(rules, model.GroupRule{
			Group: "app", Mode: model.ModeSoft, TopologyKey: "zone"})
	}

	nInst := 1 + rng.Intn(5)
	var instances []model.Instance
	for k := 0; k < nInst; k++ {
		in := model.Instance{
			ID:    fmt.Sprintf("i%02d", k),
			State: model.StatePending,
			Request: model.Resources{
				MilliCPU: int64(200 + rng.Intn(2000)),
				Memory:   1e8, Storage: 1e8,
			},
		}
		if rng.Intn(2) == 0 {
			in.Groups = map[string]string{"app": fmt.Sprintf("g%d", rng.Intn(3))}
		}
		if rng.Intn(7) == 0 {
			in.Tolerations = []model.Toleration{{Key: "dedicated"}}
		}
		instances = append(instances, in)
	}

	// Sometimes seed bound occupants to create skew.
	var bound []model.Binding
	if rng.Intn(2) == 0 {
		for k := 0; k < rng.Intn(3); k++ {
			node := nodes[rng.Intn(len(nodes))]
			g := map[string]string(nil)
			if rng.Intn(2) == 0 {
				g = map[string]string{"app": fmt.Sprintf("g%d", rng.Intn(3))}
			}
			bound = append(bound, model.Binding{
				InstanceID: fmt.Sprintf("b%02d", k), NodeID: node.ID,
				Request: model.Resources{MilliCPU: int64(100 + rng.Intn(500)),
					Memory: 1, Storage: 1},
				Groups: g,
			})
		}
	}
	return fuzzCase{nodes, instances, bound, rules}
}

func reqWellFormed(req model.PlanRequest) bool {
	if len(req.Nodes) == 0 || len(req.Instances) == 0 {
		return false
	}
	return true
}
