// Package scheduler_test contains black-box tests for the scheduler.
//
// IMPORTANT: the independent oracle below is a separate brute-force
// implementation of hard feasibility and of the documented soft objective.
// Test expected answers are NOT generated by the code under test: per-node
// reject judgments come from this independent pass, concrete small cases
// additionally carry hand-computed node expectations, and JSON fixtures
// encode expected failure categories authored directly.
package scheduler_test

import (
	"sort"

	"opp284/placement/internal/model"
	"opp284/placement/internal/scheduler"
)

// oracleCluster is a flat representation used only by the independent oracle.
type oracleCluster struct {
	nodes        []model.Node
	running      []scheduler.RunningInstance
	groupOf      map[string][]model.Group // intent id -> groups
	declared     []string
	includeEmpty bool
}

func newOracleCluster(snap scheduler.Snapshot, includeEmpty bool) *oracleCluster {
	c := &oracleCluster{
		nodes:        append([]model.Node(nil), snap.Nodes...),
		running:      append([]scheduler.RunningInstance(nil), snap.Running...),
		groupOf:      map[string][]model.Group{},
		declared:     append([]string(nil), snap.DeclaredZones...),
		includeEmpty: includeEmpty,
	}
	for _, g := range snap.Groups {
		for _, m := range g.MemberIDs {
			c.groupOf[m] = append(c.groupOf[m], g)
		}
	}
	sort.Slice(c.nodes, func(i, j int) bool { return c.nodes[i].ID < c.nodes[j].ID })
	return c
}

func (c *oracleCluster) node(id string) (model.Node, bool) {
	for _, n := range c.nodes {
		if n.ID == id {
			return n, true
		}
	}
	return model.Node{}, false
}

func (c *oracleCluster) runningLookup(id string) (scheduler.RunningInstance, bool) {
	for _, r := range c.running {
		if r.ID == id {
			return r, true
		}
	}
	return scheduler.RunningInstance{}, false
}

// reject independently evaluates whether intent may be placed on node given a
// full tentative assignment (instance id -> node id). It returns the strongest
// reject code, or "" when legal. This duplicates the documented rules without
// importing any scheduler internal.
func (c *oracleCluster) reject(in model.Intent, n model.Node, intents []model.Intent,
	assign map[string]string, evicted map[string]bool, blockedNode string) model.ReasonKind {
	if !n.Eligible {
		return model.ReasonNoEligibleNode
	}
	if in.RequiredZone != "" && n.Zone != in.RequiredZone {
		return model.ReasonZoneMismatch
	}
	if !in.NodeSelector.Matches(n.Labels) {
		return model.ReasonSelectorNoMatch
	}
	// Capacity: capacity - node.used - running(not evicted) - assigned others
	// - this intent itself.
	used := n.Used.Clone()
	for _, r := range c.running {
		if r.NodeID == n.ID && !evicted[r.ID] {
			used = used.Add(r.Request)
		}
	}
	reqByID := map[string]model.Resources{}
	for _, x := range intents {
		reqByID[x.ID] = x.Request
	}
	for iid, nid := range assign {
		if nid == n.ID {
			used = used.Add(reqByID[iid])
		}
	}
	used = used.Add(in.Request)
	if !n.Capacity.Fits(used) {
		return model.ReasonInsufficientResource
	}
	if n.ID == blockedNode {
		return model.ReasonRollingBlocked
	}
	for _, g := range c.groupOf[in.ID] {
		memberNodes := map[string]bool{}
		for _, m := range g.MemberIDs {
			if r, ok := c.runningLookup(m); ok && !evicted[r.ID] {
				memberNodes[r.NodeID] = true
			}
			if nid, ok := assign[m]; ok {
				memberNodes[nid] = true
			}
		}
		switch g.Mode {
		case model.GroupAffinity:
			if len(memberNodes) > 0 && !memberNodes[n.ID] {
				return model.ReasonAffinityConflict
			}
		case model.GroupAntiAffinity:
			if memberNodes[n.ID] {
				return model.ReasonAntiAffinityConflict
			}
		}
	}
	return ""
}

// feasibleAssignments enumerates every full assignment passing ALL hard
// constraints independently.
func (c *oracleCluster) feasibleAssignments(intents []model.Intent, evicted map[string]bool, blocked map[string]string) []map[string]string {
	var results []map[string]string
	var rec func(i int, assign map[string]string)
	rec = func(i int, assign map[string]string) {
		if i == len(intents) {
			cp := map[string]string{}
			for k, v := range assign {
				cp[k] = v
			}
			results = append(results, cp)
			return
		}
		in := intents[i]
		for _, n := range c.nodes {
			if code := c.reject(in, n, intents, assign, evicted, blocked[in.ID]); code == "" {
				assign[in.ID] = n.ID
				rec(i+1, assign)
				delete(assign, in.ID)
			}
		}
	}
	rec(0, map[string]string{})
	return results
}

// oracleScore independently computes the documented soft objective vector:
// (zone-count range, variance*1000, max node utilization milli). The
// implementation's signature tiebreak is not replicated; tests only assert
// that the chosen assignment belongs to the set tied on these three values.
type oracleScore struct {
	rng      int
	variance int64
	maxUtil  int64
}

func (c *oracleCluster) score(intents []model.Intent, assign map[string]string) oracleScore {
	zones := map[string]bool{}
	for _, n := range c.nodes {
		if n.Eligible {
			zones[n.Zone] = true
		}
	}
	if c.includeEmpty {
		for _, z := range c.declared {
			hasNode := false
			for _, n := range c.nodes {
				if n.Zone == z {
					hasNode = true
				}
			}
			if !hasNode {
				zones[z] = true
			}
		}
	}
	load := map[string]int{}
	for _, in := range intents {
		if n, ok := c.node(assign[in.ID]); ok {
			load[n.Zone]++
		}
	}
	vals := make([]int, 0, len(zones))
	for z := range zones {
		vals = append(vals, load[z])
	}
	sort.Ints(vals)
	lo, hi := 0, 0
	if len(vals) > 0 {
		lo, hi = vals[0], vals[len(vals)-1]
	}
	sum := 0
	for _, v := range vals {
		sum += v
	}
	mean := 0.0
	if len(vals) > 0 {
		mean = float64(sum) / float64(len(vals))
	}
	var variance int64
	for _, v := range vals {
		d := float64(v) - mean
		variance += int64(d*d*1000 + 0.5)
	}
	nodeUsed := map[string]model.Resources{}
	for _, n := range c.nodes {
		nodeUsed[n.ID] = n.Used.Clone()
	}
	for _, r := range c.running {
		nodeUsed[r.NodeID] = nodeUsed[r.NodeID].Add(r.Request)
	}
	for _, in := range intents {
		nodeUsed[assign[in.ID]] = nodeUsed[assign[in.ID]].Add(in.Request)
	}
	var maxUtil int64
	for _, n := range c.nodes {
		for dim, capV := range n.Capacity {
			if capV > 0 {
				if u := nodeUsed[n.ID][dim] * 1000 / capV; u > maxUtil {
					maxUtil = u
				}
			}
		}
	}
	return oracleScore{rng: hi - lo, variance: variance, maxUtil: maxUtil}
}

func scoreLess(a, b oracleScore) bool {
	if a.rng != b.rng {
		return a.rng < b.rng
	}
	if a.variance != b.variance {
		return a.variance < b.variance
	}
	return a.maxUtil < b.maxUtil
}

// bestAssignment returns the best oracle score and every assignment tied on
// it. The implementation must (a) be feasible, and (b) be among the tied set.
func (c *oracleCluster) bestAssignment(intents []model.Intent, evicted map[string]bool,
	blocked map[string]string) (oracleScore, []map[string]string) {
	all := c.feasibleAssignments(intents, evicted, blocked)
	if len(all) == 0 {
		return oracleScore{}, nil
	}
	best := c.score(intents, all[0])
	for i := 1; i < len(all); i++ {
		if s := c.score(intents, all[i]); scoreLess(s, best) {
			best = s
		}
	}
	var tied []map[string]string
	for _, a := range all {
		if c.score(intents, a) == best {
			tied = append(tied, a)
		}
	}
	return best, tied
}
