#!/usr/bin/env python3
"""Independent reference implementation of the mph-service hash spec.

This file is *not* generated by the Rust kernel: it re-implements the
documented spec in scripts/gen_reference.py and emits expected vectors
that the Rust test suite asserts against. If the kernel drifts from the
spec, the reference-vector tests fail.

Spec (all arithmetic little-endian, u64 wrapping):

    mix64(x)                 splitmix64 finalizer
    keyed64(bytes, domain)   chunked splitmix mix (see below)
    vertex_hash(seed,i,key)  keyed64(key, seed ^ mix64(GAMMA + i))
    fingerprint(seed,key)    keyed64(key, seed ^ FP_DOMAIN)

    keyed64:
      h = mix64(domain ^ (len(bytes) << 56) ^ 0xD1B54A2E7E6D73B3)
      for every 8-byte little-endian chunk:
          h = mix64(h ^ mix64(chunk + GAMMA))
      remaining bytes (as LE tail):
          h = mix64(h ^ mix64(tail + 0x9E3779B9))
      return mix64(h)
    attempt_seed(base,k)     base + k            (wrapping)
    m                        max(4, ceil(1.23 n))
    edges must be 3 pairwise-distinct vertices, else attempt retries
    peel: degree-1 queue; stack records (edge, critical vertex)
    assign in reverse: slots are handed out monotonically 0..n-1 and
        g[critical] = (slot - g[other1] - g[other2]) mod n

Run:  python3 scripts/gen_reference.py
Writes tests/fixtures/reference_vectors.json
"""

import json
import os

FNV_PRIME = 0x00000100000001B3  # retained for reference; no longer used
MASK = 0xFFFFFFFFFFFFFFFF
GAMMA = 0x9E3779B97F4A7C15
FP_DOMAIN = 0xF9B0DC5E3A71D2C3
LOAD_FACTOR = 1.23
MID_FACTOR = 1.5
MID_SET_MAX = 2048
SMALL_SET_MAX = 64
MIN_VERTICES = 3


def mix64(x):
    x &= MASK
    x ^= x >> 30
    x = (x * 0xBF58476D1CE4E5B9) & MASK
    x ^= x >> 27
    x = (x * 0x94D049BB133111EB) & MASK
    x ^= x >> 31
    return x & MASK


def keyed64(data, domain):
    h = mix64((domain ^ ((len(data) << 56) & MASK)
               ^ 0xD1B54A2E7E6D73B3) & MASK)
    i = 0
    while i + 8 <= len(data):
        chunk = int.from_bytes(data[i:i + 8], "little")
        h = mix64(h ^ mix64((chunk + GAMMA) & MASK))
        i += 8
    if i < len(data):
        tail = int.from_bytes(data[i:], "little")
        h = mix64(h ^ mix64((tail + 0x9E3779B9) & MASK))
    return mix64(h)


def vertex_hash(seed, i, key):
    domain = seed ^ mix64((GAMMA + i) & MASK)
    return keyed64(key.encode("utf-8"), domain)


def fingerprint(seed, key):
    return keyed64(key.encode("utf-8"), seed ^ FP_DOMAIN)


def vertex_count(n):
    if n == 0:
        return 0
    if n <= SMALL_SET_MAX:
        return max(MIN_VERTICES, 2 * n)
    if n <= MID_SET_MAX:
        return int(MID_FACTOR * n + 0.999999)
    return int(LOAD_FACTOR * n + 0.999999)


def build_case(keys, base_seed, max_attempts=128):
    unique = []
    for k in keys:
        if k not in unique:
            unique.append(k)
    n = len(unique)
    if n == 0:
        return {"seed": base_seed, "m": 0, "g": [],
                "slots": {}, "fingerprints": {}}
    m = vertex_count(n)
    for attempt in range(max_attempts):
        seed = (base_seed + attempt) & MASK
        edges = []
        degenerate = False
        for k in unique:
            vs = [vertex_hash(seed, i, k) % m for i in range(3)]
            if len(set(vs)) != 3:
                degenerate = True
                break
            edges.append(vs)
        if degenerate:
            continue
        degree = [0] * m
        adj = [[] for _ in range(m)]
        for idx, e in enumerate(edges):
            for v in e:
                degree[v] += 1
                adj[v].append(idx)
        removed = [False] * n
        stack = []
        queue = [v for v in range(m) if degree[v] == 1]
        head = 0
        while head < len(queue):
            v = queue[head]
            head += 1
            if degree[v] != 1:
                continue
            edge_id = next(e for e in adj[v] if not removed[e])
            removed[edge_id] = True
            stack.append((edge_id, v))
            for u in edges[edge_id]:
                degree[u] -= 1
                if degree[u] == 1:
                    queue.append(u)
        if len(stack) != n:
            continue
        g = [0] * m
        for next_slot, (edge_id, critical) in enumerate(reversed(stack)):
            s_others = sum(g[v] for v in edges[edge_id] if v != critical)
            g[critical] = (next_slot - s_others) % n
        slots = {}
        for k in unique:
            vs = [vertex_hash(seed, i, k) % m for i in range(3)]
            slots[k] = (g[vs[0]] + g[vs[1]] + g[vs[2]]) % n
        return {"seed": seed, "m": m, "g": g,
                "slots": slots,
                "fingerprints": {k: fingerprint(seed, k) for k in unique}}
    raise RuntimeError("peeling exhausted for every attempt")


CASES = [
    {
        "name": "empty",
        "seed": 42,
        "keys": [],
    },
    {
        "name": "single",
        "seed": 1,
        "keys": ["alpha"],
    },
    {
        "name": "eight_words_seed42",
        "seed": 42,
        "keys": ["alpha", "bravo", "charlie", "delta",
                 "echo", "foxtrot", "golf", "hotel"],
    },
    {
        "name": "with_duplicates_seed7",
        "seed": 7,
        "keys": ["k1", "k2", "k1", "k3", "k2", "k4", "k5"],
    },
    {
        "name": "binary_safe_ascii_seed99",
        "seed": 99,
        "keys": ["", " ", "\t", "a", "ab", "abc", "ABCD", "key=value;x=1"],
    },
    {
        "name": "fifteen_numeric_seed2024",
        "seed": 2024,
        "keys": [f"id-{i:04d}" for i in range(15)],
    },
]


def main():
    out = {"format": "mphf-bdz-reference/1",
           "load_factor": LOAD_FACTOR,
           "mid_factor": MID_FACTOR,
           "mid_set_max": MID_SET_MAX,
           "small_set_max": SMALL_SET_MAX,
           "min_vertices": MIN_VERTICES,
           "cases": []}
    for case in CASES:
        keys = list(case["keys"])
        uniq = []
        for k in keys:
            if k not in uniq:
                uniq.append(k)
        built = build_case(keys, case["seed"])
        out["cases"].append({
            "name": case["name"],
            "base_seed": case["seed"],
            "input_keys": keys,
            "unique_keys": uniq,
            "duplicates_removed": len(keys) - len(uniq),
            **built,
        })
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, "..", "tests", "fixtures",
                          "reference_vectors.json")
    with open(target, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {os.path.normpath(target)} with {len(CASES)} cases")


if __name__ == "__main__":
    main()
