#!/usr/bin/env python3
"""Independent reference oracle and golden-fixture generator.

INDEPENDENCE CONTRACT
=====================
This module is the reference answer source for the test suite. It deliberately
imports **none** of the light-client core package (``lc.*``). It independently:

* serializes headers/committees with its own little-endian packer,
* computes roots/commitments with its own domain tags,
* signs the certificate message directly with the Ed25519 primitive from the
  audited ``cryptography`` library (the crypto primitive, not the client),
* states the expected verdict, failure *category* and failure *code* for every
  fixture from first principles.

The core's rules are considered correct only when they reproduce this oracle's
expected roots, commitments, weights and accept/reject verdicts. The reverse
must never be true: the oracle is not generated by the code under test.

Run directly to (re)generate tests/fixtures/golden.json::

    .venv/bin/python scripts/oracle.py
"""

from __future__ import annotations

import hashlib
import json
import os
import struct
from typing import Any, Dict, List, Optional, Tuple

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

# ---------------------------------------------------------------------------
# Independent constants (mirror the protocol spec; intentionally redeclared).
# ---------------------------------------------------------------------------
O_DOM_HEADER = b"LC\x01HDR"
O_DOM_COMMITTEE = b"LC\x01COM"
O_DOM_SIGN = b"LCSIGNH\x01"

# Weight scheme: equal weight per member; threshold floor(2n/3)+1.


# ---------------------------------------------------------------------------
# Deterministic test keys (TEST-ONLY, never used on any real network).
# Seeded Ed25519 from a counter so golden.json is reproducible.
# ---------------------------------------------------------------------------
def _seed(member_index: int) -> bytes:
    return hashlib.sha256(b"local-lc-test-key-v1:" + str(member_index).encode()).digest()


def test_key(member_index: int) -> Tuple[Ed25519PrivateKey, bytes]:
    sk = Ed25519PrivateKey.from_private_bytes(_seed(member_index))
    pk = sk.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return sk, pk


# ---------------------------------------------------------------------------
# Independent serialization (separate code path from lc.encoding).
# ---------------------------------------------------------------------------
def o_encode_header(h: Dict[str, Any]) -> bytes:
    ncc = bytes.fromhex(h["next_committee_commitment"][2:]) if h.get(
        "next_committee_commitment"
    ) else b"\x00" * 32
    flag = b"\x01" if h.get("next_committee_commitment") else b"\x00"
    return (
        struct.pack("<Q", h["round"])
        + bytes.fromhex(h["parent_root"][2:])
        + bytes.fromhex(h["body_root"][2:])
        + struct.pack("<Q", h["timestamp"])
        + flag
        + ncc
    )


def o_header_root(h: Dict[str, Any]) -> bytes:
    return hashlib.sha256(O_DOM_HEADER + o_encode_header(h)).digest()


def o_encode_committee(c: Dict[str, Any]) -> bytes:
    members = sorted(c["members"], key=lambda m: m["public_key"])
    out = struct.pack("<I", len(members))
    for m in members:
        out += bytes.fromhex(m["public_key"][2:])
        out += struct.pack("<Q", m["weight"])
    return out


def o_committee_commitment(c: Dict[str, Any]) -> bytes:
    return hashlib.sha256(O_DOM_COMMITTEE + o_encode_committee(c)).digest()


def o_cert_message(root: bytes) -> bytes:
    return O_DOM_SIGN + root


def o_sign(sk: Ed25519PrivateKey, root: bytes) -> bytes:
    return sk.sign(o_cert_message(root))


# ---------------------------------------------------------------------------
# Independent verdict logic (spec reference).
# ---------------------------------------------------------------------------
def o_threshold(total_weight: int) -> int:
    return (2 * total_weight) // 3 + 1


def expected_reject(category: str, code: str, reason: str) -> Dict[str, Any]:
    return {"verdict": "reject", "category": category, "code": code, "reason": reason}


def expected_accept() -> Dict[str, Any]:
    return {"verdict": "accept"}


# ---------------------------------------------------------------------------
# Fixture construction helpers.
# ---------------------------------------------------------------------------
def make_committee(
    members: List[Tuple[int, int]],
) -> Tuple[Dict[str, Any], Dict[bytes, Ed25519PrivateKey]]:
    """members: list of (key_index, weight). Returns committee dict + key map."""
    out_members = []
    keys: Dict[bytes, Ed25519PrivateKey] = {}
    for idx, weight in members:
        sk, pk = test_key(idx)
        keys[pk] = sk
        out_members.append({"public_key": "0x" + pk.hex(), "weight": weight})
    committee = {"members": out_members}
    # canonical sort for presentation too
    committee["members"].sort(key=lambda m: m["public_key"])
    return committee, keys


def make_header(
    round_index: int,
    parent_root: bytes,
    timestamp_ms: int,
    *,
    body_root: Optional[bytes] = None,
    next_committee_commitment: Optional[bytes] = None,
) -> Dict[str, Any]:
    return {
        "round": round_index,
        "parent_root": "0x" + parent_root.hex(),
        "body_root": "0x" + (
            body_root or hashlib.sha256(b"body:%d" % round_index).digest()
        ).hex(),
        "timestamp": timestamp_ms,
        "next_committee_commitment": (
            None
            if next_committee_commitment is None
            else "0x" + next_committee_commitment.hex()
        ),
    }


def make_certificate(
    root: bytes,
    keys_by_pub: Dict[bytes, Ed25519PrivateKey],
    signer_pubkeys: List[bytes],
) -> Dict[str, Any]:
    sigs = []
    for pk in signer_pubkeys:
        sig = o_sign(keys_by_pub[pk], root)
        sigs.append({"public_key": "0x" + pk.hex(), "signature": "0x" + sig.hex()})
    return {"header_root": "0x" + root.hex(), "signatures": sigs}


def pubkeys(committee: Dict[str, Any]) -> List[bytes]:
    return [bytes.fromhex(m["public_key"][2:]) for m in committee["members"]]


def weight_of(committee: Dict[str, Any], pub: bytes) -> int:
    for m in committee["members"]:
        if bytes.fromhex(m["public_key"][2:]) == pub:
            return m["weight"]
    raise KeyError("pubkey not in committee")


# ---------------------------------------------------------------------------
# Golden vector set.
# ---------------------------------------------------------------------------
def build_golden() -> Dict[str, Any]:
    T0 = 1_700_000_000_000  # fixed synthetic genesis time
    SLOT = 6_000  # 6 seconds per round
    N = 6  # committee members, weight 10 each -> W=60, threshold 41

    committee, keys = make_committee([(i, 10) for i in range(N)])
    pks = pubkeys(committee)
    commitment = o_committee_commitment(committee)
    required = o_threshold(60)

    # Checkpoint header: round 100 pointing at synthetic genesis parent zeros.
    genesis_parent = b"\x00" * 32
    cp_header = make_header(100, genesis_parent, T0, body_root=b"\xaa" * 32)
    cp_root = o_header_root(cp_header)
    cp_cert = make_certificate(cp_root, keys, pks[:5])  # cert present; checkpoint
    # installs assert it regardless.

    vectors: List[Dict[str, Any]] = []

    # 1. continuous legal headers (a short run of 3).
    legal_chain = []
    parent = cp_root
    for k in range(3):
        h = make_header(101 + k, parent, T0 + (k + 1) * SLOT)
        root = o_header_root(h)
        cert = make_certificate(root, keys, pks[:5])  # 50 >= 41
        legal_chain.append(
            {
                "header": h,
                "certificate": cert,
                "root": "0x" + root.hex(),
                "expected": expected_accept(),
            }
        )
        parent = root

    vectors.append(
        {
            "id": "legal_continuous_3",
            "kind": "chain",
            "description": "three contiguous headers, each signed by 5/6 (50w >= 41w)",
            "items": legal_chain,
        }
    )

    # 2. insufficient weight: 4 signers = 40 < 41 (the 2/3 boundary!).
    h_low = make_header(201, cp_root, T0 + 201 * SLOT, body_root=b"\x01" * 32)
    low_root = o_header_root(h_low)
    cert_low = make_certificate(low_root, keys, pks[:4])
    vectors.append(
        {
            "id": "weight_below_threshold",
            "kind": "single",
            "description": "4/6 signers = weight 40, required 41 -> reject",
            "header": h_low,
            "certificate": cert_low,
            "root": "0x" + low_root.hex(),
            "expected": expected_reject(
                "computation_failure",
                "INSUFFICIENT_WEIGHT",
                "signed weight 40 < required 41 of total 60",
            ),
            "signed_weight": 40,
            "required_weight": required,
        }
    )

    # exactly-at-threshold accepted (41 impossible with w=10; use a dedicated
    # 5-member committee W=50 -> threshold 34: members weights 10,10,10,10,10,
    # 34 needs four signers = 40 >= 34; 3 signers = 30 < 34)
    cmt5, keys5 = make_committee([(10 + i, 10) for i in range(5)])
    pks5 = pubkeys(cmt5)
    commit5 = o_committee_commitment(cmt5)
    # rotation header from base committee, announcing committee5
    rot_h = make_header(
        300,
        cp_root,
        T0 + 300 * SLOT,
        body_root=b"\xcc" * 32,
        next_committee_commitment=commit5,
    )
    rot_root = o_header_root(rot_h)
    rot_cert = make_certificate(rot_root, keys, pks[:5])  # old committee 5/6
    vectors.append(
        {
            "id": "committee_rotation_authorized",
            "kind": "single",
            "description": "rotation header authorized by 5/6 of the OLD committee",
            "header": rot_h,
            "certificate": rot_cert,
            "next_committee": cmt5,
            "root": "0x" + rot_root.hex(),
            "expected": expected_accept(),
            "new_committee_commitment": "0x" + commit5.hex(),
        }
    )

    # 3. post-rotation header signed by the OLD committee -> SIGNER_UNKNOWN.
    post_h = make_header(301, rot_root, T0 + 301 * SLOT, body_root=b"\x0d" * 32)
    post_root = o_header_root(post_h)
    post_cert_old = make_certificate(post_root, keys, pks[:5])  # OLD keys
    vectors.append(
        {
            "id": "old_committee_signs_after_rotation",
            "kind": "single",
            "description": "after rotation, old committee's 5/6 cert is rejected",
            "prerequisite": "committee_rotation_authorized",
            "header": post_h,
            "certificate": post_cert_old,
            "root": "0x" + post_root.hex(),
            "expected": expected_reject(
                "computation_failure",
                "SIGNER_UNKNOWN",
                "signers are not members of the now-active committee",
            ),
        }
    )
    # Same header signed by the NEW committee, only 3/5 = 30 < 34 -> underweight.
    post_cert_3 = make_certificate(post_root, keys5, pks5[:3])
    vectors.append(
        {
            "id": "new_committee_underweight",
            "kind": "single",
            "description": "new committee, 3/5 = 30w < 34w required",
            "prerequisite": "committee_rotation_authorized",
            "header": post_h,
            "certificate": post_cert_3,
            "root": "0x" + post_root.hex(),
            "expected": expected_reject(
                "computation_failure",
                "INSUFFICIENT_WEIGHT",
                "signed weight 30 < required 34 of total 50",
            ),
            "signed_weight": 30,
            "required_weight": o_threshold(50),
        }
    )
    # Same header with 4/5 new committee = 40 >= 34 -> accept.
    post_cert_4 = make_certificate(post_root, keys5, pks5[:4])
    vectors.append(
        {
            "id": "new_committee_authorized",
            "kind": "single",
            "description": "new committee, 4/5 = 40w >= 34w",
            "prerequisite": "committee_rotation_authorized",
            "header": post_h,
            "certificate": post_cert_4,
            "root": "0x" + post_root.hex(),
            "expected": expected_accept(),
        }
    )

    # 4. conflicting header at the same round as a trusted tip.
    # Apply legal round-101 first; an alternative round-101 child must fail.
    h101 = legal_chain[0]
    conflict = make_header(101, cp_root, T0 + SLOT, body_root=b"\xf0" * 32)
    cfl_root = o_header_root(conflict)
    cfl_cert = make_certificate(cfl_root, keys, pks[:5])
    vectors.append(
        {
            "id": "conflict_same_round_equivocation",
            "kind": "single",
            "description": "second header at round 101 branching from checkpoint",
            "prerequisite": "legal_continuous_3:first",
            "header": conflict,
            "certificate": cfl_cert,
            "root": "0x" + cfl_root.hex(),
            "expected": expected_reject(
                "state_conflict",
                "CONFLICT_EQUIVOCATION",
                "different header at the same round as trusted tip",
            ),
        }
    )

    # Unknown-parent (untrusted branch) header.
    orphan = make_header(101, b"\xbe" * 32, T0 + SLOT, body_root=b"\x0b" * 32)
    orphan_root = o_header_root(orphan)
    orphan_cert = make_certificate(orphan_root, keys, pks[:5])
    vectors.append(
        {
            "id": "untrusted_branch_unknown_parent",
            "kind": "single",
            "description": "header whose parent is not the tip and unknown",
            "header": orphan,
            "certificate": orphan_cert,
            "root": "0x" + orphan_root.hex(),
            "expected": expected_reject(
                "state_conflict",
                "UNTRUSTED_BRANCH",
                "cannot update root from an untrusted branch",
            ),
        }
    )

    # stale round
    stale = make_header(50, cp_root, T0 + 10 * SLOT, body_root=b"\x05" * 32)
    stale_root = o_header_root(stale)
    stale_cert = make_certificate(stale_root, keys, pks[:5])
    vectors.append(
        {
            "id": "stale_round",
            "kind": "single",
            "description": "round 50 <= checkpoint round 100",
            "header": stale,
            "certificate": stale_cert,
            "root": "0x" + stale_root.hex(),
            "expected": expected_reject(
                "state_conflict", "STALE_ROUND", "round must strictly increase"
            ),
        }
    )

    # bad signature: valid 5 signers but flip one signature byte.
    bad = make_header(202, cp_root, T0 + 202 * SLOT, body_root=b"\x02" * 32)
    bad_root = o_header_root(bad)
    bad_cert = make_certificate(bad_root, keys, pks[:5])
    flipped = bytearray.fromhex(bad_cert["signatures"][0]["signature"][2:])
    flipped[0] ^= 0xFF
    bad_cert["signatures"][0]["signature"] = "0x" + flipped.hex()
    vectors.append(
        {
            "id": "bad_signature",
            "kind": "single",
            "description": "one corrupted Ed25519 signature among five",
            "header": bad,
            "certificate": bad_cert,
            "root": "0x" + bad_root.hex(),
            "expected": expected_reject(
                "computation_failure",
                "CRYPTO_BAD_SIGNATURE",
                "individual signature verification failed",
            ),
        }
    )

    # cert binds to a different root
    bind_h = make_header(203, cp_root, T0 + 203 * SLOT, body_root=b"\x03" * 32)
    bind_root = o_header_root(bind_h)
    other = make_header(204, cp_root, T0 + 204 * SLOT, body_root=b"\x04" * 32)
    other_root = o_header_root(other)
    bind_cert = make_certificate(other_root, keys, pks[:5])
    vectors.append(
        {
            "id": "cert_bound_to_other_header",
            "kind": "single",
            "description": "certificate.header_root mismatches header root",
            "header": bind_h,
            "certificate": bind_cert,
            "root": "0x" + bind_root.hex(),
            "expected": expected_reject(
                "input_error",
                "CERT_BIND_MISMATCH",
                "certificate is bound to a different header",
            ),
        }
    )

    # rotation commitment mismatch
    rot_bad = make_header(
        310,
        cp_root,
        T0 + 310 * SLOT,
        body_root=b"\x31" * 32,
        next_committee_commitment=b"\xde" * 32,
    )
    rb_root = o_header_root(rot_bad)
    rb_cert = make_certificate(rb_root, keys, pks[:5])
    vectors.append(
        {
            "id": "rotation_commitment_mismatch",
            "kind": "single",
            "description": "supplied committee doesn't hash to declared commitment",
            "header": rot_bad,
            "certificate": rb_cert,
            "next_committee": cmt5,
            "root": "0x" + rb_root.hex(),
            "expected": expected_reject(
                "input_error",
                "ROTATION_COMMITMENT_MISMATCH",
                "committee commitment mismatch",
            ),
        }
    )

    return {
        "protocol": "local-header-lightclient/simplified-v1",
        "note": "Independent oracle fixture. Not a public-chain client.",
        "constants": {
            "T0": T0,
            "SLOT_MS": SLOT,
            "trust_period_ms": 7 * 24 * 60 * 60 * 1000,
            "base_committee_size": N,
            "base_total_weight": 60,
            "base_required_weight": required,
            "domains": {
                "header": O_DOM_HEADER.hex(),
                "committee": O_DOM_COMMITTEE.hex(),
                "cert_sign": O_DOM_SIGN.hex(),
            },
        },
        "checkpoint": {
            "header": cp_header,
            "committee": committee,
            "root": "0x" + cp_root.hex(),
            "committee_commitment": "0x" + commitment.hex(),
            "certificate": cp_cert,
        },
        "vectors": vectors,
    }


def main() -> None:
    golden = build_golden()
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "tests", "fixtures", "golden.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(golden, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"wrote {os.path.abspath(out)}")
    print(f"vectors: {len(golden['vectors'])}")
    # Independent self-check: header roots are 32 bytes and threshold math.
    assert golden["constants"]["base_required_weight"] == 41
    print("oracle self-check: required_weight(W=60) = 41 OK")


if __name__ == "__main__":
    main()
