#!/usr/bin/env bash
# End-to-end verification for the test-asset UTXO ledger.
#
# Runs three independent checks and leaves replayable artifacts under logs/:
#   1. offline fixture-case replay (each case on a fresh on-disk DB), with the
#      expected verdicts generated by the independent tests/oracle.py;
#   2. chain rebuild: commit blocks to a source DB, then rebuild state from the
#      block log into a separate DB and compare the resulting tip hash;
#   3. the full pytest suite (encoding/crypto/kernel/storage/API), which itself
#      asserts concrete codes/categories, per-transaction reference states and
#      whole-block atomicity.
#
# Usage: scripts/verify.sh [extra pytest args]
set -euo pipefail

cd "$(dirname "$0")/.."

PY=.venv/bin/python
LOGDIR="logs"
mkdir -p "$LOGDIR"

echo "== [1/3] offline fixture replay (independent oracle expectations) =="
$PY -m utxo_ledger.replay fixtures \
    --file fixtures/cases.jsonl \
    --logdir "$LOGDIR" \
    --report "$LOGDIR/fixture-report.json"

echo
echo "== [2/3] chain rebuild from committed block log =="
$PY scripts/make_chain_db.py --db "$LOGDIR/demo-source.db"
$PY -m utxo_ledger.replay chain \
    --db "$LOGDIR/demo-source.db" \
    --logdir "$LOGDIR" \
    --keep-target "$LOGDIR/demo-rebuilt.db"

echo
echo "== [3/3] full pytest suite =="
$PY -m pytest "$@"

echo
echo "All verification checks passed. Replay artifacts: $LOGDIR"
