"""Local synthetic fixtures shared by tests.

Kept as hand-written data (not generated by the core) so expected outputs can
be audited directly.
"""

from __future__ import annotations

# (label, text)
TEXTS: dict[str, str] = {
    "ascii_simple": "hello world, hello again",
    "adjacent": "aaaa",
    # multibyte: € = U+20AC (3 UTF-8 bytes), 世 = 3 bytes, emoji = 4 bytes
    "multibyte": "a€b 世界c 😀 x",
    "crlf": "line1\r\nline2\rend",
    "zero_width_play": "a€b a€b",
    "overlap_story": "cat and catbird sit on a catalog",
    "optional": "Mr Smith; Ms; Doctor Who",
    "lines": "ab\ncd\nef",
}

# Rulesets expressed as plain dicts (RuleSpec shape), plus the hand-computed
# expected outputs for selected (text, ruleset) pairs.
RULESET_BASIC = [
    {"rule_id": "hello", "pattern": r"hello", "template": "HI"},
    {"rule_id": "world", "pattern": r"world", "template": "[$0]"},
]
EXPECT_BASIC = {
    "ascii_simple": "HI [world], HI again",
}

# Zero-width word-boundary insertion. Expected positions computed by hand over
# BYTES and also compared against stdlib re in the oracle test.
RULESET_WORDBOUNDARY = [
    {"rule_id": "bar", "pattern": r"\b", "template": "|"},
]
# Expected output when BOTH rules run on the multibyte text. Note the
# documented interaction: the ASCII-scoped \b fires at the boundary between 'a'
# and € (offset 1); that zero-width candidate owns the point and (same-start
# rule, rule_id "bar" < "euro") suppresses the euro match at the same offset.
EXPECT_WORDBOUNDARY = {
    "zero_width_play": "|a|€|b| |a|€|b|",
}

# Same multibyte text with the euro rule given HIGHER priority: it then claims
# the non-empty € ranges; the boundary zero-width at offset 1 still precedes
# it (bar fires at 0, euro at 1), yielding pipes around EURO.
RULESET_EURO_PRIORITY = [
    {"rule_id": "bar", "pattern": r"\b", "template": "|", "priority": 0},
    {"rule_id": "euro", "pattern": r"€", "template": "EURO", "priority": 5},
]
EXPECT_EURO_PRIORITY = "|aEURO|b| |aEURO|b|"

RULESET_WORDBOUNDARY_ALONE = [
    {"rule_id": "bar", "pattern": r"\b", "template": "|"},
]

RULESET_WORDBOUNDARY_EURO = [
    {"rule_id": "bar", "pattern": r"\b", "template": "|"},
    {"rule_id": "euro", "pattern": r"€", "template": "EURO"},
]

# Overlapping rules exercising same-round priority.
RULESET_OVERLAP = [
    {"rule_id": "cat", "pattern": r"cat", "template": "FELIX", "priority": 5},
    {"rule_id": "catbird", "pattern": r"catbird", "template": "BIRD", "priority": 1},
    {"rule_id": "catalog", "pattern": r"catalog", "template": "LOG", "priority": 1},
    {"rule_id": "a", "pattern": r"a", "template": "_A_", "priority": 0},
]
# Hand-computed: 'cat' wins everywhere it matches, so 'catbird' and 'catalog'
# are wholly suppressed -- INCLUDING the 'a' inside 'catalog' (it starts at an
# offset owned by the winning cat range). Remaining 'a's outside cat ranges
# become _A_:
#   "cat and catbird sit on a catalog"
EXPECT_OVERLAP = "FELIX _A_nd FELIXbird sit on _A_ FELIX_A_log"

# Optional capture: title then optional name.
RULESET_OPTIONAL = [
    {
        "rule_id": "title",
        "pattern": r"(Mr|Ms|Doctor)(?:\s+([A-Z][a-z]+))?",
        "template": "[${1}:$2]",
        # $2 unmatched on bare "Ms" -> must raise capture_missing by default
    },
]
RULESET_OPTIONAL_LENIENT = [
    {
        "rule_id": "title",
        "pattern": r"(Mr|Ms|Doctor)(?:\s+([A-Z][a-z]+))?",
        "template": "[${1}:$2]",
        "missing_capture": "empty",
    },
]
EXPECT_OPTIONAL_LENIENT = "[Mr:Smith]; [Ms:]; [Doctor:Who]"

# Zero-width pattern that matches at EVERY codepoint boundary: x* empty chains
RULESET_ASTAR = [
    {"rule_id": "astar", "pattern": r"a*", "template": "X"},
]
# stdlib re.sub semantics reference; our planning semantics deliberately fire
# the same candidate sequence as re.finditer (validated in oracle tests).
