"""Independent page-level D/R oracle (fastparquet parser over PyArrow files).

PyArrow's Python bindings do not expose definition/repetition levels per data
page. fastparquet is a *separate, independent* Parquet implementation (its own
Thrift metadata handling and its own RLE/bit-packed level decoder), so parsing
the PyArrow-written file with fastparquet gives us a genuinely external
oracle: neither side of the comparison is generated by the kernel under test.

The function returns, for every leaf column, a list of pages with the levels
as decoded by fastparquet, keeping the page boundary information intact (that
boundary is the whole point -- it lets the tests assert
"no page starts inside a record").
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import numpy as np

try:
    from fastparquet import ParquetFile  # type: ignore
    from fastparquet import cencoding as _ce  # type: ignore
    from fastparquet import core as _fp_core  # type: ignore
    _AVAILABLE = True
except Exception:  # pragma: no cover - import guard
    _AVAILABLE = False


@dataclass
class OraclePage:
    index: int
    num_values: int
    definition_levels: Optional[list[int]]
    repetition_levels: Optional[list[int]]
    page_version: int  # 1 or 2


@dataclass
class OracleColumn:
    path: str
    max_definition_level: int
    max_repetition_level: int
    pages: list[OraclePage]


def available() -> bool:
    return _AVAILABLE


def extract_pages(path: Path) -> list[OracleColumn]:
    if not _AVAILABLE:
        raise RuntimeError("fastparquet oracle is not installed")
    pf = ParquetFile(str(path))
    columns: list[OracleColumn] = []
    for rg in pf.row_groups:
        for chunk in rg.columns:
            cmd = chunk.meta_data
            path_in_schema = ".".join(cmd.path_in_schema)
            max_def = pf.helper.max_definition_level(cmd.path_in_schema)
            max_rep = pf.helper.max_repetition_level(cmd.path_in_schema)
            pages = _read_chunk_pages(str(path), chunk, pf)
            columns.append(OracleColumn(
                path=path_in_schema,
                max_definition_level=max_def,
                max_repetition_level=max_rep,
                pages=pages,
            ))
        # A single row group is sufficient and deterministic for the tests.
        break
    return columns


def _read_chunk_pages(path: str, chunk: Any, pf: Any) -> list[OraclePage]:
    cmd = chunk.meta_data
    with open(path, "rb") as fh:
        offset = cmd.dictionary_page_offset or cmd.data_page_offset
        fh.seek(offset)
        raw = fh.read(cmd.total_compressed_size)
    io = _ce.NumpyIO(raw)
    pages: list[OraclePage] = []
    consumed = 0
    while consumed < cmd.num_values:
        ph = _ce.ThriftObject.from_buffer(io, "PageHeader")
        if ph.type == 0:  # DATA_PAGE (v1)
            d, r, _vals = _fp_core.read_data_page(io, pf.helper, ph, cmd)
            n = ph.data_page_header.num_values
            pages.append(OraclePage(
                index=len(pages), num_values=n,
                definition_levels=None if d is None else np.asarray(d).tolist(),
                repetition_levels=None if r is None else np.asarray(r).tolist(),
                page_version=1,
            ))
            consumed += n
        elif ph.type == 3:  # DATA_PAGE_V2
            n = ph.data_page_header_v2.num_values
            d, r = _read_v2_levels(io, ph, pf.helper, cmd)
            pages.append(OraclePage(
                index=len(pages), num_values=n,
                definition_levels=d, repetition_levels=r, page_version=2,
            ))
            consumed += n
            # Skip the values region: header lengths were for levels only.
            data_bytes = (
                ph.compressed_page_size
                - ph.data_page_header_v2.repetition_levels_byte_length
                - ph.data_page_header_v2.definition_levels_byte_length
            )
            io.seek(data_bytes, 1)
        elif ph.type == 2:  # DICTIONARY_PAGE
            # Skip via the fastparquet helper so its state advances correctly.
            from fastparquet.core import read_dictionary_page
            read_dictionary_page(io, pf.helper, ph, cmd)
        else:
            raise NotImplementedError(f"unsupported page type {ph.type}")
    return pages


def _read_v2_levels(io: Any, ph: Any, helper: Any, cmd: Any):
    h = ph.data_page_header_v2
    max_rep = helper.max_repetition_level(cmd.path_in_schema)
    max_def = helper.max_definition_level(cmd.path_in_schema)
    rep = None
    if max_rep:
        bw = _ce.width_from_max_int(max_rep)
        bio = _ce.NumpyIO(io.read(h.repetition_levels_byte_length))
        arr = np.empty(h.num_values, dtype="uint8")
        _ce.read_rle_bit_packed_hybrid(
            bio, bw, h.num_values, _ce.NumpyIO(arr), itemsize=1)
        rep = arr.tolist()
    dfn = None
    if max_def:
        bw = _ce.width_from_max_int(max_def)
        bio = _ce.NumpyIO(io.read(h.definition_levels_byte_length))
        arr = np.empty(h.num_values, dtype="uint8")
        _ce.read_rle_bit_packed_hybrid(
            bio, bw, h.num_values, _ce.NumpyIO(arr), itemsize=1)
        dfn = arr.tolist()
    return dfn, rep
