#!/usr/bin/env python3
"""Generate golden test vectors with the independent Python reference.

Output: tests/fixtures/golden_vectors.json with cases covering:
  * empty / extremely short inputs,
  * long repetitive runs,
  * alternating symbols,
  * full-alphabet coverage,
  * unequal frequency weights.

Each case pins: freqs, bound, symbols, exact hex payload, byte length,
and per-symbol (low, range) trace after encoding — so Rust tests assert
concrete values produced by an independent implementation, never values
generated by the code under test.
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from reference_rangecoder import encode_vec, FreqTable  # noqa: E402

BOUND = 1 << 14

cases = []


def add(name, freqs, symbols, bound=BOUND):
    payload, trace = encode_vec(freqs, bound, symbols)
    cases.append(
        {
            "name": name,
            "freqs": freqs,
            "bound": bound,
            "symbols": symbols,
            "payload_hex": payload.hex(),
            "byte_len": len(payload),
            "trace_low": [t[0] for t in trace],
            "trace_range": [t[1] for t in trace],
        }
    )


# 1. Empty input.
add("empty_binary", [1, 1], [])
# 2. Extremely short: one symbol each way.
add("single_zero", [1, 1], [0])
add("single_one", [1, 1], [1])
# 3. Long repetitive runs.
add("long_run_zeros", [1, 1], [0] * 500)
add("long_run_ones", [1, 1], [1] * 500)
add("run_then_switch", [1, 1], [0] * 300 + [1] * 300)
# 4. Alternating.
add("alternating_ab", [1, 1], [i % 2 for i in range(400)])
# 5. Full alphabet (256 symbols) each once.
full_freqs = [1] * 256
add("full_alphabet_once", full_freqs, list(range(256)))
add("full_alphabet_cycle", full_freqs, [i % 256 for i in range(1024)])
# 6. Unequal weights.
w = [1, 2, 3, 5, 8]
seq = [i % 5 for i in range(500)]
add("fibonacci_weights", w, seq)
# 7. Sparse alphabet (zero-frequency entries present in the table).
add("sparse_table", [0, 1, 0, 3, 0, 2], [1, 3, 5, 3, 1, 5, 5, 3, 1], bound=64)
# 8. Boundary: total exactly equals bound.
f = [8192, 8192]
add("total_equals_bound", f, [i % 2 for i in range(64)])
# 9. All-same symbol over full alphabet.
add("all_same_in_full", [1] * 256, [7] * 300)
# 10. Pseudorandom walk (deterministic LCG), independent of Rust RNG.
state = 0x12345678
rnd = []
for _ in range(2000):
    state = (state * 1103515245 + 12345) & 0x7FFFFFFF
    rnd.append(state % 256)
add("lcg_walk_full", [1] * 256, rnd)

out = {"format": "rangecode-golden-v1", "cases": cases}
target = os.path.join(os.path.dirname(__file__), "..", "tests", "fixtures", "golden_vectors.json")
target = os.path.abspath(target)
os.makedirs(os.path.dirname(target), exist_ok=True)
with open(target, "w") as fh:
    json.dump(out, fh, indent=1)

print(f"wrote {len(cases)} golden cases to {target}")
