"""Standard-library-only self-check.

Why this exists
---------------
The authoritative test-suite uses ``pytest`` + the mature ``eth_abi`` /
``pycryptodome`` / ``eth-keys`` libraries as independent oracles (see
``tests/``). In an offline/sandboxed environment where those wheels cannot be
installed, this script still verifies the hand-written codec against:

  * an *independently written* pure-python Keccak-256 (not the code under test);
  * hand-fixed canonical byte vectors (fixed constants, not generated by the
    decoder);
  * encode->decode round trips and exact failure categories for hostile input.

It deliberately does NOT import pycryptodome/eth_abi/eth_keys/fastapi. Run::

    python tools/selfcheck.py

Exit code is non-zero if any check fails; every check logs input + verdict.
"""
from __future__ import annotations

import sys
import traceback
from pathlib import Path

# Make src importable without installing the package.
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

# Import the ABI package but neutralise its production Keccak backend for the
# selector check by monkeypatching encoder's lazy import target. We instead
# compute selectors with the reference keccak below.
from abibackend import abi as codec  # noqa: E402
from abibackend.abi import (  # noqa: E402
    LengthTooLarge,
    NonCanonicalEncoding,
    NonCanonicalPadding,
    OffsetOutOfBounds,
    OffsetOverlap,
    TrailingBytes,
    ValueOutOfRange,
)
from abibackend.abi import encoder as _enc  # noqa: E402


# --------------------------------------------------------------------------- #
# Independent reference Keccak-256 (standard library, not part of src/)
# --------------------------------------------------------------------------- #
def _keccak256(message: bytes) -> bytes:
    RC = [
        0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000,
        0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
        0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
        0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003,
        0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A,
        0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008,
    ]
    ROT = [
        [0, 36, 3, 41, 18],
        [1, 44, 10, 45, 2],
        [62, 6, 43, 15, 61],
        [28, 55, 25, 21, 56],
        [27, 20, 39, 8, 14],
    ]
    M = [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
    ]
    MASK = (1 << 64) - 1
    rate = 136

    def rol(x, n):
        return ((x << n) | (x >> (64 - n))) & MASK

    def keccak_f(state):
        for rnd in range(24):
            # theta
            C = [state[x][0] ^ state[x][1] ^ state[x][2] ^ state[x][3] ^ state[x][4] for x in range(5)]
            D = [C[(x - 1) % 5] ^ rol(C[(x + 1) % 5], 1) for x in range(5)]
            for x in range(5):
                for y in range(5):
                    state[x][y] ^= D[x]
            # rho + pi
            B = [[0] * 5 for _ in range(5)]
            for x in range(5):
                for y in range(5):
                    B[y][(2 * x + 3 * y) % 5] = rol(state[x][y], ROT[x][y])
            # chi
            for x in range(5):
                for y in range(5):
                    state[x][y] = B[x][y] ^ ((~B[(x + 1) % 5][y]) & B[(x + 2) % 5][y])
            # iota
            state[0][0] ^= RC[rnd]
        return state

    # pad: keccak uses 0x01 ... 0x80
    msg = bytearray(message)
    msg.append(0x01)
    while len(msg) % rate != 0:
        msg.append(0x00)
    msg[-1] ^= 0x80

    state = [[0] * 5 for _ in range(5)]
    for block_off in range(0, len(msg), rate):
        block = msg[block_off:block_off + rate]
        for i in range(rate // 8):
            lane = int.from_bytes(block[i * 8:i * 8 + 8], "little")
            x, y = M[i % 5][i // 5] if False else (i % 5, i // 5)
            state[x][y] ^= lane
        state = keccak_f(state)

    out = bytearray()
    while len(out) < 32:
        for y in range(5):
            for x in range(5):
                out += state[x][y].to_bytes(8, "little")
                if len(out) >= 32:
                    return bytes(out[:32])
    return bytes(out[:32])


# Wire the reference keccak into the encoder's lazy selector lookup.
def main() -> int:
    # Make the production encoder's lazy ``from ..crypto import keccak256``
    # resolve to this independent reference implementation.
    import types
    fake_crypto = types.ModuleType("abibackend.crypto")
    fake_crypto.keccak256 = _keccak256
    sys.modules["abibackend.crypto"] = fake_crypto

    passed = failed = 0
    failures = []

    def check(name, cond, detail=""):
        nonlocal passed, failed
        if cond:
            passed += 1
            print(f"  ok   {name}")
        else:
            failed += 1
            failures.append((name, detail))
            print(f"  FAIL {name} :: {detail}")

    def expect_raise(name, cats, fn):
        nonlocal passed, failed
        if isinstance(cats, tuple):
            cat_tuple = cats
        else:
            cat_tuple = (cats,)
        try:
            fn()
        except Exception as exc:  # noqa: BLE001
            ok = isinstance(exc, cat_tuple)
            check(f"{name} [{type(exc).__name__}]", ok,
                  f"wanted {[c.__name__ for c in cat_tuple]} got {type(exc).__name__}: {exc}")
            return
        failed += 1
        failures.append((name, "no exception"))
        print(f"  FAIL {name} :: no exception raised")

    # ---- 0. reference keccak known answers ------------------------------- #
    print("[keccak reference vectors]")
    check("keccak('')",
          _keccak256(b"").hex() == "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470")
    check("keccak('abc')",
          _keccak256(b"abc").hex() == "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45")

    print("[fixed canonical vectors]")
    W = 32

    def w(n): return n.to_bytes(32, "big")

    fixed = [
        (["uint256"], [1], "0" * 63 + "1"),
        (["int256"], [-1], "f" * 64),
        (["int8"], [-128], "f" * 62 + "80"),
        (["uint8"], [255], "0" * 62 + "ff"),
        (["bool"], [True], "0" * 63 + "1"),
        (["bytes4"], [b"\xde\xad\xbe\xef"],
         "deadbeef" + "0" * 56),
        (["bytes"], [b""], ("0" * 62 + "20") + ("0" * 64)),
        (["string"], [""], ("0" * 62 + "20") + ("0" * 64)),
        (["bytes"], [b"\xca\xfe"],
         ("0" * 62 + "20") + ("0" * 62 + "02") + "cafe" + "0" * 60),
        (["string"], ["abc"],
         ("0" * 62 + "20") + ("0" * 62 + "03") + "616263" + "0" * 58),
        (["uint256[]"], [[]], ("0" * 62 + "20") + ("0" * 64)),
        (["uint256[]"], [[1, 2]],
         ("0" * 62 + "20") + ("0" * 62 + "02") + ("0" * 63 + "1") + ("0" * 63 + "2")),
    ]
    for types, values, want in fixed:
        got = codec.encode(types, values).hex()
        check(f"encode {types} <- {values!r}", got == want, f"got {got} want {want}")
        # round trip
        rt = codec.decode(types, bytes.fromhex(got))
        check(f"decode {types}", _norm(types, rt) == _norm(types, tuple(values)),
              f"got {rt}")

    print("[nested dynamic arrays / tuples]")
    nested = [
        (["uint256[][]"], ([[1], [2, 3], []],)),
        (["bytes[][]"], ([[b"", b"x"], [b"yy"], []],)),
        (["uint256[][2]"], (([1, 2], []),)),
        (["(uint256,bytes)[]"], ([(1, b"a"), (2, b"")],)),
        (["(bytes,uint256[],string)"], ((b"Q", [1, 2, 3], "s"),)),
        (["(uint256,(bytes,string)[])"], ((3, [(b"k", "v"), (b"", "")]),)),
        (["(int256,string)"], [(-42, "neg")]),
        (["int256[]"], ([-1, -(2**200), 0, 2**255 - 1],)),
    ]
    for types, values in nested:
        blob = codec.encode(types, list(values))
        back = codec.decode(types, blob)
        check(f"roundtrip {types} {values!r}", _norm(types, back) == _norm(types, tuple(values)),
              f"blob={blob.hex()} back={back}")

    print("[selectors via reference keccak]")
    check("transfer(address,uint256)",
          codec.function_selector("transfer", ["address", "uint256"]).hex() == "a9059cbb")
    check("approve(address,uint256)",
          codec.function_selector("approve", ["address", "uint256"]).hex() == "095ea7b3")
    check("transferFrom(address,address,uint256)",
          codec.function_selector("transferFrom", ["address", "address", "uint256"]).hex()
          == "23b872dd")

    print("[hostile inputs -> exact categories]")
    # offset into head (child1 pointer 0 -> into-head) => OOB
    expect_raise("bytes,bytes offset->head", (OffsetOutOfBounds,),
                 lambda: codec.decode(["bytes", "bytes"], w(0x40) + w(0) + w(0)))
    # duplicate pointers -> overlap
    expect_raise("bytes,bytes duplicate ptr", (OffsetOverlap,),
                 lambda: codec.decode(["bytes", "bytes"], w(0x40) + w(0x40) + w(0)))
    # aligned pointer far past blob end
    expect_raise("bytes,bytes ptr OOB", (OffsetOutOfBounds,),
                 lambda: codec.decode(["bytes", "bytes"], w(0x40) + w(0x10000) + w(0)))
    # unaligned pointer is also rejected (non-canonical)
    expect_raise("bytes,bytes unaligned ptr", (NonCanonicalEncoding, OffsetOutOfBounds),
                 lambda: codec.decode(["bytes", "bytes"], w(0x40) + w(0x9999) + w(0)))
    # huge length, tiny allocator
    expect_raise("huge bytes length", (LengthTooLarge, OffsetOutOfBounds),
                 lambda: codec.decode(["bytes"], w(0x20) + w(2**64 - 1), max_alloc=1024))
    # huge array count (single top-level dynamic array)
    expect_raise("huge array count", (LengthTooLarge, OffsetOutOfBounds),
                 lambda: codec.decode(["uint256[]"], w(0x20) + w(2**60), max_alloc=4096))
    # count so large count*32 overflows a naive unchecked multiply
    expect_raise("array count overflow", (LengthTooLarge, OffsetOutOfBounds),
                 lambda: codec.decode(["uint256[]"], w(0x20) + w((1 << 256) - 1)))
    # all-ones into narrow unsigned
    expect_raise("uint8 = -1", ValueOutOfRange,
                 lambda: codec.decode(["uint8"], b"\xff" * 32))
    # int8 word 0x00..ff = 255 -> exceeds int8 range (ValueOutOfRange)
    expect_raise("int8 255 out of range", ValueOutOfRange,
                 lambda: codec.decode(["int8"], b"\x00" * 30 + b"\x00\xff"))
    # 0x00..80 = 128 -> just above int8 max (127), out of range
    expect_raise("int8 128 out of range", ValueOutOfRange,
                 lambda: codec.decode(["int8"], b"\x00" * 31 + b"\x80"))
    # bool 2
    expect_raise("bool=2", NonCanonicalPadding, lambda: codec.decode(["bool"], w(2)))
    # bytesN right padding dirty
    expect_raise("bytes1 pad dirty", NonCanonicalPadding,
                 lambda: codec.decode(["bytes1"], b"\xab" + b"\x00" * 30 + b"\x01"))
    # bytes tail padding dirty: head offset 0x20, len 1, data 0xab, dirty pad
    expect_raise("bytes tail pad dirty", NonCanonicalPadding,
                 lambda: codec.decode(
                     ["bytes"],
                     w(0x20) + w(1) + b"\xab" + b"\x00" * 30 + b"\x01"))
    # invalid utf-8 lone continuation byte
    expect_raise("string bad utf8", NonCanonicalPadding,
                 lambda: codec.decode(
                     ["string"],
                     w(0x20) + w(1) + b"\xff" + b"\x00" * 31))
    # truncated
    expect_raise("truncated uint", OffsetOutOfBounds,
                 lambda: codec.decode(["uint256"], b"\x00" * 10))
    # trailing bytes
    expect_raise("trailing bytes", TrailingBytes,
                 lambda: codec.decode(["uint256"], w(1) + b"\x00"))
    # unaligned pointer
    expect_raise("unaligned pointer", NonCanonicalEncoding,
                 lambda: codec.decode(["bytes", "bytes"], w(0x41) + w(0x60) + b"\x00" * 32))
    # encode range errors
    expect_raise("encode uint overflow", ValueOutOfRange,
                 lambda: codec.encode(["uint256"], [2**256]))
    expect_raise("encode int underflow", ValueOutOfRange,
                 lambda: codec.encode(["int256"], [-(2**255) - 1]))
    expect_raise("encode arity", ValueOutOfRange,
                 lambda: codec.encode(["uint256[3]"], [[1, 2]]))

    print()
    print(f"SELFCHECK RESULT: passed={passed} failed={failed}")
    if failed:
        print("FAILURES:")
        for name, detail in failures:
            print(f"  - {name}: {detail}")
        return 1
    print("ALL SELF-CHECKS PASSED")
    return 0


def _norm(types, values):
    out = []
    for t, v in zip(types, values):
        out.append(_norm_one(codec.parse_type(t), v))
    return tuple(out)


def _norm_one(header, v):
    from abibackend.abi.types import (
        AddressType, DynamicArrayType, FixedArrayType, FixedBytesType, BytesType, TupleType,
    )
    if isinstance(header, (BytesType, FixedBytesType)):
        return bytes(v)
    if isinstance(header, AddressType):
        return int(v)
    if isinstance(header, TupleType):
        return tuple(_norm_one(h, x) for h, x in zip(header.components, v))
    if isinstance(header, (DynamicArrayType, FixedArrayType)):
        return tuple(_norm_one(header.element, x) for x in v)
    return v


if __name__ == "__main__":
    raise SystemExit(main())
