//! Independent truth-table oracle.
//!
//! This module is the *reference answer* source for verification. It does
//! **not** import or use the BDD kernel: expressions are interpreted directly
//! against assignments, and truth tables are enumerated by a Gray-code-free
//! plain binary counter. That independence is deliberate — test oracles
//! generated by the code under test would prove nothing.

use std::collections::BTreeMap;

use crate::kernel::{KernelError, Op};
use crate::lang::{BinOp, Expr};

/// Evaluate an expression under a total assignment.
///
/// Returns an error if a variable in the expression is absent from `values`.
pub fn evaluate(expr: &Expr, values: &BTreeMap<String, bool>) -> Result<bool, KernelError> {
    match expr {
        Expr::Const(b) => Ok(*b),
        Expr::Var(name) => values.get(name).copied().ok_or_else(|| {
            KernelError::new(
                crate::kernel::ErrorKind::UnknownVariable,
                format!("oracle assignment missing variable {name:?}"),
            )
        }),
        Expr::Not(e) => Ok(!evaluate(e, values)?),
        Expr::Binary { op, lhs, rhs } => {
            let a = evaluate(lhs, values)?;
            let b = evaluate(rhs, values)?;
            Ok(match op {
                BinOp::And => a && b,
                BinOp::Or => a || b,
                BinOp::Xor => a ^ b,
                BinOp::Implies => !a || b,
                BinOp::Equiv => a == b,
            })
        }
    }
}

/// Evaluate a kernel connective directly (used to cross-check `apply`).
pub fn eval_op(op: Op, a: bool, b: bool) -> bool {
    op.eval(a, b)
}

/// Iterate all 2^n assignments to `variables` in lexicographic index order.
///
/// The first variable in the slice is the most-significant counter bit.
pub fn all_assignments(variables: &[String]) -> impl Iterator<Item = BTreeMap<String, bool>> + '_ {
    let n = variables.len();
    assert!(n < 64, "oracle supports fewer than 64 variables");
    (0u64..(1u64 << n)).map(move |mask| {
        variables
            .iter()
            .enumerate()
            .map(|(i, name)| {
                let bit = n - 1 - i;
                (name.clone(), (mask >> bit) & 1 == 1)
            })
            .collect()
    })
}

/// Full truth table as a `Vec<bool>` in the order of [`all_assignments`].
pub fn truth_table(expr: &Expr, variables: &[String]) -> Result<Vec<bool>, KernelError> {
    all_assignments(variables)
        .map(|a| evaluate(expr, &a))
        .collect()
}

/// First assignment on which two expressions disagree, or `None` if they are
/// equal for every assignment to `variables`.
pub fn differing_assignment(
    lhs: &Expr,
    rhs: &Expr,
    variables: &[String],
) -> Result<Option<BTreeMap<String, bool>>, KernelError> {
    for assignment in all_assignments(variables) {
        if evaluate(lhs, &assignment)? != evaluate(rhs, &assignment)? {
            return Ok(Some(assignment));
        }
    }
    Ok(None)
}
