"""Verification orchestration.

Given a schema + records, runs the full evidence chain and returns a
structured report. Three independent sources of truth are used -- the
expected answer is never generated by the core under test:

1. ``expected`` tree supplied by the client (hand-written fixtures), compared
   structurally against the kernel round trip;
2. PyArrow: the same records are written to a real Parquet file and read
   back -- a value-level external oracle;
3. fastparquet parsing the PyArrow-written file: a page-level external
   oracle for definition/repetition levels and page-boundary placement.

Known cross-implementation dialect differences are not hidden: the NULL
struct-element case (Parquet gives the repeated element group no null bit,
and PyArrow materialises it as a struct with all-NULL fields) is reported as
an UNCERTTAIN/INFO observation rather than a pass or a silent rewrite.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from .errors import ErrorCode, Severity
from .kernel import EncodedTable, decode_table, encode_table
from .pager import paginate_table
from .schema import Node, Schema
from ..adapters import level_oracle
from ..adapters.pyarrow_adapter import (
    read_parquet_values,
    write_parquet,
)


@dataclass
class Finding:
    severity: str
    code: str
    message: str
    location: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "severity": self.severity, "code": self.code,
            "message": self.message, "location": self.location,
        }


def _all_null_struct(node: Node) -> dict[str, Any]:
    return {c.name: None for c in node.children}


def normalize_dialect(value: Any, node: Node, inside_list: bool = False) -> Any:
    """Apply documented cross-implementation dialect normalisation.

    PyArrow does not preserve the identity "struct group itself is NULL":
    when reading Parquet it materialises a null struct as a struct whose
    fields are all NULL. This occurs for:

    * a NULL element of a ``list<struct>`` (the REPEATED element group has no
      null bit);
    * a NULL standalone optional struct (PyArrow's struct assembly fills the
      value with all-null children).

    The kernel preserves the distinction internally; for the value-level
    comparison both trees are normalised to PyArrow's reading and the
    locations are reported as an explicit dialect observation.
    """
    if node.kind == "primitive":
        return value
    if node.kind == "struct":
        if value is None:
            return _all_null_struct(node)
        return {c.name: normalize_dialect(value.get(c.name), c,
                                          inside_list=inside_list)
                for c in node.children}
    # list
    assert node.item is not None
    if value is None:
        return None
    return [normalize_dialect(elem, node.item, inside_list=True)
            for elem in value]


def _collect_null_structs(value: Any, node: Node, path: str,
                          acc: list[str]) -> None:
    """Record every location where a struct value is exactly None.

    These are the points where PyArrow's assembled object identity differs
    from the kernel's (it returns an all-null-fields struct instead).
    """
    if value is None:
        if node.kind == "struct":
            acc.append(path)
        return
    if node.kind == "primitive":
        return
    if node.kind == "struct":
        for c in node.children:
            _collect_null_structs(value.get(c.name), c, f"{path}.{c.name}", acc)
        return
    assert node.item is not None
    for i, elem in enumerate(value):
        _collect_null_structs(elem, node.item, f"{path}[{i}]", acc)


def _slots_levels(table: EncodedTable) -> dict[str, dict[str, list[int]]]:
    return {
        ".".join(c.node.path[1:]): {
            "definition": [s.d for s in c.slots],
            "repetition": [s.r for s in c.slots],
        }
        for c in table.columns
    }



def _is_struct_null_d_quirk(kd: list[int], oracle_d: list[int],
                            kr: list[int], oracle_r: list[int]) -> bool:
    """Recognise fastparquet struct definition-level collapse.

    fastparquet does not round-trip the OPTIONAL definition level of a
    STRUCT group the way the kernel encodes it:

    * on a NULL standalone struct it reports the leaves one level LOW;
    * on a NULL struct element of a list it reports them one level HIGH
      (it attributes the element group's D differently from PyArrow).

    In both shapes the discrepancy is exactly +/-1 per affected slot, the
    stream lengths and the repetition levels agree, and the PyArrow *value*
    oracle confirms the kernel. A genuine list/leaf D error (e.g. an empty
    vs null list confusion) changes levels by 2+ or breaks R, so it is not
    absorbed here.
    """
    if len(kd) != len(oracle_d):
        return False
    if oracle_r and oracle_r != kr:
        return False
    saw_diff = False
    for a, b in zip(kd, oracle_d):
        if a == b:
            continue
        if abs(a - b) != 1:
            return False
        saw_diff = True
    return saw_diff


def verify(
    schema: Schema,
    records: list[dict[str, Any]],
    *,
    workdir: Path,
    page_slot_target: int,
    page_version: str = "2.0",
    expected: Optional[list[dict[str, Any]]] = None,
    parquet_page_bytes: int = 256,
) -> dict[str, Any]:
    findings: list[Finding] = []
    steps: list[dict[str, Any]] = []

    # 1) Kernel encode -> decode round trip ------------------------------
    encoded = encode_table(schema, records)
    steps.append({
        "step": "kernel_encode",
        "status": "PASS",
        "leaf_columns": schema.describe_for_headers(),
    })
    decoded = decode_table(encoded)
    steps.append({"step": "kernel_decode", "status": "PASS",
                  "records": len(decoded)})

    if expected is not None:
        # Compare under the same documented struct-null dialect normalisation
        # used for the PyArrow value oracle, so a hand-written NULL struct
        # element matches the assembled all-null-fields representation.
        expected_norm = [
            {ch.name: normalize_dialect(rec.get(ch.name), ch)
             for ch in schema.root.children}
            for rec in expected
        ]
        decoded_norm = [
            {ch.name: normalize_dialect(rec.get(ch.name), ch)
             for ch in schema.root.children}
            for rec in decoded
        ]
        if decoded_norm != expected_norm:
            findings.append(Finding(
                Severity.FATAL.value, ErrorCode.ROUNDTRIP_MISMATCH.value,
                "kernel round trip differs from hand-written expected tree",
                {"first_diff_index":
                 _first_diff(decoded_norm, expected_norm)},
            ))
        else:
            steps.append({"step": "expected_tree", "status": "PASS",
                          "records": len(expected)})

    # 2) Kernel paging invariant ------------------------------------------
    paged = paginate_table(encoded, page_slot_target)
    page_report = {}
    for pc in paged:
        page_report[pc.column] = [
            {"page": p.index, "slots": p.num_slots,
             "record_start": p.record_start, "record_end": p.record_end,
             "oversized": p.oversized,
             "first_repetition_level": p.slots[0].r}
            for p in pc.pages
        ]
    steps.append({"step": "kernel_paging", "status": "PASS",
                  "target_slots": page_slot_target, "pages": page_report})

    # 3) PyArrow value oracle ---------------------------------------------
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    parquet_path = workdir / "candidate.parquet"
    write_parquet(
        schema, records, parquet_path,
        data_page_size=parquet_page_bytes, page_version=page_version,
    )
    arrow_values = read_parquet_values(parquet_path)
    steps.append({
        "step": "pyarrow_write_read",
        "status": "PASS",
        "path": str(parquet_path),
        "page_version": page_version,
    })

    # Compare values under dialect normalisation.
    dialect_locations: list[str] = []
    for child in schema.root.children:
        for i, r in enumerate(records):
            _collect_null_structs(r.get(child.name), child,
                                  f"records[{i}].{child.name}",
                                  dialect_locations)
    value_diffs = {}
    for child in schema.root.children:
        name = child.name
        kernel_norm = [normalize_dialect(r.get(name), child) for r in decoded]
        arrow_norm = arrow_values.get(name)
        if kernel_norm != arrow_norm:
            value_diffs[name] = {
                "first_diff_index": _first_diff(kernel_norm, arrow_norm),
            }
    if value_diffs:
        findings.append(Finding(
            Severity.FATAL.value, ErrorCode.REFERENCE_MISMATCH.value,
            "kernel values differ from the PyArrow Parquet round trip",
            {"columns": value_diffs},
        ))
    else:
        steps.append({"step": "pyarrow_value_oracle", "status": "PASS"})
    if dialect_locations:
        findings.append(Finding(
            Severity.UNCERTAIN.value, "DIALECT_NULL_STRUCT",
            "A struct that is NULL is stored only as NULL markers on its "
            "leaf fields; PyArrow assembles it back as a struct whose "
            "fields are all NULL rather than None (applies to standalone "
            "optional structs and to NULL elements of list<struct>). The "
            "physical D/R levels agree; only the assembled object identity "
            "differs, so the result is reported UNCERTAIN at these points.",
            {"locations": dialect_locations},
        ))

    # 4) fastparquet page-level D/R oracle --------------------------------
    oracle_cols = {c.path: c for c in level_oracle.extract_pages(parquet_path)}
    kernel_levels = _slots_levels(encoded)
    level_findings = []
    dialect_level_columns: list[str] = []
    page_boundary_ok = True
    for c in encoded.columns:
        path = ".".join(c.node.path[1:])
        oc = oracle_cols.get(path)
        if oc is None:
            findings.append(Finding(
                Severity.FATAL.value, ErrorCode.REFERENCE_MISMATCH.value,
                "leaf column missing from PyArrow/fastparquet file",
                {"column": path},
            ))
            continue
        oracle_d = [d for p in oc.pages for d in (p.definition_levels or [])]
        oracle_r = [r for p in oc.pages for r in (p.repetition_levels or [])]
        node = c.node
        kd = kernel_levels[path]["definition"]
        kr = kernel_levels[path]["repetition"]
        r_ok = (oracle_r == kr) if node.max_rep > 0 else all(
            x == 0 for x in oracle_r)
        # A fully-required leaf carries no Parquet definition stream.
        if node.max_def == 0:
            d_ok = True
        elif oracle_d == kd:
            d_ok = True
        elif _is_struct_null_d_quirk(kd, oracle_d, kr, oracle_r):
            # fastparquet collapses the OPTIONAL D level of a NULL standalone
            # struct onto ALL leaves beneath it (including list leaves). The
            # R streams and the PyArrow value oracle both confirm the kernel;
            # only this reference-reader's D on null-struct slots differs.
            d_ok = False
            dialect_level_columns.append(path)
        else:
            d_ok = False
        if not (d_ok and r_ok):
            page_boundary_ok = False
            level_findings.append({
                "column": path,
                "first_def_diff": None if d_ok else _first_diff(kd, oracle_d),
                "first_rep_diff": None if r_ok else _first_diff(kr, oracle_r),
                "kernel_def_head": kd[:12], "oracle_def_head": oracle_d[:12],
                "kernel_rep_head": kr[:12], "oracle_rep_head": oracle_r[:12],
            })
        # Page-boundary contract on the external file: every page starts R=0.
        for p in oc.pages:
            if p.repetition_levels and p.repetition_levels[0] != 0:
                page_boundary_ok = False
                findings.append(Finding(
                    Severity.FATAL.value,
                    ErrorCode.PAGE_TRUNCATES_RECORD.value,
                    "PyArrow file contains a page beginning at non-zero "
                    "repetition level (record truncated across pages)",
                    {"column": path, "page": p.index,
                     "first_repetition_level": p.repetition_levels[0]},
                ))
    hard_level_findings = [f for f in level_findings
                           if f["column"] not in dialect_level_columns
                           or f["first_rep_diff"] is not None]
    if dialect_level_columns:
        findings.append(Finding(
            Severity.UNCERTAIN.value, "DIALECT_FASTPARQUET_NULL_STRUCT_D",
            "fastparquet collapses the definition level of a NULL standalone"
            " (non-list) optional struct onto its leaves, reporting D one "
            "level below the kernel encode and the PyArrow value oracle. "
            "LIST D/R levels -- the contract under test -- and all values "
            "match; only this reference-reader encoding differs.",
            {"columns": dialect_level_columns},
        ))
    if hard_level_findings:
        findings.append(Finding(
            Severity.FATAL.value, ErrorCode.REFERENCE_MISMATCH.value,
            "kernel D/R levels differ from the fastparquet-decoded PyArrow "
            "file",
            {"columns": hard_level_findings},
        ))
    else:
        steps.append({
            "step": "fastparquet_level_oracle",
            "status": "PASS",
            "page_boundaries_start_at_r0": page_boundary_ok,
            "oracle_columns": sorted(oracle_cols),
        })

    fatal = [f for f in findings if f.severity == Severity.FATAL.value]
    uncertain = [f for f in findings if f.severity == Severity.UNCERTAIN.value]
    status = "FAILED" if fatal else ("UNCERTAIN" if uncertain else "OK")
    return {
        "status": status,
        "steps": steps,
        "findings": [f.as_dict() for f in findings],
        "kernel_levels": kernel_levels,
        "kernel_pages": page_report,
        "decoded": decoded,
        "pyarrow_values": arrow_values,
        "oracle_page_count": {
            p: len(col.pages) for p, col in oracle_cols.items()
        },
    }


def _first_diff(a: list[Any], b: list[Any]) -> int:
    for i, (x, y) in enumerate(zip(a, b)):
        if x != y:
            return i
    return min(len(a), len(b))
